### DISCUSSION TITLE
How to use `gitbash.exe` in Windows?

### DISCUSSION THREAD

**Discussion by bukowa** [actions/virtual-environments#10138] [General questions] [answered]
https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#shells
I tried gitbash, gitbash.exe, full path.... 
`Error: gitbash: command not found`

```yaml

name: "Windows"
jobs:

  windows:
    runs-on: "windows-latest"
    defaults:
      run:
        shell: "gitbash"
    steps:
      - uses: actions/checkout@v4

      - run:
          echo "Hello, Windows!"
```
