### DISCUSSION TITLE
Finer granularity for the macos github runners

### DISCUSSION THREAD

**Discussion by miguelcoolchips** [actions/virtual-environments#10217] [General questions]
I am currently using macos-13 as my github runner. However, this label does not fully reflect all the changes that the runner goes through. Changes like the default XCode version. Is there a way to use a label with more granularity such that my builds do not unexpectedly break overnight?

**Comment by Cheesebaron** [comment]
For Xcode specifically I ensure the version of Xcode by selecting the specific version. In Azure Pipelines this looks like:

```
steps:
- script: |
    echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_15.4.app;sudo xcode-select --switch /Applications/Xcode_15.4.app/Contents/Developer
  displayName: 'Select Xcode'
  condition: eq(variables['Agent.OS'], 'Darwin')
```

I highly suggest you do something similar, pinning versions of tools you use to build with.
