### DISCUSSION TITLE
How to configure clang-format version in a ubuntu-22.04 and 24.04 runners?

### DISCUSSION THREAD

**Discussion by SimonBaeumer** [actions/virtual-environments#10640] [General questions] [answered]
Hello,
we would like to use a specific clang-format version, I see there multiple installed in the ubuntu images but I've not figured out how to configure a different version to use (e.g. in 22.04 we want to use clang-format version 15).

I've found the following links and expected to find an env var or overwrite the `toolset-2204.json` config somehow.

 - https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
 - https://github.com/actions/runner-images/blob/main/images/ubuntu/toolsets/toolset-2204.json
 - https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-clang.sh

Any tips how to achieve this?

cc @Molter73

**Comment by erik-bershel** [comment, marked as answer]
Hey @SimonBaeumer!

Different versions of `clang` and it's tools available via `clang-{tool}-{major_version}`

One of the possible solutions:

```yml
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: apt list
        run: |
          # Extract clang-format versions and store in an array
          clang_formats=$(apt list --installed 2>/dev/null | grep clang-format | awk -F/ '{print $1}')
          # Loop through each version and run --version
          for clangFormat in $clang_formats; do
              $clangFormat --version
          done
```

Another option:

```yml
jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            version: "13"
          - os: ubuntu-22.04
            version: "14"        
          - os: ubuntu-22.04
            version: "15"
          - os: ubuntu-24.04
            version: "16"
          - os: ubuntu-24.04
            version: "17"
          - os: ubuntu-24.04
            version: "18"
    runs-on: ${{ matrix.os }}
    steps:
      - name: clang-format-${{ matrix.version }}
        run: |
          clang-format-${{ matrix.version }} --version
```
