### DISCUSSION TITLE
Migrating off NuGetCommand is unclear

### DISCUSSION THREAD

**Discussion by FizzBuzz791** [actions/virtual-environments#12267] [General questions]
We've hit the well-documented "mono is removed from ubuntu-latest" issue and I'm not here to contest that, it is what it is.

Reading the doco for `NuGetCommand@2` - which is what we currently use to push packages to our organization scoped feed - the [documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/nuget-command-v2?view=azure-pipelines#support-for-newer-ubuntu-hosted-images) says: 
> Users of this task on Ubuntu should migrate to the long term supported cross-platform task NuGetAuthenticate@1 with .NET CLI.

That's fine, makes sense. I added `- task: NuGetauthenticate@1`, and then I started looking at `DotNetCoreCLI@2` and the [remarks](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/dotnet-core-cli-v2?view=azure-pipelines#remarks) say:
> The [NuGet Authenticate](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/nuget-authenticate-v1?view=azure-pipelines) task is the new recommended way to authenticate with Azure Artifacts and other NuGet repositories. The restore and push commands of this .NET Core CLI task no longer take new features and only critical bugs are addressed.

So, now I'm in an **infinite loop**.

I've implemented this for now, but I feel this is not correct:
```yaml
          - task: NuGetAuthenticate@1
          
          - task: DotNetCoreCLI@2
            displayName: Push to NuGet
            inputs:
              command: push
              packagesToPush: $(Pipeline.Workspace)/**/*.nupkg;!$(Pipeline.Workspace)/**/*.symbols.nupkg
              nuGetFeedType: 'internal'
              publishVstsFeed: "<GUID>"
```
