### DISCUSSION TITLE
Is there any problem to install ninja too

### DISCUSSION THREAD

**Discussion by ClausKlein** [actions/virtual-environments#2275] [Installed software]
Ninja is a small build system with a focus on speed. https://ninja-build.org/

It can be used with `cmake -B ../build -G Ninja -S $PWD`

And is much faster than make!

**Comment by maxim-lobanov** [comment]
Already discussed in https://github.com/actions/virtual-environments/issues/514 and https://github.com/actions/virtual-environments/issues/741
Considering pretty quick installation in runtime and existing of GitHub community tasks to install in runtime, we don't have plans to bake this tool into images.

**Reply by ClausKlein** [reply]
Exist there a better solution?

```yml
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [macos-latest, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2

    - name: Add nina to Build Environment
      shell: bash
      run: test $OSTYPE != "darwin19" && sudo apt-get install ninja-build || brew install ninja
```
