### DISCUSSION TITLE
IPC=host

### DISCUSSION THREAD

**Discussion by mattvb91** [actions/virtual-environments#2697] [Image configuration]
This may not be the right place but im trying to figure out how to set `--ipc=host` through my actions?

https://docs.docker.com/engine/reference/run/#ipc-settings---ipc

**Comment by maxim-lobanov** [comment]
Hello @mattvb91 , how do you use docker in your workflow?

**Reply by mattvb91** [reply]
Hi @maxim-lobanov managed to solve it with the post below. Thanks!

**Comment by catthehacker** [comment]
Below are examples of 3 possible ways to run Docker container with custom options
```yaml
jobs:
  job:
    # via run: step
    steps:
      - name: Run docker container
        run: docker run --ipc=host ubuntu:latest
    # via services:
    services:
      ubuntu:
        image: ubuntu
        options: --ipc=host
    # via container: 
    container:
      image: ubuntu:latest
      options: --ipc=host
```

Reference:
  - [`jobs.<job_id>.container`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer)
  - [`jobs.<job_id>.services`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idservices)
  - [`jobs.<job_id>.steps[*].run`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsrun)
