### DISCUSSION TITLE
Docker on macOS

### DISCUSSION THREAD

**Discussion by AdamSzendrei** [actions/virtual-environments#3284] [Installed software]
Docker is already preinstalled on Microsoft-hosted Ubuntu and Windows Agents.
Is there a roadmap for Docker on macOS as well?

**Comment by maxim-lobanov** [comment]
We can't install Docker on macOS due to legal issue (EULA license).
See related discussion in https://github.com/actions/virtual-environments/issues/17#issuecomment-614726536

**Comment by AdamSzendrei** [comment]
is there any way or documentation to install Docker at runtime?

**Reply by maxim-lobanov** [reply]
I haven't tested but https://medium.com/crowdbotics/a-complete-one-by-one-guide-to-install-docker-on-your-mac-os-using-homebrew-e818eb4cfc3 should work.
Brew and virtualbox are already pre-installed on Hosted runners:

**Reply by catthehacker** [reply]
Here is example job installing and using `docker` on `macos-latest` but be warned that performance is absolute disaster and just the installation itself takes 10 minutes
```yaml
  test-macos:
    name: Test on MacOS
    runs-on: macos-latest
    continue-on-error: true # Don't let macos test fail whole workflow
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Install MacOS Docker
        uses: docker-practice/actions-setup-docker@master

      - run: go test -v -timeout 1h -cover ./...
        env:
          CGO_ENABLED: 0
```

**Reply by catthehacker** [reply]
here is manual install that should work much faster, we're using it in https://github.com/nektos/act
[[gist]](https://gist.github.com/catthehacker/68702214908bcb10a8977bef0b087ba3)
```yaml
  test-macos:
    name: Test on MacOS
    runs-on: macos-latest
    continue-on-error: true # Don't let macos test fail whole workflow
    env:
      ISO_PATH: ~/.docker/machine/cache/boot2docker.iso
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/cache@v2
        with:
          key: boot2docker
          path: ${{ env.ISO_PATH }}
          restore-keys: boot2docker
      - name: Install Docker on macOS
        run: |
          printf "Downloading boot2docker.iso\n\n"
          mkdir -p ~/.docker/machine/cache/
          test -f ${{ env.ISO_PATH }} && printf "${{ env.ISO_PATH }} successfully restored" || wget "https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso" -O ${{ env.ISO_PATH }}
          printf "Installing Docker from Homebrew\n\n"
          brew install docker docker-machine
          printf "Creating Docker VM\n\n"
          docker-machine create --driver virtualbox --virtualbox-boot2docker-url ${{ env.ISO_PATH }} default
          docker-machine env default
          printf "Adding Docker VM info to environment\n\n"
          eval "$(docker-machine env default)"
          echo "DOCKER_TLS_VERIFY=$DOCKER_TLS_VERIFY" | tee -a $GITHUB_ENV
          echo "DOCKER_HOST=$DOCKER_HOST" | tee -a $GITHUB_ENV
          echo "DOCKER_CERT_PATH=$DOCKER_CERT_PATH" | tee -a $GITHUB_ENV
          echo "DOCKER_MACHINE_NAME=$DOCKER_MACHINE_NAME" | tee -a $GITHUB_ENV
          printf "Install Qemu for running containers with different architecture\n\n"
          docker run --rm --privileged tonistiigi/binfmt --install all
      - run: go test -v -timeout 30m -cover ./...
        env:
          CGO_ENABLED: 0
```
