### DISCUSSION TITLE
Issues adding path in windows

### DISCUSSION THREAD

**Discussion by robinmatz** [actions/virtual-environments#5107] [General questions] [answered]
Hi there,

I am facing issues with a ci job that depends on wc3270, a software that can be installed with chocolatey.

For the job to pass, I need to add the wc3270 installation folder to path. After some research, I came across this reference: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files

You can find my ci config here: https://github.com/robinmatz/Robot-Framework-Mainframe-3270-Library/blob/d68170fbe318062062cbe98d4ea2aa502c447caf/.github/workflows/run-tests.yml

As you can see, I install wc3270 with ``choco install wc3270``.

The output says: 
Software installed to 'C:\Program Files\wc3270' https://github.com/robinmatz/Robot-Framework-Mainframe-3270-Library/runs/5259461675?check_suite_focus=true#step:5:1216

Later in the script, I try to append this folder to the path by running ``echo "C:\Program Files\wc3270" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append``

Verifying the installation with ``echo (get-command wc3270.exe).Path`` however, throws the following error

> The term 'wc3270.exe' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

https://github.com/robinmatz/Robot-Framework-Mainframe-3270-Library/runs/5259461675?check_suite_focus=true#step:7:1

I would be very happy, if you could help me identify the error. 

For convenience, I also attached the .yml below:

```
name: tests

on: [push, pull_request]

jobs:
  tests:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: [3.7, 3.10.0]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install -y xvfb x3270 locales xterm
        sudo locale-gen en_US

    - name: Install dependencies windows
      if: matrix.os == 'windows-latest'
      run: |
        choco install wc3270

    - name: Install python dependencies
      run: python -m pip install -r requirements-dev.txt

    # - name: Lint
    #   run: |
    #     inv lint

    # - name: Run utests with coverage
    #   run: |
    #     coverage run --branch --source Mainframe3270/ -m pytest --verbose utest/
    #     coverage report
    #     coverage xml

    # - name: Upload unit test coverage to Codecov
    #   uses: codecov/codecov-action@v2
    #   with:
    #     files: coverage.xml
    #     flags: unit
    #     move_coverage_to_trash: true

    # - name: Run atests with coverage linux
    #   if: matrix.os == 'ubuntu-latest'
    #   run: |
    #     LANG=en_US.iso88591 xvfb-run coverage run --branch --source Mainframe3270/ -m robot --exclude no-ci --loglevel DEBUG atest/
    #     coverage report
    #     coverage xml

    - name: Run atests with coverage windows
      if: matrix.os == 'windows-latest'
      run: |
        echo "C:\Program Files\wc3270" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "C:\ProgramData\chocolatey\lib\WC3270" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo (get-command wc3270.exe).Path
        coverage run --branch --source Mainframe3270/ -m robot --exclude no-ci --loglevel DEBUG atest/

    # - name: Upload acceptance tests coverage to Codecov
    #   uses: codecov/codecov-action@v2
    #   with:
    #     files: coverage.xml
    #     flags: acceptance

    # - uses: actions/upload-artifact@v2
    #   if: ${{ always() }}
    #   with:
    #     name: Tests results python${{ matrix.python-version }}
    #     path: |
    #       log.html
    #       report.html
    #       output.xml
```
