### DISCUSSION TITLE
ROS2 not compiling with CMake 3.24.0 on GHA ubuntu 20.04 and 22.04

### DISCUSSION THREAD

**Discussion by SamerKhshiboun** [actions/virtual-environments#6179] [General questions]
CMake 3.24.0 is not compatible with ros ament_cmake (galactic, foxy, humble, rolling)
While CMake 3.23.0 does.

All builds related to ROS2 packages, in all 4 distros above, will fail
A [PR395](https://github.com/ament/ament_cmake/pull/395) has been merged for ament_cmake in all distros, but still not released outside.

Is it possible to use an older CMake version in GHA till ament_cmake fixes will be formally released for above distros ??

Thanks,
Samer

**Comment by al-cheb** [comment]
@SamerKhshiboun, you can downgrade cmake version in runtime using  [actions-setup-cmake](https://github.com/jwlawson/actions-setup-cmake) task.

```
- name: Setup cmake
  uses: jwlawson/actions-setup-cmake@v1.12
  with:
          cmake-version: '3.23.x'
- name: Use cmake
  run: cmake --version
```
