### DISCUSSION TITLE
Looks there are `RUNNER_OS` and `RUNNER_ARCH` did not get setup for windows environments

### DISCUSSION THREAD

**Discussion by chenrui333** [actions/virtual-environments#6667] [General questions] [answered]
Just found out that both `RUNNER_OS` and `RUNNER_ARCH` are empty for windows-2019 and windows-2022 environments.

This is the action run I referred to, https://github.com/chenrui333/github-action-test/actions/runs/3587487284/jobs/6037890862

**Comment by panekj** [comment, marked as answer]
It should be `$env:RUNNER_OS`, not `$RUNNER_OS`

**Reply by chenrui333** [reply]
Let me give that a try. Not quite familiar with Windows myself 😅

**Reply by chenrui333** [reply]
This is what I tried, still not working

```
  windows_jobs:
    strategy:
      matrix:
        os:
          - windows-2019
          - windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - run: |
          echo "RUNNER_OS: $env::RUNNER_OS"
          echo "RUNNER_ARCH: $env::RUNNER_ARCH"
```

Action run ref, https://github.com/chenrui333/github-action-test/actions/runs/3587755034/jobs/6038440409
![image](https://user-images.githubusercontent.com/1580956/204925810-19d99910-2c33-4c47-ad26-4ff262c07e14.png)
