### DISCUSSION TITLE
Previous and current version container images used in same job with matrix

### DISCUSSION THREAD

**Discussion by MikeMcC399** [actions/virtual-environments#7436] [General questions]
- Cypress Cloud users with GitHub Actions are reporting an issue for parallel test recording on Chrome at the moment. See issue https://github.com/cypress-io/github-action/issues/602.

- This concerns the rollout of [ubuntu-22.04: 20230409.1](https://github.com/actions/runner-images/blob/releases/ubuntu22/20230409/images/linux/Ubuntu2204-Readme.md) which bumps the version of Google Chrome from `111.0.5563.146` to `112.0.5615.49`, which is a major version change. See also https://github.com/actions/runner-images/pull/7419.

- It seems that the images started by a matrix strategy in the same job are currently sometimes invoked as `20230402.1` (previous) and sometimes as `20230409.1` (current).

    ```yml
    test:
        runs-on: ubuntu-latest
        strategy:
        matrix:
            # run copies of the current job in parallel
            containers: [1, 2, 3, 4]
    ```

Is this expected or is it a bug?

Edit: This question should probably be in https://github.com/actions/runner/discussions instead of `runner-images`. Feel free to move it.
Since the rollout is now > 99.9% complete, this issue is no longer occurring, however it can be expected to happen at the next rollout, so feedback is still welcome!

**Comment by MikeMcC399** [comment]
I have transferred this question to the GitHub product feedback page

- https://github.com/orgs/community/discussions/52956

**Comment by erik-bershel** [comment]
@MikeMcC399
Hello! Such a situation is quite possible. Updating the image version does not happen simultaneously - it is a quite time-consuming process due to many reasons. Therefore, at the same moment in time, two different versions of the runner can be found in the ecosystem, which happened in this case.

**Comment by MikeMcC399** [comment]
Hi @erik-bershel 

In the meantime I've submitted https://github.com/orgs/community/discussions/52956 as an enhancement request. It has however not received any response so far.

**Reply by erik-bershel** [reply]
You did it right - unfortunately, we cannot influence this from our side.

**Comment by sgronblo** [comment]
Would it not be possible to allow users to specify the version explicitly? Our Cypress tests currently cannot be run due to this behavior. It would be nice if when this happens we could temporarily put a version in place to ensure all runners use the same version and then remove the version specifier once the rollout is complete.

It would be even better if you could put something like "ensure_same_runner_image: true" in the job definition and have Github not mix up different runner images.

**Reply by ilia-shipitsin** [reply]
maybe specifying container images could help (i.e. running CI inside some containers)

```
name: CI

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: php:${{ matrix.php_version }}
    strategy:
      matrix:
        php_version: ["8.2", "8.1"]
        
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: php --version
```
