### DISCUSSION TITLE
What are the differences between image used for GH Runners and Self-hosted runners?

### DISCUSSION THREAD

**Discussion by simpson** [actions/virtual-environments#7618] [General questions]
I recently got the ARC runners set working with a lot of trial and error. The issue I'm facing now is that all of my builds work fine when using GH hosted runners (runs-on: ubuntu-latest), but when I shift to using my runner set the builds fail because it seems like there aren't the same packages installed (Ex. Python).

Are the differences in the GH image and the image that ARC runners use documented anywhere to understand the differences? Why not just use the same image? I'm using the latest action-runner image as far as I can tell.

Thanks!

```
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        resources:
          requests:
            memory: "12G"
          limits:
            memory: "16G"
```
