### DISCUSSION TITLE
[SOLVED] Force cmake to use gcc/mingw makefiles on Windows runner

### DISCUSSION THREAD

**Discussion by fangq** [actions/virtual-environments#7998] [General questions] [answered]
I use github action to build a [binary Python module](https://github.com/fangq/mcxcl/tree/master/pmcxcl). It works by calling `python setup.py bdist_wheel` in the action script, and [`setup.py`](https://github.com/fangq/mcxcl/blob/master/pmcxcl/setup.py) calls `cmake` to build the module [on different platforms](https://github.com/fangq/mcxcl/tree/master/.github/workflows). I have trouble forcing `cmake` to use mingw64-gcc as the compiler on Windows. it insists on using `msvc` to build my code (it can be compiled but the execution is incorrect).

I've spent a few days on this, [tried a bunch of settings](https://github.com/fangq/mcxcl/commits/master), all of them had failed, below link is a summary for some of my attempts, together with their error logs

https://github.com/actions/runner-images/issues/1621#issuecomment-1656404279

does gcc/mingw generator work on the windows runner image? what do I need to switch to it?

**Comment by fangq** [comment, marked as answer]
never mind. figured it out. it turns out one has to install ninja via msys2 before one can set `-GNinja` with cmake.

although `cmake -G` lists Ninja, it does not mean the system has ninja system installed, it just means it can work with it. this is why I thought all generators in the printed list have already been installed.

I managed to use the setting from
https://github.com/scivision/rpn-calc-fortran/blob/main/.github/workflows/ci_cmake.yml

specifically
```
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-ninja

    - name: Put MSYS2_MinGW64 on PATH
      run: echo "D:/a/_temp/msys64/mingw64/bin" >> $GITHUB_PATH
```

presumably, one could also use [other packages](https://github.com/marketplace/actions/install-ninja-build-tool) to install ninja as well. 


anyways, once ninja is added, after passing `-GNinja` to cmake, it finds mingw64 gcc and build the binaries without any problem.
