### DISCUSSION TITLE
[AzureDevops] install DotNet SDK 8.0

### DISCUSSION THREAD

**Discussion by JaehwanMango** [actions/virtual-environments#8645] [General questions] [answered]
Can you please share with us how to install DotNet SDK 8.0

**Comment by ilia-shipitsin** [comment, marked as answer]
depending on CI used, 

GHA [actions/setup-dotnet](https://github.com/actions/setup-dotnet):
```
name: CI

on: [ push, pull_request, workflow_dispatch ]

jobs:

  build:

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
          
      - name: Run a multi-line script
        run: |
          dotnet --list-sdks
```

ADO [UseDotNET@2](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/use-dotnet-v2?view=azure-pipelines):
```

trigger:
- main

pool:
  vmImage: windows-latest

steps:

- task: UseDotNet@2
  inputs:
    version: 8.x
    includePreviewVersions: true

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'dotnet --list-sdks'
```
