### DISCUSSION TITLE
Strange difference between host system and WSL system

### DISCUSSION THREAD

**Discussion by Vampire** [actions/virtual-environments#8791] [General questions] [answered]
Given the following workflow:
```yaml
name: Debug
on:
  push: {}
jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
    - name: Setup Debian
      uses: Vampire/setup-wsl@v2
      with:
        distribution: Debian
        additional-packages: python3-pip
    - name: Install HTTPie in Debian
      shell: wsl-bash {0}
      run: python3 -m pip install --upgrade pip wheel httpie
    - name: Install HTTPie in Windows
      run: python -m pip install --upgrade pip wheel httpie
    - name: Check Python version in Debian
      shell: wsl-bash {0}
      run: python3 --version
    - name: Check Python version in Windows
      run: python --version
    - name: Check HTTPie version in Debian
      shell: wsl-bash {0}
      run: http --version
    - name: Check HTTPie version in Windows
      run: http --version
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: always()
```
If you execute this and then SSH into the runner once the tmate session is setup and prints the connection details.
If you now do
```shell
http -fp HBh POST https://store.rg-adguard.net/api/GetFiles type=ProductId url=9p804crf0395
```
You get a "403 Forbidden" response.
If you do the same just in the WSL distribution
```shell
wsl http -fp HBh POST https://store.rg-adguard.net/api/GetFiles type=ProductId url=9p804crf0395
```
you get a "200 OK" response.

I cannot see why it is working from within the WSL distribution but not from the host system.
From the host system it also worked fine until recently before the tests for my `setup-wsl` action went to red because of this.

If I do
```shell
http https://api.ipify.org format==json | jq .ip
```
and
```shell
wsl http https://api.ipify.org format==json | jq .ip
```
I get the same IP

If I do
```shell
http -fp b POST https://echo.free.beeceptor.com/api/GetFiles type=ProductId url=9p804crf0395
```
and
```shell
wsl http -fp b POST https://echo.free.beeceptor.com/api/GetFiles type=ProductId url=9p804crf0395
```
I get the exact same response.

If I listen to port 1234 on `my.serv.er` using `nc -l -p 1234 | xxd` and then do
```shell
http -f POST http://my.serv.er:1234/api/GetFiles type=ProductId url=9p804crf0395
```
and
```shell
wsl http -f POST http://my.serv.er:1234/api/GetFiles type=ProductId url=9p804crf0395
```
I get the exact same bytes transferred.

I'm a bit lost why this behaves differently.
Does anyone have any idea?
