### DISCUSSION TITLE
How can I run the ubuntu image

### DISCUSSION THREAD

**Discussion by moazelgandy** [actions/virtual-environments#9333] [Image configuration]
I want to run the ubuntu image in the workflow

**Comment by Alexey-Ayupov** [comment]
Please use the next snippet to run the ubuntu latest image
```
jobs:
  Run-on-Ubuntu:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - ...
 ```
More details could be found here - https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners
