### ISSUE TITLE
Ubuntu 18.04 Virtual Environment: MongoDB GPG key issue

### ISSUE THREAD

**Issue by darkwizard242** [actions/virtual-environments#1019]
**Describe the bug**
Appears that the mongodb gpg key is missing on Ubuntu 18.04 LTS virtual environment

**Area for Triage**: 
Servers

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Clean update of repository cache using `sudo apt-get update`

**Actual behavior**
An error for mongodb repository's gpg key. 

To reproduce, run `sudo apt-get update` on Ubuntu 18.04 LTS virtual environment.

Error:
```shell
Err:14 https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 Release.gpg
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 656408E390CFB1F5

W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 656408E390CFB1F5
W: Failed to fetch https://repo.mongodb.org/apt/ubuntu/dists/bionic/mongodb-org/4.2/Release.gpg  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 656408E390CFB1F5
```

**Temporary workaround**
Adding the missing (or updated) key manually in a step within the workflow with something like the following:

```yaml
steps:
- name: Adding missing key and update repository cache
  run: |
      sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 656408E390CFB1F5
      sudo apt-get update
```

**Comment by clhuang** [comment]
it seems to be a mistake on the mongodb side of things-- the key 656408E390CFB1F5 seems to be their 4.4 release signing key:
![image](https://user-images.githubusercontent.com/1694228/84070417-f59f7e80-a980-11ea-830a-1d9f639a2af9.png)
(from https://keyserver.ubuntu.com/pks/lookup?search=mongodb&fingerprint=on&op=index)

**Comment by miketimofeev** [comment]
Hi @darkwizard242 as @clhuang said this is MongoDB issue, we're experiencing the same issue at the moment and can't build an Ubuntu 16 or 18 image.

**Comment by darkwizard242** [comment]
@miketimofeev @clhuang - Thanks for checking up on that. Please forgive my ignorance, is there any issue with adding the key 656408E390CFB1F5 to the Ubuntu (bionic/xenial) image builds? Purely asking out of curiosity.

**Comment by miketimofeev** [comment]
@darkwizard242 actually it looks like the issue has already resolved,
```
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: check update18
        run: |
          sudo apt-get update
```
works just fine for me
