### ISSUE TITLE
Unable to compile project that links to atls.lib

### ISSUE THREAD

**Issue by cmconti** [actions/virtual-environments#1020]
**Describe the bug**
We have a number of C++ projects that link to atls.lib, are built using the v141 toolset, and are not using the spectre mitigations.  Starting with 20200531.1, compilation now fails with the error:
`##[error]LINK(0,0): Error LNK1104: cannot open file 'atls.lib'`

This worked previously with 20200517.1
Further investigation shows that the installed VS2019 image appears to be missing the components:
- Microsoft.VisualStudio.Component.VC.v141.ATL
- Microsoft.VisualStudio.Component.VC.v141.MFC

**Area for Triage**: C/C++

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
Expect project to compile

**Actual behavior**
Attached a zip of a sample project (just an empty wizard-generated ATL exe) and a zip of the pipeline logs.

[Az_ATLS.zip](https://github.com/actions/virtual-environments/files/4748093/Az_ATLS.zip)
[logs_1922.zip](https://github.com/actions/virtual-environments/files/4748094/logs_1922.zip)

**Comment by miketimofeev** [comment]
Hi @cmconti! These workloads were supposed to be installed during the build
https://github.com/actions/virtual-environments/releases/tag/win19%2F20200531.1
Could you please try to install them manually by adding this as the first step of your workflow? Does it help?
```
jobs:
  add workflows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: add workload
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
          $InstallPath = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
          $WorkLoads = '--add Microsoft.VisualStudio.Component.VC.v141.ATL.ARM.Spectre '
          '--add Microsoft.VisualStudio.Component.VC.v141.ATL.ARM64.Spectre ' + `
          '--add Microsoft.VisualStudio.Component.VC.v141.ATL.Spectre ' + `
          '--add Microsoft.VisualStudio.Component.VC.v141.MFC.ARM.Spectre ' + `
          '--add Microsoft.VisualStudio.Component.VC.v141.MFC.ARM64.Spectre ' + `
          '--add Microsoft.VisualStudio.Component.VC.v141.MFC.Spectre '
          $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"", $WorkLoads, '--quiet', '--norestart', '--nocache')
          $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
        shell: powershell
```

**Comment by cmconti** [comment]
I have not done much with multiple jobs, and can't find any examples of adding to the workflow.  What is the proper syntax for merging the above yml snippet into my pipeline file?

```yml
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x86'
  buildConfiguration: 'Debug'

steps:
#- script : |
#    "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" export --installpath "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise" --config "%TEMP%\atls.vsconfig" --noweb --quiet
#    type "%TEMP%\atls.vsconfig"

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
```
