### ISSUE TITLE
Update Python to 3.8.3

### ISSUE THREAD

**Issue by retnikt** [actions/virtual-environments#1023]
**Tool information**
- Tool name:  Python
- Tool license:  PSF License
- Add or update?  Update
- Desired version:  3.8.3
- Approximate size: 

**Area for Triage**:

Python

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

(PS: while checking which OSs are affected I noticed that in the README for Ubuntu 16.04 and 18.04 Python is listed twice)

**Comment by dibir-magomedsaygitov** [comment]
Hello @retnikt.

To get desired version of Python you can simply use this setup-python task.
```
steps:
- uses: actions/checkout@v2
- uses: actions/setup-python@v2
  with:
    python-version: '3.8.3'
    architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
- run: python my_script.py
```
Also, python has been updated to version 3.8.3 on Ubuntu 20.04 LTS. `20200607.1` image with this changes is currently deploying and will be available later this week. I'll post message when it will be ready to use.

Feel free to contact us if you have any questions or concerns.
