### ISSUE TITLE
[Windows] Started to get LINK : fatal error LNK1104: cannot open file 'mfc140u.lib' this week

### ISSUE THREAD

**Issue by Shchvova** [actions/virtual-environments#1028]
**Describe the bug**
I have a big build pipeline, I got it working, but now I am getting erros building via Actions. Everything still works on my local machine. More thant that. I tried to build from point which was working week ago, and rebuilding that job now fails.
Was working week ago:
Now fails: https://github.com/Shchvova/corona/runs/753535362?check_suite_focus=true
Then working: https://github.com/coronalabs/corona/runs/729889290?check_suite_focus=true
Note that SHA is same for both builds e365728

**EDIT:** After some investigation, I found that Visual Studio generated files are ferring to the mfc140u.lib. So probably some part of the installation got deleted improperly?

**Area for Triage**: 
Area: C/C++
Visual Studio

**Question, Bug, or Feature?**: 
"Question", "Bug"

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x ] Windows Server 2019

**Expected behavior**
I would expect that builds which were working not stop working.

**Actual behavior**
Build now fails

1. Step 1
I created a workflow which fails faster (not after hour, but in like 15 minutes)
https://github.com/Shchvova/corona/runs/757650052?check_suite_focus=true

Really, If I knew how to fix this, I would. Is it possible some wrong props files are included in visual studio? I don't see anything 140 referenced in my code. Could it be binaries? This is frustrating...

**Comment by Shchvova** [comment]
OK. So adding this step solved my issue. But probably some package got removed without mention of it in the changelog:
```yml
      - name: Add NuGet
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify --channelId VisualStudio.16.Release --productId Microsoft.VisualStudio.Product.Enterprise -q --includeRecommended --add "Microsoft.VisualStudio.Component.VC.ATL" --add "Microsoft.VisualStudio.Component.VC.ATLMFC" --add "Microsoft.VisualStudio.Component.VC.v141.x86.x64" --add "Microsoft.VisualStudio.Component.VC.140" --add "Microsoft.VisualStudio.Component.WinXP" --add "Microsoft.VisualStudio.Component.VC.v141.ATL" --add "Microsoft.VisualStudio.Component.VC.v141.MFC"

```

While quick fix works, it is alarming to see componets gone without changes in the [file](https://github.com/actions/virtual-environments/commits/master/images/win/Windows2019-Readme.md)
(also it takes extra 16 minutes)
