### ISSUE TITLE
Update/Add mdBook

### ISSUE THREAD

**Issue by PsiACE** [actions/virtual-environments#105]
**Tool information**
- Tool name: mdBook
- Add or update? Add
- Desired version: Latest
- Approximate size:  0.93 MB, But there are many dependencies.
- If this is an add request:
  - Brief description of tool: mdBook is a utility to create modern online books from Markdown files.
  - URL for tool's homepage: https://github.com/rust-lang/mdBook

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

Yes, we can install it during the build. Just run `cargo install mdbook`, of course, this requires a Rust environment, and Linux support only. But it takes about 15 minutes to execute each time, and mdBook is already a widely used tool.

**Are you willing to submit a PR?**
I don't know, if I'm free this weekend.

**Comment by peaceiris** [comment]
We can install it as a binary file `mdbook-v0.3.5-x86_64-unknown-linux-gnu.tar.gz`.

**Comment by PsiACE** [comment]
> 我們可以將其安裝為二進製文件`mdbook-v0.3.5-x86_64-unknown-linux-gnu.tar.gz`。

Okay, I'll try to improve my `Actions`.

**Comment by peaceiris** [comment]
Here is an example mdbook workflow to deploy to GitHub Pages with GitHub Actions.

[mdbook example workflow - peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages)

**Comment by peaceiris** [comment]
The install step completes in 1 sec. The total duration is 14 sec. Fast!

**Comment by PsiACE** [comment]
Good job. I used some of your code, it works fine now.

```yml
name: Deploy Docs

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    release:
        name: "GitHub Pages"
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout Repository"
              uses: actions/checkout@v1
              
            - name: Setup mdBook
              run: |
                    export MDBOOK_VERSION="v0.3.5"
                    export MDBOOK_TARBALL="mdbook-${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
                    wget -q "https://github.com/rust-lang/mdBook/releases/download/${MDBOOK_VERSION}/${MDBOOK_TARBALL}"
                    tar -zxvf "${MDBOOK_TARBALL}"
                    rm "${MDBOOK_TARBALL}"
                    mkdir ~/bin
                    mv ./mdbook ~/bin/
                    echo "::add-path::~/bin"
            - name: "Build Docs"
              run: mdbook build

            - name: "Deploy Docs"
              uses: JamesIves/github-pages-deploy-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BASE_BRANCH: master
                  BRANCH: gh-pages
                  FOLDER: docs/book
```

**Comment by peaceiris** [comment]
[peaceiris/actions-mdbook: GitHub Actions for mdBook (rust-lang/mdBook)](https://github.com/peaceiris/actions-mdbook#table-of-contents)

```yaml
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.3.5'
        # mdbook-version: 'latest'
```

cf. https://github.com/rust-lang/mdBook/issues/1090
