### ISSUE TITLE
Update/Add mongodb

### ISSUE THREAD

**Issue by ritmos** [actions/virtual-environments#1080]
**Tool information**
- Tool name: mongodb community server
- Tool license: SSPL
- Add or update? Add
- Desired version: Latest, which is 4.2.8 as of today
- Approximate size: 18 MB
- If this is an add request:
  - Brief description of tool: MongoDB is the famous no-sql database
  - URL for tool's homepage: https://www.mongodb.com/try/download/community

**Area for Triage**:
# Area: MongoDB
- valueFor: '**Area for Triage**'
  contains: 'MongoDB'
  addLabels: ['Area: MongoDB']

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-os-x/
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-windows/

**Tool installation time in runtime**
Few minutes

**Are you willing to submit a PR?**
Only if it's the only way to get mongodb included

**Comment by maxim-lobanov** [comment]
Hello, we have already added MongoDB on images in scope of #20 a week ago.
Could you please if it works for you?

**Comment by miketimofeev** [comment]
And, unfortunately, MongoDB 4.2.* is not available for Ubuntu20 at the moment

**Comment by ritmos** [comment]
Hi,
Just tried with 20.04. and sadly it is not available. 
I also tried with 1804 and I saw that the CLI is there but not the daemon, or at least it is not running and it's name is not what should be expected in ubuntu.

I'v tried executing the following command in azure pipelines without sucess:
sudo systemctl start mongod

Am I expected to install it or run it in a different way? Any help is greatly appreciated

**Comment by maxim-lobanov** [comment]
@ritmos , as Mikhail mentioned above, looks like MongoDB doesn't support Ubuntu 20.04 yet: https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/ so we can't install it there.

As for the ubuntu-1804, + @dsame could you please take a look?

**Comment by dsame** [comment]
@ritmos 

Hi, the flow confirmed to work:
```
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: launch
      shell: bash
      run: |
        mkdir /tmp/d
        mongod --dbpath /tmp/d --fork --logpath /tmp/log
        sleep 5
        echo 'db'  | mongo 127.0.0.1
```
I suspect you are expecting to see mongo v2.6 which is packaged with Ubuntu by default. Pay attention we does not support that pretty old version but have v4 installed.

You can install mongo v2 with apt in your workflow though
