### ISSUE TITLE
repository revision at queue time for multi-repository pipeline

### ISSUE THREAD

**Issue by compnerd** [actions/virtual-environments#1086]
**Describe the bug**
I dont think that this is a bug, merely a documentation thing.  I am trying to figure out how to optionally specify the revision for repositories (as variables or some other means) to checkout multiple repositories in a pipeline.  Variables (even with libraries for pre-defined values) do not get applied at the right time to allow the user to add a variable to change the checkout point.

**Area for Triage**: 
question

**Question, Bug, or Feature?**: 
Question

**Virtual environments affected**
- [X] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**
Be able to specify the revision for repositories

**Actual behavior**

```yaml
resources:
  repositories:
    - repository: apple/swift-log
      type: github
      name: apple/swift-log
      endpoint: GitHub
    - repository: apple/swift-numerics
      type: github
      name: apple/swift-numerics
      endpoint: GitHub
```

This can specify an explicit ref or be defaulted to master.  I would like to be able to specify the ref at the time that the build is queued.
