### ISSUE TITLE
gcloud openssl issue on ubuntu runner

### ISSUE THREAD

**Issue by lechen26** [actions/virtual-environments#1106]
our CI workflow  stopped working and we get the following error after using 'gcloud auth docker-configure'
`ERROR: gcloud failed to load: /tmp/_MEIYv9Scj/libssl.so.1.1: version OPENSSL_1_1_1 not found (required by /usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so)
`

we use Ubuntu-18.04 runner. 20200614.1

i've investigated and seems like when using latest version of gcloud (through setup-gcloud action) which is 298.0.0 we get this failure, while when switching back to previous version 297.0.1 we are OK again.
i've noticed this comment on the release note of 298:
```
"Changed the bq and gcloud command-line tools to prefer Python 3 for component-based Cloud SDK installs on Unix. See gcloud topic startup for information on configuring the Python interpreter used by the Cloud SDK."
```

i know this runner includes both python2 and python3, while the default is python2.
also openssl 1.1.1 looks installed. i'm not sure why it tries to reach to /tmp/_MEIYv9Scj/libssl.so.1.1.

i've added 2 envs on the workflow:
```
CLOUDSDK_PYTHON: python3
LD_LIBRARY_PATH: "/usr/local/lib"
```
and latest version started working again.

so my question is, i'm not sure who should 'fix' the problem, 
the gcloud-sdk works locally.
sorry if its not the right location, wasnt sure where exactly to open this issue.

thanks

**Comment by al-cheb** [comment]
Hello, @lechen26

Could you please provide a minimal step to reproduce, becase I can't reproduce the issue from my side with the test pipeline:

```
jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '298.0.0'
      - run: gcloud info
      - name: gcloud
        run: |
         gcloud auth configure-docker && docker pull ubuntu
```

![image](https://user-images.githubusercontent.com/47745270/85540175-57b5e000-b61f-11ea-9aa9-69aefa508281.png)

**Comment by al-cheb** [comment]
@lechen26, Any updates?

**Comment by al-cheb** [comment]
Feel free to open the thread if you have any concerns.

**Comment by jimmyvo2410** [comment]
same problem here

**Comment by al-cheb** [comment]
@jimmy-vo, Could you please provide steps to reproduce the issue?

**Comment by jimmy-vo** [comment]
Here is the code, but there are my GitHub secret variables in there. You may replace them with yours. `docker-compose -f docker-compose.yml build` just builds an angular application
```
name: Build and Deploy to Cloudrun

on:
  push:
    branches: 
      - master
      
env:
  MAX_INSTANCE_NGINX: 5
  SERVICE_NGINX_ML: ml
  SERVICE_NGINX_TECH: tech
  SERVICE_NGINX_DEV: dev
  SERVICE_BACKEND: backend
  IMAGE_NGINX_ML: gcr.io/${{ secrets.GCP_PROJECT }}/ml:${{ github.sha }}
  IMAGE_NGINX_TECH: gcr.io/${{ secrets.GCP_PROJECT }}/tech:${{ github.sha }}
  IMAGE_NGINX_DEV: gcr.io/${{ secrets.GCP_PROJECT }}/dev:${{ github.sha }}
  IMAGE_BACKEND: gcr.io/${{ secrets.GCP_PROJECT }}/backend:${{ github.sha }}
  GKE_ZONE: us-central1
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_ACCOUNT: ${{ secrets.GCP_ACCOUNT }}
  GITHUB_SHA: ${{ github.sha }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 
      
    # Setup Service account: Cloud Run Admin, Cloud Build Editor, Service Account User, Editor, Cloud Run Service Agent
    # to get key: cat *.json  | base64
    - name: Setup Gcloud 
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_KEY }}
        export_default_credentials: true
      env:
        CLOUDSDK_PYTHON: python3

    - name: Connect Gcloud
      run: |
        gcloud auth configure-docker
    - name: Build
      run: |
        docker-compose -f docker-compose.yml build
        
    - name: Deploy
      run: |
        if [[ "$(docker images -q $IMAGE_NGINX_TECH 2> /dev/null)" != "" ]]; then
          docker push $IMAGE_NGINX_TECH
          gcloud run deploy $SERVICE_NGINX_TECH \
            --image $IMAGE_NGINX_TECH \
            --region $GKE_ZONE \
            --port 80 \
            --platform managed \
            --allow-unauthenticated \
            --service-account $GCP_ACCOUNT \
            --max-instances $MAX_INSTANCE_NGINX
        else
          echo "IMAGE_NGINX_TECH not found"
        fi
```
