### ISSUE TITLE
Azure CLI prefixed az ad app permission fail on Microsoft Hosted Agents pool windows-latest

### ISSUE THREAD

**Issue by mcalnd70** [actions/virtual-environments#1151]
**Describe the bug**
Commands starting with "az ad app permission" fail when using the '**windows-latest**' pool for Microsoft Hosted Agents

**Area for Triage**: 

Deployment/Release

**Question, Bug, or Feature?**: 

Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x ] Windows Server 2019

**Expected behavior**
Running any Azure CLI command with az ad app permission should work and complete or return output when targeting the 'windows-latest' pool

**Actual behavior**
Attempt to use ANY "az ad app permission" command fails with..

```
az : command ran in 6.441 seconds.
At D:\a\1\a\scripts\AzureCLI\AzureActiveDirectory\Update_AppReg_APIPerms.ps1:37 char:1
+ az ad app permission list --id $clientappid --verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (command ran in 6.441 seconds.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

To fix this, selecting the '**vs2017-win2016**' pool works OK - I have not tried other pools, just noticed this with windows-latest. 

Its taken days to get this worked out!

**Comment by al-cheb** [comment]
Hello, @mcalnd70
Could you please provide an additional information about build?
1. `az --version`
2. ImageVersion - Initialize job(Azure Pipelines) / Set up job (GitHub)

**Comment by mcalnd70** [comment]
@al-cheb Versions are here https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md

This is running Azure CLI commands inside a Powershell Script invoking the Azure CLI task in Azure DevOps Pipelines

```
- task: AzureCLI@2
displayName: 'Azure CLI : Update the Azure AD App Registration Client PERMISSIONS that will access the API'
inputs:
   azureSubscription: 'MyAzureSubscriptionServiceConnection'
   scriptType: ps
   scriptPath: '$(System.ArtifactsDirectory)/scripts/AzureCLI/AzureActiveDirectory/Update_AppReg_APIPerms.ps1'
   arguments: '-clientappregname "my-client-app-id" -apiappregname "my-api-app-id"
```

Any prefixed "az ad app permission" command fails...eg..

`az ad app permission list --id "my-client-app-id"`

Switching the pool from 'windows-latest' to 'vs2017-win2016' and the script works fine. Script also runs locally OK

**Comment by miketimofeev** [comment]
@mcalnd70 could you please change scriptType to  `scriptType: pscore`? Does it help?

**Comment by mcalnd70** [comment]
@miketimofeev Just tried this, it behaves differently, some commands work, some don't

The az ad permission **list** works 
The **delete / add / grant** sub commands all fail with the same generic error...

```
The command failed with an unexpected error. Here is the traceback:

not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-_kvuguic\knack\knack\cli.py", line 215, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 654, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 718, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 709, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\command_modules\role\commands.py", line 69, in graph_err_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 688, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\commands\__init__.py", line 325, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\core\__init__.py", line 545, in default_command_handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\command_modules\role\custom.py", line 863, in add_permission
ValueError: not enough values to unpack (expected 2, got 1)

To open an issue, please run: 'az feedback'
```

**Comment by miketimofeev** [comment]
@mcalnd70 it looks like some Azure-cli error. Could you try to add a step to update az-cli in runtime? 
```
- powershell: 'choco upgrade -PackageName azure-cli'
  displayName: 'Update az-cli'
```
It will bump the version to 2.8.0. We're going to start image rollout with this version today.

**Comment by mcalnd70** [comment]
@miketimofeev I've just seen your prior updated comment with the pipelines step - ran that. here is the output...

```
azure-cli                          2.7.0 *

command-modules-nspkg              2.0.3
core                               2.7.0 *
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
azure-devops                      0.18.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Program Files\Common Files\AzureCliExtensionDirectory'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal



Please let us know how we are doing: https://aka.ms/clihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
You have 2 updates available. Consider updating your CLI installation with 'https://aka.ms/installazurecliwindows'. Detailed instructions can be found at https://aka.ms/doc/UpdateAzureCliMsi
```

Run the same thing again but with the choco update to 2.8.0, and the same errors as-above appeared

**Comment by miketimofeev** [comment]
@mcalnd70 just to clarify, did your script work on win2019 sometime ago and then stopped with the errors or it never worked?

**Comment by mcalnd70** [comment]
@miketimofeev It has never worked against win2019 (latest). I struggled on for ages trying to work out why, but yesterday switched to an older agent pool - worked first time, just like when I run it locally

**Comment by miketimofeev** [comment]
@mcalnd70 could you share minimal repro steps for the initial error? Because this inline command itself works for us
```
steps:
- task: AzureCLI@2
  displayName: 'Azure CLI '
  inputs:
    azureSubscription: 'valeche_delete'
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: 'az ad app permission list --id "subscription id"'
```

**Comment by mcalnd70** [comment]
Hi @miketimofeev 

```
- task: AzureCLI@2
  displayName: 'Azure CLI : Update the Azure AD App Registration Client PERMISSIONS that will access the API'
  inputs:
    azureSubscription: 'MySubscriptionConnection'
    scriptType: ps
    scriptPath: '$(System.ArtifactsDirectory)/scripts/AzureCLI/AzureActiveDirectory/Update_AppReg_APIPerms.ps1'
    arguments: '-clientappregname $(appregnameclient) -apiappregname $(appregnameapi)'
```

This is the PowerShell script that contains the Azure CLI commands...There are a lot of Write-Host statements here so that I can use them as break-points to understand where a failure occurs...

```
<#
.SYNOPSIS
Allows API permissions to the Client App for the API Appreg exposed-API scope with AAD Graph
.DESCRIPTION
Using Azure CLI inside a Powershell script
.EXAMPLE
.\Update_AppReg_APIPerms.ps1 -clientappregname APPREG-IN-AAD -apiappregname APPREG-IN-AAD2
.NOTES
Written by mcalnd70 @ GitHub - June 2020
.LINK
To display these messages in-line type "Get-Help .\scriptname -full"
#>
param (
	[Parameter(Mandatory=$true)]
    [string]$clientappregname,
    [Parameter(Mandatory=$true)]
    [string]$apiappregname
)

# Obtain details for Appregs passed in as parms
$clientappid = & az ad app list --display-name $clientappregname --query [0].appId -o tsv
$apiappid = & az ad app list --display-name $apiappregname --query [0].appId -o tsv
#
Write-host $clientappregname $clientappid
Write-host $apiappregname $apiappid
#
# Obtain the API Files.Read id from the AppReg manifest
$apipermsid = & az ad app list --display-name $apiappregname --query [0].oauth2Permissions[0].id -o tsv 
Write-host $apipermsid
#
# Set perms for API
Write-host "DEBUG 1"
az ad app permission delete --id $clientappid --api $apiappid
Write-host "DEBUG 2"
az ad app permission add --id $clientappid --api $apiappid --api-permissions $apipermsid=Scope
Write-host "DEBUG 3"
az ad app permission grant --id $clientappid --api $apiappid --expires never
```
