### ISSUE TITLE
Hello, @lechen26

### ISSUE THREAD

**Issue by MHMYunos2020** [actions/virtual-environments#1159]
Hello, @lechen26

Could you please provide minimal steps to reproduce the issue , because I can't reproduce from my side with the test pipeline:

```
jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '298.0.0'
      - run: gcloud info
      - name: gcloud
        run: |
         gcloud auth configure-docker && docker pull ubuntu
```

![image](https://user-images.githubusercontent.com/47745270/85540175-57b5e000-b61f-11ea-9aa9-69aefa508281.png)

_Originally posted by @al-cheb in https://github.com/actions/virtual-environments/issues/1106#issuecomment-648740258_
