### ISSUE TITLE
Homebrew no longer works on Mac OS Jobs

### ISSUE THREAD

**Issue by JasonGross** [actions/virtual-environments#1198]
**Describe the bug**

I have the build job
```
name: CI (Coq, MacOS)

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:

    runs-on: macos-latest

    env:
      NJOBS: "2"
      COQ_VERSION: "master"

    # initial steps copied from https://github.com/coq/coq/blob/cfc41cb79e2364f19d97e7e5c94262132972b0b2/azure-pipelines.yml#L41-L110
    steps:
    - name: Install system dependencies
      run: |
        set -e
        brew update
        (cd $(brew --repository)/Library/Taps/homebrew/homebrew-core/ && git fetch --shallow-since=${HBCORE_DATE} && git checkout ${HBCORE_REF})
        brew install gnu-time opam pkg-config gtksourceview3 adwaita-icon-theme
        pip3 install macpack
      env:
        HOMEBREW_NO_AUTO_UPDATE: "1"
        HBCORE_DATE: "2019-09-03"
        HBCORE_REF: "44ee64cf4b9f2d2bf000758d356db0c77425e42e"
```

I get the error
```
==> Installing adwaita-icon-theme
==> Pouring adwaita-icon-theme-3.32.0.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/adwaita-icon-theme/3.32.0: 5,827 files, 22.6MB
Error: /usr/local/opt/ruby@2.6 is not a valid keg
```

See https://github.com/mit-plv/fiat-crypto/runs/846886316

**Area for Triage**: Apple

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [x] macOS 10.15

**Expected behavior**

It was working fine before without errors, but it started failing within the past couple of days.

**Actual behavior**
https://github.com/mit-plv/fiat-crypto/runs/846886316
