### ISSUE TITLE
Running pipeline with windows-latetst as image uses windows-2019-vs2019

### ISSUE THREAD

**Issue by mlindeman30** [actions/virtual-environments#12307]
### Description

With this announcement #12045 we checked all our pipelines and we saw that everything was set to windows-latest. Which was fine. However I now have a problem.

I have a pipeline which depends on another pipeline to build a C# project. That pipeline uses very nicely windows-latest. However when running the second pipeline it says it is using `windows-2019-vs2019`, while the pool image is set to windows latest. 

First i thought the culprit was getting the artifact from another pipeline, but it was the variable which will not correctly be used in the vmImage variable. I find it odd that the image would default to `windows-2019-vs2019` when running the pipeline.

This results into an error when running de pipeline. It will give this error:

![Image](https://github.com/user-attachments/assets/c80f88e2-7e6b-4642-b743-5fa000b022a2)

As the error states `windows-20219` is deprecated an will be removed at the end of the month. I don't know if this should be an error.

### Platforms affected

- [x] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [x] Windows Server 2019
- [x] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

Here is the part of the pipeline that determines the vmImage:
```
variables:
  vmImageName: 'windows-latest'

jobs:
- deployment: Deploy
  displayName: Deploy acceptance
  environment: Acceptance
  pool: 
    vmImage: $(vmImageName)
  strategy:
    runOnce:
      deploy:
```

### Is it regression?

It worked before the deprication of windows-2019

### Expected behavior

I had three expectation for this:

The first is that the pipeline would use windows-latest as image to deploy the application. 

The second was that the pipeline would give an warning instead of an error when using windows-2019. 

The last is that the use of an variable like this would set the vmImage to the correct image. When no image would be given the default should be windows-latest or a later version of vm images.

### Actual behavior

The behavior is now:

The pipeline will not run because of the error of using windows-2019 being deprecated.

The image name is not correctly set using the variable vmImageName and then defaulting to windows-2019. 

### Repro steps

I ran the pipeline again and it gave the same result. 

Changing the vmImage from $(vmImageName) to hard coded windows-latest it worked.

**Comment by kishorekumar-anchala** [comment]
Hi @mlindeman30 - Thank you for bringing this issue to our attention. We will look into this issue and will update you after investigating.

**Comment by akilesh-amaran** [comment]
Hi @mlindeman30 ,Could you please share the repro steps or workflow where you are facing the issue. It will help us debug the problem more effectively. Thanks.

**Comment by scs-jewarner** [comment]
@akilesh-amaran  I am seeing the same behaviour as @mlindeman30 - the VM image is specified as 'windows-latest' but the run is resolving 'windows-2019-vs2019'. This occured 6/4/2025 last week (last run on this pipeline).

Output from the job:
```
,##[warning]The windows-2019 runner image is being deprecated, consider switching to windows-2022(windows-latest) or windows-2025 instead. For more details see https://github.com/actions/runner-images/issues/12045.
Pool: [Azure Pipelines](https://dev.azure.com/<removed>/<removed>/_settings/agentqueues?poolId=&queueId=180)
Image: windows-2019-vs2019
Agent: Azure Pipelines 2
Started: Wed at 1:13 PM
Duration: 2m 42s
```

Here is the relevant yml file (with other sections removed) where I am seeing this behaviour. Hopefully this is helpful in tracking down the issue.

```
...
variables:
 ...
  # Build image for the DB build
  DBBuildImage: "windows-latest"
...
pool:
  vmImage: windows-latest
...
jobs:
- deployment: DeployDevDB
        displayName: Deploy DB to Dev
        environment: "<env name>"
        variables:
          - group: "<variable group name>"
        pool:
          vmImage: $(DBBuildImage)

        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  submodules: true

                - task: DownloadPipelineArtifact@2
                  inputs:
                    buildType: "current"
                    artifactName: "$(dbArtifact)"
                    targetPath: "$(Pipeline.Workspace)"

                - task: ExtractFiles@1
                  inputs:
                    archiveFilePatterns: "$(Pipeline.Workspace)/**/$(dbZipName).zip"
                    destinationFolder: "$(Pipeline.Workspace)/db_output"
                    cleanDestinationFolder: true
                    overwriteExistingFiles: true

                - task: SqlAzureDacpacDeployment@1
                  inputs:
                    azureSubscription: "<Azure Subscription>"
                    AuthenticationType: "servicePrincipal"
                    ServerName: "<servername>.database.windows.net"
                    DatabaseName: "<dbName>"
                    deployType: "DacpacTask"
                    DeploymentAction: "Publish"
                    DacpacFile: "$(Pipeline.Workspace)/db_output/*.dacpac"
                    AdditionalArguments: "/p:BlockOnPossibleDataLoss=True /p:CompareUsingTargetCollation=True /p:IgnorePermissions=True /p:DropStatisticsNotInSource=False /p:IgnoreRoleMembership=True"
                    IpDetectionMethod: "AutoDetect"
...
```
