### ISSUE TITLE
Windows 2025 Arm image seems to be missing Git

### ISSUE THREAD

**Issue by nadavash** [actions/virtual-environments#12481]
### Description

Windows 2025 Arm image is missing Git, and therefore `actions/checkout@v4` when checking out a repo with submodules.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [x] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022
- [x] Windows Server 2025

### Image version and build link

VM Image
  - OS: Windows (Arm64)
  - Source: Partner
  - Name: Base Image for Windows 11 Desktop
  - Version: 20250616.11.

### Is it regression?

No

### Expected behavior

I expect actions/checkout@v4 to checkout a repo with submodules without error.

### Actual behavior

I get this error:

```
Error: Input 'submodules' not supported when falling back to download using the GitHub REST API. To create a local Git repository instead, add Git 2.18 or higher to the PATH.
```

### Repro steps

1. Create an action that checks out a repo with submodule. E.g.:
```
- uses: actions/checkout@v4
  with:
    submodules: recursive
    # Need to fetch tags so that the build populates the build number correctly.
    fetch-tags: true
    fetch-depth: 0
```

2. Enable Windows on Arm image as one of the runners.
