### ISSUE TITLE
Latest windows-2022 should contain .NET 8.0.314 sdk but UseDotNet task does not find the tool and installs it

### ISSUE THREAD

**Issue by Styxxy** [actions/virtual-environments#12494]
### Description

According the documentation https://github.com/actions/runner-images/blob/win22/20250617.1/images/windows/Windows2022-Readme.md the image has the .NET tools for .NET 8.0.314 cached. Yet the `UseDotNet` task (with global.json) still needs to install this sdk because it can't find it.

![.NET Core Tools](https://github.com/user-attachments/assets/0b829572-fe37-497e-bc8f-d7ca08123d4a)

### Platforms affected

- [x] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [x] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link
```
Starting: Initialize job
Agent name: 'Azure Pipelines 2'
Agent machine name: 'fv-az619-267'
Current agent version: '4.258.1'
Operating System
Microsoft Windows Server 2022
10.0.20348
Datacenter
Runner Image
Image: windows-2022
Version: 20250623.1.0
Included Software: https://github.com/actions/runner-images/blob/win22/20250623.1/images/windows/Windows2022-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20250623.1
Runner Image Provisioner
2.0.437.1
Current image version: '20250623.1.0'
```

### Is it regression?

no

### Expected behavior

The SDK version in found in the cache and doesn't need to be downloaded and installed.

### Actual behavior

The SDK is being downloaded and installed.

```
Starting: Use dotnet (global.json)
==============================================================================
Task         : Use .NET Core
Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
Version      : 2.259.0
Author       : Microsoft Corporation
Help         : https://aka.ms/AA4xgy0
==============================================================================
Found version 8.0.314 in channel 8.0 for user specified version spec: 8.0.314
Getting URL to download .NET Core sdk version: 8.0.314.
Detecting OS platform to find correct download package for the OS.
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'D:\a\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.259.0\externals\get-os-platform.ps1'"
Primary:win-x64
Detected platform (Primary): win-x64
Version 8.0.314 was not found in cache.
Downloading: https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.314/dotnet-sdk-8.0.314-win-x64.zip
Extracting downloaded package D:\a\_temp\8e619b65-e83c-4f5d-8d3a-c035d74935ec.
Extracting archive
C:\Windows\system32\chcp.com 65001
Active code page: 65001

C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\8e619b65-e83c-4f5d-8d3a-c035d74935ec', 'D:\a\_temp\a581')"

Successfully installed .NET Core sdk version 8.0.314.
Creating global tool path and pre-pending to PATH.
Finishing: Use dotnet (global.json)
```

### Repro steps

Make sure the following global.json is available in the root of the repository:
```json
{
  "sdk": {
    "version": "8.0.314",
    "rollForward": "latestPatch"
  }
}
```

Use following pipeline to run and see the result:
```yaml
pool:
  vmImage: windows-2022

steps:
  - task: UseDotNet@2
    displayName: Use dotnet (global.json)
    inputs:
      packageType: sdk
      useGlobalJson: true
      performMultiLevelLookup: true
```

**Comment by Frulfump** [comment]
It's this issue https://github.com/microsoft/azure-pipelines-tasks/issues/10405 from 2019 that's still not fixed...
Or these dupes https://github.com/microsoft/azure-pipelines-tasks/issues/15020
https://github.com/microsoft/azure-pipelines-tasks/issues/19019

With a PR that supposedly fixed it here https://github.com/microsoft/azure-pipelines-tasks/pull/19415 but it continues to be ignored by Microsoft....

**Comment by Prabhatkumar59** [comment]
Hi @Styxxy - Thank you for bringing this issue to our attention. We will look into this issue and will update you after investigating.

**Comment by Styxxy** [comment]
> It's this issue [microsoft/azure-pipelines-tasks#10405](https://github.com/microsoft/azure-pipelines-tasks/issues/10405) from 2019 that's still not fixed... Or these dupes [microsoft/azure-pipelines-tasks#15020](https://github.com/microsoft/azure-pipelines-tasks/issues/15020) [microsoft/azure-pipelines-tasks#19019](https://github.com/microsoft/azure-pipelines-tasks/issues/19019)
> 
> With a PR that supposedly fixed it here [microsoft/azure-pipelines-tasks#19415](https://github.com/microsoft/azure-pipelines-tasks/pull/19415) but it continues to be ignored by Microsoft....

Thanks for the references. I thought I remembered the task not installing the Dotnet SDK unnecessarily, but probably I am reminder it wrongly and am thinking of the build logs from the Linux agents.

But still, I believe this issue should be resolved because it adds wasted seconds (between 30 and 60 seconds) in each run. Having a lot of pipelines running constantly, it adds up.

**Comment by Frulfump** [comment]
Ah no worries!

Yeah it absolutely needs fixing it's especially annoying when the .NET SDK suffers from unusually long install times during intermittent issues or complete failures that are simply essentialy busy-work.

**Comment by subir0071** [comment]
As a workaround you can use the below task before `UseDotNet@2` task, as answered [here](https://stackoverflow.com/questions/77662155/why-usedotnet2-tasks-downloads-sdk-even-if-it-is-already-present-on-build-agent).

```
- task: PowerShell@2
  displayName: 'UseDotNet@2 fix'
  inputs:
    targetType: inline
    script: |
       Set-Content -Path 'C:\Program Files\dotnet\sdk\8.0.314.complete' -Value 'dummy'
```

Resolution of this open bug being [tracked here](https://github.com/microsoft/azure-pipelines-tasks/issues/15020)

Will close this issue as it does not relate to the runner images.

**Comment by Frulfump** [comment]
That's not an appropriate solution, review and merge the PR https://github.com/microsoft/azure-pipelines-tasks/pull/19415 here instead to fix the issue properly, why are you so lazy it's mind blowing.

**Comment by Styxxy** [comment]
> As a workaround you can use the below task before `UseDotNet@2` task, as answered [here](https://stackoverflow.com/questions/77662155/why-usedotnet2-tasks-downloads-sdk-even-if-it-is-already-present-on-build-agent).

For others: don't forget to update the `UseDotNet@2` to set in the inputs the property `installationPath: C:\Program Files\dotnet`.

I updated the script to make it generic and create the "complete" file for all sdks installed.

```yaml
- task: PowerShell@2
  displayName: UseDotNet@2 fix
  inputs:
    workingDirectory: C:\Program Files\dotnet\sdk
    targetType: inline
    script: |
      Get-ChildItem -Directory | ForEach-Object { Set-Content -Path "$($_.Name).complete" -Value "$($_.Name)" }

- task: UseDotNet@2
  displayName: Use dotnet (global.json)
  inputs:
    packageType: sdk
    useGlobalJson: true
    performMultiLevelLookup: true
    installationPath: C:\Program Files\dotnet
```
