### ISSUE TITLE
Older macOS versions?

### ISSUE THREAD

**Issue by The-Compiler** [actions/virtual-environments#1256]
**Area for Triage**:
Apple

**Question, Bug, or Feature?**:
Question/Feature

---

I'm not sure if this really is the right place to ask, but it seems to me like the most fitting one: Are there any plans to add environments for older macOS versions? While trying to move release building for my [qutebrowser](https://github.com/qutebrowser/qutebrowser) project to GitHub Actions, I noticed that only macOS 10.15 is available. From my experience, a binary built on macOS 10.15 will not work correctly on older versions (but the reverse works fine), so I'm currently building on macOS 10.13 High Sierra (which is the oldest version I want to support). Thus, this currently keeps me from automating building of releases, unfortunately.

**Comment by vmapetr** [comment]
Hi @The-Compiler !
For Github Actions, we're not planning to add macOS versions older than Catalina, but it may change in the future. However, we're support macOS 10.14 for Azure DevOps.

**Comment by andy-mishechkin** [comment]
Hello, @The-Compiler.
According to https://github.com/actions/virtual-environments/issues/461, we have no plans to add previous versions in the nearest time.

**Comment by Safihre** [comment]
For anyone also looking into this to build Python-packages or use PyInstaller to build an `.app`: Python actually offers support for this, by setting the `MACOSX_DEPLOYMENT_TARGET` environment variable.
However, it is not possible using the Python versions installed on the GA workers, because they are compiled on macOS 10.15 or newer.
Simply getting the official Python installer make the magic work! 🥳 
Just make sure to use `python3` and `pip3` in your commands.

```yml
jobs:
  build_macos:
    name: Build macOS binary
    runs-on: macos-latest
    env:
      # We need the official Python, because the GA ones only support newer macOS versions
      # The deployment target is picked up by the Python build tools automatically
      PYTHON_VERSION: 3.9.1
      MACOSX_DEPLOYMENT_TARGET: 10.9
    steps:
    - uses: actions/checkout@v2
    - name: Cache Python download
      id: cache-python-download
      uses: actions/cache@v2
      with:
        path: python.pkg
        key: ${{ env.PYTHON_VERSION }}
    - name: Get Python
      if: steps.cache-python-download.outputs.cache-hit != 'true'
      run: curl https://www.python.org/ftp/python/${PYTHON_VERSION}/python-${PYTHON_VERSION}-macosx10.9.pkg -o "python.pkg"
    - name: Install Python
      run: sudo installer -pkg python.pkg -target /
    - name: Install Python dependencies
      run: |
        python3 --version
        pip3 install --upgrade -r requirements.txt
```
