### ISSUE TITLE
Restore SQL Server Express 2019

### ISSUE THREAD

**Issue by kblok** [actions/virtual-environments#1282]
**Tool information**
- Tool name: SQL Server Express 2019
- Tool license: 
- Add or update? Re-Add (it was removed here https://github.com/actions/virtual-environments/pull/707)
- Desired version: 2019
- Approximate size: 
- If this is an add request:
  - Brief description of tool: The current sqllocaldb is compatible with SQL Server 2016. It would be great to support SQL Server 2019 compatibility
  - URL for tool's homepage: https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-ver15
  - Provide a basic test case to validate the tool's functionality: Deploy a SQL Project type Microsoft.Data.Tools.Schema.Sql.Sql150DatabaseSchemaProvider to the localDB.

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**
**Tool installation time in runtime**
**Are you willing to submit a PR?**

https://github.com/actions/virtual-environments/pull/707 removes this product. I don't know what we would break if we restore it.

**Comment by multitracks** [comment]
🙏

**Comment by Darleev** [comment]
Hello, @kblok @multitracks,
First of all, let me provide you steps to install SQL Express in runtime and use it:
```
- Install SQLEXPRESS using command: choco install sql-server-express
- After installation %SERVERNAME%\SQLEXPRESS instance will be created with full access for current user who installed the package
- You can connect to this instance and use it. I have tested that version is Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)
```

We will consider the idea of installing a separate SQL Server Express in order to have more up-to-date version of LocalDB.

**Comment by kblok** [comment]
Thank you for your feedback @Darleev. I tried that, but I considered waiting 5 minutes for that task quite excessive.

**Comment by musmuris** [comment]
@kblok  If you only need 2019 Local DB (and not full express) then you can use this bit of powershell to download and install just that MSI - seems to take ~30 seconds on my pipeline - and is ok whilst we await it being available on an image.

```yaml
- task: PowerShell@2
  displayName: Install SQL 2019 Localdb
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Downloading"
      Import-Module BitsTransfer
      Start-BitsTransfer -Source https://download.microsoft.com/download/7/c/1/7c14e92e-bdcb-4f89-b7cf-93543e7112d1/SqlLocalDB.msi -Destination SqlLocalDB.msi
      Write-Host "Installing"
      Start-Process -FilePath "SqlLocalDB.msi" -Wait -ArgumentList "/qn", "/norestart", "/l*v SqlLocalDBInstall.log", "IACCEPTSQLLOCALDBLICENSETERMS=YES";
      Write-Host "Checking"
      sqlcmd -l 60 -S "(localdb)\MSSQLLocalDB" -Q "SELECT @@VERSION;"
```

**Comment by krokofant** [comment]
If you've installed a newer Local DB but you still have the older one take precedence on your path you can use this wrapper to select the newest one:
```powershell
function Invoke-SqlLocalDb {
  $localDbArgs = $args;
  Get-Command SqlLocalDB.exe -All | Sort-Object -Property Version -Descending -Top 1 | % {
    & $_ $localDbArgs
  }
}
```
And use it like `Invoke-SqlLocalDb info`.
![bild](https://user-images.githubusercontent.com/5908498/90310595-3bce0c80-def3-11ea-8133-edadfd3a4a67.png)

**Comment by krokofant** [comment]
We're still using the old install the repo had included for SQL Server Express (with some minor changes). It's been notably slower on Az Pipeline than our old ci system which runs of worse hardware. That is strange.

I'm starting to suspect this is because (correct me if I'm wrong) installing SQL Server with no updates downloaded during install, gives you the first release without any cumulative updates. I will try and apply the CUs to our image and see if it will make a difference. If we add the SQL Server back to this repo then including updates should be considered.

**Comment by krokofant** [comment]
To build the example from @musmuris here is a job to test on multiple versions of localdb:
```yaml
          - job: sql_version_test
            displayName: 🗃 SQL Version
            strategy:
                matrix:
                    SQL2012SP4:
                        InstallerUrl: https://download.microsoft.com/download/B/D/E/BDE8FAD6-33E5-44F6-B714-348F73E602B6/ENU/x64/SqlLocalDB.msi
                        SqlVersionCode: '11.0'
                        InstanceName: SQL2012
                    SQL2014SP3:
                        InstallerUrl: https://download.microsoft.com/download/3/9/F/39F968FA-DEBB-4960-8F9E-0E7BB3035959/ENU/x64/SqlLocalDB.msi
                        SqlVersionCode: '12.0'
                        InstanceName: SQL2014
                    SQL2016SP2:
                        InstallerUrl: https://download.microsoft.com/download/4/1/A/41AD6EDE-9794-44E3-B3D5-A1AF62CD7A6F/sql16_sp2_dlc/en-us/SqlLocalDB.msi
                        SqlVersionCode: '13.0'
                        InstanceName: SQL2016
                    SQL2017:
                        InstallerUrl: https://download.microsoft.com/download/E/F/2/EF23C21D-7860-4F05-88CE-39AA114B014B/SqlLocalDB.msi
                        SqlVersionCode: '14.0'
                        InstanceName: SQL2017
                    SQL2019:
                        InstallerUrl: https://download.microsoft.com/download/7/c/1/7c14e92e-bdcb-4f89-b7cf-93543e7112d1/SqlLocalDB.msi
                        SqlVersionCode: '15.0'
                        InstanceName: SQL2019
            pool:
                vmImage: 'vs2017-win2016'
            steps:
                - checkout: none
                - task: PowerShell@2
                  displayName: Install SQL LocalDB $(InstanceName)
                  inputs:
                      targetType: 'inline'
                      script: |
                          Write-Host "Downloading"
                          Import-Module BitsTransfer
                          Start-BitsTransfer -Source $(InstallerUrl) -Destination SqlLocalDB.msi
                          Write-Host "Installing"
                          Start-Process -FilePath "SqlLocalDB.msi" -Wait -ArgumentList "/qn", "/norestart", "/l*v SqlLocalDBInstall.log", "IACCEPTSQLLOCALDBLICENSETERMS=YES";
                          SqlLocalDB.exe stop $(InstanceName) -k
                          SqlLocalDB.exe delete $(InstanceName)
                          SqlLocalDB.exe create $(InstanceName) $(SqlVersionCode) -s
                - pwsh: Install-Module dbatools -Force
                  displayName: Install DBATools
                - pwsh: Invoke-DbaQuery -SqlInstance "(localdb)\$(InstanceName)" -Query "SELECT @@VERSION;" | Write-Output
                  displayName: Show server version
```
