### ISSUE TITLE
"--platform" is only supported on a Docker daemon with experimental features enabled

### ISSUE THREAD

**Issue by BrightRan** [actions/virtual-environments#1368]
Associated community ticket: https://github.community/t/enabling-docker-cli-experimental/126247

When setup a container job in the workflow, and use the '**--platform**' at the '**options**' key,
```yaml
jobs:
  job1:
    runs-on: ubuntu-latest
    container: 
      image: racket/racket-ci:latest
      options: --init --platform linux/amd64
    steps:
      . . .
```
The "**Initialize containers**" step always returns the error below:
```
"--platform" is only supported on a Docker daemon with experimental features enabled
```
