### ISSUE TITLE
Inconsistent drive letter on Windows when using tox and pytest

### ISSUE THREAD

**Issue by eine** [actions/virtual-environments#1381]
I'm finding that the same branch/commit works in a repo but fails in a fork. The difference I found is that drive letters are uppercase in the former and lowercase in the latter:

- https://github.com/VUnit/vunit/runs/956274623?check_suite_focus=true#step:7:9
- https://github.com/eine/vunit/runs/959031516?check_suite_focus=true#step:7:9

The command that is being tested is `tox -e py36-unit -- --color=yes` from VUnit/vunit, which executes `{envpython} -m pytest -v -ra tests/unit {posargs}`.

AFAIU, Windows is not case sensitive, hence I'd expect drive letters to always be uppercase.

**Comment by al-cheb** [comment]
Hello, @eine 
Could you please provide a simple test to reproduce this behavior? Does it reproduce with default shell instead of bash?

**Comment by eine** [comment]
@al-cheb, unfortunately, I don't know how to simplify it further. The workflows linked above do only:

- Checkout.
- Setup Python.
- Install deps through pip.
- Execute tox.

The first thing tox does, which is to setup the environment, is already inconsistent: `GLOB sdist-make: D:\a\vunit\vunit\setup.py` vs `GLOB sdist-make: d:\a\vunit\vunit\setup.py`. If I remove any of the previous steps, tox cannot be executed.

I will try with powershell.

**Comment by al-cheb** [comment]
@eine,
I can't reproduce the issue from my side using  'VUnit/vunit' / 'eine/vunit' repoes.

```
steps:
    - uses: actions/checkout@v2
      with:
        repository: 'VUnit/vunit'
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: install dependencies
      run: |
        pip install -U pip --progress-bar off
        pip install -U virtualenv tox --progress-bar off
    - name: run job
      shell: bash
      run: |
        export PATH=$PATH:$(pwd)/../ghdl-v0.37/bin
        tox -e py36-unit -- --color=yes 
```

![image](https://user-images.githubusercontent.com/47745270/89783688-08206a80-db20-11ea-9439-86e4be1ae5a6.png)


Second variant:

```
    - uses: actions/checkout@v2
      with:
        repository: 'eine/vunit'
```
![image](https://user-images.githubusercontent.com/47745270/89783798-37cf7280-db20-11ea-9d5d-67fe8ecefeb1.png)
