### ISSUE TITLE
Problem creating files using powershell step on ubuntu-20.04

### ISSUE THREAD

**Issue by jwillemsen** [actions/virtual-environments#1475]
**Description**  
We are using a powershell step to create some files but on ubuntu-20.04 that fails silently with:
```
 mkdir: cannot create directory ‘/run/user/1001’: Permission denied
```
The step is shown as succeeded

**Area for Triage**:  
['Area: Scripting and command line']

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [X] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Created the file, see the build log for the detailed error message

**Actual behavior**  
```
 mkdir: cannot create directory ‘/run/user/1001’: Permission denied
```
The build step isn't failing

**Repro steps**  
See https://github.com/jwillemsen/actiontest/blob/master/.github/workflows/linux.yml

Or use:
```
name: linux

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
          - os: ubuntu-20.04
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    env:
      ACE_ROOT: ${{ github.workspace }}/FOO/ACE
      TAO_ROOT: ${{ github.workspace }}/FOO/TAO
    steps:
    - name: checkout ACE
      uses: actions/checkout@v2
      with:
        repository: DOCGroup/ACE_TAO
        path: FOO
    - name: create $ACE_ROOT/ace/config.h
      run: |
        '#include "ace/config-linux.h"' > ${env:ACE_ROOT}/ace/config.h
      shell: pwsh
```
