### ISSUE TITLE
GitHub needs to code sign the ps1 scripts.

### ISSUE THREAD

**Issue by LanceMcCarthy** [actions/virtual-environments#1503]
**Description**  

GitHub/Microsoft does not sign autogenerated ps1 scripted steps, this causes a failure on a self-hosted Windows runners. 

For example, let's take this step:

`Run dotnet restore some.csproj`

Which is turned into the following ps1 file that gets downloaded to the runner:

`C:\actions-runner\_work\_temp\7af2df60-c729-42fb-85a1-d9de2fd74369.ps1`

However, when the runner tries to execute it, you get the expected trust error:

`The file 
C:\actions-runner\_work\_temp\7af2df60-c729-42fb-85a1-d9de2fd74369.ps1 is not digitally signed.  You cannot run this 
script on the current system.`

The workaround is to change execution policy, but this _is extremely dangerous and a very bad idea_. Microsoft should sign any ps1 steps it creates.

**Area for Triage**:  

- .NET Core
- Scripting and command line

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019
- [x] Self-Hosted Windows Runner

**Expected behavior**  

Steps work

**Actual behavior**  

Steps fail due to unsigned ps1 file.

```powershell
Run dotnet restore $env:SolutionPath --configfile $env:NugetConfigPath --runtime $env:RID

. : File C:\actions-runner\_work\_temp\7af2df60-c729-42fb-85a1-d9de2fd74369.ps1 cannot be loaded. The file 
C:\actions-runner\_work\_temp\7af2df60-c729-42fb-85a1-d9de2fd74369.ps1 is not digitally signed. You cannot run this 
script on the current system. For more information about running scripts and setting execution policy, see 
about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:3
+ . 'C:\actions-runner\_work\_temp\7af2df60-c729-42fb-85a1-d9de2fd74369 ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
##[error]Process completed with exit code 1.
```

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Create a Windows self-hosted runner
2. Run a workflow that uses any steps that creates a ps1 file for the step's instructions.

For a repro example, you can use the following:

```yaml
name: GitHub Actions Repro

on:
  push

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.302'

    # This will fail
    - name: NuGet Restore
      run: dotnet restore some.csproj --runtime win-x86
```

**Comment by maxim-lobanov** [comment]
@LanceMcCarthy  thank you for report.
I think wrapping inline scripts to temporary ps1 files is something that [actions/runner](https://github.com/actions/runner) does.
cc: @ericsciple @dakale could you please take a look if it is something that should be transfered to your repo?

**Comment by LanceMcCarthy** [comment]
Thanks @maxim-lobanov 

@ericsciple @dakale

I did try to run `run: Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope Process -Force` before the other steps. However, that command also gets wrapped as a ps1, lol.

![image](https://user-images.githubusercontent.com/3520532/91475352-762b9800-e869-11ea-89e1-ea8996842fdb.png)

**Comment by ericsciple** [comment]
For the above command, a [different shell](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell) should work:

```yaml
steps:
  - shell: cmd
    run: dotnet restore some.csproj
```

We can't sign user scripts with a GitHub certificate.
