### ISSUE TITLE
Failed to open TCP connection to 127.0.0.1:9515 on ubunut-latest.20200825.1

### ISSUE THREAD

**Issue by anark** [actions/virtual-environments#1516]
**Description**  
When trying to run rspec tests that use selenium webdriver on ubuntu-latest.20200825.1  I get the following error.
```
##[error]Failure/Error:
  raise e, "Failed to open TCP connection to " +
    "#{conn_address}:#{conn_port} (#{e.message})"

Errno::ECONNREFUSED:
  Failed to open TCP connection to 127.0.0.1:9515 (Connection refused - connect(2) for "127.0.0.1" port 9515)
```

This worked fine on ubunu-latest.20200817.1
**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
I expect the to be able to use chromedriver the same way I was in version 20200817.1

**Actual behavior**  
When attempting to use chromedriver on ubuntu-latest 20200825.1 I get an error, connection refused

**Comment by andy-mishechkin** [comment]
Hello, @anark 
May you provide link to workflow, where you've got this error ?
Thank you.

**Comment by anark** [comment]
I'm experiencing this with the following workflow

```
jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: ${{ env.PGUSER }}
          POSTGRES_PASSWORD: ${{ env.PGPASSWORD }}
          POSTGRES_DB: test_sky_pilot
        ports:
        - 5432:5432
        # options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: styfle/cancel-workflow-action@0.4.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - run: bin/rails db:schema:load
    - run: bin/rspec --format RSpec::Github::Formatter
```

This is on a fairly standard rails app with capybara setup in the following way
```
Capybara.register_driver :selenium do |app|
  options = Selenium::WebDriver::Chrome::Options.new(
    args: %w[headless disable-gpu no-sandbox]
  )
  Capybara::Selenium::Driver.new(app, browser: :chrome, options: options)
end
Capybara.javascript_driver = :selenium
```

This worked fine up until about a week ago when it started failing with no code changes.
