### ISSUE TITLE
Unable to reach internet from github actions virtual environment

### ISSUE THREAD

**Issue by mous2890** [actions/virtual-environments#1519]
**Description**  
Despite no changes being made to my github actions, my actions can no longer deploy to my server, Upon further investigation, i found that the virtual environment is no longer able to reach my target server. I went and inspected my server and everything seemed fine. I then decided to run some connectivity tests from the github action to google to see if it can reach that. Unfortunately it wasn't even able to reach that. 

```
Current runner version: '2.273.0'
Operating System
  Ubuntu
  18.04.5
  LTS
Virtual Environment
  Environment: ubuntu-18.04
  Version: 20200817.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20200817.1/images/linux/Ubuntu1804-README.md
```
Ping from github action:
```
ping -c 10 google.com
PING google.com (172.217.2.110) 56(84) bytes of data.

--- google.com ping statistics ---
10 packets transmitted, 0 received, 100% packet loss, time 9199ms
```

**Area for Triage**:  
Git

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Previously, i was able to reach the internet and deploy to my server. I expect the virtual environment to have outbound connectivity to the internet.

**Actual behavior**  
github action virtual environment has no access to the internet.

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

Ignore the bad indentations on below workflow file, copy and pasting didn't work too great. Simply run any github action using ubuntu-latest or v20 and you'll find no connectivity to the internet.

```
name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Test Connectivity
        run: |
          ping -c 10 google.com
```
