### ISSUE TITLE
task.setvariable changes variable casing

### ISSUE THREAD

**Issue by asklar** [actions/virtual-environments#1578]
**Description**  
Azure DevOps sets NPM_CONFIG_CACHE (all uppercase). Some tools like yarn/node, they manage to add a lowercase version of some npm variables (`npm_config_cache` for example) by directly setting it in an environment block when calling CreateProcess. This breaks some tools when they encounter duplicate variables in their environment block, like msbuild/CL.exe.

I've submitted a fix to the script that sets up the uppercase variable #1566 .
To work around the problem in the meantime, I added a task in my pipeline to reset the NPM_CONFIG_CACHE variable and then reset it as npm_config_cache:
`Write-Host "##vso[task.setvariable variable=npm_config_cache]$npm_config_cache"`

However it seems like `##vso[task.setvariable]` always sets the variable in uppercase. This is a problem because it makes it impossible for anyone to work around the duplicate env variable problem.

**Area for Triage**:  Scripting and command line

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**  
task.setvariable does not alter the casing of env variables

**Actual behavior**  
task.setvariable uses the uppercase version of a variable's name

**Repro steps**  

```yaml
  - task: PowerShell@2
    displayName: Reset NPM_CONFIG_CACHE
    inputs:
      targetType: "inline"
      script: Write-Host "##vso[task.setvariable variable=lowercase_variable]some value"
  - task: PowerShell@2
    displayName: Display env
    inputs:
      targetType: "inline"
      script:  gci env:* | sort-object name
```

And notice that the variable shown is `LOWERCASE_VARIABLE` instead of `lowercase_variable`.
