### ISSUE TITLE
ubuntu-latest uses ubuntu-tools-v2-runner-2 instead of Ubuntu 18.04

### ISSUE THREAD

**Issue by AlexVanderbist** [actions/virtual-environments#1594]
**Description**  
Action with `runs-on: ubuntu-latest` uses `ubuntu-tools-v2-runner-2` instead of Ubuntu 18.04. This behaviour changed for just one repository without any changes made to the workflow files. I first noticed this because `yarn` was suddenly not found in said action.

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
`runs-on: ubuntu-latest` should use Ubuntu 18.04, `yarn` should be available.

Example from this was still working:
![image](https://user-images.githubusercontent.com/6287961/93213598-5995c800-f764-11ea-9116-75c763e16663.png)

**Actual behavior**  
`runs-on: ubuntu-latest` uses another runner that's not Ubuntu 18.04.

Example from the same configuration, a couple days later:
![image](https://user-images.githubusercontent.com/6287961/93213699-8053fe80-f764-11ea-8e5f-73fedfe733c4.png)

**Repro steps**  

Unfortunately I haven't got a public repo to share. I've tried to reproduce this issue on a public repository but that all worked as expected. I understand that this isn't much to go on but hopefully someone else can shine some light on what the `ubuntu-tools-v2-runner-2` is and how GitHub actions started using those for 1 repository without any changes.

**Comment by yaananth** [comment]
@AlexVanderbist do you have checks URL (even if it isn't public), where you saw this? That helps a lot in investigating this

**Comment by AlexVanderbist** [comment]
I'm not sure what a checks URL is. Just the action output?

This one is broken: https://github.com/blueoceanideas/sail-amx/runs/1117694189
This one is the same action a couple days earlier, working: https://github.com/blueoceanideas/sail-amx/runs/1096404000

**Comment by AlexVanderbist** [comment]
For completion: this is the action's config. Changing `runs-on: 'ubuntu-latest'` to `runs-on: 'ubuntu-18.04'` fixes the issues we're having on the action for that repo.

```yaml
name: 'Code formatting'

on:
    push:
        paths:
            - '**.php'
            - '.github/workflows/code-formatting.yml'
jobs:
    code-formatting:
        runs-on: 'ubuntu-latest'

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Cache yarn dependencies
              uses: actions/cache@v2
              with:
                  path: node_modules
                  key: yarn-${{ hashFiles('yarn.lock') }}

            - name: Yarn format
              run: yarn && yarn format

            - name: Run php-cs-fixer
              uses: docker://oskarstark/php-cs-fixer-ga
              with:
                  args: --config=.php_cs --allow-risky=yes

            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v2.3.0
              with:
                  commit_message: PHP CS changes
                  branch: ${{ steps.extract_branch.outputs.branch }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
