### ISSUE TITLE
CMake+Ninja detects GCC as the default compiler on Windows

### ISSUE THREAD

**Issue by FranciscoPombal** [actions/virtual-environments#1621]
**Description** 

CMake+Ninja detects GCC as the default compiler on Windows, causing builds that are meant to use MSVC break. See the result of this example workflow run, where I try to build a project with CMake+Ninja+vcpkg+pwsh: 

https://github.com/FranciscoPombal/qBittorrent/runs/1136169917?check_suite_focus=true

This does not happen if I force CMake to use a VS generator, but I'd rather use Ninja.

**Area for Triage**:  C/C++

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2 - maybe? I assume it also happens here.
- [x] Windows Server 2019

**Expected behavior**  

Build tools such as Ninja are able to detect the latest `cl.exe` as the default compiler on Windows.

**Actual behavior**  

GCC is detected and used instead by default.

**Repro steps**  

Here is a minimal example of a step definition for reproducing the problem.

```yaml
- name: build project
  shell: pwsh
  run: |
    cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_DEST_WIN }}/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static
    cmake --build build
```

See https://github.com/FranciscoPombal/qBittorrent/runs/1136169917?check_suite_focus=true as a real-world example.

Sample output excerpt:

```
-- The CXX compiler identification is GNU 8.1.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/ProgramData/chocolatey/bin/c++.exe - skipped
-- Detecting CXX compile features
...
```

**Extra notes**

I am aware of the many possible workarounds for this, including dedicated actions for setting up MSVC environment, `vswhere`, etc. But this is a simple case where I'm only really interested in the latest `cl.exe`, and all VS components that come installed are sufficient for my use case. Why can't the latest `cl` be detected and used by default? Maybe this is a bug with the vcpkg toolchain file or something though.
