### ISSUE TITLE
Broken builds after 10.09.2020 that says a container can't connect to MySQL

### ISSUE THREAD

**Issue by dloranc** [actions/virtual-environments#1651]
**Description**
All builds for our applications started failing from 14.09.2020 due to some changes in `ubuntu-latest` image. Instead of initialise a database and running Ruby tests it's raising an error that it can't connect to MySQL server.

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [X] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
I expected build to run correctly and broke only on failed tests, not on missing MySQL server or something.

**Actual behavior**  
As I wrote before, instead of running tests I'm getting this build error:

```
rails aborted!
Mysql2::Error::ConnectionError: Can't connect to MySQL server on 'mysql' (115)
/usr/local/bundle/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `connect'
/usr/local/bundle/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `initialize'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:879:in `new_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:923:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:902:in `try_to_checkout_new_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:863:in `acquire_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:587:in `checkout'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:431:in `connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:1111:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_handling.rb:231:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_handling.rb:199:in `connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:59:in `check_protected_environments!'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/railties/databases.rake:15:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/railties-6.0.0/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/usr/local/bundle/gems/railties-6.0.0/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/local/bundle/gems/railties-6.0.0/lib/rails/command.rb:48:in `invoke'
/usr/local/bundle/gems/railties-6.0.0/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:schema:load => db:check_protected_environments
(See full trace by running task with --trace)
##[error]Process completed with exit code 1.
```

My configuration files are:

`./.github/workflows/docker_ci.yml`:

```
name: Docker CI

on:
  pull_request:
    branches:
      - development
      - master
  push:
    branches:
      - development
      - master
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Spec
      run: docker-compose -f docker-travis.yml run spec
    - name: Run Test
      run: docker-compose -f docker-travis.yml run test
```

`./docker_travis.yml`:
```
version: '2'

services:
  mysql:
    image: my-company/mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: 'development'
      MYSQL_TEST_DATABASE: 'test'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis:5.0-alpine
    command: redis-server
    volumes:
      - redis:/var/lib/redis/data

  spec:
    build: .
    image: my-company/private-image:test
    command: bin/rails db:schema:load db:sql:run spec
    working_dir: /app/user
    env_file: .env.test
    depends_on:
      - mysql
      - redis

  test:
    image: my-company/private-image:test
    command: npm run test-ci
    working_dir: /app/user
    env_file: .env.test
    depends_on:
      - mysql
      - redis

volumes:
  mysql:
  redis:
```

Don't get misguided by `docker_travis.yml` filename, we're using GitHub Actions for CI.

Anyway, I tried to check `docker-compose -f docker-travis.yml run spec` on my localhost environment and it works like a charm and the problem seems to be with changes introduced between 10.09.2020 (date of last good build) and 14.09.2020 (first broken build after week end) to virtual-environments. I tried to use other environments like `ubuntu-16.04` and `ubuntu-20.04`, but without success. Only for `ubuntu-16.04` one build succeeded, but it was only once.

**Repro steps**  
Currently it's not possible to reproduce this issue by people outside our company as we're using private docker images. Sorry for that, I have hope that someone will give me at least a small advice how to resolve/debug this issue.

**Comment by maxim-lobanov** [comment]
Hello @dloranc , could you please check correlation between image version of your builds and build health around these dates? Range between a few latest green builds and a few first failed ones.

Image version can be found in `Set up job` step:
![image](https://user-images.githubusercontent.com/16715858/94002716-ec58e700-fda2-11ea-832e-94cf59d45009.png)

**Comment by dloranc** [comment]
OK, so last four green builds have:
![image](https://user-images.githubusercontent.com/364417/94003377-6e451200-fd9b-11ea-9883-4fd5c21e63b1.png)

or if you prefer to have it written down:
```
Current runner version: '2.273.0'
Operating System
  Ubuntu
  18.04.5
  LTS
Virtual Environment
  Environment: ubuntu-18.04
  Version: 20200901.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20200901.1/images/linux/Ubuntu1804-README.md
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/checkout@v2'
```

Red builds have:
![image](https://user-images.githubusercontent.com/364417/94003528-9f254700-fd9b-11ea-8b36-1194d09bb579.png)
```
Current runner version: '2.273.2'
Operating System
  Ubuntu
  18.04.5
  LTS
Virtual Environment
  Environment: ubuntu-18.04
  Version: 20200914.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20200914.1/images/linux/Ubuntu1804-README.md
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/checkout@v2'
```

One red build (not first, but later one) have `Version: 20200908.1`.

**Comment by al-cheb** [comment]
Hello, @dloranc 
I can't reproduce the issue with default mysql-5.7

```
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run client
      run: docker-compose -f docker-compose.yml run client 2>&1 | tail -n 5
```
docker-compose.yml:
```
version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: 'development'
      MYSQL_TEST_DATABASE: 'test'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
    volumes:
      - mysql:/var/lib/mysql
  redis:
    image: redis:5.0-alpine
    command: redis-server
    volumes:
      - redis:/var/lib/redis/data
  client:
    image: ubuntu
    command: bash -c "apt update &>/dev/null && apt-get install -y mariadb-client &>/dev/null && mysql -uadmin -ppassword -hmysql -e 'SHOW DATABASES;'"
    depends_on:
    - mysql
    - redis
volumes:
  mysql:
  redis:
```

![image](https://user-images.githubusercontent.com/47745270/94026959-05719000-fdc3-11ea-8111-7b5cf8f061cb.png)
