### ISSUE TITLE
Update helm to v3.3.4

### ISSUE THREAD

**Issue by zackijack** [actions/virtual-environments#1654]
**Description**  
There is a bug in helm v3.3.2 & v3.3.3 and solved on v3.3.4 https://github.com/helm/helm/issues/8771

**Area for Triage**:  
Containers

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Update helm to v3.3.4

**Actual behavior**  
The command `helm repo add <name> <url>` fails as it is no longer idempotent. This worked fine in version v3.3.1 and earlier. It now fails in v3.3.2 and v3.3.3. This is a breaking change that has broken automation relying on helm and tools `helmfile`.

**Comment by dibir-magomedsaygitov** [comment]
Hello, @zackijack! 
Thank you for your report. We are installing latest available version at the moment. New Ubuntu images are coming with `helm v3.3.3`. 
As a workaround I'd suggest you to update helm in a runtime using:
```
wget https://get.helm.sh/helm-v3.0.2-linux-amd64.tar.gz
tar xvf helm-v3.0.2-linux-amd64.tar.gz
sudo mv linux-amd64/helm /usr/local/bin/
rm helm-v3.0.2-linux-amd64.tar.gz
rm -rf linux-amd64
```

**Comment by Darleev** [comment]
Hello @zackijack,

Maybe a solution below will be more convenient for you:

github actions

```
- uses: azure/setup-helm@v1
  with:
    version: '3.3.1' # default is latest stable
  id: install
```

Azure DevOps

```
- task: HelmInstaller@1
  displayName: Helm installer
  inputs: 
    helmVersionToInstall: 3.3.1
```

In case of any questions, do not hesitate to contact us.
