### ISSUE TITLE
dotnet dev-certs started failing in macOS

### ISSUE THREAD

**Issue by kblok** [actions/virtual-environments#1690]
**Description**  
The `dotnet dev-certs` started to fail here https://github.com/hardkoded/playwright-sharp/pull/878/checks?check_run_id=1176770064 from one day to the other.

This is part of the workflow definition

```
jobs:
  chromium-mac:
    name: Chromium on MacOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Create Certificate
        run: |
          dotnet dev-certs https --clean
          dotnet dev-certs https -ep src/PlaywrightSharp.TestServer/testCert.cer
````

You can see the rest here https://github.com/hardkoded/playwright-sharp/blob/master/.github/workflows/tests.yml

**Area for Triage**:  
.NET Core

**Virtual environments affected**  
- [X] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019
