### ISSUE TITLE
Add docker and docker-compose to macOS

### ISSUE THREAD

**Issue by kaylangan** [actions/virtual-environments#17]
**Tool information**
- Tool name: Docker and docker compose
- Add or update? Add
- Desired version: 
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Used for container applications
  - URL for tool's homepage: https://www.docker.com/

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

Already exists on the Windows and Linux environments.

**Can this tool be installed during the build?**

**Are you willing to submit a PR?**

**Comment by dmitry-shibanov** [comment]
Hello, thank you for your response. Pull request with adding docker and docker compose was merged and change would be added in next images rollout.

**Comment by dmitry-shibanov** [comment]
Hello, docker, docker-machine and docker-compose were added to image. If you have any concerns please feel free to reopen the issue.

**Comment by thomaseizinger** [comment]
Is there anything that needs to be done for docker to be started? Our tests fail with an error from the `docker` CLI:

https://github.com/comit-network/comit-rs/pull/2345/checks?check_run_id=544450918#step:8:177

**Comment by dmitry-shibanov** [comment]
Hello @thomaseizinger, thank you for your response. I have confirmed issue and looking into it

**Comment by alepauly** [comment]
For those watching this issue, we've discovered that due to licensing we are unable to bake docker and docker-compose into the macOS image and will have to back out some of our changes.

**Comment by joeldodge79** [comment]
@alepauly is it possible to install docker and docker-compose at runtime?

**Comment by alepauly** [comment]
> @alepauly is it possible to install docker and docker-compose at runtime?

It should work but I haven't tried, @maxim-lobanov, do you know if it's possible?

**Comment by joeldodge79** [comment]
I just found [actions/setup-docker](https://github.com/marketplace/actions/setup-docker) - gonna give that a run. thanks!

**Comment by karimhm** [comment]
Docker offers [Docker Desktop Enterprise](https://hub.docker.com/editions/community/docker-desktop-ent) for macOS now.

**Comment by kopax-polyconseil** [comment]
> I just found [actions/setup-docker](https://github.com/marketplace/actions/setup-docker) - gonna give that a run. thanks!

I can't use this with macos runner, I have `docker command not found` error as soon as the action start

**Comment by verdverm** [comment]
@kopax-polyconseil This might be a better issue for docker not working on macos

https://github.com/docker-practice/actions-setup-docker/issues/27

**Comment by fawazahmed0** [comment]
As mentioned [here](https://blog.netnerds.net/2022/11/docker-macos-github-actions/), you can use
```
brew install docker
colima start
```

**Comment by crazy-max** [comment]
You can also check https://github.com/crazy-max/ghaction-setup-docker. You can set up Docker for the version you want like:

```
      -
        name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v1
        with:
          version: 23.0.1
```

**Comment by xtermi2** [comment]
When using testcontainers for me only https://github.com/marketplace/actions/setup-docker is working with macos and linux containers.

**Comment by joffrey-bion** [comment]
@xtermi2 You can get Testcontainers to find the socket by creating a symlink to Colima's Docker socket location. The following seems to serve me well at the moment, and it's rather quick (~1m45):

```yaml
- name: Setup docker (missing on MacOS)
  if: runner.os == 'macos'
  run: |
    brew install docker
    colima start
    
    # For testcontainers to find the Colima socket
    # https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running
    sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock
```
