### ISSUE TITLE
can't get git tag annotation

### ISSUE THREAD

**Issue by classabbyamp** [actions/virtual-environments#1717]
**Description**  
`git tag -l --format='%(subject)' <tag name>` returns the commit message, not the tag subject. `git tag -l --format='$(body)' <tag name>` returns the commit body (if it exists), not the tag body (if it exists).

Related to actions/runner#712

**Area for Triage**: Git

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Workflow prints
```
SUBJECT=this is the tag subject
BODY=this is the tag body
-----BEGIN PGP SIGNATURE-----

<tag pgp signature here>
-----END PGP SIGNATURE-----
```
If the tag is not signed, it would not have the PGP block.

**Actual behavior**  
Workflow prints
```
SUBJECT=this is the commit subject
BODY=this is the commit body
```

**Repro steps**  
Example run: https://github.com/classabbyamp/git-tag-bug/actions/runs/283446508

1. Create a new repository on Github, and clone it to your local machine.
2. Create a workflow `.github/workflows/bug.yml`:

```yaml
on:
  push:
    tags:
      - 'v*'

name: Showcase Bug

jobs:
  ubuntu-1804:
    name: Showcase Bug on 18.04
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Tag Info
        id: get_tag
        shell: bash
        run: |
          SUBJECT=$(/usr/bin/git tag -l ${GITHUB_REF#refs/tags/} --format='%(subject)')
          echo SUBJECT=$SUBJECT
          BODY=$(/usr/bin/git tag -l ${GITHUB_REF#refs/tags/} --format='%(body)')
          echo BODY=$BODY
  ubuntu-2004:
    name: Showcase Bug on 20.04
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Tag Info
        id: get_tag
        shell: bash
        run: |
          SUBJECT=$(/usr/bin/git tag -l ${GITHUB_REF#refs/tags/} --format='%(subject)')
          echo SUBJECT=$SUBJECT
          BODY=$(/usr/bin/git tag -l ${GITHUB_REF#refs/tags/} --format='%(body)')
          echo BODY=$BODY
```
This job will demonstrate the issue on both the 18.04 and 20.04 runners.
3. Stage, commit, and push this file
4. Create a file, stage, and commit it. In the commit message, put:
```
this is the commit subject

this is the commit body
```
5. Tag this commit as `v1.0.0` with `git tag -s v1.0.0`. In the annotation message, put:
```
this is the tag subject

this is the tag body
```
Signing is not required for this behaviour, only that the tag is annotated, so `git tag -a v1.0.0` would also work. The only difference in expected behaviour would be not having the PGP block in the body output.
6. Push the commit and the tag
7. Observe the results of the action

**Comment by classabbyamp** [comment]
Also note that the expected behaviour happens when running the `git tag -l` commands on my local arch and ubuntu machines, which have the same git version as the github workflow runners.

**Comment by vsafonkin** [comment]
Hello @classabbyamp , I believe the point is that the task `actions/checkout` fetches only last commit object from repository by default. For example, you will see error, if you tried `git checkout v1.0.0`.  In order to avoid it, you can set the `fetch-depth` parameter on the task (get all history for all branches and tags):
```
uses: actions/checkout@v2
  with:
    fetch-depth: 0
```
It's worked as expected: [link](https://github.com/vsafonkin/git-tag-bug/runs/1198798156?check_suite_focus=true)

**Comment by classabbyamp** [comment]
Setting `fetch-depth: 0` did not solve it for me, but this did (it works at all `fetch-depth`s, tested for 0-10):

```yaml
uses: actions/checkout@v2
with:
  ref: ${{ github.ref }}
```
