### ISSUE TITLE
.NET core: DotNetCoreCLI takes suddenly too long

### ISSUE THREAD

**Issue by FrancescElies** [actions/virtual-environments#1733]
**Description**  

DotNetCoreCLI@2 is suddenly extremely slow around 30 minutes without any code changes.
[example build (not open source)](https://mbbm-ast.visualstudio.com/AST/_build/results?buildId=40887&view=logs&j=478d6457-175a-5a6d-2808-da0dbe793335&t=5647d006-93ac-5ad2-cb47-052317d432cb)

Could someone help me understand if we are doing something wrong or something is going on with the windows images?

**Area for Triage**:  
.NET Core

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
I expect that task to take around ~5min instead of ~30min

**Actual behavior**  
Linked task takes ~30min

**Comment by dibir-magomedsaygitov** [comment]
Hello, @FrancescElies!
Thank you for your report. Could you please provide minimal repro steps since we don't have permissions to build that you have linked.

**Comment by FrancescElies** [comment]
This is the task we are using. more details about what we are doing I cant post it here.
```
- task: DotNetCoreCLI@2
    displayName: UnitTests 
    inputs:
      command: test
      projects: 'myproj.csproj'
      arguments: '--configuration $(buildConfig) --no-restore'
      testRunTitle: UnitTests 
```

Image version Infos:
```
Agent name: 'Azure Pipelines 12'
Agent machine name: 'WIN-LHABSG1F61T'
Current agent version: '2.175.2'
Current image version: '20200920.1'
```
