### ISSUE TITLE
Duplicated and extra matrix jobs generated when using macOS runner

### ISSUE THREAD

**Issue by BrightRan** [actions/virtual-environments#1738]
Associated GitHub Community ticket: https://github.community/t/specific-workflow-runs-keeps-failing-with-an-internal-error-on-macos/135997

The customer set a matrix in his workflow like as below:
```yaml
  ci_macos:
    name: macOS + vcpkg
    runs-on: macos-10.15
    strategy:
      matrix:
        qbt_gui: ["GUI=ON", "GUI=OFF"]
      fail-fast: false
```
According to the matrix configurations, it should only generate 2 matrix jobs:
* **`macOS + vcpkg (GUI=ON)`** runs on **`macos-10.15`**
* **`macOS + vcpkg (GUI=OFF)`** runs on **`macos-10.15`**

But when executing the workflow, it will generate some duplicated and extra matrix jobs, and all the extra matrix jobs will immediately go failed. See the following two example:
https://github.com/qbittorrent/qBittorrent/actions/runs/277763652/workflow
https://github.com/qbittorrent/qBittorrent/actions/runs/277637794/workflow

The customer also set the similar matrix configurations to run on the Ubuntu runners, the matrix can work fine, and no any extra matrix jobs generated.
```yaml
  ci_ubuntu:
    name: Ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
        qbt_gui: ["GUI=ON", "GUI=OFF"]
      fail-fast: false
```
