### ISSUE TITLE
Tool cache empty on macOS-latest

### ISSUE THREAD

**Issue by matchai** [actions/virtual-environments#174]
**Describe the bug**

Listing the contents of `$RUNNER_TOOL_CACHE`, it appears to be empty on macOS-latest and ubuntu-latest, stopping the installation of Ruby on either environment.

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
`$RUNNER_TOOL_CACHE` contains a list of available tools, including Ruby.

**Actual behavior**
Here is a link to a run with the following steps done:
https://github.com/starship/starship/runs/353090556#step:2:1

Steps to reproduce:
1. Run the following action:
```yml
jobs:
  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - run: ls $RUNNER_TOOL_CACHE
```
2. Check the output to see what is present in the tool cache.
