### ISSUE TITLE
Network flakiness continued

### ISSUE THREAD

**Issue by simonklb** [actions/virtual-environments#1759]
**Description**  
Seeing the same network flakiness as described in https://github.com/actions/virtual-environments/issues/1187

The accepted workaround seems to be to disable checksum offload. How would I do this if I run the job steps inside a container?

```
jobs:
  name:
    runs-on: ubuntu-latest
    container: foo/bar
```

**Area for Triage**:  
Servers

**Question, Bug, or Feature?**:  
Question

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
No timeouts.

**Actual behavior**  
Timeouts almost every run.

**Comment by LeonidLapshin** [comment]
Hi, @simonklb !
Unfortunately, there are no options in container job to set some privileges for docker container, but you still can do it manually, for example
```
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: check env
        run: |
          docker run --cap-add SYS_ADMIN --cap-add NET_ADMIN --security-opt apparmor:unconfined \
          --security-opt seccomp=unconfined --workdir /github/workspace ubuntu:latest \
          /bin/bash -c "apt-get update; apt-get install ethtool -y; ethtool -K eth0 tx off rx off"
```
Could you please check if the hardware checksum offloading disabling works for your case?

**Comment by simonklb** [comment]
I worked around it by running each step with `uses` and `with.args` instead of `container` and `run`:
```
jobs:
  name:
    runs-on: ubuntu-latest
    steps:
    - run: sudo ethtool -K eth0 tx off rx off
   ...
    - uses: docker://foo/bar
      with:
        args: xyz
```
So far I've not seen any timeouts, but it might be a bit early to tell. Also, this might not be suitable in all cases since you have to start a new container each time and rely on the default volumes if you want to share data such as `/github/home` etc.

Is there a reason why this is not fixed upstream instead of everyone having to inject this workaround?
