### ISSUE TITLE
Could not find 'bundler' (2.1.4) required by Gemfile.lock on macOS 10.15 using Xcode 11.7 / Ruby 2.6.6

### ISSUE THREAD

**Issue by simondelphia** [actions/virtual-environments#1976]
**Description**  
Running Github action where I specify Ruby 2.6.6 and Xcode 11.7 now fails on step `bundle install` because it can't find the right version of Bundler (2.1.4). According to https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md this version seems to be available. Running `gem install bundler` wastes an extra minute or two on each run. I started having issues when the default Ruby version was updated to 2.7.2 and Xcode to 12.1. I can't update to Xcode 12.1 yet because of a known compatibility issue with Carthage (and their workarounds are not working for me yet). I also tried just updating to Ruby 2.7.2 but then I would get the opposite error:

>Your Ruby version is 2.6.6, but your Gemfile specified 2.7.2

Presumably because of specifying Xcode 11.7 (using [maxim-lobanov/setup-xcode@v1](https://github.com/marketplace/actions/setup-xcode-version))? Does specifying Xcode 11.7 lead to an environment using Ruby 2.6.6?

**Area for Triage**:  Apple

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Bundler 2.1.4 should already be installed and no error should show. `bundle install` should work as before.

**Actual behavior**  
> Run bundle install
/Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.1.4) required by your /Users/runner/work/waterclock-ios/waterclock-ios/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.1.4`
	from /Users/runner/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
	from /Users/runner/hostedtoolcache/Ruby/2.6.6/x64/bin/bundle:23:in `<main>'
Error: Process completed with exit code 1.

Note if I try `bundle update --bundler` I get an error message about needing to use Bundler 2 or later, which indicates the environment is using Bundler 1.x.

**Repro steps**  

Workflow: 

```
name: Swift

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 11.7

      - name: Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.6

      - name: Bundle Install
        env:
          BUNDLE_FROZEN: "true"
        run: bundle install
```
I don't think the rest of yml file is relevant to this issue.

**Comment by dsame** [comment]
From the  error output you have provided i see the problem is you've updated your Gemfile lock file somehow to request bundler2:

```
Could not find 'bundler' (2.1.4) required by your ... Gemfile.lock
```

Most probably you have upgraded your local bundler to version 2 and issues `bundle update`.  From this you have to use bunder 2 across all your builds.

We can not afford to upgrade the bundler on the runners because it breaks the builds of the guys who continue to use bundler 1.

Thus you have either to upgrade the bundler to 2nd version in your pipeline or try to downgrade your lock file back to the first version by replacing 2.1.4 at the bottom of the file with 1.17.2

**Comment by simondelphia** [comment]
But https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md says

> Bundler version 2.1.4

And my workflow worked fine with Bundler 2.1.4 until recently.

**Comment by dsame** [comment]
The Readme says about default OSX ruby that is confirmed to have bundler 2.1.4, you do not need to switch to toolcache ruby which do not have bundler 2.

Please, provide the log of the build without this step

```
     - name: Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.6
```
