### ISSUE TITLE
Upgrade Windows 2019 image Visual Studio 16.8

### ISSUE THREAD

**Issue by robertmclaws** [actions/virtual-environments#2022]
Hey folks! Just wanted to give you folks a heads-up that a breaking change was introduced into .NET 5 that required mixed Framework / Core projects to use a version of MSBuild that only ships with the latest release. Since the "VS Preview" image was eliminated, there hasn't been a way to build our mixed projects in Azure DevOps for several months. 

I'm raising this ticket to make sure VS2019 gets upgraded in a timely manner, so those of us that can't build with `dotnet build` can still enjoy the magic that is .NET 5. You're awesome, thanks so much! 👊🏻

**Comment by Darleev** [comment]
Hello @robertmclaws,

We keep the visual studio version always up to date. However, deploying images can sometimes take a week(or two).

I will let you know right after the next image rollout.

**Comment by tsigereda** [comment]
Waiting for this eagerly, getting an error in AzureDevops pipelines that use MSbuild. Version 16.8.0 of MSBuild missing.

**Comment by tsigereda** [comment]
We are also waiting for this, we couldn't build our projects (Azure devops) that we upgraded to .Net 5 and waiting eagerly for the VS 16.8 to be available in the images.

**Comment by kvpt** [comment]
While waiting for the image to be updated a workaround is to update Visual Studio directly within the script.

This can be done like mentioned here : https://www.cazzulino.com/vs-preview-ci.html

I added these steps to my pipeline (it add 5/10 minutes to the build but the build pass now).

```yaml
- bash: dotnet tool update -g dotnet-vs
- bash: vs install preview sku:enterprise --quiet +Microsoft.VisualStudio.Component.ManagedDesktop.Core +Microsoft.NetCore.Component.DevelopmentTools
- bash: echo "##vso[task.prependpath]$(vs where preview --prop=InstallationPath)\MSBuild\Current\Bin"
```

No need to use the Net installer to install Net5 in this case as it is included with Visual Studio.
I tried to use the **[vs update](url)** command, but it was not working so I choose to install the preview version like in the blog post.
