### ISSUE TITLE
Windows Server 2019 20201108.1 breaks a build that works in 20201021.0

### ISSUE THREAD

**Issue by MarkStega** [actions/virtual-environments#2041]
**Description**  
A build of a dotnet project fails in 20201108.1

The csproj step that is failing is
```
  <Target Name="CheckIfNpmExists" Inputs="@(InputStaticAssetsScripts);@(InputStaticAssetsStyles)" Outputs="@(OutputStaticAssetsScripts);@(OutputStaticAssetsStyles)" BeforeTargets="PreBuildEvent">
    <Exec Command="echo ***** npm install" />
    <Exec Command="npm install" ContinueOnError="true" StandardOutputImportance="low" StandardErrorImportance="low" LogStandardErrorAsError="false" IgnoreExitCode="true">
      <Output TaskParameter="ExitCode" PropertyName="NpmReturnCode" />
    </Exec>
    <Exec Command="echo ***** 'npm install' return code was $(NpmReturnCode) (0 indicates npm is available)" />
  </Target>
```

My trace log shows
```
  ***** npm install
  ***** 'npm install' return code was 1 (0 indicates npm is available)
```
We have two developers collaborating and each has a fork of the repository in question

The developer with the failing run shows a virtual environment of
```
Virtual Environment
  Environment: windows-2019
  Version: 20201108.1
  Included Software: https://github.com/actions/virtual-environments/blob/win19/20201108.1/images/win/Windows2019-Readme.md
```
The developer whose fork build successfully (with all else the same) has
```
Virtual Environment
  Environment: windows-2019
  Version: 20201021.0
  Included Software: https://github.com/actions/virtual-environments/blob/win19/20201021.0/images/win/Windows2019-Readme.md
```
The builds are running as GitHub actions

**Area for Triage**:  

Scripting and command line

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [*] Windows Server 2019

**Expected behavior**  
I expect the 1108.1 build to succeed as the 1021.1 build does.

**Actual behavior**  
npm fails to run in the newer environment.

**Repro steps**  

1. The repository can be found at [https://github.com/Material-Blazor/Material.Blazor](https://github.com/Material-Blazor/Material.Blazor)
2. Fork the repository
3. Push a change to the main branch
4. Observe the failure of the build triggered by the push (GitHubActionsWIP.yaml is the WF file).
5. Force the earlier environment (I don't know how to do this but if I did it would be a suitable workaround until the error is fixed)
6. Push the change
7. Observe a successful build

**Comment by maxim-lobanov** [comment]
@MarkStega , I guess you are affected by this change: https://github.com/actions/virtual-environments/issues/1953.
Could you please try to follow mitigation ways to see if it helps?

**Comment by MarkStega** [comment]
It does not help
```
Run actions/setup-node@v1
  with:
    node-version: 12
    always-auth: false
  env:
    buildPlatform: Any CPU
    buildConfiguration: Release
    outputDocFx: D:\a\Material.Blazor\Material.Blazor\siteDocFx
    outputMB: D:\a\Material.Blazor\Material.Blazor\siteMB
    outputWeb: D:\a\Material.Blazor\Material.Blazor\siteWeb
    projectMB: Material.Blazor/Material.Blazor.csproj
    projectWeb: Material.Blazor.Website.WebAssembly/Material.Blazor.Website.WebAssembly.csproj
    ciSuffix: ci.2020-11-11--1511
C:\hostedtoolcache\windows\node\12.19.0\x64\node.exe --version
v12.19.0
C:\windows\system32\cmd.exe /D /S /C "C:\hostedtoolcache\windows\node\12.19.0\x64\npm.cmd --version"
6.14.8
```
The build fails in the same fashion. I have Node 14.15.0 on my local system and the build has no difficulty invoking NPM
