### ISSUE TITLE
Update Node.js to v15

### ISSUE THREAD

**Issue by umaar** [actions/virtual-environments#2051]
Regarding https://github.com/actions/node-versions - any chance of updating to use Node 15, or even 15.2.0? It's the latest current version.

**Comment by maxim-lobanov** [comment]
Hello @umaar ,
Node.JS 15 should be already available via setup tasks (it is not necessary to add it to actions/node-versions - this repo is just cache layer):
- [actions/setup-node](https://github.com/actions/setup-node) (GitHub Actions)
- [UseNode](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops) (Azure DevOps)

Please let me know if you can't select Node.JS 15 via these tasks

**Comment by umaar** [comment]
Oh true, so I can select it by specifying the exact version, but unless I'm mistaken, in the past I could use an asterisk to get the latest:

```
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '*'
```

But now the latest does not select v15

Don't know if that's tied to this repo at all, if not, please close thank you!

**Comment by maxim-lobanov** [comment]
Honestly, I am not sure why `*` is resolved as 14.x. It is better to ask for action owners in https://github.com/actions/setup-node

```yml
- uses: actions/setup-node@v1
  with:
    node-version: '15.x'
```
Works correctly for me
