### ISSUE TITLE
Ubuntu 20 Powershell execution permission bug

### ISSUE THREAD

**Issue by Satak** [actions/virtual-environments#2055]
**Description**  
Powershell script execution is not working in Ubuntu 20.04 environment:

```
Run .\scripts\test.ps1
mkdir: cannot create directory ‘/run/user/1001’: Permission denied
checking
```

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Powershell script should be run and executed without problems

**Actual behavior**  
Script is not executed and will terminate to an error: `mkdir: cannot create directory ‘/run/user/1001’: Permission denied`

**Repro steps**  

1. Create a Powershell script in repo
2. Try to run the Powershell script from GitHub actions in `pwsh` shell

Example
```yaml
runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run Powershell
        shell: pwsh
        run: ./scripts/test.ps1
```
