### ISSUE TITLE
Add support for ARM architecture in setup-python action

### ISSUE THREAD

**Issue by Elliot-Makuh-CardinalPeak** [actions/virtual-environments#2083]
**Tool information**
- Tool name: setup-python/Python
- Tool license: Free
- Add or update? Add ARM as supported architecture in setup-python action
- Desired version: Same as those supported for x86/x64
- Approximate size: 
- If this is an add request:
  - Brief description of tool: I am trying to use a RaspberryPi as a self hosted runner to run CI tests on a a hardware product I am developing.  My CI test suite relies on Python 3.7 but I cannot install Python on ARM using the [setup-python](https://github.com/marketplace/actions/setup-python) action as it is not a supported architecture in the [version-manifest](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json)
  - Provide a basic test case to validate the tool's functionality: My current action step looks like this:
```
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Hardware test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
```

**Area for Triage**: Python

**Question, Bug, or Feature?**: Feature

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
I believe I can work around the lack of ARM python support by installing this using apt but it would be very nice to have the action manage installing the version of Python.

**Tool installation time in runtime**
Should be comparable to installation time for existing x86/x64 Python versions.

**Are you willing to submit a PR?**
Potentially but I am not very familiar with what it takes to add support for this.  If I had some guidance I could submit a PR.
