### ISSUE TITLE
Add NuGet package manager

### ISSUE THREAD

**Issue by sgkoishi** [actions/virtual-environments#22]
**Tool information**
- Tool name: NuGet CLI
- Add or update? Add
- Desired version: [Latest](https://dist.nuget.org/win-x86-commandline/latest/nuget.exe)
- Approximate size: 5MB
- If this is an add request:
  - Brief description of tool: NuGet is a package manager comes with Visual Studio (as a extension/library).
  - URL for tool's homepage: https://www.nuget.org/

**Virtual environments affected**
- [ ] macOS 10.14
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
The requested version is a standalone executable, no installation required.

**Are you willing to submit a PR?**
Yes.

**Comment by xt0rted** [comment]
There's an action that will give you access to the nuget cli. It'd be nice if this was built-in though.

https://github.com/warrenbuckley/Setup-Nuget

**Comment by sgkoishi** [comment]
> 
> 
> There's an action that will give you access to the nuget cli. It'd be nice if this was built-in though.
> 
> https://github.com/warrenbuckley/Setup-Nuget

Thanks for noticing.

**Comment by mhutch** [comment]
nuget also appears to be missing from the Mono installation on Ubuntu, but is present on macOS.

**Comment by OssiGalkin** [comment]
Another workaround for this is to download nuget.exe on run-time. Windows lacks a convenient command-line tool for downloading files, but one can use certutils for that.

Complete step for it, and for restoring nuget packages, is:

```
- name: Restore NuGet Packages
  run: certutil.exe -urlcache -split -f "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe" nuget.exe
    nuget.exe restore
```

I think that on linux one can use wget to download linux version of nuget.

**Comment by krokofant** [comment]
This task seems to work as well
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/nuget?view=azure-devops
```yml
# NuGet tool installer
# Acquires a specific version of NuGet from the internet or the tools cache and adds it to the PATH. Use this task to change the version of NuGet used in the NuGet tasks.
- task: NuGetToolInstaller@0
  inputs:
    #versionSpec: '4.3.0' 
    #checkLatest: false # Optional
```
