### ISSUE TITLE
Xcode 12.2 doesn't include 10.15 SDK, causing builds to fail

### ISSUE THREAD

**Issue by jdv85** [actions/virtual-environments#2218]
**Description**  
In #2177 the default Xcode version was updated from 12.0.1 to 12.2. Unfortunately, Xcode 12.2 doesn't include the macOS 10.15 SDK. So now we need to manually select the Xcode version in order to build software targeting macOS 10.15 with the `macos-10.15` image.

**Area for Triage**:  Apple

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
The macos-10.15 image should be able to build software targetting macOS 10.15 using Xcode without manually setting the Xcode version.

**Actual behavior**  
Builds are failing because Xcode 12.2 does not know the macOS 10.15 SDK.

**Repro steps**  
In a pipeline job using the `macos-10.15` image, add an Xcode task like this:

```
- task: Xcode@5
  inputs:
    actions: 'test'
    scheme: 'scheme'
    sdk: 'macosx10.15'
    configuration: 'Debug'
    xcWorkspacePath: 'project.xcodeproj'
    xcodeVersion: 'default'
```
