### ISSUE TITLE
Hosted macOS workflows will experience longer wait times the week of December 14th.

### ISSUE THREAD

**Issue by thejoebourneidentity** [actions/virtual-environments#2247]
**Breaking changes**
GitHub's macOS datacenter is performing scheduled maintenance December 14-18. During this time customers may experience longer than normal wait times for their macOS workflows to begin.

**Target date**
December 14-18

**Possible impact**
Jobs using any of the macOS virtual environments may experience longer than normal queue times. In some cases it's possible workflows will time out, be cancelled, and need to be restarted.

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.13
- [X] macOS 10.14
- [X] macOS 10.15
- [X] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by Rashidium** [comment]
Good luck on your work. I wonder, if there will be any discounts on macOS hosted github-actions in this time interval?

**Comment by styfle** [comment]
Does this maintenance include fixing the [network issues](https://github.com/vercel/vercel/runs/1538921329) with macOS?

**Comment by dscho** [comment]
> I wonder, if there will be any discounts on macOS hosted github-actions in this time interval?

The problem is that [there is no way to re-run individual jobs](https://github.com/github/c2c-actions/issues/58) in GitHub Actions so far.

**Comment by dleff78** [comment]
Volleyball geil

**Comment by PhuocNguyen-Global** [comment]
Thank you

**Comment by regamask** [comment]
@Regarding hawkery here @regamask

**Comment by natmaxwell83** [comment]
Nice

**Comment by daniilshumkoidt** [comment]
Quite bad timing knowing that [App Store Connect is going on holiday](https://developer.apple.com/news/?id=l83x4b65) next week and everyone rushes to release their apps.

**Comment by IThinkImOKAY** [comment]
Thanks for the warning!

**Comment by TPXP** [comment]
I'm also facing network issues when installing yarn packages on a MacOS runner. I get error messages similar to the ones shown by @styfle , has this issue been identified and will the maintenance try to fix it, or should I raise it to the Github support?

**Comment by Brooooooklyn** [comment]
> Does this maintenance include fixing the [network issues](https://github.com/vercel/vercel/runs/1538921329) with macOS?

@styfle actually it's a bug from yarn. https://github.com/yarnpkg/yarn/issues/8242

The reason for this bug is that the macOS host disk is slow, and extra  large number of files from npm package such as `rxjs` would trigger this bug in yarn.

Maybe you have already observed that this  issue always happened on `rxjs` `@material/icons` etc. It couldn't be so accident that network always failure on downloading these packages.

**Comment by styfle** [comment]
@Brooooooklyn Its not just yarn that fails, all network requests fail eventually.

Even spawning a server on localhost will sometimes fail with [ECONNREFUSED](https://github.com/vercel/vercel/runs/1441269528#step:11:8148).

**Comment by nodeselector** [comment]
@styfle can you provide repro steps? I want to try and chase that down.

**Comment by styfle** [comment]
@nodeselector Thanks! The yarn issue should be easy to reproduce because it fails early.

Create a repo with this [package.json](https://github.com/vercel/vercel/blob/503b9a242976c20c48d691c72de6017da65f387a/package.json) and [yarn.lock](https://github.com/vercel/vercel/blob/503b9a242976c20c48d691c72de6017da65f387a/yarn.lock) in the root.

And then create a workflow that runs `yarn install`.

```yml
on:
  push:
    branches:
    - master
    tags:
    - '!*'
  pull_request:

jobs:
  test:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        node: [10, 12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
```
