### ISSUE TITLE
Add clang compiler for 'windows-latest'

### ISSUE THREAD

**Issue by LexouDuck** [actions/virtual-environments#2257]
**Tool information**
- Tool name: clang
- Tool license: UIUC (BSD-style) Open source
- Add or update? add
- Desired version: any
- Approximate size: 
- If this is an add request:
  - Brief description of tool: C compiler, typically installed with LLVM
  - URL for tool's homepage: https://clang.llvm.org/ and repo: https://github.com/llvm/llvm-project
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:
C/C++

**Question, Bug, or Feature?**:
Question

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Description**
When setting up a CI runner with GitHub Actions, using the `clang` terminal command in the runner does not work.
Here's an example where it is called via a Makefile:
![image](https://user-images.githubusercontent.com/35985773/102040695-cbb29300-3dcd-11eb-9ea7-0e285570b0e1.png)
I attempted to add several differents paths to to the PATH environment variable (using the new `echo "C:\path\ >> $GITHUB_PATH` syntax), to no avail.

After looking through the ["windows-latest" readme](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md), I only see Mingw-w64 in the list of installed tools - but the only occurences of 'LLVM' or 'Clang' are as Visual Studio components. Ideally, `clang` should work as a terminal command by default. I have been using a matrix to compile on all platforms using a cross-platform Makefile, and at the moment the only workaround I found is to exclude `clang` entirely from the windows build:
```yaml
...
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        compiler: [gcc, clang]
        exclude:
          - os: windows-latest
            compiler: clang

...

    - name: make (with ${{matrix.compiler}}, for ${{matrix.os}})
      run: make CC=${{matrix.compiler}}
```
Perhaps clang is in fact already installed somewhere, and I haven't looked in the right place or found the correct way to do this - any help here is much appreciated.

**Comment by maxim-lobanov** [comment]
clang is available on image as a part of MSYS2 in the following folders:
```
C:\msys64\mingw32\bin
C:\msys64\mingw64\bin
```
These folders are not in PATH by default since it will bring a lot of other tools in PATH.
You can add them to PATH during your build.

**Comment by LexouDuck** [comment]
Maybe I'm missing something, but the path you gave doesn't seem to fix this:
![image](https://user-images.githubusercontent.com/35985773/102124823-07d70980-3e49-11eb-9b94-3e031c9c5651.png)
I tried writing the path with both with single backslashes `\` and double backslashes `\\`, neither worked.
I also attempted to make an alias command with `alias clang="C:\msys64\mingw64\bin\clang.exe"` which didn't work either.
Is there something I'm missing/not understanding in your reply ?
Here's the part of the `ci.yml` in question:
```yml
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
    - uses: actions/checkout@v2

    - name: set clang env path
      if: runner.os == 'Windows'
      run: |
        echo "C:\msys64\mingw32\bin" >> $GITHUB_PATH
        echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
        clang --version

    - name: make (with ${{matrix.compiler}}, for ${{matrix.os}})
      run: make CC=${{matrix.compiler}}
```

**Comment by maxim-lobanov** [comment]
I think you use GitHub commands incorrectly. `GITHUB_PATH` is applied only to the next steps and it won't work immediately. Please follow documentation to specify proper PATH: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable

Also you should add only one path to GITHUB_PATH. `mingw32` or `mingw64` depend on what you need.

**Comment by LexouDuck** [comment]
Thanks for the clarifications. After doing several attempts, it turns out that what worked best was to manually specify to use a bash shell rather than the default (PowerShell) on all steps.

Here's the YAML runner code that ended up working:
````yml
    steps:
    - uses: actions/checkout@v2

    - name: Add clang path to $PATH env
      shell: bash
      if: runner.os == 'Windows'
      run: echo "PATH=$PATH:C:\msys64\mingw64\bin" >> $GITHUB_ENV

    - name: Build (with ${{matrix.compiler}}, for ${{matrix.os}})
      shell: bash
      run: make CC=${{matrix.compiler}}
```
