### ISSUE TITLE
Add Terragrunt

### ISSUE THREAD

**Issue by rtselizondo** [actions/virtual-environments#23]
**Tool information**
- Tool name: Terragrunt
- Add or update? Add
- Desired version: latest
- Approximate size: ~28MB
- If this is an add request:
  - Brief description of tool: Terragrunt is a thin wrapper for Terraform that provides extra tools for working with multiple Terraform modules.
  - URL for tool's homepage: https://github.com/gruntwork-io/terragrunt

**Virtual environments affected**
- [ ] macOS 10.14
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, Include appropriate binary from github.

**Are you willing to submit a PR?**
I am willing to attempt it.

**Comment by rtselizondo** [comment]
As a workaround I'm using this...



```
name: CI

on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download Terragrunt
      env:
        API_TOKEN: ${{secrets.GITHUB_API_TOKEN}}
      run: |
        terragrunt_version=$(curl -sL -H "Authorization: token ${API_TOKEN}" https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest |jq -r .tag_name)
        wget -O terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/${terragrunt_version}/terragrunt_linux_amd64
        chmod +x terragrunt

    - name: Get Versions
      run: |
        ./terragrunt --version
        terraform --version
```
