### ISSUE TITLE
missing 32-bit ("IA32") libgcc.a in the 20.04lts image

### ISSUE THREAD

**Issue by lersek** [actions/virtual-environments#2324]
**Description**
This report is basically identical to #2292, only the symptom is different. This time, our CI failure is caused by the apparent fact that the 32-bit gcc library (`libgcc`) is not installed in the Focal image, and so we cannot link 32-bit ("IA32") executables:

~~~
INFO - "gcc" -o /home/vsts/work/1/s/Build/EmulatorIA32/DEBUG_GCC5/IA32/Host -m32 -L/usr/X11R6/lib -Wl,--start-group,@/home/vsts/work/1/s/Build/EmulatorIA32/DEBUG_GCC5/IA32/EmulatorPkg/Unix/Host/Host/OUTPUT/static_library_files.lst,--end-group -lpthread -ldl -lXext -lX11
INFO - /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/9/libgcc.a when searching for -lgcc
INFO - /usr/bin/ld: cannot find -lgcc
INFO - /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/9/libgcc.a when searching for -lgcc
INFO - /usr/bin/ld: cannot find -lgcc
INFO - collect2: error: ld returned 1 exit status
INFO - make: *** [GNUmakefile:421: /home/vsts/work/1/s/Build/EmulatorIA32/DEBUG_GCC5/IA32/EmulatorPkg/Unix/Host/Host/DEBUG/Host] Error 1
~~~

Note the `-m32` flag on the gcc command line, versus the linker looking at x86_64 `libgcc.a`.

**Area for Triage**:
Packages.

**Question, Bug, or Feature?**:
Bug.

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
The link-editing phase should succeed.

**Actual behavior**  
See in the Description section.

**Repro steps**
Building any "hello world" style C program with `-m32` should reproduce the issue, especially when requesting static linking.

**Comment by dmitry-shibanov** [comment]
Hello @lersek . As I understood well ubuntu 20.04 does not provide libs for building with IA32. As the solution you can try use `sudo apt install gcc-4.8-multilib`. It should install multi-architecture [libs](https://askubuntu.com/questions/855945/what-exactly-does-gcc-multilib-mean-on-ubuntu). I added this step to extra_install_step:
```
        - bash: 
          displayName: do apt-get update
          condition: and(gt(variables.pkg_count, 0), eq(variables['Build.Arch'], 'IA32'), succeeded())
        - bash: sudo apt-get install libc6-dev:i386 libx11-dev:i386 libxext-dev:i386 lib32gcc-7-dev
          displayName: Add additional i386 packages
          condition: and(gt(variables.pkg_count, 0), eq(variables['Build.Arch'], 'IA32'), succeeded())
        - bash: |
             sudo apt install gcc-multilib
          displayName: Add additional i386 packages
          condition: and(gt(variables.pkg_count, 0), eq(variables['Build.Arch'], 'IA32'), succeeded())
```
