### ISSUE TITLE
Ubuntu 20.04: Create `$HOME/.my.cnf` configuration file to make `mysql` work out of the box and sidestep CLI issues

### ISSUE THREAD

**Issue by Calinou** [actions/virtual-environments#2372]
*See also #1432.*

**Edit:** Most of this issue is now outdated, jump to the bottom for an update.

___

**Description**  
~~The MySQL user `root` and password `root` don't appear to be valid in an Ubuntu 20.04 image, despite what the [documentation](https://github.com/actions/virtual-environments/blob/81909fddd54bd26440d1310ed37623c230944c5a/images/linux/Ubuntu2004-README.md#mysql) says.~~

**Area for Triage**: Databases

**Question, Bug, or Feature?**: ~~Bug~~ Feature

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
~~The documentation should match the actual MySQL server username/password.~~

**Actual behavior**  
~~The password is said to be incorrect, whether it's specified or not.~~

**Repro steps**  
https://github.com/Calinou/godot-website/tree/set-up-github-actions

YAML from the branch linked above (as of me posting this issue):

```yaml
name: Continuous integration
on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install October, run MySQL database and web server
        run: |
          sudo systemctl start mysql
          mysql -h localhost -u root -p root -e "CREATE DATABASE IF NOT EXISTS october;"

          pushd october
          php -r "eval('?>'.file_get_contents('https://octobercms.com/api/installer'));"
          cp -r ../plugins/* plugins
          cp -r ../themes/* themes
          sed -i "s/'password'   => ''/'password'   => 'root'/g" config/database.php
          sed -i "s/'activeTheme' => 'demo'/'activeTheme' => 'godotengine'/g" config/cms.php
          php -S localhost:8000
          popd
```

**Edit:** I'm getting this error message: ` Enter password: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)`

On second thought, maybe it's just the MySQL command line being finnicky? It would be good if a `$HOME/.my.cnf` client configuration file was included in the default installation so you don't have to specify the credentials in the command line :slightly_smiling_face: 
I could open a pull request for that.

```ini
[client]
user="root"
password="root"
```
