### ISSUE TITLE
MacOS Image 20210110.1 Android Build Fails - XA5101: Platform library directory for target Arm and API Level 4 was not found

### ISSUE THREAD

**Issue by IainS1986** [actions/virtual-environments#2481]
**Description**  
More info can be found here - https://developercommunity.visualstudio.com/content/problem/1313156/error-xa5101-platform-library-directory-for-target.html

Appears the Image released on 20210110.1 is throwing XA5101 Android build errors claiming it needed Android API Level 4 and its missing.

MacOS Image 20201212.1 works fine and is still on some of the Mac images so some builds sometimes go through fine.

Original user also reporting the issue on Windows images but I can't verify any image versions for that as we run on MacOS.

**Area for Triage**:  
Xamarin, Android, Apple

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [ ] macOS 11.0
- [X] macOS-Latest
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Android builds to build as before.

**Actual behavior**  
Android builds throwing Error : error XA5101: Platform library directory for target Arm and API Level 4 was not found.

**Repro steps**  
Setup a Xamarin Android build with msbuild and run on MacOS Image.

**Comment by david-rtf** [comment]
This is happening on the windows-latest image as well.

**Comment by al-cheb** [comment]
Hello, @IainS1986
Could you please check a comment - https://github.com/actions/virtual-environments/issues/2420#issuecomment-760969151 ? Does it work for you?

**Comment by IainS1986** [comment]
@al-cheb  Sure thing, giving it ago now

**Comment by al-cheb** [comment]
> This is happening on the windows-latest image as well.
Could you please try to install the previous version of ndk?
```
$sdkRoot = $env:ANDROID_HOME
$sdkManager = "$sdkRoot\tools\bin\sdkmanager.bat"
& $sdkManager --sdk_root=$sdkRoot install "ndk;21.3.6528147
```

**Comment by IainS1986** [comment]
@al-cheb Sorry took a while to get an image that was 202110110.1

So I added this task at the start of my android flow...

```
   - task: CmdLine@2
      displayName: "XA5101 Workaround"
      inputs:
        script: '${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.3.6528147"'
```

Seemed to execute fine, took around 1 minute but seemed to install the old NDK, last line was

`[=======================================] 100% Unzipping... android-ndk-r21d/wra`

But the android build still failed with the same error.

I can see the android build printed out

`Android NDK: /Users/runner/Library/Android/sdk/ndk-bundle/`

But don't know what NDK version was actually found there.

**Comment by IainS1986** [comment]
Missed the --sdk_root=${ANDROID_HOME}  as I saw a comment suggest it wasn't needed but I'll give it ago with that too to double check...

**Comment by IainS1986** [comment]
`${ANDROID_HOME}/tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} --install "ndk;22.0.7026061"`

Didn't work either :(

**Comment by maxim-lobanov** [comment]
Could you please try one more please: change `ANDROID_NDK_HOME` variable via bash step?
```
${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.3.6528147"
echo "##vso[task.setvariable variable=ANDROID_NDK_HOME;]$ANDROID_HOME/ndk/21.3.6528147"
```

**Comment by IainS1986** [comment]
Sure, I tried doing this with` 'export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/21.3.6528147'` and passing `msbuildArguments: '/p:AndroidNdkDirectory=$(ANDROID_NDK_HOME)'` into the XamarinAndroid@1 Task but that failed too.

I'll try your command and see how that is (I'll remove the msbuildArguments too)

**Comment by al-cheb** [comment]
@IainS1986, Could you share a sample?

**Comment by IainS1986** [comment]
Still no luck.

Can't really share a sample I'm afraid as its work related projection/solution.

As a cut down YML I have something like this for Android...

```
- job: Build_Android
    displayName: Build Android (AAB)
    steps:
    
    - task: CmdLine@2
      displayName: "XA5101/NDK r22 Workaround"
      inputs:
        script: |
          ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.3.6528147"
          echo "##vso[task.setvariable variable=ANDROID_NDK_HOME;]$ANDROID_HOME/ndk/21.3.6528147"
          echo 'Done!'

    - task: NuGetToolInstaller@1
      displayName: "Nuget Setup"

    - task: NuGetCommand@2
      displayName: "Nuget Restore"
      inputs:
        restoreSolution: '**/*.sln'   
        
    - task: XamarinAndroid@1
      inputs:
        projectFile: '$(Build.SourcesDirectory)/$(android.project.path)/$(android.project.name)'
        configuration: '$(build.configuration)'
        jdkOption: 'JDKVersion'

    - task: AndroidSigning@3
      inputs:
        apkFiles: '**/*.aab'
        apksignerKeystoreFile: 'xxx.xxx'
        apksignerKeystorePassword: '$(android.keystore.password)'
        apksignerKeystoreAlias: '$(android.key.alias)'
        apksignerKeyPassword: '$(android.key.password)'
        apksignerArguments: '--min-sdk-version 22'

    - task: CopyFiles@2
      displayName: 'Copy AAB Artifact'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/$(android.project.path)/bin/$(build.configuration)'
        Contents: '*.aab'
        TargetFolder: 'drop'

    - task: CopyFiles@2
      displayName: 'Copy Symbols Artifact(s)'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/$(android.project.path)/bin/$(build.configuration)'
        Contents: '*.pdb'
        TargetFolder: 'drop'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        pathToPublish: 'drop'
        artifactName: 'release'
```



My project has AOT, LLVM and Startup Tracing enabled.
Min API - 22 (5.0)
Target API - 30 (11)
Target Framework - Android 11 (R)

**Comment by IainS1986** [comment]
Ok think i've sorted it!

So I was close with the above but need to pass the msbuild argument still to the XamarinAndroid@1 - I guess this sets the NDK path itself regardless of what you do prior to it.

So I changed that task to...

```
    - task: XamarinAndroid@1
      inputs:
        projectFile: '$(Build.SourcesDirectory)/$(android.project.path)/$(android.project.name)'
        configuration: '$(build.configuration)'
        jdkOption: 'JDKVersion'
        msbuildArguments: '/p:AndroidNdkDirectory=$(ANDROID_NDK_HOME)'
```


And I got a green build on Image '20210110.1'

Can also confirm in the XamarinAndroid@1 output it printed Android NDK: `/Users/runner/Library/Android/sdk/ndk/21.3.6528147/` instead of the default Android NDK: `/Users/runner/Library/Android/sdk/ndk-bundle/`

Thanks for all the help with investigating a work around!

Am I right in assuming this is an issue in the latest OS images and will be resolved in future ones, or is there something else I should be investigating to resolve this NDK issue properly?

**Comment by maxim-lobanov** [comment]
@IainS1986, it is something that we should investigate before. On the latest image, NDK was updated from `21.3.6528147` to `22.0.7026061` that is expected change. You will get the same update if you run `sdkmanager --update` on local box.
Looks like we face with one of breaking change in NDK 22.x that affects Xamarin Android apps.
[In changelog](https://github.com/android/ndk/wiki/Changelog-r22) of NDK22, I see 
> The deprecated <NDK>/platforms and <NDK>/sysroot directories have been removed. These directories were merged and relocated into the toolchain during r19. The location of these contents should not be relevant to anyone, including build systems, since the toolchain handles them implicitly

That is pretty relevant to error that you experience 
```
Error : error XA5101: Platform library directory for target Arm and API Level 4 was not found. Expected path is “C:\Program Files (x86)\Android\android-sdk\ndk-bundle\platforms\android-4\arch-arm\usr\lib”
```

**Comment by maxim-lobanov** [comment]
Just to summarize thread above:
Since it looks like a breaking changes in NDK 22 (latest ndk-bundle), the best solution is upgrading app to support NDK 22.
If it is not possible, you can install NDK 21 in runtime and continue using it:
1) Add the following step at the begin of your build:
- Azure DevOps + Ubuntu / macOS (bash):
```
${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.3.6528147"
echo "##vso[task.setvariable variable=ANDROID_NDK_HOME;]$ANDROID_HOME/ndk/21.3.6528147"
```
- Azure DevOps + Windows (PowerShell):
```
& $env:ANDROID_HOME\tools\bin\sdkmanager.bat --install "ndk;21.3.6528147"
Write-Host "##vso[task.setvariable variable=ANDROID_NDK_HOME;]$env:ANDROID_HOME\ndk\21.3.6528147"
```

- GitHub Actions + Ubuntu / macOS (bash):
```
${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.3.6528147"
echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/21.3.6528147" >> $GITHUB_ENV
```
- GitHub Actions + Windows (PowerShell)
```
& $env:ANDROID_HOME\tools\bin\sdkmanager.bat --install "ndk;21.3.6528147"
echo "ANDROID_NDK_HOME=$env:ANDROID_HOME\ndk\21.3.6528147" >> $env:GITHUB_ENV
```

2. If you use Azure DevOps and Xamarin Android task, add `msbuildArguments` argument to it with proper NDK path
```
 - task: XamarinAndroid@1
      inputs:
        projectFile: '$(Build.SourcesDirectory)/$(android.project.path)/$(android.project.name)'
        configuration: '$(build.configuration)'
        jdkOption: 'JDKVersion'
        msbuildArguments: '/p:AndroidNdkDirectory=$(ANDROID_NDK_HOME)'
```
