### ISSUE TITLE
Cached gems on macOS don't work with system Ruby

### ISSUE THREAD

**Issue by igor-makarov** [actions/virtual-environments#2489]
**Description**  
At CocoaPods, we need to test our tools on the macOS system Ruby, the one that's pre-installed on the OS.

Lately, GH Actions has been failing to run gems installed from its cache. The error is
```
LoadError: dlopen(/Users/runner/work/CocoaPods/CocoaPods/vendor/bundle/gems/bigdecimal-1.3.5/lib/bigdecimal.bundle, 9): Library not loaded: /usr/local/opt/ruby/lib/libruby.2.7.dylib

  Referenced from: /Users/runner/work/CocoaPods/CocoaPods/vendor/bundle/gems/bigdecimal-1.3.5/lib/bigdecimal.bundle

  Reason: image not found - /Users/runner/work/CocoaPods/CocoaPods/vendor/bundle/gems/bigdecimal-1.3.5/lib/bigdecimal.bundle
```
Link to a sample of the failing build: https://github.com/CocoaPods/CocoaPods/runs/1701161849?check_suite_focus=true

Please note that this is already after trying to resolve the issue by changing the cache key sharing.

Thank you.

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by miketimofeev** [comment]
Hi @igor-makarov!
Most likely it's related to the new image being rolled out. As I can see from your runs cache worked on ImageVersion 20201212.1 and stopped working on 20210110.1. Could you please try to recreate it using the new Image Version?
PS: we're going to rollback the image to 20201212.1 tomorrow due to issues with Android NDK so probably the cache will work without rebuilding again after that.

**Comment by igor-makarov** [comment]
@miketimofeev I'm not sure what image version it is, but I did try in the past to use the image version in the cache key and it wasn't possible. Is it exposed as a runner var or something? 

If it was possible to use image version in the cache key, it'll be ideal.

**Comment by miketimofeev** [comment]
@igor-makarov that's what I'm also thinking about — stick the cache to the image version and it's, fortunately, possible because we have the `ImageVersion` variable on the image:
```
      - name: Set env variable
        run: echo "ImageVersion=$ImageVersion"  >> $GITHUB_ENV

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: gems@v1-${{ matrix.os }}-Ruby${{ matrix.ruby }}-${{ env.ImageVersion }}-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            gems@v1-${{ matrix.os }}-Ruby${{ matrix.ruby }}-${{ env.ImageVersion }}
```
