### ISSUE TITLE
How to select install gcc version?

### ISSUE THREAD

**Issue by tdegeus** [actions/virtual-environments#2503]
**Description**  
I have a completely naive question, but after many tries and many internet searches I still do not seem to manage. The question is:

How do I select a different than standard gcc version on GitHub actions? My latests try was this:
```yaml
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - runs-on: ubuntu-latest
            compiler: gcc
            gcc: 8
```
but the action *still* runs gcc 7.5.0.

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Question

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Select gcc 8 using CMake

**Actual behavior**  
CMake selecting 7.5.0

**Repro steps**  

See https://github.com/tdegeus/GooseFEM/pull/148

**Comment by dibir-magomedsaygitov** [comment]
Hello, @tdegeus. Thank you for your report. We've started investigation process and I'll post an update message once we have something to share.

**Comment by dibir-magomedsaygitov** [comment]
Hello, @tdegeus
Sorry for the delay with an answer. Seems like your workflow works fine and Cmake selects correct version of GCC:
![screen](https://user-images.githubusercontent.com/61747324/106136661-a5c53000-617a-11eb-89fc-23eaad928282.jpg)

**Comment by tdegeus** [comment]
Hi @dibir-magomedsaygitov . Thanks for your comment! Indeed with the current 'work-around' it works fine. I was just wondering if there is a better way to select the compiler?

**Comment by dibir-magomedsaygitov** [comment]
Thank you for your answer. There is another way to select the compiler, but that way is similar to your approach:
```
env:
        CC: gcc-${{ matrix.gcc }}
        CXX: g++-${{ matrix.gcc }}
```

**Comment by tdegeus** [comment]
That makes sense, thanks! Is there some documentation about this?

**Comment by tdegeus** [comment]
Actually... I don't know have to use the suggestion. In particular, with with `uses` should it go?

**Comment by dibir-magomedsaygitov** [comment]
You can set environment variables that are available to the steps of all jobs in the workflow. You can also set environment variables that are only available to the steps of a single job or to a single step. (See details in [docs](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#env)).
Here is an example of using evn variables on step level (for your use case):
```
    - name: Configure using CMake (!Windows)
      env:
        CC: gcc-${{ matrix.gcc }}
        CXX: g++-${{ matrix.gcc }}
      if: runner.os != 'Windows'
      run: cmake . ${{ matrix.config }}
```
