### ISSUE TITLE
[macOS] Ruby runtime failure with Xcode 12.x on macos-10.15

### ISSUE THREAD

**Issue by mkalmes** [actions/virtual-environments#2581]
**Description**  
Workflow runs with `pod install`, Xcode 12.x on `macos-10.15` fail with

```
LoadError - dlopen(/Users/runner/work/[redacted]/fastlane/temporary/bundle/ruby/2.7.0/gems/ffi-1.13.1/lib/ffi_c.bundle, 9): Library not loaded: /usr/local/opt/ruby/lib/libruby.2.7.dylib
```

**Area for Triage**:  

Apple, Ruby

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
`pod install` should install dependencies.

**Actual behavior**  
`pod install` fails and dependencies are not installed.

We've noticed our first failed run at Fri, 15 Jan 2021 11:31:52 GMT. In the last two days, our builds started to fail more often until today, every workflow run failed with the same error.

We've opened support ticket 998906 and were asked to open an issue as well.

**Comment by miketimofeev** [comment]
Hi @mkalmes!
This directory doesn't exist `/usr/local/opt/ruby/lib/libruby.2.7.dylib`, the lib is in `/usr/local/opt/ruby@2.7/lib/libruby.2.7.dylib` now because of brew installation changes. Is the path hardcoded somewhere or `pod install` resolves it automatically? And it would be great if you could provide a minimal repro.

**Comment by miketimofeev** [comment]
@mkalmes another thought — do you use actions\cache task in your workflow? We have a pretty similar issue not so long ago https://github.com/actions/virtual-environments/issues/2489

**Comment by mkalmes** [comment]
@miketimofeev: Thanks for your help. #2489 did fix the problem.

We've changed `key` and `restore-keys` to use the current image version.

```
- name: Cache gems
  uses: actions/cache@v2
  with:
    path: path/to/bundle
    key: ${{ runner.os }}-gems-${{ env.ImageVersion }}-${{ hashFiles('**/Gemfile.lock') }}
    restore-keys: |
      ${{ runner.os }}-gems-${{ env.ImageVersion }}
```

In hindsight, this was an easy fix but hard for us to investigate. If possible, could you explain how we can better triage this kind of problem?

Again, thanks for your help! 👍
