### ISSUE TITLE
Python 3.7.9 and pyodbc on app service glibc error

### ISSUE THREAD

**Issue by lukesavvatiller** [actions/virtual-environments#2634]
Have not made any changes to my python app service and it now fails. I thnk it is becuase python version has changed. I am getting an error message saying pyodbc now needs glibc 2.29. Which isnt available on the debian 9 app services.

django.core.exceptions.ImproperlyConfigured: Error loading pyodbc module: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/site/wwwroot/antenv/lib/python3.7/site-packages/pyodbc.cpython-37m-x86_64-linux-gnu.so).

To replicate try and use python 3.7.9 and pyodbc on a linux app service

**Comment by Darleev** [comment]
Hello @lukesavvatiller,
Could you please provide more details regarding the issue you have faced:
- environment(ubuntu/macos/windows)
- how to reproduce the issue(minimal steps to reproduce or test project)
- did you try to reproduce the issue locally?

We are looking forward to your reply.

**Comment by Darleev** [comment]
Hello @lukesavvatiller,
Could you please check the reply above and provide additional information regarding the issue you've reported?

We are looking forward to your reply.

**Comment by lukesavvatiller** [comment]
So i have a python django api which is built and released on ubuntu 20.04 build/ release pipelines and deployed to a linux app service. The django app used an azure sql server utilising pyodbc to connect. We use the UsePythonVersion task in our pipelines to get python. It appears that this task has been updated and now uses a different version of python/ pyodbc? 

The result is.. that pyodbc gets installed in the build pipeline and runs our tests fine.. but on deployment to the debian 9 app service it throws the error `django.core.exceptions.ImproperlyConfigured: Error loading pyodbc module: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/site/wwwroot/antenv/lib/python3.7/site-packages/pyodbc.cpython-37m-x86_64-linux-gnu.so)`.

It is complaining that pyodbc cannot find GLIBC_2.29, however the most recent GLIBC is 2.24 for debian 9 but 2.29 is available on the ubuntu 20.04 pipelines. I have tried changing to different OS on the pipelines to no avail. The (ugly) workaround for now is that i have had to write tasks to install python directly from the deadsnakes repository on the build and release pipeline. This has fixed the errors. So if i use the version of python from deadsnakes everything works but the UsePythonTask causes pyodbc to fail on debian 9.

**Comment by Darleev** [comment]
Hello @lukesavvatiller,
In order to avoid the issue, could you please try to set the exact version of Python for the UsePythonVersion task? Also, it would be great if you provide us with minimal reproduction steps or how it is possible to replicate the issue on our side.
You can find a list of changed software in the latest image version [by link](https://github.com/actions/virtual-environments/pull/2599/files), maybe it helps to find some additional details to resolve the issue.

**Comment by lukesavvatiller** [comment]
For anyone else struggling with this issue. I added this script to the build and release pipeline: 
`- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        # add deadsnakes repo, install 3.7 and symlink python to python3.7
        sudo apt update
        sudo apt install software-properties-common
        yes | sudo add-apt-repository ppa:deadsnakes/ppa 
        sudo apt-get install python3.7
        sudo rm -rf /usr/bin/python
        sudo ln -s /usr/bin/python3.7 /usr/bin/python
        python -m pip install virtualenv
        sudo apt-get install unixodbc-dev
        sudo apt install python3.7-dev
        python -m pip install --user pyodbc
        python -m virtualenv antenv
        source antenv/bin/activate
        python -V
        python -c "import sys; print(sys.executable)"
        python -m pip install --upgrade pip
        pip install setup
        pip install -r requirements.txt
      workingDirectory: $(projectRoot)
      displayName: "Install requirements"`

**Comment by lukesavvatiller** [comment]
@Darleev, in order to reproduce the issue. Create a python (it might have to be django) application that uses the pyodbc library. Build and release this application on ubuntu pipelines and deploy to a linux azure app service. You will get the error message on startup of the app service.

**Comment by Darleev** [comment]
@lukesavvatiller Did you try to specify an exact version of python in the UsePythonVersion(including minor version) task? It should also resolve the initial problem.

**Comment by Darleev** [comment]
@lukesavvatiller unfortunately, we are not deep python experts, and the creation of this test app is a significant time-consuming task, that might extend the issue investigation period. We would really appreciate it if you could provide some public repo with minimal repro steps, so we will be sure what is the exact issue and project configuration we have to deal with.

**Comment by Darleev** [comment]
Hello @lukesavvatiller,
I'm going to close the issue until further updates from your side.
In case of any questions do not hesitate to contact us.

**Comment by gtalarico** [comment]
@Darleev @alexander-smolyakov 

Same thing happened with me - working CI build stopped working with no code change.
Hope it's ok to hop on this issue to provide a minimal repro.
If you prefer, I can also move this over to a new issue.

Here is the actual project failure
https://github.com/gtalarico/gh-actions-repro/runs/2330808953?check_suite_focus=true

Workflow:
https://github.com/gtalarico/gh-actions-repro/blob/master/.github/workflows/django.yml


### Screenshot
![image](https://user-images.githubusercontent.com/9513968/114508307-0d6f1100-9be9-11eb-9014-11d6c97c36c7.png)


```
name: Bug Repro

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: python:3.8

    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests


      - name: Run Tests
        run: |
          python -c "from datetime import datetime; print(datetime.now())"

```
