### ISSUE TITLE
Add zsh shell

### ISSUE THREAD

**Issue by phil-blain** [actions/virtual-environments#264]
**Tool information**
- Tool name: zsh
- Add or update? add
- Desired version: the one that is already at `/bin/zsh` 
- Approximate size: probably 0 since it's already installed 
- If this is an add request:
  - Brief description of tool: [zsh is the new default shell starting with macOS 10.15](https://support.apple.com/en-us/HT208050) so it would make sense that jobs could easily use it as their shell.
  - URL for tool's homepage: https://www.zsh.org/

**Area for Triage**:

Scripting and command line

**Question, Bug, or Feature?**:

Feature 

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

It's already installed, so jobs can do `zsh -c 'whatever'` or use a custom shell command but it would be easier to be able to write:
~~~yml
steps:
  - name: Display the path
    run: echo $PATH
    shell: zsh
~~~

**Are you willing to submit a PR?**

How would I do that ?....

**Comment by al-cheb** [comment]
Hello, @phil-blain 

You can set the shell value to a template string using` command […options] {0} [..more_options]` : [Custom shell](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions)

Example output:
```
- name: Display the path
      run: |
        echo $ZSH_NAME $ZSH_VERSION
      shell: zsh {0}
```

![image](https://user-images.githubusercontent.com/47745270/72321159-3c2fcc00-36b4-11ea-945b-4719725e956b.png)

**Comment by maxim-lobanov** [comment]
Closing the issue since solution was provided above. Feel free to reopen if needs

**Comment by michaeltryby** [comment]
Since zsh is the default shell on Mac OS, it's surprising that it's not fully supported in Actions.

**Comment by maxim-lobanov** [comment]
@michaeltryby , bash and zsh shell are not equal. And switching to zsh can affect a lot of customers and break existing scripts

**Comment by michaeltryby** [comment]
@michaeltryby support both.

**Comment by ljharb** [comment]
@maxim-lobanov i really don't understand why this is closed. Nobody's asking to change the default, but zsh should still be a first-class supported option.

**Comment by ssbarnea** [comment]
Preinstalling zsh should be done on all platforms because it is a very common shell and many repositories do have shell support testing code. While is unlikely that someone would want to run jobs with zsh shell, the is a real chance they would have few tests around what happens with zsh (completions being one of them).

Also zsh is small, so it should not concern increasing images too much.

**Comment by ki11roy** [comment]
Why this one is closed? The shell is still missing on ubuntu-latest, for example too.

**Comment by miketimofeev** [comment]
@ki11roy installing zsh takes about 20 seconds in runtime so it shouldn't be the issue.

**Comment by ljharb** [comment]
@miketimofeev the time isn’t the issue; it’s knowing which install command to use, and having to conditionally run it when testing on a matrix of shells.

**Comment by ki11roy** [comment]
Example use case for zsh on ubuntu-latest (substitution) 
```
name: RemoveMe 
on:
  workflow_dispatch:
jobs:
  jobName:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install zsh
        run: sudo apt-get update; sudo apt-get install zsh
      - name: Print outputs branch name
        id: vars_branch
        run: echo "::set-output name=branch::${${GITHUB_BRANCH#refs/heads/}//\//-}"
        env:
          GITHUB_BRANCH: "test/1.2.3"
        shell: zsh {0}
      - name: Print branch name
        id: print
        run: echo "${{steps.vars_branch.outputs.branch}}"
```
