### ISSUE TITLE
Memory error while running mocha tests on a Windows 2019 agent

### ISSUE THREAD

**Issue by waldekmastykarz** [actions/virtual-environments#2642]
**Description**  

Memory error while running mocha tests on a Windows 2019 agent

**Bug**:  

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**

20210121.0

**Expected behavior**  

Run tests without any errors

**Actual behavior**  

While running, mocha tests are failing at some point with the following error:

```text
# Fatal error in , line 0
# Fatal process out of memory: Zone
#FailureMessage Object: 0000000E08BF9C50
```

**Repro steps**  

See this workflow run: https://github.com/waldekmastykarz/cli-githubactions/runs/1844914810?check_suite_focus=true
In the same repo you can find previous runs where I tried adjusting different Node settings without any result. I also tried to run the same tests on a Standard DS2 v2 Azure VM with Win 2019 and there the code runs as expected.

The same tests work just fine on the Ubuntu and macOS agents.

**Comment by al-cheb** [comment]
Hello, @waldekmastykarz 
Could you please increase swap at runtime?
```
- name: configure Pagefile
  uses: al-cheb/configure-pagefile-action@v1.2
  with:
      minimum-size: 16GB
      maximum-size: 16GB
      disk-root: "C:"
```
