### ISSUE TITLE
Installed Moby (docker) version is incorrect (20.10.2 vs documented 19.03.14)

### ISSUE THREAD

**Issue by csrl** [actions/virtual-environments#2654]
**Description**  
The ubuntu linux image environment README states that Docker-Moby 19.03.14 is installed in the environment.  However, when connecting to my own private registry from my own github action, I see the user agent is:

`http.request.useragent="docker/20.10.2+azure go/go1.13.15 git-commit/8891c58a433a823ce0a65b57efff45f32ee9cb45 kernel/5.4.0-1039-azure os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.15 \\(linux\\))"`

The upstream 19.03.15 client is from my action's Dockerfile `FROM: docker:19` line.  So it appears that the host environment is running `docker/20.10.2+azure`

Docker 20.10 disables support for pushing Manifest v2 Schema 1 which we currently require.  This was done in https://github.com/moby/moby/pull/41295/files

They do have an environment variable `DOCKER_ALLOW_SCHEMA1_PUSH_DONOTUSE` that can be set to 1 in order to re-enable the support.  So if https://github.com/actions/virtual-environments/blob/main/images/linux/ubuntu1804.json#L180 could be updated to support setting that env var, then the use of docker 20.10 would be acceptable.

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
  Environment: ubuntu-18.04
  Version: 20210131.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20210131.1/images/linux/Ubuntu1804-README.md

**Expected behavior**  
Docker v 19.03.14 to be in use

**Actual behavior**  
Docker v 20.10.2 is in use

**Repro steps**  
Push a docker image to a respository that requires manifest v2 schema 1.  It will fail.

We are quite aware that schema 1 is no longer supported, however this is a breaking change to upgrade to docker 20.10 to github runners that was not communicated, and we were given no time to adjust.

**Comment by miketimofeev** [comment]
Hi @csrl!
Looks like we provide only the client version in the docs and that's why it's still 19.* 
We will rework documentation generation to provide both engine and client versions and consider adding `DOCKER_ALLOW_SCHEMA1_PUSH_DONOTUSE` variable.

**Comment by csrl** [comment]
Hi @miketimofeev, thank you for the response. This of course has an immediate need/effect on us.  Can you suggest a path that could resolve this today?

Our options seem to be:

1. github restores the previous docker engine that was in use until last week
2. stop using github actions
3. run our own github runner
4. migrate our registry

It would be preferred from our side of course for option 1) to happen.  But if there is an alternative short term solution, we would appreciate your feedback.

Thanks!

**Comment by miketimofeev** [comment]
@csrl Unfortunately option 1) is almost impossible since there were a lot of changes we brought with the 20210131.1 version, so in our opinion migrating your registry is a much better solution as it will be required to do sooner or later anyway. Speaking about the env variable we also incline not to add it because it may bring issues in the future and make it difficult to support.

**Comment by csrl** [comment]
Ok, thanks for looking at this, and getting the doc PR in.  Hopefully such breaking changes can be caught ahead of time in the future.

**Comment by miketimofeev** [comment]
By the way, could you try to set this `DOCKER_ALLOW_SCHEMA1_PUSH_DONOTUSE` env variable in runtime as the very first step of your pipeline. Does it help? Or do you use `container:` task?

**Comment by csrl** [comment]
If I understood you correctly, I modified the start of the workflow to have the following (it did not work):
```
jobs:
  docker-publish:
    runs-on: ubuntu-18.04
    env:
      DOCKER_ALLOW_SCHEMA1_PUSH_DONOTUSE: 1
    steps:
    - name: Show Env
      run: |
        echo "the var is: $DOCKER_ALLOW_SCHEMA1_PUSH_DONOTUSE"

    - name: Copy Repo Files
      uses: actions/checkout@v2

    - name: Checkout Action - publish-to-docker-registry
      uses: actions/checkout@v2
      with:
        <snip>
        path: .github/actions/shared

    - name: Publish Docker Image
      uses: ./.github/actions/shared/publish-to-docker-registry
      id: docker
     <snip>
```
The Show Env step prints out 
```
Run echo "the var is: $DOCKER_ALLOW_SCHEMA1_PUSH_DONOTUSE"
the var is: 1
```
And the `./.github/actions/shared/publish-to-docker-registry` action contains:
```
<snip>
runs:
  using: 'docker'
  image: 'Dockerfile'
```
I modified the Dockerfile reference to also print out if the env var is set, and it is.  So it propagates all the way through.

However, it is the process env for the docker engine is what would need to be updated.  So the docker engine on the host would need to be restarted after setting that env var, yes?
