### ISSUE TITLE
[Windows, Ubuntu] Boost 1.72.0 will be removed from images on March, 8

### ISSUE THREAD

**Issue by MaksimZhukov** [actions/virtual-environments#2667]
**Breaking changes**
Boost 1.72.0 will be removed from Windows and Ubuntu images. Please note that 1.72.0 is the single version of Boost pre-installed on images.

**Target date**
Image deployment will start March, 8 and will take 3-4 days.

**The motivation for the changes**
We are going to deprecate Boost due to lack of free space on images, maintenance concerns and low popularity.

**Possible impact**
If your project depends on Boost 1.72.0 — build will be broken.

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.13
- [ ] macOS 10.14
- [ ] macOS 10.15
- [ ] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**What's the future of Boost?**
We don't have plans to install any version of Boost on the images. Please see details in this issue:  https://github.com/actions/virtual-environments/issues/2425

Please note the [actions/boost-versions](https://github.com/actions/boost-versions) repository will not be maintained in the future.

**Mitigation ways**
If you need to continue using Boost 1.72.0 in your build, please consider the following ways to install it in runtime:

1) Windows
- Install Boost 1.72.0 from releases of [actions/boost-versions](https://github.com/actions/boost-versions/releases) repository:
```
# Use the boost-1.72.0-win32-msvc14.1-x86_64.tar.gz for Windows 2016
$url = "https://github.com/actions/boost-versions/releases/download/1.72.0-20200608.4/boost-1.72.0-win32-msvc14.2-x86_64.tar.gz"
(New-Object System.Net.WebClient).DownloadFile($url, "$env:TEMP\boost.tar.gz")
7z.exe x "$env:TEMP\boost.tar.gz" -o"$env:TEMP\boostArchive" -y | Out-Null
7z.exe x "$env:TEMP\boostArchive" -o"$env:TEMP\boost" -y | Out-Null
Push-Location -Path "$env:TEMP\boost"
Invoke-Expression .\setup.ps1
```

The above code snippet will install Boost to the `C:\hostedtoolcache\windows\Boost\1.72.0\x86_64` folder.

- Download [official pre-build binaries](https://sourceforge.net/projects/boost/files/boost-binaries/) provided by Boost team:
```
# Use the boost_1_72_0-msvc-14.1-64.exe for Windows 2016
$Url = "https://sourceforge.net/projects/boost/files/boost-binaries/1.72.0/boost_1_72_0-msvc-14.2-64.exe"
(New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\boost.exe")
Start-Process -Wait -FilePath "$env:TEMP\boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=C:\hostedtoolcache\windows\Boost\1.72.0\x86_64"
```

2) Ubuntu:
- Install Boost 1.72.0 from releases of [actions/boost-versions](https://github.com/actions/boost-versions/releases) repository:
```
# Use the boost-1.72.0-linux-16.04-gcc-x64.tar.gz for Ubuntu 16.04
$url = "https://github.com/actions/boost-versions/releases/download/1.72.0-20200608.4/boost-1.72.0-linux-18.04-gcc-x64.tar.gz"
(New-Object System.Net.WebClient).DownloadFile($url, "/tmp/boost.tar.gz")
mkdir "/tmp/boost"
tar -xzf "/tmp/boost.tar.gz" -C "/tmp/boost"
Push-Location -Path "/tmp/boost"
Invoke-Expression "bash ./setup.sh"
```

The above code snippet will install Boost to the `/opt/hostedtoolcache/boost/1.72.0/x64` folder.

- Use apt packages: https://www.osetc.com/en/how-to-install-boost-on-ubuntu-16-04-18-04-linux.html
- Use vcpkg + caching feature (the first build could take much time but consuming existing cache works really fast)

3) macOS: install via `brew install boost`

**Comment by vadi2** [comment]
For anyone who uses a header-only boost and doesn't need to compile, the following will work on macOS/Linux/Windows. Courtesy of [Mudlet](https://github.com/Mudlet/Mudlet).

```yml
    env:
      BOOST_ROOT: ${{github.workspace}}/3rdparty/boost
      BOOST_URL: https://sourceforge.net/projects/boost/files/boost/1.72.0/boost_1_72_0.tar.bz2/download

    steps:
    - name: Restore Boost cache
      uses: actions/cache@v2
      id: cache-boost
      with:
        path: ${{env.BOOST_ROOT}}
        key: boost

    - name: Install Boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      run: |
        if [ "$OS" == "Windows_NT" ]; then
          # fix up paths to be forward slashes consistently
          BOOST_ROOT=$(echo $BOOST_ROOT | sed 's/\\/\//g')
        fi
        mkdir -p $BOOST_ROOT
        curl --progress-bar --location --output $BOOST_ROOT/download.tar.bz2 $BOOST_URL
        7z -o$BOOST_ROOT x $BOOST_ROOT/download.tar.bz2 -y -bd
        7z -o$BOOST_ROOT x $BOOST_ROOT/download.tar -y -bd
        cd $BOOST_ROOT && mv -r boost_*/* .
        rm download.tar.bz2 download.tar
      shell: bash
```
