### ISSUE TITLE
xcrun --show-sdk-version fails

### ISSUE THREAD

**Issue by michaelfletchercurve** [actions/virtual-environments#2785]
**Description**  
I have having problems building qt5-base via vcpkg.  I have narrowed down the problem to the fact that 'xcrun --show-sdk-version' fails to determine the sdk version.  The vcpkg qt build uses xcrun to determine what sdk version is being used.

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug
**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
Current image version: '20210220.1'

**Expected behavior**  
xcrun --show-sdk-version should display the sdk.  Typical output is "11.1".

**Actual behavior**  
xcodebuild: error: SDK "/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk" cannot be located.
xcrun: error: unable to lookup item 'SDKVersion' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk'

**Repro steps**  
This will trigger it ...

```
trigger:
- snipped

strategy:
  matrix:
    mac:
      imageName: 'macOS-10.15'

pool:
  vmImage: $(imageName)

steps:
- script: |
    /bin/bash -c "sudo xcode-select -s /Applications/Xcode_12.4.app/Contents/Developer"
    xcrun --show-sdk-version
  condition: eq( variables['Agent.OS'], 'Darwin' )
  displayName: Select xcode version.
```
