### ISSUE TITLE
GitHub Actions has encountered an internal error when running your job

### ISSUE THREAD

**Issue by TD-CSK** [actions/virtual-environments#2788]
**Description**  
I changed only repository name in ecosystem.config.js. When I switched it back, nothing changes. I still get this error.

**Area for Triage**:  
Deployment/Release

**Question, Bug, or Feature?**:  
Question

**Virtual environments affected**  
 Ubuntu 20.04

**Image version**
latest

**Expected behavior**  
I expected job to be run.

**Actual behavior**  
Job crashes in 3-5 seconds.

**Repro steps**  
```
name: CI - Master
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #
      # ... your other steps, such as running tests, etc...
      #
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SECRET_TEST" > ./deploy.key
          sudo chmod 600 ./deploy.key
          echo "$KNOWN_HOSTS_TEST" > ~/.ssh/known_hosts
        shell: bash
        env:
          SECRET_TEST: ${{secrets.SECRET_TEST}}
          KNOWN_HOSTS_TEST: ${{secrets.KNOWN_HOSTS_TEST}}


      - name: Install PM2
        run: sudo npm i pm2 -g

      - name: Deploy
        run: npm run deploy
```
I just changed name if the repo from https://... to git@... Then I changed it back, but it didn't help

**Comment by miketimofeev** [comment]
Hi @TD-CSK!
Could you please provide a bit more details:
- What step fails? 
- Is it happen on all ubuntu versions or Ubuntu 20 only? 
- Are there any logs of failing run?
- Is it possible to provide a link to failed run (even if it's private) or create a minimal repro?

I've tried the following steps, and for me, they run just fine except for the last step since I don't have any package.json:
```
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #
      # ... your other steps, such as running tests, etc...
      #
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "dasdsadasd" > ./deploy.key
          sudo chmod 600 ./deploy.key
          echo "10.74.5.6" > ~/.ssh/known_hosts
        shell: bash
      - name: Install PM2
        run: sudo npm i pm2 -g

      - name: Deploy
        run: npm run deploy
```
