### ISSUE TITLE
Problems with Artifactory CLI on Hosted Ubuntu Agents since new image Version

### ISSUE THREAD

**Issue by chrizzo1984** [actions/virtual-environments#279]
**Describe the bug**
Yesterday we had no issues with building Maven stuff - with image version 20191209.1; Today with image version 20200102.1 we have following error:

[Error] couldn't find plexus-classworlds-x.x.x.jar in Maven installation path, please check M2_HOME environment variable

First thougt it this Bug: https://github.com/jfrog/jfrog-cli/issues/511 => But was fixed last year by JFrog. 

==> Also tested on Windows Agents, there is no problem - Only Ubuntu (16.04 + 18.04)

**Question, Bug, or Feature?**: Bug

**Area for Triage:**
Ubuntu image

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
That it´s building like yesterday ;)

**Reproduction**
Just use Artifactory Maven step => Artifactory CLI = 1.31.2 x64, => Collect Build Info

**Tested Workaround**
- task: Bash@3
  displayName: 'Delete plexus-classworlds.license'
  inputs:
    targetType: 'inline'
    script: |
      cd $M2_HOME/boot
      ls -la
      rm ./plexus-classworlds.license
==> But is not really working, getting other errors!

**Comment by planetf1** [comment]
Thanks for the workaround! I used your script fragment and it worked for us - in a build pipeline & release. See https://github.com/odpi/egeria/issues/2442 . Much appreciated for sharing.

**Comment by thejoebourneidentity** [comment]
Thanks @chrizzo1984, @alepauly is going to investigate this as we think it may be related to #242

**Comment by alepauly** [comment]
yep. I believe this should be resolved now. @chrizzo1984, @planetf1 - please let us know if this is still broken for you. thank you!

**Comment by chrizzo1984** [comment]
@alepauly: are the new images deployed? Because error is almost there for me:

[Error] couldn't find plexus-classworlds-x.x.x.jar in Maven installation path, please check M2_HOME environment variable

**Comment by al-cheb** [comment]
Hello, @chrizzo1984 

Could you please provide steps to reproduce the issue?

**Comment by chrizzo1984** [comment]
Here is the pipeline (removed firm internal stuff)
```
trigger: 
- master

workspace:
  clean: all

pool: ''

variables:
  JAVA_HOME: /usr/lib/jvm/zulu-11-azure-amd64


steps:

#Prepare SQ Analysis
- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'Sonarqube SaaS'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: ''
    cliProjectName: ''
    extraProperties: |
      sonar.sourceEncoding=UTF-8
      sonar.sources=./src/main
      sonar.tests=./src/test
      sonar.java.binaries=./target/*
      sonar.java.libraries=/home/azure/.m2/repository/**/*.jar

#Get Artifactory CLI
- task: ArtifactoryToolsInstaller@1
  displayName: 'Artifactory Tools Installer'
  inputs:
    artifactoryService: 'Artifactory SaaS'
    cliInstallationRepo: 'jfrog-cli-go-generic-remote'
    installMavenExtractor: true
    mavenInstallationRepo: 'jcenter-maven-remote'

#Maven Artifactory - install
- task: ArtifactoryMaven@1 ======> Here the problem occurs.
  displayName: 'Artifactory Maven'
  enabled: true
  inputs:
    goals: install
    options: --batch-mode
    artifactoryResolverService: 'Artifactory SaaS'
    targetResolveReleaseRepo: ''
    targetResolveSnapshotRepo: ''
    artifactoryDeployService: 'Artifactory SaaS'
    targetDeployReleaseRepo: ''
    targetDeploySnapshotRepo: ''
    collectBuildInfo: true
    includeEnvVars: false

#Publish Build-Infos to Artifactory
- task: ArtifactoryPublishBuildInfo@1
  displayName: 'Artifactory Publish Build Info'
  enabled: true
  inputs:
    artifactoryService: 'Artifactory SaaS'

#SQ Code-Analyses
- task: SonarQubeAnalyze@4
  displayName: 'Run Code Analysis'
  enabled: true

#Publish Qualitygate Results of SQ
- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'

#Buildbreaker => Buildbreak if SQ Qualitygate fails
- task: sonar-buildbreaker@8
  enabled: false
  inputs:
    SonarQube: 'Sonarqube SaaS'
```
