### ISSUE TITLE
Port 8084 already in use on ubuntu-latest

### ISSUE THREAD

**Issue by Hugo1380** [actions/virtual-environments#2800]
**Description**  
Until today I had no issue on my tests steps using [Mocha](https://github.com/mochajs/mocha) (tests framework) on GitHub Actions using `ubuntu-latest`. But today Mocha doesn't run anymore because the port 8084 seem to be used but this is my port to test my API. I didn't do any modification on my tests suites or some networks things on my app and **my tests work fine locally**.

So is it maybe new that by default the port 8084 is use on this ubuntu image ?

**Area for Triage**:  
Testing and code coverage JavaScript and Node.js

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
The port 8084 doesn't have to be used.
**Actual behavior**  
The port 8084 is in use so my tests crashing.

**Repro steps**  
Here is my tests steps:

```
jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --global mocha
    - run: npm install
    - run: rm -rf node_modules; npm cache verify; npm install
    - run: mocha --timeout 10000
 ```

And here Mocha telling me that the port 8084 is used : 

```
   1) Uncaught error outside test suite:
     Uncaught Error: listen EADDRINUSE: address already in use :::8084
```
