### ISSUE TITLE
Ruby 2.6.3 not found - broken workflows without warning

### ISSUE THREAD

**Issue by philipengberg** [actions/virtual-environments#281]
Since last night, we're basically seeing [this](https://github.com/actions/runner/issues/283#issue-550349488) error output for all of our builds.

```
Run actions/setup-ruby@v1
##[error]Version 2.6.3 not found
##[error]Node run failed with exit code 1
```

**Comment by al-cheb** [comment]
Hello, @philipengberg 

Thank you for your time to report an issue.  We have updated all Ruby versions on Windows, Ubuntu, MacOs images in the toolcache from Ruby 2.6.3  to Ruby 2.6.5 version: `Ruby: 2.4.9, 2.5.7, 2.6.5, 2.7.0`

Documentation:
MacOS GitHub 10.15 Week 3 (https://github.com/actions/virtual-environments/pull/283)
Ubuntu 18.04 - https://github.com/actions/virtual-environments/blob/releases/ubuntu18/20200113/images/linux/Ubuntu1804-README.md
Ubuntu 16.04 - https://github.com/actions/virtual-environments/blob/releases/ubuntu16/20200113/images/linux/Ubuntu1604-README.md
Windows Server 2016 - https://github.com/actions/virtual-environments/blob/releases/win16/20200113/images/win/Windows2016-Readme.md
Windows Server 2019 - https://github.com/actions/virtual-environments/blob/releases/win19/20200113/images/win/Windows2019-Readme.md

Example output:
```
    steps:
    - name: Use Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Check Ruby version
      run: |
        ruby -v
```
![image](https://user-images.githubusercontent.com/47745270/72594720-30910f00-3919-11ea-9230-5d3f00372b17.png)
