### ISSUE TITLE
Cant' link to vcomp140.dll in Windows Server 2019 virtual environment

### ISSUE THREAD

**Issue by albarji** [actions/virtual-environments#2835]
**Description**  

I am using Github Actions to create a testing workflow, in which Python Anaconda and some python packages need to be installed on a Windows system. One of these packages (`py-xgboost`) requires in turn a shared library for running: `vcomp140.dll` or some alternative like `libgomp-1.dll`. As far as I can tell, this library is included in VS C++ Distributables, and can already be found inside the virtual environment as `C:\Windows\System32\vcomp140.dll`. However, upon running some tests I get a dynamic linking error.

**Area for Triage**:  
Python

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**
20210211.1

**Expected behavior**  
Python should be able to find  the `vcomp140.dll` library under the `C:\Windows\System32` folder without errors.

**Actual behavior**  
Python is unable to find `vcomp140.dll`  in the system, throwing the following error:

```
=================================== ERRORS ====================================
___________ ERROR collecting .github/workflows/test_environments.py ___________
.github\workflows\test_environments.py:12: in <module>
    from xgboost import XGBClassifier
C:\Miniconda\lib\site-packages\xgboost\__init__.py:11: in <module>
    from .core import DMatrix, Booster
C:\Miniconda\lib\site-packages\xgboost\core.py:161: in <module>
    _LIB = _load_lib()
C:\Miniconda\lib\site-packages\xgboost\core.py:152: in _load_lib
    'Error message(s): {}\n'.format(os_error_list))
E   xgboost.core.XGBoostError: XGBoost Library (xgboost.dll) could not be loaded.
E   Likely causes:
E     * OpenMP runtime is not installed (vcomp140.dll or libgomp-1.dll for Windows, libgomp.so for UNIX-like OSes)
E     * You are running 32-bit Python on a 64-bit OS
E   Error message(s): ['[WinError 127] The specified procedure could not be found']
============================== warnings summary ===============================
```

I am certain I'm using a 64-bit Python, and as far as I know the virtual environment also contains 64-bit OS, so among the likely causes the problem must lie in a failure to find `vcomp140.dll`..

**Repro steps**  

Here is the full YAML for the Github Action I'm creating. Although I run the tests under several OS, the only one with issues is Windows. The project can be found at https://github.com/albarji/teaching-environments-ensembles .

```yaml
name: Test the environment under different operative systems and python configurations.

on: [push]

jobs:
  test-environment:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6]

    name: ${{ matrix.os }} python ${{ matrix.python-version }} test
    steps:
    - uses: actions/checkout@v2
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Test with pytest
      run: |
        conda install pytest && conda info && conda env list && conda list && which python && which pytest && pytest tests.py
```
