### ISSUE TITLE
chocolatey fails with timeout installing any package on Windows

### ISSUE THREAD

**Issue by twpayne** [actions/virtual-environments#2876]
**Description**  

[GitHub Actions on Windows claims to include the Chocolatey package manager](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#package-management), but installing a simple package with

```yaml
name: main
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Install gpg4win
      run: choco install --trace --yes gpg4win
    - name: Check gpg4win installation
      run: gpg --version
```

Fails [with a timeout after 45 minutes](https://github.com/twpayne/github-actions-chocolatey-test/runs/2059905469?check_suite_focus=true).

**Area for Triage**:  

Packages

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**

20210219.1

**Expected behavior**  

gpg4win is installed in a timely fashion.

**Actual behavior**  

Installation fails to complete after a 45 minutes.

**Repro steps**  

https://github.com/twpayne/github-actions-chocolatey-test is a minimal reproduction, see https://github.com/twpayne/github-actions-chocolatey-test/actions for the latest run.

This was also [raised on `github.community`](https://github.community/t/installing-simple-package-with-chocolately-times-out/155265) a few months ago, without response.

Refs https://github.com/twpayne/chezmoi/pull/1057
