### ISSUE TITLE
Ubuntu latests uses already installed mysql instead the declared service

### ISSUE THREAD

**Issue by JuanCrg90** [actions/virtual-environments#2889]
**Description**  
Currently ubuntu-latest is pointing to ubuntu 20.04, after this change my CI system started to fail because the rails application tried to use the mysql 8.0 version installed by default in the ubuntu instead of the mysql:5.7 declared as a service.

- The documentation still show ubuntu-latest as the ubuntu 18.04 image.
- I found this error debugging my github action with the [tmate action](https://github.com/marketplace/actions/debugging-with-tmate)

**Area for Triage**:  Containers

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

**ubuntu-latest**

**Expected behavior**  
The container should take the `mysql:5.7` service declared in my workflow instead of the mysql 8.0 that is already installed in the container.

**Actual behavior**  
mysql 8.0 installed inside ubuntu 20.04 (latest) is take as the mysql service, despite I have a `mysql:5.7` declared in the workflow

```
      mysql:
        image: mysql:5.7.33
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
        - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10
```

**Repro steps**  
This is the workflow that I'm running (I've removed some unnecessary dependencies and folders from the matrix)

```
name: Main
on:
  pull_request:
    branches: [ daily, develop ]
  push:
    branches: [ daily, develop ]
jobs:
  test_runner:
    name: CI
    runs-on: ubuntu-latest
    # If you need DB like MySQL then define service below.
    # Example for PostgreSQL and Redis can be found here:
    # https://github.com/actions/example-services/tree/master/.github/workflows
    services:
      # How to use MySQL
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
        - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10
      # How to use Elasticsearch
      elasticsearch:
        image: elasticsearch:6.8.3
        ports:
        - 9200/tcp
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
# https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix
    strategy:
      fail-fast: false
      matrix:
        test_folder: [test/models]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Create DB
        env:
          RAILS_ENV: test
          DB_PASSWORD: root
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          sudo /etc/init.d/mysql start
          cp config/database.ci.yml config/database.yml
          bin/rails db:setup
      - name: Setup translations
        run: |
          bin/rails makemo > /dev/null 2>&1
      - name: Run tests
        env:
          DB_PASSWORD: root
          DB_PORT: ${{ job.services.mysql.ports[3306] }} # get randomly assigned published port
          ELASTICSEARCH_PORT: ${{ job.services.elasticsearch.ports[9200] }}
          RAILS_ENV: test
        run: |
          bin/rails test ${{matrix.test_folder}}
```

you can add 

```
- name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
```

and ensure if you run `RAILS_ENV=test bin/rails db` or `mysql --version` you get a mysql 8.0 versión instead the declared `mysql:5.7` service.

I've temporary fixed it updating `runs-on: ubuntu-latest` to `runs-on: ubuntu-18.04` but It would be nice to be able to use `ubuntu-latest` as usual.

**Comment by nikita-bykov** [comment]
Hello @JuanCrg90. Unfortunately we are unable to reproduce the issue with the repro steps in your workflow due to missing some of the configuration files mentioned there.
We have tested the mysql 5.7 service on the ubuntu-latest image using the workflow below:
```
name: Service_test
on:
  workflow_dispatch:

jobs:
  test_runner:
    name: CI
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
        - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: mysql version
        run: mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "SELECT @@VERSION"
``` 
We got the 5.7 version as expected (https://github.com/nikita-bykov/test-repo/actions/runs/657369769).
Most likely your workflow is configured to use mysql from the host instead of docker container. Ubuntu 18.04 has mysql 5.7 installed on host as you configured in the container, and this is probably why you've had successful builds before.
