### ISSUE TITLE
Github Actions fail to install some packages on Ubuntu 20.04

### ISSUE THREAD

**Issue by hndgzkn** [actions/virtual-environments#2902]
**Description**  
In Github actions I install `libopenmpi-dev` and `openmpi-bin` on ubuntu 20.04 using the command:

`sudo apt-get install -qy libopenmpi-dev openmpi-bin`

It used to run without problems until last week. It started failing recently. 

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210302.0

**Expected behavior**  
Installation of libopenmpi-dev and openmpi-bin and dependencies without problems.

**Actual behavior**  
It fails with the following error message:

```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/n/nvidia-settings/libxnvctrl0_440.82-0ubuntu0.20.04.1_amd64.deb  404  Not Found [IP: 52.154.174.208 80]
Fetched 6232 kB in 0s (33.3 MB/s)
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```

Actually when I check http://azure.archive.ubuntu.com/ubuntu/pool/main/n/nvidia-settings/ for `libxnvctrl0`, I see that `libxnvctrl0_440.82-0ubuntu0.18.04.1_amd64.deb` exists for 18.04. However for 20.04 the package name is `libxnvctrl0_460.39-0ubuntu0.20.04.1_amd64.deb`.

**Repro steps**  
Using ubuntu-20.04 image I run:

`sudo apt-get install -qy libopenmpi-dev openmpi-bin`

Running:

`sudo apt-get update & sudo apt-get install -qy libopenmpi-dev openmpi-bin` 

does not help either.

**Comment by al-cheb** [comment]
Hello, @hndgzkn 
I can't reproduce the issue on Version: 20210302.0.

```
jobs:
  demo:
        runs-on: ubuntu-20.04
        steps:
          - run: sudo apt update
          - run: apt-cache madison libopenmpi-dev openmpi-bin
          - run: sudo apt-get install -qy libopenmpi-dev openmpi-bin
```
![image](https://user-images.githubusercontent.com/47745270/110793439-aaa2f680-8285-11eb-8537-f8ed8b5d2503.png)
