### ISSUE TITLE
Add ansible-lint

### ISSUE THREAD

**Issue by nielsvbrecht** [actions/virtual-environments#291]
- Tool name: ansible-lint
- Add or update? Add
- Desired version: latest
- Approximate size:
- If this is an add request:
  - Brief description of tool: Ansible Lint is a commandline tool for linting playbooks. Use it to detect behaviors and practices that could potentially be improved.
  - URL for tool's homepage: https://docs.ansible.com/ansible-lint/

**Area for Triage**:

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [X] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, through 'pip install ansible-lint', will take approximately 15 to 60 seconds.
But doesn't work now on the Microsoft hosted build agents due to errors.
**Are you willing to submit a PR?**
Depends if I feel comfortable with adding code :)

**Comment by thejoebourneidentity** [comment]
What's the error you're running into? Can you share?

**Comment by nielsvbrecht** [comment]
Ansible-lint is not present on the hosted agents and I've tried with pip install and with the explicit python task to do pip install but did not succeed. But if you can help me out with that, that would be great. And if it can be added to the hosted agents by default would be even greater :)

**Comment by markdorison** [comment]
> I've tried with pip install and with the explicit python task to do pip install but did not succeed. But if you can help me out with that, that would be great.

I was able to install `ansible-lint` with the following steps:

```yaml
jobs:
  ansible-lint:
    runs-on: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.x

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install ansible-lint
        run: pip install ansible-lint
```

> And if it can be added to the hosted agents by default would be even greater :)

Agreed. ++
