### ISSUE TITLE
Ubuntu 16.04: apt fails when installing gcc-multilib

### ISSUE THREAD

**Issue by mole99** [actions/virtual-environments#2917]
**Description**  
When trying to install `gcc-multilib` apt fails with the following error:

> The following packages have unmet dependencies:
>  gcc-multilib : Depends: gcc-5-multilib (>= 5.3.1-3~) but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.
> Error: Process completed with exit code 100.

This seems to be a regression. 7 days ago I could succesfully install gcc-multilib and g++-multilib to compile a program for i386. Yesterday I ran the script again and got this error. 

**Area for Triage**:  
Packages

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
```
Virtual Environment
7  Environment: ubuntu-16.04
8  Version: 20210302.0
9  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu16/20210302.0/images/linux/Ubuntu1604-README.md
10  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu16%2F
```

**Expected behavior**  
apt should successfully install `gcc-multilib` 

**Actual behavior**  
apt exits with an error 

**Repro steps**  

A minimal example configuration to reproduce the issue:

```
name: Test
on: [push]

jobs:
  Install-gcc-multilib:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2

      - name: Install gcc-multilib
        run: |
          sudo apt update
          sudo apt install gcc-multilib -y
```
