### ISSUE TITLE
Value of environment variable XDG_CONFIG_HOME is always "/home/runner/.config"

### ISSUE THREAD

**Issue by shibataka000** [actions/virtual-environments#2954]
**Description**  
I set some value to environment variable `XDG_CONFIG_HOME` by `jobs.<job_id>.env.XDG_CONFIG_HOME` . But value of environment variable `XDG_CONFIG_HOME` is always `/home/runner/.config` .

**Area for Triage**:  

Servers

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

20210315.1

**Expected behavior**  
Value of environment variable `XDG_CONFIG_HOME` should be same as value of `jobs.<job_id>.env.XDG_CONFIG_HOME` .

**Actual behavior**  
Value of environment variable `XDG_CONFIG_HOME` is always `/home/runner/.config` .

**Repro steps**  
1. Set up workflows like follow.

```yaml
# .github/workflows/test.yaml
name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      XDG_CONFIG_HOME: /github/home/.config
    steps:
      - run: echo $XDG_CONFIG_HOME
```

2. See workflow output.

I created sample repository in https://github.com/shibataka000/github-actions-issue-2826 . You can see [workflow setting](https://github.com/shibataka000/github-actions-issue-2826/blob/main/.github/workflows/test.yaml) and [its result](https://github.com/shibataka000/github-actions-issue-2826/actions/runs/660438764).

**Comment by shibataka000** [comment]
I guess this issue might be related to #2826 .

**Comment by miketimofeev** [comment]
Hi @shibataka000!
Yes, you're right it's related. The variable didn't work at all before https://github.com/actions/virtual-environments/pull/2826
but now it looks like the variable from $BASH_ENV overrides the variable from the env block. Sorry for the inconvenience. Could you please try the following?
```
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "export XDG_CONFIG_HOME=/github/home/.config" | sudo tee -a $BASH_ENV
      - run: echo $XDG_CONFIG_HOME
```
