### ISSUE TITLE
Switch python version not working properly on Ubuntu

### ISSUE THREAD

**Issue by majorvin** [actions/virtual-environments#302]
**Describe the bug**
Using the task switch python version is not working. 

**Area for Triage**: 

**Question, Bug, or Feature?**: 
"Bug"

**Virtual environments affected**
- [ ] macOS 10.15
- [ x] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Actual behavior**
```

Version spec 3.7 for architecture x64 did not match any version in Agent.ToolsDirectory.
Versions in /var/lib/waagent/custom-script/download/1/agent/_work/_tool:
If this is a Microsoft-hosted agent, check that this image supports side-by-side versions of Python at https://aka.ms/hosted-agent-software.
If this is a self-hosted agent, see how to configure side-by-side Python versions at https://go.microsoft.com/fwlink/?linkid=871498.
```

should $AGENT_TOOLSDIRECTORY points to /opts/hostedtoolscache? If yes, then this is not the right behaviour because right now when running on the agent, its pointing to `tools/` and that folder is empty

**Comment by al-cheb** [comment]
Hello @majorvin 

Could you please provide steps to reproduce the issue? What kinds of agents do you use self-hosted or github-hosted?

**Comment by majorvin** [comment]
Hi @al-cheb nothing special. I just add the python switch task.

**Comment by al-cheb** [comment]
Hi @majorvin 

Couldn't reproduce
```
steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - run: |
        python -c "import sys; print(sys.version)"
```

![image](https://user-images.githubusercontent.com/47745270/72912374-97189180-3d4c-11ea-9c74-773dd1c4852d.png)

**Comment by majorvin** [comment]
hi @al-cheb can you run it on a freshly build agent?   also, it is ubuntu agent. 
What i noticed so far is i had to run it twice to get it to work on a freshly build agent.

**Comment by al-cheb** [comment]
@majorvin 

```
jobs:
  build:
    runs-on: [ubuntu-16.04]
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - run: |
        python -c "import sys; print(sys.platform,sys.version)"
```
![image](https://user-images.githubusercontent.com/47745270/72913512-4d30ab00-3d4e-11ea-9faf-897a3ebcc2b5.png)
