### ISSUE TITLE
mini-kube instable on macos

### ISSUE THREAD

**Issue by sebastian-toepfer** [actions/virtual-environments#3031]
**Description**  
We use mini-kube to setup our application to run test agains.
To setup mini-kube we use fork from `medyagh/setup-minikube` (fork only has macos support). This action works most time, sometimes the setup failed. After setup we must install/active a ingress. this setp timed out in 5 of 10 runs. Some days we have multiple runs without issues on other we have more runs that failed.

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
setup an ingress node failed every time or run every time stable.

**Actual behavior**  
setup of an ingress node failed randomly.
```
Verifying ingress addon...

X Exiting due to MK_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]
* 

* If the above advice does not help, please let us know: 
  - https://github.com/kubernetes/minikube/issues/new/choose
Error: Process completed with exit code 10.
```

**Repro steps**  
sample workflow
```
- name: start minikube
      id: minikube
      uses: sebastian-toepfer/setup-minikube@master
      with:
        minikube-version: 1.17.1

    - name: configure minikube
      run: |
        minikube addons enable ingress
        minikube update-context
        kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
```
