### ISSUE TITLE
Running yarn can uninstall Python in CI

### ISSUE THREAD

**Issue by blink1073** [actions/virtual-environments#307]
**Describe the bug**
Our application installs `puppeteer` inside the Python `/share` folder using `yarn`.
Since a few days ago, our CI builds that perform this install (both in Azure Workflows and Github Actions) started failing with the following output:

```
> chmod +x ./setup.sh && ./setup.sh

Check if Python hostedtoolcache folder exist...
Delete Python 3.7.* if installed
removed '/opt/hostedtoolcache/Python/3.7.6/x64/include/python3.7m/pystate.h'
removed '/opt/hostedtoolcache/Python/3.7.6/x64/include/python3.7m/pyconfig.h'
...
```

**Area for Triage**: 

Containers
JavaScript and Node.js
Python

**Question, Bug, or Feature?**: 

Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Change directories into a subdirectory of `/opt/hostedtoolcache/Python/3.7.6/x64` (e.g. ` /share`).
Install a node dependency using `yarn`.

**Actual behavior**
After the `yarn` (or `npm install`) command is run, the Python directory is removed.

Run the following workflow:

```
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '10.x'
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Run tests
      run: |
        cd $(dirname $(which python))
        mkdir temp
        cd temp
        yarn
```

Example: https://github.com/jupyterlab/extension-cookiecutter-ts/pull/53/checks?sha=0ec0ec9dfe3fcdd7d03336b8e69550beba9bcb96

I tried with both 16.04 and 18.04, and with both the system Node/Python and the `hostedtoolcache` versions.

It may be related to https://github.com/actions/virtual-environments/pull/216
