### ISSUE TITLE
Experimental Docker inside action

### ISSUE THREAD

**Issue by elgohr** [actions/virtual-environments#3090]
**Description**  
I'm trying to enable experimental Docker inside an action.
Generally https://github.com/actions/virtual-environments/issues/368 was a good hint.
Nevertheless it looks like that doesn't work when not using `run` directly.

Example:
```
on: [push]
jobs:
  build:
    runs-on: [ubuntu-16.04]
    steps:
      - name: Plain job
        run: |
          echo $'{"experimental": true}' | sudo dd status=none of=/etc/docker/daemon.json 
          sudo service docker restart
          docker version -f '{{.Server.Experimental}}' 
      - name: In with
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: lgohr/test-push
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          platforms: linux/amd64,linux/arm64
```

As shown in https://github.com/elgohr/actions-test/runs/2264996919?check_suite_focus=true , the `Plain job` executes fine; where `In with` is not able to find `/etc/docker/daemon.json`.
Even when using the exact same lines of code (see https://github.com/elgohr/Publish-Docker-Github-Action/blob/master/entrypoint.sh#L91 for the actions implementation).
My guess is, that it can't find the file, because it's executed in the given Docker container.
Nevertheless this would limit the use of experimental Docker to non-Docker actions.

**Question, Bug, or Feature?**:  
Question/Bug

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
Have a way to use experimental Docker inside a reusable action.

**Actual behavior**  
Fails when trying to adapt workaround for using experimental Docker features.
