### ISSUE TITLE
Mono 6 not available on macOS 10.14

### ISSUE THREAD

**Issue by kaylangan** [actions/virtual-environments#31]
**Describe the bug**
From reading this post, one could assume that both `macOS-14.04` and `macOS-latest` virtual environments have been updated to Mono 6.0 (among other things): https://github.blog/changelog/2019-10-04-github-actions-macos-virtual-environment-updates/

This doesn't seem to be the case, as both of these virtual environments are still on Mono 5.x (not to mention older versions of Xamarin, msbuild etc.).
I'm assuming this is either a bug, or a really slow rollout, but in either case I'd appreciate it if you could let me know if/when this will be fixed, as I desperately need an up-to-date environments, so my builds don't break. :)

**Virtual environments affected**
- [x] macOS 10.14
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Virtual environment has Mono 6.

**Actual behavior**
Has Mono 5

**Comment by Dids** [comment]
Repro action:

```yml
name: Build

on: [push]

jobs:
  build:

    runs-on: macOS-10.14
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install dependencies
      run: nuget restore || true
    - name: Build solution
      run: msbuild
```

In my case, I'm trying to build Xamarin/.NET Standard projects and libraries, and thanks to a dependency (Fody) I discovered that it is using msbuild 15/mono 5, instead of the newer versions that _should've_ been included with the environment update.
