### ISSUE TITLE
Update/Add App Center CLI

### ISSUE THREAD

**Issue by mhd-babikir** [actions/virtual-environments#3119]
**Tool information**
- Tool name: App Center CLI
- Add or update? Add
- Desired version: Any version will do 
- Approximate size: 
- If this is an add request:
  - Brief description of tool: App Center CLI 
  - URL for tool's homepage: https://docs.microsoft.com/en-us/appcenter/cli/
  - Provide a basic test case to validate the tool's functionality: run this on terminal "appcenter -v"

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04

**Can this tool be installed during the build?**

**Tool installation time in runtime**

**Are you willing to submit a PR?**

**Comment by al-cheb** [comment]
Hello, @mhd-babikir 
Unfortunately, we wouldn't like to bake `App Center CLI` into the images. Please consider installation in runtime like:

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: appcenter-cli
        run: sudo npm install -g appcenter-cli
      - name: get version
        run: appcenter -v
```

![image](https://user-images.githubusercontent.com/47745270/113750230-325c1380-9713-11eb-908e-77c82847a833.png)
