### ISSUE TITLE
Bundler and RubyGem versions incorrect

### ISSUE THREAD

**Issue by IkeLutra** [actions/virtual-environments#3237]
**Description**  
The bundler and RubyGems versions in the Mac OS 10.15 image (20210419.2) aren't as documented in the [readme](https://github.com/actions/virtual-environments/blob/macOS-10.15/20210419.2/images/macos/macos-10.15-Readme.md)

**Area for Triage**:  

Ruby

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

20210419.2

**Expected behavior**  

Bundler version should be 2.2.16
RubyGems should be 3.2.16

**Actual behavior**  

Bundler version is 2.1.4
RubyGems version is 3.1.6

**Repro steps**  

Below is a minimum YAML to reproduce this issue:
```yaml
name: $(Build.SourceVersion)
trigger: none
jobs:
  - job: experiment
    timeoutInMinutes: 120
    pool:
      vmImage: macOS-10.15
    steps:
      - task: UseRubyVersion@0
        inputs:
          versionSpec: "2.7.3"
          displayName: "Use Ruby version"
      - bash: bundle env
```

Here is a trimmed output of `bundle env` which shows the versions of Bundler and RubyGems:
```
Bundler       2.1.4
  Platforms   ruby, x86_64-darwin-19
Ruby          2.7.3p183 (2021-04-05 revision 6847ee089d7655b2a0eea4fee3133aeacd4cc7cc) [x86_64-darwin19]
  Full Path   /Users/runner/hostedtoolcache/Ruby/2.7.3/x64/bin/ruby
  Config Dir  /Users/runner/hostedtoolcache/Ruby/2.7.3/x64/etc
RubyGems      3.1.6
  Gem Home    /Users/runner/hostedtoolcache/Ruby/2.7.3/x64/lib/ruby/gems/2.7.0
  Gem Path    /Users/runner/.gem/ruby/2.7.0:/Users/runner/hostedtoolcache/Ruby/2.7.3/x64/lib/ruby/gems/2.7.0
  User Home   /Users/runner
  User Path   /Users/runner/.gem/ruby/2.7.0
  Bin Dir     /Users/runner/hostedtoolcache/Ruby/2.7.3/x64/bin
Tools         
  Git         2.31.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```
