### ISSUE TITLE
An error occurred while provisioning resources (Error Type: Failure).

### ISSUE THREAD

**Issue by uchar** [actions/virtual-environments#3250]
**Description**  
In my private repo macOS action fails with this error (It doesn't event start) :

`An error occurred while provisioning resources (Error Type: Failure).
`

![image](https://user-images.githubusercontent.com/5172296/115905554-80934580-a47b-11eb-9375-4879768eb661.png)

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

It doesn't even run, there is no Setup job, so I don't know but the build script contains this : 

```
  ReleaseToAppStore:
    name: Release to the App Store
    runs-on: macos-latest
    needs: buildForiOsPlatform
.....
```
