### ISSUE TITLE
vs2017-win2016 no longer using Chrome v77 ?

### ISSUE THREAD

**Issue by AutomationSifu** [actions/virtual-environments#328]
**Describe the bug**
When running Selenium tests against vm vs2017-win2016 I receive an error:  session not created:  This version of ChromeDriver only supports Chrome version 77.  When looking at the list of installed software for that vm, Chrome version 77 is listed as the installed version.

**Area for Triage**: 

**Question, Bug, or Feature?**: 

Question

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
A description of what you expected to happen.

The expectation was that Chrome 77 was still valid for vs2017-win2016

**Actual behavior**
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Run tests with Azure DevOps using ChromeDriver version 77

**Comment by miketimofeev** [comment]
@AutomationSifu thanks for reporting this. It seems that docs are slightly outdated at the moment because we install the latest chrome and chrome driver during every image generation and there should be a version 79. You can check installed chrome version by running the job like this
```
jobs:
  build:
    runs-on: vs2017-win2016
    steps:
    - name: Check Chrome Version
      run: |
        $fileVersion = (Get-Item (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe').'(Default)').VersionInfo.FileVersion
        Write-Host "Chrome version is $fileversion"
      shell: pwsh
```
