### ISSUE TITLE
[windows] Rust Bindgen does not work because libclang.dll could not be loaded

### ISSUE THREAD

**Issue by wrenger** [actions/virtual-environments#3316]
**Description**  
Rusts bindgen build tool panics because libclang.dll cannot be opened.

**Area for Triage**:  

Rust

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Image version**
20210425.1

**Expected behavior**  
It should be possible to use bindgen as (build) depenency to generate rust bindings for C APIs, similar to the linux and mac environments.

**Actual behavior**  
Bindgen crashes because it cannot open libclang.dll:

```
thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at C:\\msys64\\mingw64\\bin\\libclang.dll could not be opened: LoadLibraryExW failed"', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.58.1\src/lib.rs:2057:31
```

**Repro steps**  

1. Create a Rust Project which uses bindgen during build.
2. Create a Build Action
3. Execute the Build Action

Example Project, that uses bindgen:
https://github.com/wrenger/rust-ffi-test

Here the associated Action: https://github.com/wrenger/rust-ffi-test/actions/runs/812930118

**Comment by miketimofeev** [comment]
Hi @wrenger!
Thank you for providing repro steps, we will take a look.

**Comment by Darleev** [comment]
Hello @wrenger,
I found the issue in [the rust repository](https://github.com/rust-lang/rust-bindgen/issues/1797) with exactly the same description. The following approach was used in order to mitigate the issue:


```
name: Rust

on:
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - name: Install LLVM and Clang # required for bindgen to work, see https://github.com/rust-lang/rust-bindgen/issues/1797
      uses: KyleMayes/install-llvm-action@32c4866ebb71e0949e8833eb49beeebed48532bd
      if: matrix.os == 'windows-latest'
      with:
        version: "11.0"
        directory: ${{ runner.temp }}/llvm
    - name: Set LIBCLANG_PATH
      run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
      if: matrix.os == 'windows-latest'
    - uses: actions/checkout@v2
    - name: Run
      run: cargo run --verbose
      shell: cmd
```

I've verified that it works fine for your test repo as well. Could you please check for your main project and provide feedback?
We are looking forward to your reply.
