### ISSUE TITLE
GitHub Action steps stopped working starting 2021-05-04

### ISSUE THREAD

**Issue by ldttmt** [actions/virtual-environments#3327]
**Description**  
We have a setup script in GitHub Action for our integration tests to install the [KITE](https://github.com/webrtc/KITE/blob/master/configureLinux.sh#L51) library. It has been working fine until today morning (May 4th 2021).
```
./configureLinux.sh: line 45: x-terminal-emulator: command not found
```
We have been using Ubuntu-latest but switching to Ubuntu-18 did not resolve the issue either.
Not sure if this is related to #3325

**Area for Triage**:  

Deployment/Release, Scripting and command line
**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
ubuntu-latest
ubuntu-18.04

**Expected behavior**  
Setup script runs sucessfully

**Actual behavior**  
Setup script failed

**Repro steps**  
Setup a job like this and observe the error message in the last step Install Kite
```
  jobs:
    integ-meeting-end:
      name: Integration Test
      runs-on: ubuntu-latest

      steps:
        - name: Create a Job ID
          id: create-job-id
          uses: filipstefansson/uuid-action@ce29ebbb0981ac2448c2e406e848bfaa30ddf04c
        - name: Setup Node.js - 14.x
          uses: actions/setup-node@v1
          with:
            node-version: 14.x
        - name: Install Kite
          run: script/install-kite
```
install-kite script
```
#!/bin/bash
set -o xtrace

cd ~/build

mkdir GitHub
cd GitHub
git clone https://github.com/webrtc/KITE.git
cd KITE

chmod -R +x scripts/linux

chmod +x configureLinux.sh
yes n | ./configureLinux.sh

cd KITE-AppRTC-Test
../scripts/linux/path/c all > /dev/null
```
