### ISSUE TITLE
[macos-latest]Image does not contains fastlane

### ISSUE THREAD

**Issue by roncsak** [actions/virtual-environments#3337]
**Description**  
Hello,  
I'm using macos-latest (10.15.7) in a GitHub Action and I would like to use fastlane as an included software described in [macos-10.15-Readme.md](https://github.com/actions/virtual-environments/blob/macOS-10.15/20210503.2/images/macos/macos-10.15-Readme.md).  
As it is written in the documentation, fastlane is included in the macos image so I would like to use it by calling `fastlane` or by calling `bundle exec fastlane`.

**Area for Triage**:  
contains: 'Apple'
contains: 'Containers'
contains: 'Scripting and command line'

**Bug**:  

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210503.2

**Expected behavior**  
I expect that fastlane is really available in the system and I can use it.

**Actual behavior**  
In `Step1` the following error happens:  
```
Run fastlane create_keychain name:name_of_keychain password:chosen_password
/Users/runner/work/_temp/41526cfc-b927-4b40-954c-2e8c9acc1da2.sh: line 1: fastlane: command not found
Error: Process completed with exit code 127.
```

In `Step2` the following error happens:  
```
Run bundle exec fastlane create_keychain name:name_of_keychain password:chosen_password
bundler: command not found: fastlane
Install missing gem executables with `bundle install`
Error: Process completed with exit code 127.
```

As it seems fastlane is not found in the system.

**Repro steps**  
My action file:
```
on: [workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Step1 Setup keychain
        continue-on-error: true
        run: fastlane create_keychain name:name_of_keychain password:chosen_password

      - name: Step2 Setup keychain with bundle
        run: bundle exec fastlane create_keychain name:name_of_keychain password:chosen_password
```
