### ISSUE TITLE
Add NVM-windows which will allow users to choose between npm 6 or 7

### ISSUE THREAD

**Issue by helen3141** [actions/virtual-environments#3429]
**Tool information**
- Tool name: nvm-windows
- Tool license: 
- Add or update? add
- Desired version: 1.17 (the latest maintenance release)
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Node Version Manager (nvm) for Windows written in Go
  - URL for tool's homepage: https://github.com/coreybutler/nvm-windows
  - Provide a basic test case to validate the tool's functionality: Type nvm in the console window. It should show the help menu
 
**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
1. Remove the node installation script
2. Add a new script to install nvm for windows
3. In the script programmatically follow the steps in the manual install guidehttps://github.com/coreybutler/nvm-windows/wiki#manual-installation
4. Restart the computer
5. Use nvm to install node lts (which includes npm 6) and also node latest (which includes npm 7)
6. Use nvm to select node lts as its default (users can specify to use the other version of node by the nvm command in their pipeline)

**Tool installation time in runtime**
Should not be long

**Are you willing to submit a PR?**
Yes

**Comment by Darleev** [comment]
Hello @helen3141,
We already have such functionality on our images, just need to use github actions `setup-node` task. More information about it you can find [by the link](https://github.com/actions/setup-node).

Example for `windows-latest`:
```
jobs:
  build:
    runs-on: windows-latest
    name: Node sample
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          architecture: 'x64' # optional, x64 or x86. If not specified, x64 will be used by default
      - run: npm install
      - run: npm test
```
In order to install a particular node version and add it to the PATH  in Azure DevOps, you can [follow this link](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops).

In case of any questions, feel free to contact us.
