### ISSUE TITLE
Add VSWhere to Windows-latest

### ISSUE THREAD

**Issue by timheuer** [actions/virtual-environments#346]
**Tool information**
- Tool name: VSWhere (Visual Studio Install locator)
- Add or update? Add
- Desired version: latest
- Approximate size: 25kb
- If this is an add request:
  - Brief description of tool: Tool that helps locate versions of Visual Studio installations
  - URL for tool's homepage: https://github.com/microsoft/vswhere

**Area for Triage**: .NET Framework

**Question, Bug, or Feature?**: Feature
This tool is needed for .NET Framework workflows to more easily located MSBuild versions depending on different versions of VS that may exist in the runner.  It rapidly helps establish better workflows for these customers.

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Are you willing to submit a PR?**
Submitting!

**Comment by al-cheb** [comment]
Hello, @timheuer 

VSWhere tool is already pre-installed on the windows latest image:
```
jobs:
  build:
    runs-on: [windows-latest]
    steps:
    - name: VSWhere
      run: |
        & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
```

![vs](https://user-images.githubusercontent.com/47745270/73630525-63e8d300-4667-11ea-8500-33c0406da649.JPG)
