### ISSUE TITLE
The ps commands fails in workflows running on macos-latest

### ISSUE THREAD

**Issue by rlepigre** [actions/virtual-environments#3462]
**Description**  
Running the `ps` command (without any argument) in a `macos-latest` virtual environment fails after only printing the header line of its output. On the other hand, running `ps $$` succeeds as expected.

In an `ubuntu-latest` environment both commands succeed as expected.

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

Possibly macOS 11 as well, but I could not test for some reason.

**Image version**
20210525.2

**Repro steps**  

To reproduce the following trivial workflow can be used:
```yaml
name: Debugging workflow
on: [push]
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Testing the ps command (with $$)
        run: ps $$
      - name: Testing the ps command (no argument)
        run: ps
```

A failing run with this workflow can be found [here](https://github.com/rlepigre/GameShell/runs/2680376882?check_suite_focus=true).
