### ISSUE TITLE
Ability to shutdown/disable system services on an image 

### ISSUE THREAD

**Issue by n1hility** [actions/virtual-environments#348]
The Ubuntu images start mysql by default, which interferes with the ability to follow the service pattern with mysql (like all other databases). Steps can't be used to shutdown the service because the services block is ran earlier.

Alternatively a setup-script option would suffice.

For example, the following currently fails because of the port conflict with the pre-running service:
```yaml
services:
    mysql:
        image: mysql:8
        env:
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pass
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
```

Ideally you would be able to do something liike

```yaml
runs-on: ubuntu-latest
without-service: mysql
```
or Alternatively

```yaml
runs-on: ubuntu-latest
setup-step:
    shell: bash
    run: |
      sudo service mysql stop || true
```
