### ISSUE TITLE
Accessing LocalDb shows System.InvalidOperationException: Timeout expired.  

### ISSUE THREAD

**Issue by imranbaloch** [actions/virtual-environments#3529]
**Description**  
I have the following yml,

```yml
name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
```

My project depends upon LocalDB. When the Github Action runs, its failes with the below error,

```
The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
```

**Area for Triage**:  
.NET Core

**Question, Bug, or Feature?**:  
Question

**Virtual environments affected**  
- [x ] Ubuntu 16.04

- [x ] Windows Server 2019

**Image version**
Latest

**Expected behavior**  
The build should be passed.

**Actual behavior**  
The build failed with error,
```
Application startup exception: System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
```

On ubuntu, it says PlatformNotSupportedException 

**Repro steps**  
Copy paste the above yml and run any dotnet project with LocalDB.
