### ISSUE TITLE
Usage of latest Git PPA breaks git-svn installation

### ISSUE THREAD

**Issue by HeroCC** [actions/virtual-environments#3586]
**Description**  
Unable to install `git-svn` on `ubuntu-20.04` or `ubuntu-18.04`. This broke a while ago and has impacted a job of mine, but I haven't been able to debug it until now. I use a cron workflow to mirror an SVN repo into a public git one while my org works to transition fully.

**Area for Triage**:  

Area: Git
Area: Packages

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04 (untested)
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15 (untested)
- [ ] macOS 11 (untested)
- [ ] Windows Server 2016 R2 (untested)
- [ ] Windows Server 2019 (untested)

**Image version**

Just tested on 20210606.1

Last worked with 20210405.1

Broke on 20210412.1, when the git ppa was introduced.

**Expected behavior**  
`apt-get update && apt-get install -y git-svn` should return a success, and `git svn` would be available.

**Actual behavior**  
```
The following packages have unmet dependencies:
 git-svn : Depends: git (< 1:2.17.1-.) but 1:2.31.1-0ppa1~ubuntu18.04.1 is to be installed
```

**Repro steps**  
```yaml
jobs:
  svn-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Install git-svn
        run: |
          sudo apt-get update
          sudo apt-get install -y git-svn
          git svn --version
```
