### ISSUE TITLE
`metacity` install fails on Ubuntu-20.04

### ISSUE THREAD

**Issue by sdruskat** [actions/virtual-environments#3661]
**Description**  
```yaml
jobs:
  test_jdk11:
    name: OpenJDK 11 + SonarCloud code analysis
    runs-on: ubuntu-20.04
    steps:
      - name: Install metacity window manager for background tests
        run: sudo apt-get install metacity
```

fails with

```bash
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/p/pulseaudio/libpulse0_13.99.1-1ubuntu3.10_amd64.deb  404  Not Found [IP: 52.250.76.244 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Fetched 28.7 MB in 1s (53.2 MB/s)
Error: Process completed with exit code 100.
```

**Area for Triage**:  

Packages? (Sorry, I'm not sure what the "Area for Triage" is.)

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

Image version where you are experiencing the issue.

- `20210606.1`

**Expected behavior**  

`metacity` installs without issues.

**Actual behavior**  

Installation  of `metacity` fails as a dependency cannot be found: `http://azure.archive.ubuntu.com/ubuntu/pool/main/p/pulseaudio/libpulse0_13.99.1-1ubuntu3.10_amd64.deb`

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. See https://github.com/hexatomic/hexatomic/runs/2819373126?check_suite_focus=true
