### ISSUE TITLE
Jobs that run privileged containers started failing

### ISSUE THREAD

**Issue by orlangure** [actions/virtual-environments#3673]
### Description

In [gnomock](https://github.com/orlangure/gnomock) there is an automated test that runs lightweight kubernetes distribution (k3s) inside a docker container. This test passed successfully [5 days ago](https://github.com/orlangure/gnomock/runs/2916092414?check_suite_focus=true), and [started to fail consistently](https://github.com/orlangure/gnomock/runs/2951632183?check_suite_focus=true) after the latest github environments upgrade.

The error that occurs inside the container is 
```
151 conntrack.go:103] Set sysctl 'net/netfilter/nf_conntrack_max' to 131072
2021-06-30T11:22:53.9605151Z F0630 11:22:53.387138     151 server.go:495] open /proc/sys/net/netfilter/nf_conntrack_max: permission denied
```
but I'm not sure this is the root cause.

I have the same test running on circleci, and it [continues to pass](https://app.circleci.com/pipelines/github/orlangure/gnomock/335/workflows/0b82c5e0-b647-45a3-94e6-33bd0a6e2449/jobs/4605/parallel-runs/0/steps/0-104).

I have a few other jobs that set up docker containers, and they still work. The difference is that `k3s` job starts a privileged container.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

```
   Environment: ubuntu-20.04
  Version: 20210628.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210628.1/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210628.1

```

Failed build: https://github.com/orlangure/gnomock/runs/2951632183?check_suite_focus=true
Successful build (5 days ago): https://github.com/orlangure/gnomock/runs/2916092414?check_suite_focus=true

### Is it regression?

20210614.1

### Repro steps

Run ` [preset] k3s ` job from [Gnomock](https://github.com/orlangure/gnomock) repository.

**Comment by dibir-magomedsaygitov** [comment]
Hello @orlangure. Thank you for your report. We will take a look.

**Comment by lukaszo** [comment]
We have the same error when using kind.

**Comment by al-cheb** [comment]
Looks like the issue is not with image - https://github.com/rancher/rancher/issues/33300 . Manually set up `nf_conntrack_max=131072` do the trick:

```
    steps:
        - uses: actions/checkout@v2
          with:
            repository: 'orlangure/gnomock'
        - run: sudo sysctl -w net/netfilter/nf_conntrack_max=131072
        - name: Set up Go 1.16
          uses: actions/setup-go@v1
          with:
            go-version: 1.16
        - name: Get dependencies
          run: go get -v -t -d ./...
        - name: Test preset
          run: go test -race -cover -coverprofile=preset-cover.txt -coverpkg=./... -v ./preset/k3s/...
        - name: Test server
          run: go test -race -cover -coverprofile=server-cover.txt -coverpkg=./... -v ./internal/gnomockd -run TestK3s
```

![image](https://user-images.githubusercontent.com/47745270/123968516-f5c15080-d9bf-11eb-9115-d04ab634282e.png)
