### ISSUE TITLE
Xcode iOS unit testing error: The request was denied by service delegate

### ISSUE THREAD

**Issue by simondelphia** [actions/virtual-environments#3678]
### Description

After upgrade our Github Actions workflows to use macOS 11 I have seen our unit tests fail with this error:

> error = Error Domain=FBSOpenApplicationServiceErrorDomain Code=1 "The request to open "com.myapp.name" failed." UserInfo={BSErrorCodeDescription=RequestDenied, NSLocalizedDescription=The request to open "com.myapp.name" failed., NSUnderlyingError=0x7fea39024630 {Error Domain=FBProcessExit Code=64 "The process failed to launch." UserInfo={NSUnderlyingError=0x7fea39054c80 {Error Domain=RBSRequestErrorDomain Code=4 "Launch prevented due to "prevent launch" assertion" UserInfo={NSLocalizedFailureReason=Launch prevented due to "prevent launch" assertion}}, BSErrorCodeDescription=launch-failed, NSLocalizedFailureReason=The process failed to launch.}}, FBSOpenApplicationRequestID=0xacc, NSLocalizedFailureReason=The request was denied by service delegate (SBMainWorkspace).})

Not sure what to do about it. Wasting a lot of time on our workflows.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

Not sure where "Set up job" is

### Repro steps

1. Run Xcode unit tests on Github Actions with our repo
2. Sometimes it fails

**Comment by dibir-magomedsaygitov** [comment]
Hello @simondelphia. Thank you for your report. Could you please share the link to your repo to help us to investigate the issue.

**Comment by simondelphia** [comment]
Thank you for your reply. The repository is private.

**Comment by dibir-magomedsaygitov** [comment]
> Thank you for your reply. The repository is private. I am not allowed to make it public. Is there a way forward without that?

Could you please create public repo with minimal reprosteps?

**Comment by simondelphia** [comment]
I could try but since I don't know what's causing it I suspect it will be hard to do.

**Comment by miketimofeev** [comment]
@simondelphia thanks, we're waiting for the repro. A couple of questions:
- Have you tried different Xcode versions? Are all of them have the issue?
- Is it possible to make screenshots during the tests? I wonder if there is some permission access notification on the desktop.

**Comment by simondelphia** [comment]
Well I don't recall this particular error happening prior to using Xcode 11.

How would I take screenshots?

**Comment by miketimofeev** [comment]
@simondelphia well, maybe it's better to try video recording instead since `screencapture` will take the screenshot only after the failure occurred. The recording is not that easy, but something like this using `ffmpeg` and node should work:
```
- name: run integration tests
      timeout-minutes: 30
      run: |
          brew install ffmpeg
          tccutil reset ScreenCapture com.apple.Terminal
          node -e "const exec = require('child_process'); exec.exec('ffmpeg -f avfoundation -i 0 -t 420 out.mov'); exec.exec('xcodebuild clean -scheme \"AccessibilityElementAdaptor UI Tests\" -configuration \"UI Testing\" test');"
    - name: upload screenshot
      if: ${{ always() }}
      uses: actions/upload-artifact@master
      with:
        name: out
        path: out.mov
```
Have you tried to select different Xcode versions?
`sudo xcode-select -s "/Applications/Xcode_<version>.app"`
for example
`sudo xcode-select -s "/Applications/Xcode_12.4.app"` or `sudo xcode-select -s "/Applications/Xcode_11.7.app"` (Both version are available on macOS-11 image)

**Comment by simondelphia** [comment]
We can't really downgrade our workflows back to Xcode 12.4 because the tests wouldn't compile without changes.

Will look into the recording, thanks for the suggestion. That could be pretty helpful for some other problems we've been having too.

**Comment by Brett-Best** [comment]
Might be related to this issue https://developer.apple.com/forums/thread/679098

**Comment by nikita-bykov** [comment]
Hello @simondelphia! Were you able to record a video, was it helpful? If the issue persists, could you please provide us with a public simple repository where the issue can be reproduced for further investigation?

**Comment by simondelphia** [comment]
No, I couldn't get that command to work. Wasn't sure how it fit in. I've been trying to reproduce it on a self-hosted runner instead.

**Comment by simondelphia** [comment]
Haven't been able to reproduce it on my self-hosted runner yet… 

I  couldn't get the syntax right, could you explain this line further?

> node -e "const exec = require('child_process'); exec.exec('ffmpeg -f avfoundation -i 0 -t 420 out.mov'); exec.exec('xcodebuild clean -scheme \"AccessibilityElementAdaptor UI Tests\" -configuration \"UI Testing\" test');"

Would the call to run the tests go after this?

e.g.,

    bundle exec fastlane integration_test

**Comment by simondelphia** [comment]
I thought about using `xcrun` but how would you stop the recording when the tests finish?

**Comment by simondelphia** [comment]
Getting an "Invalid workflow file: You have an error in your yaml syntax" error.

**Comment by simondelphia** [comment]
Seems to get stuck after the `tccutil` line.

**Comment by nikita-bykov** [comment]
@simondelphia, some time ago we got an [issue ](https://github.com/actions/virtual-environments/issues/3395)related to Xcode tests and it reproduces only when flag `Application is agent (UIElement)` is enabled in the `Info.plist`. Could you please check if this flag is enabled and if so then disable it and run your tests.
In the `Info.plist`, this flag is specified as follows:
```
<key>LSUIElement</key>
<true/>
```

**Comment by dmitry-shibanov** [comment]
Hello @simondelphia. Thank you for your response. I think you can run it without tccutil. The first `exec.exec` starts video recording, the second command should start your ui tests.
You should enter approximate time for video recording to record the case when your UI tests fail.
```
    - name: run ui test and video recording
      run: |
          brew install ffmpeg
          node -e "const exec = require('child_process'); exec.exec('ffmpeg -f avfoundation -i 0 -t 420 out.mov'); exec.exec('command to run tests');"
    - name: upload video
      uses: actions/upload-artifact@master
      with:
        name: out
        path: out.mov
```
 - 420 - is time for recording in seconds.

**Comment by simondelphia** [comment]
> @simondelphia, some time ago we got an [issue ](https://github.com/actions/virtual-environments/issues/3395)related to Xcode tests and it reproduces only when flag `Application is agent (UIElement)` is enabled in the `Info.plist`. Could you please check if this flag is enabled and if so then disable it and run your tests.
> In the `Info.plist`, this flag is specified as follows:
> 
> ```
> <key>LSUIElement</key>
> <true/>
> ```

I don't see this key in any of the Info.plist files in my project.

**Comment by dmitry-shibanov** [comment]
Hello @simondelphia. Were you able to record a video? Besides, could you please share which IOS simulators do you use (iPhone XS, iPhone 11 or default one) ?

**Comment by simondelphia** [comment]
No I haven't gotten it working. 

iPhone 12 simulator.

**Comment by dmitry-shibanov** [comment]
Hello @simondelphia. Thank you for your response. Could you please share more details about video recording issue or if it's possible provide us with a public sample repository where the issue can be reproduced.
Besides, could you please try another simulator ?

**Comment by simondelphia** [comment]
I got this error when I tried it:

> No files were found with the provided path: out.mov. No artifacts will be uploaded.

```
      - name: run integration tests
        run: |
              brew install ffmpeg
              tccutil reset ScreenCapture com.apple.Terminal
              node -e "const exec = require('child_process'); exec.exec('ffmpeg -f avfoundation -i 0 -t 420 out.mov'); exec.exec('bundle exec fastlane integration_test');"
      - name: upload screenshot
        if: ${{ always() }}
        uses: actions/upload-artifact@master
        with:
           name: out
           path: out.mov
```
