### ISSUE TITLE
cannot push to another repo

### ISSUE THREAD

**Issue by mgood7123** [actions/virtual-environments#3681]
### Description

i cannot push to another repository in github even when i am using a encrypted secret PAT with all scopes granted

i keep getting

```
[master (root-commit) d34fe09] first commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 DO_NOT_DELETE_ME.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_RESET_POINT On branch main
nothing to commit, working tree clean
origin	***github.com/mgood7123/prebuilder-ubuntu-latest.git (fetch)
origin	***github.com/mgood7123/prebuilder-ubuntu-latest.git (push)
* remote origin
  Fetch URL: ***github.com/mgood7123/prebuilder-ubuntu-latest.git
  Push  URL: ***github.com/mgood7123/prebuilder-ubuntu-latest.git
  HEAD branch: (unknown)
remote: Invalid username or password.
```

with

```shell
rm -rf .git; \
git init; \
touch DO_NOT_DELETE_ME.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_RESET_POINT; \
git add DO_NOT_DELETE_ME.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_RESET_POINT; \
git commit -m "first commit"; \
git branch -M main; \
git remote add origin https://${{env.REPO_ACCESS_TOKEN}}:x-oauth-basic@github.com/${{github.repository}}-${{matrix.os}}.git; \
git status; \
git remote -v; \
git remote show origin; \
git push --set-upstream origin main; \
```

i have tried credential helper but i get same result

please note that this WORKS if i manually ssh into the build via tmate action, and then invoke the commands stated above

the repo i am pushing to is `https://github.com/mgood7123/prebuilder-ubuntu-latest`

the repository i am pushing from is `https://github.com/mgood7123/prebuilder`

the PAT i am using has all scopes granted to it and is stored in a repository secret in my `https://github.com/mgood7123/prebuilder` repository

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019

### Image version and build link

  Environment: ubuntu-20.04
  Version: 20210628.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210628.1/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210628.1

https://github.com/mgood7123/prebuilder/runs/2967752965

copy of yaml:
```yaml
name: CMake

on:
  push:
    branches: [ main ]

concurrency:
  group: build
  cancel-in-progress: true

env:
  # Put your secret here
  # to create a secret, go to
  
  # User Profile -> Settings ->
  # Developer Settings (at the bottom of page) -> Persional Access Tokens
  
  # then generate a new token and give it [public_repo] scope and then
  # click [Generate token]
  # finally copy its token id
  
  # next, go to your repository containing this workflow
  # Settings -> Secrets -> New repository secret
    
  # in the [Value] field, past the token id that you copied earlier
  
  # in the [Name] field, enter a name, replacing spaces with underscore (_)
  # for example, we will name it REPO_ACCESS_TOKEN
  
  # and then enter it here as ${{secrets.REPO_ACCESS_TOKEN}}
  
  REPO_ACCESS_TOKEN: ${{secrets.REPO_ACCESS_TOKEN}}
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    strategy:
#      fail-fast: false
      max-parallel: 1
      matrix:
        include:
        
        - os: ubuntu-latest
        - os: macOS-latest
        - os: windows-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
    
    - name: create EXTERNAL REPO
      run: |
        # modify this to point to your external repo
        git clone https://github.com/${{github.repository}}-${{matrix.os}} EXTERNAL_REPO
        cd EXTERNAL_REPO
        rm -rf .git
        git init
        touch README.md
        git add README.md
        git commit -m "first commit"
        git branch -M main
        # modify this to point to your repo
        git remote add origin https://${{env.REPO_ACCESS_TOKEN}}:x-oauth-basic@github.com/${{github.repository}}-${{matrix.os}}.git
        git status
        git remote -v
        git remote show origin
        git push --set-upstream origin main --force
```

### Expected behavior

i expect the push to succeed since i own the repository

### Actual behavior

the push is failing with invalid username or password

i do not know why

### Repro steps

make a new repository called X

make a new repository called X2

in repository X, create a new workflow

in this workflow, create an action that initializes a new repository with its URL as X2 and then push to X2 (as stated in the X2 initialization readme for empty repositories)

the push will fail even if a PAT is used

however the push can succeed if you add a tmate action and then ssh into the session and push to the repo via the ssh session
