### ISSUE TITLE
libcurl not included in ubuntu-latest software

### ISSUE THREAD

**Issue by iMacTia** [actions/virtual-environments#37]
**Describe the bug**
[This article](https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts) lists `libcurl` between the available software for `ubuntu-latest`, however installing the `Patron` ruby gem fails with `Can't find libcurl or curl/curl.h (RuntimeError)`.

**Virtual environments affected**
- [ ] macOS 10.14
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
It should be possible to install the patron gem without first installing any other dependency (apart from `bundler`).

**Actual behavior**
Installation of `Patron` ruby gem fails with `Can't find libcurl or curl/curl.h (RuntimeError)`.
Adding `sudo apt-get install libcurl4-openssl-dev` to the step fixes the issue, but it should not be necessary.

Workflow job:
```yaml
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.3.x, 2.4.x, 2.5.x, 2.6.x]
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get install libcurl4-openssl-dev
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
```

Gemfile:

```yaml
# frozen_string_literal: true

source 'https://rubygems.org'

group :test do
  gem 'patron', '>= 0.4.2'
end
```

**Comment by ethomson** [comment]
> This article lists libcurl between the available software for ubuntu-latest, however installing the Patron ruby gem fails with Can't find libcurl or curl/curl.h (RuntimeError).

This seems correct.  libcurl is documented as being installed, and _is_ installed.  We don't document that the development headers are installed, and indeed, they are not.

Your `apt-get install ...` step seems expected and correct to me?

**Comment by iMacTia** [comment]
Hi @ethomson thanks for getting back to me.
I may be confusing one thing for another as I'm not the expert with cURL, but my understanding is that `curl` and `libcurl` are two completely different things (see [this page](https://daniel.haxx.se/docs/curl-vs-libcurl.html)).

Now, my understanding of the Patron gem is that the latter, `libcurl`, is necessary as it contains the development libraries, not the Command Line tool (`curl`).

When you say
> libcurl is documented as being installed, and is installed
are you sure you're referring to the development libraries? Or are you referring to the command line tool to make requests?
If `libcurl` is actually installed as you say, is there another reason you could think of that may cause this?
I can only think of:
1. I'm installing something else with my command (a third, different thing?!), although my understanding is that I'm installing `libcurl` (dev libraries) with my command.
2. `libcurl` is actually installed, but for some reason `gem` can't access it while installing Patron; that may due to permissions or the PATH not set correctly?

**Comment by ethomson** [comment]
> I may be confusing one thing for another as I'm not the expert with cURL, but my understanding is that curl and libcurl are two completely different things (see this page).

Yes, this is 100% correct, they are different things.  However, many Linux distributions split up the distribution of libraries into two different packages:

1. The compiled library itself (in this case `libcurl`).  This is `libcurl-1.2.3.so` (where `1.2.3` is the actual version number installed).  This allows programs that were compiled against `libcurl` to use it.  So it's useful if you're installing some application (`git`, for instance) that was linked against libcurl to be able to use it.

2. The "development headers" for the library (in this case, `libcurl-dev`).  These are the header files (eg `curl.h`) that allows other developers to build and link against libcurl.

So libcurl itself is operational and usable when only the `libcurl` package is installed, but you can't build applications against it until you also install `libcurl-dev`.  This is basically the default for Debian-based distributions, to avoid having a lot of header files that you don't need.

(Note that I simplified a little in calling this `libcurl-dev`.  What I described is actually the general case for how things operate in Debian-based distributions.  Curl itself is a particularly difficult package to wrangle here since it has so many different variants.  You mentioned that you installed `libcurl4-openssl-dev` - there are other versions of curl that are available for other crypto providers (eg gnuTLS), so you actually have to decide which curl implementation you want.)

**Comment by iMacTia** [comment]
I see, that was really insightful, thank you @ethomson.
Hopefully this chat can be useful in future to other people with my same doubts 😃.
I'll close the issue then as it seems I'm already doing the correct thing anyway in this case.

Thanks for the clarification!

**Comment by ethomson** [comment]
Thanks @iMacTia!  😁 Let us know if you have any other questions or concerns.

**Comment by mxcl** [comment]
Since installing libcurl-openssl-dev changes libcurl from libcurl3 to libcurl4, this can break some other things you may need, thus you can get the headers by themselves like so:

```yaml
      - name: Install cURL Headers
        run: curl https://curl.haxx.se/download/curl-$V.tar.gz | sudo tar xz -C /usr --strip-components=1 curl-$V/include
        env:
          V: 7.58.0
```
