### ISSUE TITLE
Regression: Unable to use a GitHub-Repo as build-context for docker-compose

### ISSUE THREAD

**Issue by GabrielInTheWorld** [actions/virtual-environments#3799]
### Description

We have a service-oriented architecture and several services as sub-repos. One service (`openslides-auth-service`) makes system tests and uses for this purpose one other service. To do so, we use docker and docker-compose to start the services.
Until the 14th January 2021 this setup works well even with GitHub-Actions. Since the 15th January 2021 it doesn't work anymore.

Here is the GitHub-Action file:
```yml
name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build-and-test-dev-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create docker dev image
        run: make build-dev

      - name: Run tests in docker
        run: make run-tests
```

Here is a snippet of the makefile:
```make
build-dev:
	docker build -t openslides-auth-dev -f Dockerfile.dev .

run-tests: | build-dev
	@echo "########################################################################"
	@echo "###################### Start full system tests #########################"
	@echo "########################################################################"
	docker-compose -f docker-compose.dev.yml up -d
	docker-compose -f docker-compose.dev.yml exec -T auth wait-for-it auth:9004
	docker-compose -f docker-compose.dev.yml exec -T auth npm run test
	docker-compose -f docker-compose.dev.yml exec -T auth pytest
	docker-compose -f docker-compose.dev.yml down
```

Here is the docker-compose file:
```yml
version: "3"

services:
  auth:
    image: openslides-auth-dev
    restart: always
    depends_on:
      - datastore-reader
      - datastore-writer
      - message_bus
      - cache
    env_file: services.env
    volumes:
      - ./auth/libraries:/app/libraries
      - ./auth/src:/app/src
      - ./auth/test:/app/test
    ports:
      - "9004:9004"

  message_bus:
    image: redis:alpine
    expose:
      - 6379

  cache:
    image: redis:alpine
    expose:
      - 6379

  datastore-reader:
    build:
      context: "https://github.com/OpenSlides/openslides-datastore-service.git"
      dockerfile: Dockerfile
      args:
        MODULE: "reader"
        PORT: "9010"
    image: openslides-datastore-reader
    ports:
      - "9010:9010"
    depends_on:
      - postgresql
  datastore-writer:
    build:
      context: "https://github.com/OpenSlides/openslides-datastore-service.git"
      dockerfile: Dockerfile
      args:
        MODULE: "writer"
        PORT: "9011"
    image: openslides-datastore-writer
    ports:
      - "9011:9011"
    environment:
      - DATASTORE_ENABLE_DEV_ENVIRONMENT=1
      - COMMAND=create_initial_data
      - DATASTORE_INITIAL_DATA_FILE=https://raw.githubusercontent.com/OpenSlides/OpenSlides/openslides4-dev/docs/example-data.json
    depends_on:
      - postgresql
      - redis

  postgresql:
    image: postgres:11
    environment:
      - POSTGRES_USER=openslides
      - POSTGRES_PASSWORD=openslides
      - POSTGRES_DB=openslides
  redis:
    image: redis:alpine
```

Here is the Docker file:
```Docker
FROM python:3.9.0-slim-buster

RUN apt-get -y update && apt-get -y upgrade && \
    apt-get install --no-install-recommends -y wait-for-it && \
    apt-get install -y make git curl openssl

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y nodejs

ENV LD_LIBRARY_PATH=/usr/local/lib

WORKDIR /app

# Install dependencies. the `node_modules` folder is in /app
COPY auth/package*.json ./
RUN npm install

# Application lays in /app/src
COPY ./auth ./
COPY auth/entrypoint.sh ./

# Install pip-dependencies.
RUN pip install --no-cache-dir -r ./libraries/pip-auth/requirements.txt -r ./libraries/pip-auth/requirements_development.txt

EXPOSE 9004

ENV OPENSLIDES_DEVELOPMENT 1

ENTRYPOINT [ "./entrypoint.sh" ]
CMD ["npm", "run", "dev"]
```

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

20210718.1
Link: https://github.com/OpenSlides/openslides-auth-service/pull/74/checks

### Is it regression?

Yes: The GitHub-Action does not work anymore since the 15th January 2021. Unfortunately, I cannot see the environment used anymore. But I have noticed, that it works on Ubuntu-18.04.

### Expected behavior

I expect, that the services will be built through the docker-compose file and the tests run.

### Actual behavior

The services are not built through the docker-compose file and the workflow breaks with the following error-message:
```
########################################################################
###################### Start full system tests #########################
########################################################################
docker-compose -f docker-compose.dev.yml up -d
Creating network "openslides-auth-service_default" with the default driver
Pulling message_bus (redis:alpine)...
alpine: Pulling from library/redis
Digest: sha256:420c98f3fedeb9a1d6d2bcdfe19b15fa8e1382e73559ea69e21aee7dbce23da3
Status: Downloaded newer image for redis:alpine
Pulling postgresql (postgres:11)...
11: Pulling from library/postgres
Digest: sha256:13e23e5f97a42286c5703691e2fbad0806970bd13121fe7c28f32349ee0cf917
Status: Downloaded newer image for postgres:11
Building datastore-reader
unable to prepare context: unable to 'git clone' to temporary context directory: error fetching: /usr/lib/git-core/git-remote-https: /tmp/_MEIUancU6/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by /lib/x86_64-linux-gnu/libssh.so.4)
: exit status 128
Service 'datastore-reader' failed to build : Build failed
make: *** [Makefile:30: run-tests] Error 1
Error: Process completed with exit code 2.
```

### Repro steps

1. Make a docker-compose file
2. Build at least one service through a git context
3. Let GitHub-Actions execute this docker-compose file
