### ISSUE TITLE
Running out of storage with jacoco tests of an android app

### ISSUE THREAD

**Issue by jordankettles** [actions/virtual-environments#3886]
### Description

Hi GitHub actions, 
I'm a university student at Otago University with a problem that's affecting my software engineering project and our instructor encouraged us to write an issue. We are supposed to have CI and code coverage through GitHub actions and are creating an android app that uses a deep learning model to generate poems. Our problem is that when running the code coverage tests on github actions, gradle always gives some error about insufficient storage. The app is quite large considering the ai model is ~236MB. We would really appreciate if someone could help us identify what is wrong.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

[345-group-project/tree/code_coverage](https://github.com/jordankettles/345-group-project/tree/code_coverage)

### Expected behavior

Tests run

### Actual behavior

 > Task :app:connectedDebugAndroidTest
Unable to install /Users/runner/work/345-group-project/345-group-project/app/build/outputs/apk/debug/app-debug.apk
com.android.ddmlib.InstallException: Unknown failure: Exception occurred while executing:
android.os.ParcelableException: java.io.IOException: Requested internal only, but not enough space

### Repro steps

1. Create an android app that's ~250MB.
2. Run code coverage tests through github actions.

**Comment by LeonidLapshin** [comment]
Hey, @jordankettles !
We'll take a look soon:)
Thanks!

**Comment by Yuriy-Kukushkin** [comment]
Hello, @jordankettles!
The issue is caused by the incorrect value of the `sdcard-path-or-size` input. According to the [documentation](https://github.com/ReactiveCircus/android-emulator-runner#configurations) of the Android Emulator Runner action, the `sdcard-path-or-size` input must be in KB or MB, not GB. For example: `sdcard-path-or-size: 5000M`

**Comment by jordankettles** [comment]
> The issue is caused by the incorrect value of the `sdcard-path-or-size` input. According to the [documentation](https://github.com/ReactiveCircus/android-emulator-runner#configurations) of the Android Emulator Runner action, the `sdcard-path-or-size` input must be in KB or MB, not GB. For example: `sdcard-path-or-size: 5000M`

Hi Yuriy, Thank you for the suggestion but unfortunately I have tried many various sizes of 'M' without any luck.

**Comment by Yuriy-Kukushkin** [comment]
Hey @jordankettles,
In order to fix the error you need to change the configuration by adding command-line option `-partition-size 2048` as follows:
```
- name: Build with Gradle
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -partition-size 2048
          sdcard-path-or-size: 5000M
          ram-size: 4000M
          script: ./gradlew jacocoTestReport connectedCheck
```
