### ISSUE TITLE
`Kotlin` command is missing on windows-latest virtual env path.

### ISSUE THREAD

**Issue by sureshg** [actions/virtual-environments#4066]
### Description

Github action has recently added support for `Kotlin`, which enables us to execute the kotlin script directly on mac/windows/linux CI builds. Even though things are working fine on Mac and Linux, the script execution fails on windows with the following error

```
Run kotlin -e 'System.getProperty("kotlin.home")'
  kotlin -e 'System.getProperty("kotlin.home")'
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
  env:
    author: Suresh
    name: Github Action Test
    deployKey: test
    jdk-version: 16
    JAVA_HOME: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\16.0.2-7\x64
  }
D:\a\_temp\a05a1d69-9e84-476f-a706-cd41bb2bb465.sh: line 1: kotlin: command not found
Error: Process completed with exit code 127.
```

It seems the `kotlin` command is not added to PATH on windows.

Also, it would be great to add `KOTLIN_HOME` env variable (similar to `GRAALVM_11_ROOT` or `GO_ROOT`) which can be used to add plugins jars available in the kotlin distribution.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Current runner version: '2.281.1'
Operating System
  Ubuntu
  20.04.3
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20210906.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210906.1/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210906.1
  ```

### Is it regression?

No

### Expected behavior

Could able to execute all the kotlin commands on windows/linux and mac envs

 * kapt          
 * kotlin        
 * kotlin-dce-js 
 * kotlinc       
 * kotlinc-js    
 * kotlinc-jvm

### Actual behavior

Can't execute the `kotlin` command on windows.

### Repro steps

```yaml
    - name: Run Kotlin Script
        run: |
          kotlin -e 'System.getProperty("kotlin.home")'
        shell: bash     
```

**Comment by Darleev** [comment]
Hello @sureshg,
Thank you for the detailed report.
We will investigate the issue.

**Comment by dibir-magomedsaygitov** [comment]
Hello @sureshg. I've been able to reproduce the issue using `kotlin -e 'System.getProperty("kotlin.home")'` command. Try to use `kotlinc` instead of `kotlin` on Windows. Your runs should pass after that ([test run](https://github.com/dibir-magomedsaygitov/stm-actor/actions/runs/1230139279)).
```
    name: kotlin test
    runs-on: windows-latest
    steps:
      - name: test
        run: kotlinc -e 'System.getProperty("kotlin.home")'
        shell: bash
```
