### ISSUE TITLE
Running Maven commands in PowerShell with dots in the parameters

### ISSUE THREAD

**Issue by bonigarcia** [actions/virtual-environments#4106]
### Description

I want to run the following command in GitHub Actions:

```
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        java: [ 8 ]

    steps:
    - name: Test with Maven
      run: mvn -B test -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
```

The `mvn` command is failing, and it seems it is because it has dots in the parameters. When passing this command to PowerShell, it fails:

```
Run mvn -B test -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
  mvn -B test -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"

...

Error:  Unknown lifecycle phase ".keepAlive=false". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
```

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/bonigarcia/selenium-webdriver-java/runs/3630641622?check_suite_focus=true

### Repro steps

This issue can be reproduced trying to execute this patch:

https://github.com/bonigarcia/selenium-webdriver-java/commit/e9aaf07234d08f4aab6459f10a86dedd2a8c6d81

The error is the following:

https://github.com/bonigarcia/selenium-webdriver-java/runs/3630641622?check_suite_focus=true

I have managed to reproduce the issue in a Windows machine, by executing an equivalent command:

```
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command "mvn -B test -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120"
```
