### ISSUE TITLE
Add Xcode 11.4 beta

### ISSUE THREAD

**Issue by ydnar** [actions/virtual-environments#411]
**Tool information**
- Tool name: 
- Add or update? 
- Desired version: 11.4 beta
- Approximate size: ~9GB
- If this is an add request:
  - Brief description of tool: most recent version of Xcode
  - URL for tool's homepage: https://developer.apple.com

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Sort of—via [`xcode-install`](https://github.com/xcpretty/xcode-install). It takes a while.

**Are you willing to submit a PR?**
Sure?

**Notes**
Xcode 11.4 adds Swift 5.2, compiler performance updates, and major updates to SwiftUI and Swift compiler error messages.

**Comment by al-cheb** [comment]
Hello, @ydnar 

Xcode 11.4 is already present on the macos image. Please check the Xcode section in documentation, macOs 10.15 documentation - https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md

`11.4 (beta) | 11N111s | /Applications/Xcode_11.4_beta.app`

Example:
```
jobs:
  build:
    runs-on: [macos-latest]
    steps:
      - name: Xcode 11.
        run: |
          sudo xcode-select -s /Applications/Xcode_11.4.app/Contents/Developer
          xcodebuild -version
```


![xcode - Copy](https://user-images.githubusercontent.com/47745270/74585167-d99b5a00-4fea-11ea-993a-bc1ea1b9adc9.JPG)
