### ISSUE TITLE
VSTest Failure on Windows-2022

### ISSUE THREAD

**Issue by nibanks** [actions/virtual-environments#4123]
### Description

We are trying out running updating our tests to run on the windows-2022 image (now that test-signing is rolling out) and encountered an issue where the tests don't even run, claiming that Visual Studio 2015 wasn't found ([link](https://mscodehub.visualstudio.com/WindowsXDP/_build/results?buildId=211460&view=logs&j=dc73162c-e9a5-5aad-58cc-3e7f05745135&t=af2b7667-eb8e-5aaa-734b-1af5cfae6110)).

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Environment: windows-2022
Version: 20210920.1
Included Software: https://github.com/actions/virtual-environments/blob/win22/20210920.1/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/win22%2F20210920.1

### Is it regression?

No

### Expected behavior

The tests should run.

### Actual behavior

The tests fail to start:
```
======================================================
Test selector : Test assemblies
Test filter criteria : null
Search folder : D:\a\1\s
Action when minimum tests threshold not met : donothing
Minimum tests expected to be run: 0
VisualStudio version selected for test execution : latest
Attempting to find vstest.console from a visual studio installation with version [16.0,17.0).
Attempting to find vstest.console from a visual studio build tools installation with version [16.0,17.0).
Attempting to find vstest.console from a visual studio installation with version [15.0,16.0).
Attempting to find vstest.console from a visual studio build tools installation with version [15.0,16.0).
##[error]Error: Visual Studio 2015 is not found. Try again with a version that exists on your build agent machine.
```

### Repro steps

1. Build a test on `windows-latest` image.
2. Run the tests on `windows-2022` image.

**Comment by dibir-magomedsaygitov** [comment]
Hello @nibanks. Thank you for your report. Could you please provide us more detailed repro steps since we don't have permissions to your project.
I've seen [similar issue](https://github.com/Microsoft/vstest/issues/1349) to yours. If you are using VSTest Task, could you please try to choose the option as "Installed by tools installer" for the "Test platform version" input and check if it helps.

**Comment by nibanks** [comment]
Simply, we have a solution (`xdp.sln`), that we run the following on `windows-latest`:
```
  - task: VSBuild@1
    displayName: Build Solution (Debug)
    condition: and(succeeded(), contains('${{ parameters.config }}', 'Debug'))
    inputs:
      solution: xdp.sln
      platform: ${{ parameters.arch }}
      configuration: debug
```
and then run this on `windows-2022`:
```
  - task: VSTest@2
    timeoutInMinutes: 10
    inputs:
        testSelector: testAssemblies
        testAssemblyVer2: artifacts/bin/${{ parameters.arch }}_${{ parameters.config }}/xdpfunctionaltests.dll
```

**Comment by nadesu** [comment]
@shreyasrmsft - pls take a look at it

**Comment by ShreyasRmsft** [comment]
@al-cheb is there any version of Visual studio installed on the agent machine?

If you do not have visual studio installed you'd need to use https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/vstest-platform-tool-installer?view=azure-devops

**Comment by al-cheb** [comment]
> @al-cheb is there any version of Visual studio installed on the agent machine?
> 
> If you do not have visual studio installed you'd need to use https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/vstest-platform-tool-installer?view=azure-devops

 @ShreyasRmsft, Windows Server 2022 hosted agent:

# Microsoft Windows Server 2022 Datacenter
- OS Version: 10.0.20348 Build 230
- Image Version: 20210920.1
- 
### Visual Studio Enterprise 2022
| Name                          | Version      | Path                                                  |
| ----------------------------- | ------------ | ----------------------------------------------------- |
| Visual Studio Enterprise 2022 | 17.0.31710.8 | C:\Program Files\Microsoft Visual Studio\2022\Preview |

**Comment by ShreyasRmsft** [comment]
@al-cheb got it, we'll update the task to have support for VS 2022 in the coming release. Thanks for letting us know that the hosted pools are being updated with the preview versions of 2022.

@v-pkoneti will be working on it and can provide further updates.

**Comment by FlsZen** [comment]
@nibanks I came across this issue this morning. My temporary workaround is to use the `dotnet test` task in my pipeline (below). I look forward to switching back to the VSTest task at some point since it kind of feels wrong to be mixing `VSBuild` and `dotnet test`, although the tests all seem to run fine.

```
- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: '*.sln'
```
