### ISSUE TITLE
env variables like GOROOT_1_17_X64 missing from macos

### ISSUE THREAD

**Issue by codefromthecrypt** [actions/virtual-environments#4156]
### Description

It seems a mistake that environment variables like GOROOT_1_17_X64 are present on windows and linux, but not on macos. Can you please add them?

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20210914.1

### Expected behavior

I would expect syntax like this to work portably

```
    echo "GOROOT=$GOROOT_1_17_X64" >> $GITHUB_ENV
    echo "$GOROOT_1_17_X64/bin" >> $GITHUB_PATH
```

### Actual behavior

The `GOROOT_1_17_X64` variable isn't set, so you can't use it

### Repro steps

Do this and expect the same result
```
echo $GOROOT_1_17_X64
/opt/hostedtoolcache/go/1.17.1/x64
```

**Comment by codefromthecrypt** [comment]
here's a patch I'm using meanwhile

```yaml
env:
  GOROOT_NAME: GOROOT_1_17_X64
```

then...

```yaml
      # This sets the version-specific GOROOT env on macOS until actions/virtual-environments#4156
      #
      # This must happen before interpolating ${!GOROOT_NAME} on macOS
      - name: "Set GOROOT_X64 env (macOS)"
        if: runner.os == 'macOS'
        run: |  # ex GOROOT_1_17_X64 -> 1.17
          go_version=$(echo ${GOROOT_NAME}| cut -d_ -f2,3| tr _ .)
          go_root=$(ls -d /Users/runner/hostedtoolcache/go/${go_version}*/x64|sort -n|tail -1)
          echo "${GOROOT_NAME}=${go_root}" >> $GITHUB_ENV
```
