### ISSUE TITLE
git works unstable via HTTPS for npm ci

### ISSUE THREAD

**Issue by ArtjomP** [actions/virtual-environments#416]
**Describe the bug**
We do node builds on ubuntu agents. It worked well until today. Today npm ci returns

> npm ERR! fatal: unable to access 'https://dev.azure.com/Company/Project/_git/repo.js/': The requested URL returned error: 500

It works unstable sometimes npm ci does the job from the first time, sometimes I need to restart the failed jobs and it does the job only from n-s attempt. 

I noticed that the jobs started to execute longer on the ubuntu-latest agents something about 20% longer.

**Area for Triage**: 

**Question, Bug, or Feature?**: 
"Bug"
**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
get the code from the first try for 
npm ci (git clone)

**Actual behavior**
1. Add dependency hosted on Azure DevOps repo to a Node.js project
2. Create pipeline for Node.js
3. Use PAT in the pipeline:
> git config --global url."https://${VCS_TOKEN}@dev.azure.com/".insteadOf "https://Company@dev.azure.com/"
4. npm ci returns:
> npm ERR! fatal: unable to access 'https://dev.azure.com/Company/Webprints/_git/repo.js/': The requested URL returned error: 500

**Comment by vmapetr** [comment]
Hi @ArtjomP! Thanks for reporting this issue. Could you please provide additional information, before we proceed with investigation?
1. Is this issue affecting only AzureDevops Artifacts, or it's appearing when you use global NPM feeds too?
2. Can you reproduce this issue locally and not trough pipelines?

**Comment by ArtjomP** [comment]
1. It affects only getting repos via HTTPS on an MS agent (ubuntu & macOS).
It fails even when npm ci from a container running on the ubuntu-latest.

2. No I can't reproduce it on an local machine or on a private hosted agent.

**Comment by ArtjomP** [comment]
1. It affects only getting repos via HTTPS on an MS agent. We have 5 agents in the Azure pool. I simplified the steps and sometimes even this fails
`
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: 'dev.azure.com'
    sshPublicKey: 'ssh-rsa bla bla'
    sshKeySecureFile: 'azdo'

- script: |
    git clone git@ssh.dev.azure.com:v3/Compa/Webprints/BookBlock BookBlockSsh
    ls -hal BookBlockSsh
    git clone https://FarHeapSolutions:$(azure.git_token)@dev.azure.com/FarHeapSolutions/Webprints/_git/BookBlock BookBlockHttps
    ls -hal BookBlockHttps
`

**Comment by ArtjomP** [comment]
Update.
We got the same error on our some private hosted agents.

**Comment by ArtjomP** [comment]
Even simple git fetch fails sometimes.
Just a fresh one from a private hosted agent:
```
git fetch --force --tags --prune --progress --no-recurse-submodules origin '+refs/heads/*:refs/remotes/origin/*' +refs/heads/branch1
fatal: unable to access 'https://***@dev.azure.com/Company/Project/_git/Repo/': The requested URL returned error: 500
```

**Comment by maxim-lobanov** [comment]
Since it reproduces on private agent, it doesn't look like image issue but probably some infra issue.
@alepauly do you have any ideas?

**Comment by ArtjomP** [comment]
Some more data.
**Azure hosted agent:**
```
2020-02-19T08:10:34.0403481Z Agent name: 'Hosted Agent'
2020-02-19T08:10:34.0403586Z Agent machine name: 'fv-az161'
2020-02-19T08:10:34.0403647Z Current agent version: '2.164.8'
2020-02-19T08:10:34.0404500Z Current image version: '20200211.1'
2020-02-19T08:10:34.0412563Z Agent running as: 'vsts'
...
2020-02-19T08:10:37.8603458Z + ping -c 3 dev.azure.com
2020-02-19T08:10:49.9389837Z PING dev.azure.com (13.107.42.20) 56(84) bytes of data.
2020-02-19T08:10:49.9392236Z 
2020-02-19T08:10:49.9393372Z --- dev.azure.com ping statistics ---
2020-02-19T08:10:49.9393482Z 3 packets transmitted, 0 received, 100% packet loss, time 2053ms
```

**Comment by ArtjomP** [comment]
Hello!
We have 5 Azure agents.
Here is a test pipeline:
```
trigger: none

jobs:  
- job: pingUbuntu
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    maxParallel: 5
    matrix: 
      job1:
        test_var: 'job1.sh'        
      job2:
        test_var: 'job2.sh'
      job3:
        test_var: 'job3.sh'
      job4:
        test_var: 'job4.sh'
      job5:
        test_var: 'job5.sh'
  variables:
  - group: 'Access tokens'
  - group: 'Dependencies versions'
  steps:
  - checkout: self
    clean: true
    fetchDepth: 1

  - script: |
      ping -c 10 dev.azure.com

  - task: NodeTool@0
    inputs:
      versionSpec: $(node.version)
    displayName: 'Install Node.js'

  - script: |
      git config --global url."https://$(azure.git_token)@dev.azure.com/".insteadOf "https://Company@dev.azure.com/"
      npm ci
    displayName: 'npm install and build'

- job: pingMac
  pool:
    vmImage: 'macOS-latest'
  strategy:
    maxParallel: 5
    matrix: 
      job1:
        test_var: 'job1.sh'        
      job2:
        test_var: 'job2.sh'
      job3:
        test_var: 'job3.sh'
      job4:
        test_var: 'job4.sh'
      job5:
        test_var: 'job5.sh'
  variables:
  - group: 'Access tokens'
  - group: 'Dependencies versions'
  steps:
  - checkout: self
    clean: true
    fetchDepth: 1

  - script: |
      ping -c 10 dev.azure.com

  - task: NodeTool@0
    inputs:
      versionSpec: $(node.version)
    displayName: 'Install Node.js'

  - script: |
      git config --global url."https://$(azure.git_token)@dev.azure.com/".insteadOf "https://Company@dev.azure.com/"
      npm ci
    displayName: 'npm install and build'

- job: pingWindows
  pool:
    vmImage: 'windows-latest'
  strategy:
    maxParallel: 5
    matrix: 
      job1:
        test_var: 'job1.sh'        
      job2:
        test_var: 'job2.sh'
      job3:
        test_var: 'job3.sh'
      job4:
        test_var: 'job4.sh'
      job5:
        test_var: 'job5.sh'
  variables:
  - group: 'Access tokens'
  - group: 'Dependencies versions'
  steps:
  - checkout: self
    clean: true
    fetchDepth: 1

  - script: |
      ping dev.azure.com

  - task: NodeTool@0
    inputs:
      versionSpec: $(node.version)
    displayName: 'Install Node.js'

  - script: |
      git config --global url."https://$(azure.git_token)@dev.azure.com/".insteadOf "https://Company@dev.azure.com/"
      npm ci
    displayName: 'npm install and build'

- job: pingPrivate
  pool: 'Privage pool'
  strategy:
    maxParallel: 2
    matrix: 
      job1:
        test_var: 'job1.sh'
      job2:
        test_var: 'job2.sh'
  variables:
  - group: 'Access tokens'
  - group: 'Dependencies versions'
  steps:
  - checkout: self
    clean: true
    fetchDepth: 1

  - script: |
      ping -c 10 dev.azure.com

  - task: NodeTool@0
    inputs:
      versionSpec: $(node.version)
    displayName: 'Install Node.js'

  - script: |
      git config --global url."https://$(azure.git_token)@dev.azure.com/".insteadOf "https://Company@dev.azure.com/"
      npm ci
    displayName: 'npm install and build'

```
Please, look at the result:
![image](https://user-images.githubusercontent.com/20728465/74899482-1d58df80-53ae-11ea-9956-758a9e718cc9.png)

CmdLine error is:
```
ping -c 10 dev.azure.com
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/377c4e94-2542-4696-9ac0-b9681d3049f2.sh
PING dev.azure.com (13.107.42.20) 56(84) bytes of data.

--- dev.azure.com ping statistics ---
10 packets transmitted, 0 received, 100% packet loss, time 9198ms
```
npm install & build error is:
`fatal: unable to access 'https://dev.azure.com/Company/Project/_git/Repo/': The requested URL returned error: 500`

Could somebody help with it?

Thank you in advance!
