### ISSUE TITLE
Virtual Environment Provisioner version includes the word `master`

### ISSUE THREAD

**Issue by QuintinWillison** [actions/virtual-environments#4189]
### Description

This may not be the right place to report this, but I would appreciate it if someone with more knowledge of GitHub's repository structures (perhaps including internal ones) could register this in the right place if this repository isn't that place.

If I open up the 'Set up job' section of one of my workflow runs then I see log output entitled 'Virtual Environment Provisioner' (e.g. [here](https://github.com/ably/ably-js/runs/3723146132?check_suite_focus=true#step:1:12)) with something like:

    1.0.0.0-master-20210914-1

I consider this to be a bug because it's been a long time since, as far as I am aware, GitHub committed to making changes in this area ([you have published guidance](https://github.com/github/renaming)).

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

In case it helps, the full 'Set up job' section output, from [this run](https://github.com/ably/ably-js/runs/3723146132?check_suite_focus=true):

```
Current runner version: '2.283.1'
Operating System
  Ubuntu
  20.04.3
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20210919.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210919.1/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210919.1
Virtual Environment Provisioner
  1.0.0.0-master-20210914-1
GITHUB_TOKEN Permissions
  Contents: read
  Metadata: read
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2' (SHA:5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f)
Download action repository 'actions/setup-node@v1' (SHA:f1f314fca9dfce2769ece7d933488f076716723e)
```

Generated by [this workflow (permalink)](https://github.com/ably/ably-js/blob/f42c0b956f34cae0314d3cc075a45eea488b2341/.github/workflows/check.yml):

```yaml
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build
      - run: npm run check-closure-compiler
```

### Is it regression?

no

### Expected behavior

Non-inclusive terms like `master` should not be used, especially not if that means they appear in every workflow run for every GitHub user.

### Actual behavior

GitHub's default behaviour is to emit the non-inclusive term `master` in every single GitHub user's workflow run log output.

### Repro steps

1. Create a workflow
2. Run it 😞
