### ISSUE TITLE
Cannot register Azure DevOps PowerShell repository

### ISSUE THREAD

**Issue by iainbrighton** [actions/virtual-environments#4221]
### Description

We have many pipelines running `windows-2016` and `windows-2019` that successfully register an internal PowerShell repository (the repo is also hosted by Azure DevOps). This post was used as a basis for registering the repository: https://devblogs.microsoft.com/powershell/using-powershellget-with-azure-artifacts/

However, when switching to the new `windows-2022` image, the repository fails to register with a `Get-CredsFromCredentialProvider : Cannot bind argument to parameter 'Path' because it is null.` error.

I can only assume that the `PowerShellGet` module needs to be updated or is incompatible with the version of Nuget installed.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Virtual Environment
Environment: windows-2022
Version: 20210927.1
Included Software: https://github.com/actions/virtual-environments/blob/win22/20210927.1/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/win22%2F20210927.1

### Actual behavior

The Azure DevOps module repository fails to register with a `Get-CredsFromCredentialProvider : Cannot bind argument to parameter 'Path' because it is null.` error (works on `windows-2016` and `windows-2019`).
```
VERBOSE: Registering package source 'https://pkgs.dev.azure.com/<redacted>/PSRepository/_packaging/modules/nuget/v2'
VERBOSE: Saving a config with a file path 'C:\Users\VssAdministrator\AppData\Roaming\NuGet\nuget.config'.
VERBOSE: Registering package repository 
'https://pkgs.dev.azure.com/<REDACTED>/PSRepository/_packaging/modules/nuget/v2'
VERBOSE: PowerShellGet Calling 'CallCredProvider' on 
https://pkgs.dev.azure.com/<REDACTED>/PSRepository/_packaging/modules/nuget/v2
Get-CredsFromCredentialProvider : Cannot bind argument to parameter 'Path' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1:11499 char:40
+ ... redential = Get-CredsFromCredentialProvider -SourceLocation $SourceLo ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-CredsFromCredentialProvider], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Get-CredsFromCredentialProvider
```

### Repro steps

Here is a sample YAML file that recreates the problem:
```
trigger: none

pool:
  vmImage: windows-2022

steps:

- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Microsoft Partner Network'
    KeyVaultName: '<REDACTED>'
    SecretsFilter: 'PackageRepositoryToken'
    RunAsPreJob: false

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $null = Install-PackageProvider -Name NuGet -ForceBootstrap -Force -Confirm:$false -Verbose
      $null = Register-PackageSource -Name Test -Location 'https://pkgs.dev.azure.com/<REDACTED>/PSRepository/_packaging/modules/nuget/v2' -ProviderName NuGet -SkipValidate -Verbose
      $null = Register-PSRepository -Name Test -SourceLocation 'https://pkgs.dev.azure.com/<REDACTED>/PSRepository/_packaging/modules/nuget/v2' -InstallationPolicy Trusted -Verbose
  env:
    VSS_NUGET_EXTERNAL_FEED_ENDPOINTS: '{"endpointCredentials": [{"endpoint":"https://pkgs.dev.azure.com/<REDACTED>/PSRepository/_packaging/modules/nuget/v2", "username":"<REDACTED>", "password":"$(PackageRepositoryToken)"}]}'
```
