### ISSUE TITLE
CMake does not find PostgreSQL anymore

### ISSUE THREAD

**Issue by d-frey** [actions/virtual-environments#4243]
### Description

About 2 days ago, CMake stopped finding PostgreSQL in the system. I have changes some source code, then reverted it back. But the build fails before even trying to compile my code, so from my perspective it has to be some change in the virtual environment.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

# Failing builds

## Windows Server 2019
https://github.com/taocpp/taopq/runs/3842056429?check_suite_focus=true
Version: 20211003.2

## Windows Server 2016
https://github.com/taocpp/taopq/runs/3842056518?check_suite_focus=true
Version: 20211003.1

# Working builds, 2 days ago

## Windows Server 2019
https://github.com/taocpp/taopq/runs/3820206113?check_suite_focus=true
Version: 20210928.2

## Windows Server 2016
https://github.com/taocpp/taopq/runs/3820205739?check_suite_focus=true
Version: 20210927.1

### Is it regression?

https://github.com/taocpp/taopq/actions/runs/1313629530

### Expected behavior

Just like 2 days ago, PostgreSQL should be found by CMake.

### Actual behavior

CMake fails to find PostgreSQL with

```
-- Detecting CXX compile features - done
CMake Error at C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PostgreSQL (missing: PostgreSQL_LIBRARY) (found version
-- Configuring incomplete, errors occurred!
See also "D:/a/taopq/taopq/build/CMakeFiles/CMakeOutput.log".
  "11.3")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.21/Modules/FindPostgreSQL.cmake:269 (find_package_handle_standard_args)
  CMakeLists.txt:7 (find_package)
```

### Repro steps

Run the CI jobs.

**Comment by miketimofeev** [comment]
Hi @d-frey!
The Postgres version was updated from 13 to 14 across all the images. Most likely your issue is related to that.

**Comment by d-frey** [comment]
I do not require any specific version, I just use [`find_package(PostgreSQL REQUIRED)`](https://github.com/taocpp/taopq/blob/549a5d797cb0cce859181218c1f51720842828fb/CMakeLists.txt#L7).

If PostgreSQL version 14 is installed correctly, it should be found just like version 13 before, right? (Again, CMake fails *before* it even tries to compile my code)

**Comment by miketimofeev** [comment]
We haven't changed the installation process. Is there a possibility that `find_package(PostgreSQL REQUIRED)` is not adapted for Postgre14?

**Comment by wojsmol** [comment]
Short googling bring [this documentation of find_package](https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure)

**Comment by d-frey** [comment]
BTW: What looks really weird to me is the part of the error message where it seems to find an older version of PostgreSQL:

```
  Could NOT find PostgreSQL (missing: PostgreSQL_LIBRARY) (found version
-- Configuring incomplete, errors occurred!
See also "D:/a/taopq/taopq/build/CMakeFiles/CMakeOutput.log".
  "11.3")
```

It looks like the first and the last line belong together, so it is effectively trying to say

```
  Could NOT find PostgreSQL (missing: PostgreSQL_LIBRARY) (found version "11.3")
```

Which is a bit self-contradictory. If it found version "11.3", then why does it say it could NOT find PostgreSQL.
Maybe that might help someone to debug the issue.

**Comment by wojsmol** [comment]
@d-frey I'm not CMake expert - maybe this will help virtual environments people to help you.

**Comment by wojsmol** [comment]
`D:/a/taopq/taopq/build/CMakeFiles/CMakeOutput.log` - personalty I will try use `actions/download-arteffact` to get that log.

**Comment by mikhailkoliada** [comment]
There is a bug in the `FindPostgreSQL` of cmake that I suggest reporting upstream. Downgrading to postgresql13 helps

The workaround would be the following workflow:


```
name: PostgreSQL cmake test
on: [push]

jobs:
    Workaround-PostgreSQL:
        runs-on: windows-latest
        steps:
            - name: remove currently installed version
              run: choco uninstall postgresql
            - name: install Postgresql 13
              run: choco install postgresql13 -y
            - name: checkout repo
              uses: actions/checkout@v2
            - name: run cmake configure
              run: cmake .
            - name: setup environment and show env variables
              run: |
                  $env:PGROOT='C:\Program Files\PostgreSQL\13'
                  $env:PGBIN='C:\Program Files\PostgreSQL\13\bin'
                  $env:PGDATA='C:\Program Files\PostgreSQL\13\data'
                  echo $env:PGROOT
                  echo $env:PGBIN
                  echo $env:PGDATA
              shell: powershell
```

I've tested it on a pretty primitive `CMakeLists.txt` file and it works just fine:


```
cmake_minimum_required(VERSION 3.0)
project(pgtest)
find_package(PostgreSQL REQUIRED)

```
