### ISSUE TITLE
Add RSAT PowerShell Modules (ActiveDirectory)

### ISSUE THREAD

**Issue by aolszowka** [actions/virtual-environments#4280]
### Tool name

Remote Server Administration Tools (RSAT) for Windows

### Tool license

Windows License

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Latest

### Brief description of tool

RSAT enables IT administrators to remotely manage roles and features in Windows Server from a computer that is running Windows 10 and Windows 7 Service Pack 1.

I really just want the PowerShell Modules Available to me; specifically:

* ActiveDirectory https://docs.microsoft.com/en-us/powershell/module/activedirectory/?view=windowsserver2019-ps

There are actually a fair number of these, but this is the most most commonly used currently by our Self Hosted Agent.

Technically because the image is Windows Server we should just need to install the Administrative Roles for the above to get access to these modules.

Our use case of this is we have several Custom PowerShell Modules that we use the Pipeline to package and push out to our NuGet Feed, as part of this we have the pipeline run several Pester tests on these scripts. The functions themselves are mocked out, however due to the use of PowerShell's `#requires` statement (https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_requires?view=powershell-7.1) this module needs to exist. Furthermore in several places we leverage Pester's ability to determine the correct function overload, meaning we don't often "stub out" the function, instead relying on Pester to determine this.

These modules do not ship outside of the Windows Feature or RSAT (in other words they're not on the PowerShell Gallery to consume as we would other modules).

### URL for tool's homepage

https://docs.microsoft.com/en-US/troubleshoot/windows-server/system-management-components/remote-server-administration-tools

### Provide a basic test case to validate the tool's functionality.

```bash
<# To reproduce the failure you only need this line#>
#Requires -Module ActiveDirectory

<# The following Pester Test shows how we would use this #>
#Requires -Module Pester
Describe 'PesterTest' {
    Context 'ActiveDirectory' {
        It 'MocksOutCalls' {
            Mock -CommandName Get-ADUser -MockWith { return [PSCustomObject]@{ SAMAccountName = 'FakeUser' } } -Verifiable
            $result = Get-ADUser -Filter "SAMAccountName -eq 'FakeUser'"
            $result.SAMAccountName | Should -Be 'FakeUser'
            Assert-VerifiableMock
        }
    }
}
```

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
# Assuming you can use Install-WindowsFeature on Windows Server
Install-WindowsFeature -Name "RSAT-AD-PowerShell" –IncludeAllSubFeature
```

### Are you willing to submit a PR?

Sure; if someone could guide me?

**Comment by miketimofeev** [comment]
Hi @aolszowka!
Considering quick installation time in runtime (~1 minute), we'd rather not add the tool to the image to avoid additional maintenance efforts.
I'm going to close the issue, but feel free to contact us if you have any concerns.
Thank you!

**Comment by aolszowka** [comment]
@miketimofeev Indeed I am, I apologize:

azure-pipelines.yml
```yaml
---
pool:
  vmImage: "windows-2019"

stages:
  - stage:
    jobs:
      - job: "Build"
        displayName: "Build"
        condition: true
        steps:
          - task: PowerShell@2
            displayName: "Install Feature"
            name: "installFeature"
            condition: always()
            inputs:
              targetType: inline
              script: |
                Install-WindowsFeature -Name RSAT-AD-PowerShell
                Get-Command -Module ActiveDirectory
              pwsh: true
            timeoutInMinutes: 5
```

Output:
```
Success Restart Needed Exit Code      Feature Result
------- -------------- ---------      --------------
True    No             Success        {Remote Server Administration Tools, Active 

Verb                : Add
Noun                : ADCentralAccessPolicyMember
HelpFile            : Microsoft.ActiveDirectory.Management.dll-Help.xml
.
. (continues on for all members)
.
```
