### ISSUE TITLE
[dotnet] installed nugets are not found in build

### ISSUE THREAD

**Issue by mmulhearn** [actions/virtual-environments#4307]
### Description

I have an action that pulls a dotnet core 3.1 solution from a GitHub repo and then restores and builds it.  Turning on "normal" logging, I can see the nuget packages from my private GitHub Packages feed installing, but the build fails with errors that would indicate the packages aren't found or the DLLs are missing.

I need to be careful about pasting as the projects and Nuget include my employers name, so please bear with me.

The build error is:

```
 Using shared compilation with compiler from directory: /home/runner/.dotnet/sdk/3.1.414/Roslyn/bincore
     2>Constants.cs(1,18): error CS0234: The type or namespace name 'Entities' does not exist in the namespace 'Employer.Cs' (are you missing an assembly reference?) [/home/runner/work/mercury-middleware/mercury-middleware/src/common/Employer.Cs.Mercury/Employer.Cs.Mercury.csproj]
```

This reference is to Employer.Entities, which comes from the Nuget `Employer.Cs.Core`

Installation of packages:
```
[...]
OK https://nuget.pkg.github.com/<org>/download/employer.cs.core/index.json 1562ms
[...]
GET https://nuget.pkg.github.com/<org>/download/employer.cs.core/21.24.0/employer.cs.core.21.24.0.nupkg
[...]
OK https://nuget.pkg.github.com/<org>/download/employer.cs.core/21.24.0/employer.cs.core.21.24.0.nupkg 954ms
[...]
Installed employer.Cs.Core 21.24.0 from https://nuget.pkg.github.com/<org>/index.json with content hash 276giT0IuhtgSsOZAQtVMaWwD1mFC3CtkfX5AwopsFZ/XNCDdzTe0lcYgJt2S+eiBC5zNUwOfe3Bap/MzPEUbg==.
```

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Environment: ubuntu-20.04
  Version: 20211011.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20211011.1/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20211011.1

### Expected behavior

The logs indicate the nuget package was found and installed.  Expected behavior is the solution should build.  The solution builds fine locally even when nuget caches are cleared.

### Actual behavior

Build fails.

### Repro steps

Not sure how to repo this.

**Comment by al-cheb** [comment]
@mmulhearn , Could you check?

```
- uses: actions/checkout@v2
- uses: actions/setup-dotnet@v1
  with:
    dotnet-version: '3.1'
    source-url: https://nuget.pkg.github.com/<org>/index.json
  env:
    NUGET_AUTH_TOKEN: ${{secrets.GHP_READ}}
- name: restore
      run: dotnet restore
- name: build
      run: dotnet build --configuration Release --no-restore
```
