### ISSUE TITLE
Cache action on Windows doesn't seem to restore to the expected place

### ISSUE THREAD

**Issue by vsajip** [actions/virtual-environments#4334]
### Description

A file is cached but apparently not restored, even though the cache step claims success. The file is in the `$env:USERPROFILE\bin` directory, but apparently not restored there. Here is the cache step:
```
    - name: Cache Jython (Windows)
      if: ${{ (matrix.os == 'windows-latest') }}
      id: cache-jython-windows
      uses: actions/cache@v2
      with:
        path: ${env:USERPROFILE}/bin/jython.jar
        key: ${{ runner.os }}-jython
```
The step which uses the cache is:
```
    - name: Setup Jython 2.7.2 (Windows)
      if: ${{ matrix.os == 'windows-latest' && (steps.cache-jython-windows.outputs.cache-hit != 'true') }}
      run: |
        $source = 'https://repo1.maven.org/maven2/org/python/jython-standalone/2.7.2/jython-standalone-2.7.2.jar'
        $destination = "${env:USERPROFILE}/bin/jython.jar"
        Invoke-WebRequest -Uri $source -OutFile $destination
```
However, the cache restoring command seems to be
```
C:\Windows\System32\tar.exe -z -xf D:/a/_temp/3cd9d6af-2308-473f-a1ed-8d4953b0908d/cache.tgz -P -C D:/a/javacc21/javacc21
```
Which will not work, as it restores to `D:/a/javacc21` - not the source of the cached file, which is `$env:USERPROFILE\bin`.

Note that the parallel caching done on POSIX works fine.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image version: 20211018.0

[Build link](https://github.com/javacc21/javacc21/runs/3995456332?check_suite_focus=true)

### Expected behavior

The cache step should restore the file to the place it came from.

### Actual behavior

The cache step should restore the file to the place it came from.

### Repro steps

See the linked build.
