### ISSUE TITLE
Ruby's FileUtils.copy_file does not copy Tempfile properly

### ISSUE THREAD

**Issue by lizgorb** [actions/virtual-environments#4443]
### Description

We are using ubuntu-18.04 with ruby:2.7.1 for running our specs in a github action.
We started experiencing odd failures at about the same time the latest ubuntu image (https://github.com/actions/virtual-environments/blob/releases/ubuntu18/20211101/images/linux/Ubuntu1804-README.md) was rolled out. 
The issue manifested for us as an error with minimagick image conversion, specifically we got the error 
```
       convert-im6.q16: insufficient image data in file ...
```

Upon further investigation we narrowed down the issue to ruby's ` FileUtils.copy_file` in conjunction with `Tempfile`. 
The `copy_file` operation leaves the target file empty (causing the above error). This can be reproduced with the following snippet
```
require 'tempfile'

file_to_copy_from = File.open('origin_test', 'w') { |file| file.write("test test"); file }
puts "Origin file stats"
puts File.stat(file_to_copy_from.path).inspect
tempfile = Tempfile.new(["tmp", ".txt"]).tap do |tempfile|
  IO.copy_stream(file_to_copy_from.path, tempfile)
  tempfile.close
end
puts "Temp file stats"
puts File.stat(tempfile).inspect

copy_to_path = "copy_to"

FileUtils.copy_file tempfile.path , copy_to_path
puts "Dest file stats"
puts File.stat(copy_to_path).inspect
```

The above can be store as a file and executes by a github workflow with `ruby ./test_tempfile.rb`

Run locally (mac) or on ubuntu the line `puts File.stat(copy_to_path).inspect` 
outputs:
```
#<File::Stat dev=0x10302, ino=965, mode=0100600, nlink=1, uid=1009, gid=1009, rdev=0x0, size=9, blksize=4096, blocks=8, atime=2021-11-08 13:49:45 -0500, mtime=2021-11-08 13:49:45 -0500, ctime=2021-11-08 13:49:45 -0500>
```

However as part of a github action the output indicates the size of the Dest file is 0
```
#<File::Stat dev=0x811, ino=805133, mode=0100600, nlink=1, uid=0, gid=0, rdev=0x0, size=0, blksize=4096, blocks=0, atime=2021-11-08 18:27:01.391047037 +0000, mtime=2021-11-08 18:27:01.391047037 +0000, ctime=2021-11-08 18:27:01.391047037 +0000>
```

### Virtual environments affected

- [X] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20211101.1

### Is it regression?

20211017.0

### Expected behavior

The file should be copied correctly and have the appropriate size

Run locally (mac) or on ubuntu the stats for the copied files are:
```
#<File::Stat dev=0x10302, ino=965, mode=0100600, nlink=1, uid=1009, gid=1009, rdev=0x0, size=9, blksize=4096, blocks=8, atime=2021-11-08 13:49:45 -0500, mtime=2021-11-08 13:49:45 -0500, ctime=2021-11-08 13:49:45 -0500>
```

### Actual behavior

The destination file has a size of 0:
```
#<File::Stat dev=0x811, ino=805133, mode=0100600, nlink=1, uid=0, gid=0, rdev=0x0, size=0, blksize=4096, blocks=0, atime=2021-11-08 18:27:01.391047037 +0000, mtime=2021-11-08 18:27:01.391047037 +0000, ctime=2021-11-08 18:27:01.391047037 +0000>
```

### Repro steps

1. Create a `test_tempfile.rb` file with content:
```
require 'tempfile'

file_to_copy_from = File.open('origin_test', 'w') { |file| file.write("test test"); file }
puts "Origin file stats"
puts File.stat(file_to_copy_from.path).inspect
tempfile = Tempfile.new(["tmp", ".txt"]).tap do |tempfile|
  IO.copy_stream(file_to_copy_from.path, tempfile)
  tempfile.close
end
puts "Temp file stats"
puts File.stat(tempfile).inspect

copy_to_path = "copy_to"

FileUtils.copy_file tempfile.path , copy_to_path
puts "Dest file stats"
puts File.stat(copy_to_path).inspect
```

2. Create a github workflow `test.yml` with content:
```
name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test_tempfile:
    runs-on: ubuntu-18.04

    container:
      image: ruby:2.7.1

    steps:
      - name: Print env variables
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          printenv
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Run test
        run: |
          ruby ./test_tempfile.rb
```
3. Invoke the workflow. The output of the "Run test" step will display the issue.
