### ISSUE TITLE
Latest VirtualBox doesn't work in macOS 10.15 virtualenv

### ISSUE THREAD

**Issue by rgraber** [actions/virtual-environments#4466]
### Description

Setting up docker in Mac with `docker-machine --debug create --driver virtualbox default` fails with: 
```
VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp
}
```
This is preventing us from running our ci tests in the mac virtualenv. We believe the culprit to be an upgrade to VirtualBox after looking at this thread https://discuss.hashicorp.com/t/vagrant-2-2-18-osx-11-6-cannot-create-private-network/30984/4 (the thread deals with Mac 11 and Vagrant but the problem and suggested fixes seem to indicate it's the same root issue). 

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

version 20211106.1

https://github.com/edx/devstack/runs/4168506146?check_suite_focus=true

### Expected behavior

We expect docker-machine to set up the virtual environment using VirtualBox that we can use to run our tests.

### Actual behavior

Error: 
```
VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp
}
```

### Repro steps

Simple github actions config to reproduce:
```
name: Minimal

on:
  pull_request:
    branches:
      - '**'

jobs:
  run_ci:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Docker installation - Mac
        run: |
          brew install docker docker-machine
          docker-machine --debug create --driver virtualbox default

```
