### ISSUE TITLE
curl: command not found in Ubuntu20.04

### ISSUE THREAD

**Issue by rufusnufus** [actions/virtual-environments#4495]
### Description

I'm facing a problem with curl command. 
According to installed apt packages in [https://github.com/actions/virtual-environments/blob/ubuntu20/20211108.1/images/linux/Ubuntu2004-README.md](https://github.com/actions/virtual-environments/blob/ubuntu20/20211108.1/images/linux/Ubuntu2004-README.md) curl package should be installed. In one repository action works without any problem, however in another repository it doesn't work even if I try to install it through apt-get install(apt-get command not found as well).
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/24591578/141516620-358c8fd3-62c3-49f3-b0aa-dfa62055cac2.png">

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20211108.1

### Expected behavior

curl is installed

### Actual behavior

curl command not found

### Repro steps

1. Create `example.yaml` in `.github/workflows/` directory in GitHub. 
2. Put the code below:
```yaml
name: Deploy new stand

on:
  workflow_dispatch:

env:
  ARGOCD_VERSION: v2.1.6

jobs:
  prepare:
    name: Get ArgoCD cli
    runs-on: ubuntu-20.04  
    steps:
      - name: Install ArgoCD CLI
        id: install_argocd
        shell: bash
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/${{ env.ARGOCD_VERSION }}/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd
```
3. Run the workflow.
