### ISSUE TITLE
Opening Simulator app fails often with error `The executable is missing`

### ISSUE THREAD

**Issue by fluiddot** [actions/virtual-environments#4545]
### Description

I experienced often failures on different workflows that open and use the Simulator app for running mobile end-to-end tests, so far the failure ratio is 70-50%.

The command used for opening the Simulator app is:
```
open -Fn /Applications/Xcode_13.0.app/Contents/Developer/Applications/Simulator.app
```

And the error message:
```
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10827 "kLSNoExecutableErr: The executable is missing" UserInfo={_LSLine=3844, _LSFunction=_LSOpenStuffCallLocal}
```

In the beginning, I wasn't sure if this issue might be produced by other steps in the workflow, so for this reason, I created an empty repository with a basic workflow to confirm that the issue could be reproduced by only opening the Simulator app. In the following PR you can check the workflow https://github.com/fluiddot/test-virtual-environment-macos-11/pull/1 and the failure.

As a side note, I'd like to highlight that I only encountered this error when using the `macOS 11` image, on previous macOS images opening the Simulator app work without issues.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

- **Image version:** 20211114.1
- **Build link:** https://github.com/fluiddot/test-virtual-environment-macos-11/runs/4267476811

### Is it regression?

Not sure.

### Expected behavior

Opening the Simulator app shouldn't produce errors.

### Actual behavior

Around 50-70% of runs that open the Simulator app produce an error and makes the workflow fail.

### Repro steps

1. Create a workflow with the following code.
```
name: Test Simulator app

on:
    pull_request:

jobs:
    test:
        runs-on: macos-11
        strategy:
            matrix:
                xcode: ['13.0']

        steps:
            - name: Open Simulator app
              run: open -Fn /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer/Applications/Simulator.app
```
2. Trigger several runs until producing a failure (usually it happens around the 2nd-5th run).
3. Observe the `The executable is missing` error related to the step that opens the Simulator app.
