### ISSUE TITLE
Update/Add the service fabric sdk to the windows-2022 image

### ISSUE THREAD

**Issue by grantborthwick** [actions/virtual-environments#4546]
### Description

When I upgrade to the windows-2022 image, my tests that use the service fabric dlls are no longer able to load them. 

I do see that the service fabric tools component was upgraded with the new image, but I would expect the dlls to still be present.
[2019](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#workloads-components-and-extensions): Microsoft.VisualStudio.Component.Azure.ServiceFabric.Tools | 17.0.31804.368
[2022](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#workloads-components-and-extensions): Microsoft.VisualStudio.Component.Azure.ServiceFabric.Tools | 16.4.29313.120

Is there a different path that I should be using? If not, will you please make sure that the service fabric sdk gets properly installed as a part of the image?

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20211109.2

![image](https://user-images.githubusercontent.com/2301725/142712828-12fc2da5-aa1b-4c2b-9a7c-0fea7cd34ffd.png)

### Is it regression?

windows-2019

### Expected behavior

Service fabric sdk dlls are present and able to load.

### Actual behavior

The service fabric dlls are not present and thus fail to load.

### Repro steps

When I run

```yaml
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 2022.yaml

parameters:
- name: images
  type: object
  default:
  - windows-2019
  - windows-2022

variables:
  skipComponentGovernanceDetection: true

jobs:
  - ${{ each image in parameters.images }}:
    - job: ${{ replace(image,'-','') }}
      pool:
        vmImage: ${{ image }}
      steps:
      - checkout: none
      - powershell: |
            function Test-Folder {
                [CmdletBinding()]
                param(
                    [string]$path
                )
                Write-Host "##[group]$path"
                try {
                    if (-not (Test-Path $path)) {
                        Write-Host "$path does not exist"
                    } else {
                        gci $path -File -Recurse | ForEach-Object {
                            Write-Host $_.FullName
                        }
                    }
                } catch {
                    Write-Host "Failed to check $path | $_"
                }
                Write-Host "##[endgroup]"
            }
            Test-Folder "$env:ProgramFiles\Microsoft Service Fabric\bin\Fabric\Fabric.Code\"
            Test-Folder "$env:ProgramFiles\Microsoft Service Fabric\bin\Fabric\"
            Test-Folder "$env:ProgramFiles\Microsoft Service Fabric\bin\"
            Test-Folder "$env:ProgramFiles\Microsoft Service Fabric\"
            Test-Folder "$env:ProgramData\Microsoft Service Fabric"
```
on 2019, I find files as expected, but on 2022, none of the folders exist:

![image](https://user-images.githubusercontent.com/2301725/142712814-75ed9bec-4f88-490d-b92a-442edd7986f2.png)

![image](https://user-images.githubusercontent.com/2301725/142712805-5272b395-25a4-49c9-bfd8-8465ec0e35ac.png)
