### ISSUE TITLE
Error: The operation was canceled.

### ISSUE THREAD

**Issue by yaroslavyaroslav** [actions/virtual-environments#4643]
### Description

While running `swift test` in github actions it canceles tests in the testing proccess.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

failed run: 
https://github.com/yaroslavyaroslav/web3swift/actions/runs/1521747691
https://github.com/yaroslavyaroslav/web3swift/actions/runs/1521676808

### Expected behavior

Tests run till the end.

### Actual behavior

Tests canceled with the message: `Error: The operation was canceled.`

### Repro steps

workflow that fails: https://github.com/yaroslavyaroslav/web3swift/actions/runs/1521747691/workflow

**Comment by shilovmaksim** [comment]
Hi @yaroslavyaroslav. 
Your workflow runs cancelling due to timeout exceeded, that set up in your [workflow yaml file](https://github.com/yaroslavyaroslav/web3swift/blob/github-actions/.github/workflows/ci.yml)
```
jobs:
  macOS_5_4:
    name: Test macOS 11 (5.4)
    runs-on: macOS-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.5.1.app/Contents/Developer
    timeout-minutes: 10
```
