### ISSUE TITLE
windows-2022 agent - Grunt@0 task not working

### ISSUE THREAD

**Issue by mariusandersen** [actions/virtual-environments#4661]
### Description

On windows-2019 we could just run with a pwsh task "yarn && grunt".

In windows-2022 I previously had to use the dedicated [grunt task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/grunt?view=azure-devops) as it seemed grunt-cli was now removed. This worked for several weeks.

Today, the windows-2022 gives error using the Grunt@0 task:
##[error]Grunt-cli is not installed globally (or is not in the path of the user the agent is running as) and it is not in the local working folder: D:\a\1\s\node_modules\grunt-cli\bin\grunt

Can you fix the Grunt@0 task in windows-2022?

Would also love it if you could globally install grunt-cli also, would simplify our migration from windows-2019 to windows-2022.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20211130.3

### Is it regression?

20211115.1

### Expected behavior

pwsh task "grunt" works on windows-2022 to make migration from windows-2019 smooth

Grunt@0 task works ok on windows-2022

### Actual behavior

pwsh task "grunt" does not work, never has done on windows-2022 but inconsistent with windows-2019

Grunt@0 task does not work in newer versions of windows-2022

### Repro steps

using windows-2022 run the Grunt@0 task. It fails with 
##[error]Grunt-cli is not installed globally (or is not in the path of the user the agent is running as) and it is not in the local working folder: D:\a\1\s\node_modules\grunt-cli\bin\grunt

**Comment by al-cheb** [comment]
Hello, @mariusandersen 
We will take a look at it.

**Comment by vsafonkin** [comment]
Hi @mariusandersen, I've tried to create sample project with Grunt: 
package.json deps:
```json
"dependencies": {
    "semver": "^6.1.1",
    "grunt": "^1.4.1",
    "grunt-contrib-jshint": "^3.1.1",
    "grunt-contrib-watch": "^1.1.0"
  }
```
gruntfile.js:
```js
module.exports = function(grunt) {

  grunt.initConfig({
    jshint: {
      files: ['Gruntfile.js', 'src/**/*.js', 'test/**/*.js'],
      options: {
        globals: {
          jQuery: true
        }
      }
    },
    watch: {
      files: ['<%= jshint.files %>'],
      tasks: ['jshint']
    }
  });

  grunt.loadNpmTasks('grunt-contrib-jshint');
  grunt.loadNpmTasks('grunt-contrib-watch');

  grunt.registerTask('default', ['jshint']);

};
```
azure-pipelines.yaml:
```yaml
jobs:
  - job:
    pool:
      vmImage: 'windows-2022'
    steps:
    - pwsh: npm install
      displayName: Install deps
    - task: Grunt@0
      inputs:
        gruntFile: 'gruntfile.js'
```
and it works as expected: https://dev.azure.com/v-vlsafo/test/_build/results?buildId=41&view=results
Image version is `20211130.3`

Could you provide any sample demo to reproduce this error?

**Comment by mariusandersen** [comment]
@vsafonkin Thanks for a very detailed example. The grunt task seem to actually work OK in the example you provided. After some investigation in order for you to reproduce it:

package.json
```
{
  "name": "example",
  "version": "1.0.0",
  "devDependencies": {
    "grunt": "~0.4.5",
    "grunt-shell": "^1.1.1"
  }
}
```
Gruntfile.js
```
module.exports = function (grunt) {
	grunt.initConfig({
		pkg: grunt.file.readJSON("package.json"),
		configuration: grunt.option("configuration") || "Release",
		shell: {
			test: {
				command: "ls"
			},
		}
	});

	grunt.loadNpmTasks("grunt-shell");

	// Default task(s).
	grunt.registerTask("default", ["shell:test"]);
};
```

pipeline.yml
```
stages:
  - stage: "Example"
    dependsOn: []
    jobs:
      - job: "producegruntissues"
        pool:
          vmImage: "windows-2022"
        steps:
          - pwsh: yarn
            displayName: 'yarn'

          - task: Grunt@0
            inputs:
                targets: 'default'
            displayName: 'grunt task'

          - pwsh: grunt
            displayName: 'grunt with pwsh'
```

I actually could make the Grunt@0 task work OK if I changed from 
```
"grunt": "~0.4.5", 
```
to 
```
"grunt": "^1.4.1",
```
but it still causes some headache to upgrade grunt version in the migration process as the pipelines are shared across several repositories.
