### ISSUE TITLE
Gradle buils is slow on macOS agents

### ISSUE THREAD

**Issue by tyagirajnish** [actions/virtual-environments#4691]
### Description

I have an android project where I am running two test pipeline

- Unit test pipeline
- UI test pipeline 

For the unit test pipeline, I am using an [Ubuntu machine](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md) which gets complicated in less than 5 minutes including my 400 unit test cases but On UI pipeline where I am using [macOS agents](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md) to create an android simulator and run the build which takes almost 10 minutes to build the app even I am not running any UI test cases, why is there so much time difference in build with same application in different agents.

 

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Agent name: 'Azure Pipelines 2'
Agent machine name: 'Mac-1638971449039'
Current agent version: '2.195.2'
```

### Expected behavior

Build time should be same on different environment 

### Repro steps

Use any android project and create two Pipeline, in the First one use an ubuntu agent, and the second pipeline use a macOS machine, you can see easily see the build time difference between them.

**Comment by al-cheb** [comment]
Hello, @tyagirajnish
Could you provide steps to reproduce an issue or share repository?

**Comment by tyagirajnish** [comment]
hello @al-cheb 

sorry I can't share the repo but I have shared how you can reproduce this issue all you need a sample application, create two pipelines in the first one use ubuntu image and in second one use mac machine

here is a sample project i found over the GitHub: https://github.com/imShakil/BloodBank

Attached screenshot it's clearly visible the time difference between two pipelines with same code, only difference is agent
![Screenshot 2021-12-08 at 8 56 30 PM](https://user-images.githubusercontent.com/46373586/145235420-cfb136d6-a56b-4226-b551-fcfdd31630e8.png)

**Comment by dibir-magomedsaygitov** [comment]
Hello @tyagirajnish. Could you please share yaml file with reprosteps in order to be able properly investigate the issue.

**Comment by tyagirajnish** [comment]
hi @dibir-magomedsaygitov ,

i tried to run some test cases on the [given project](https://github.com/imShakil/BloodBank) but here I can see vice versa case here ubuntu vm are slow to build
![Screenshot 2021-12-13 at 2 35 02 PM](https://user-images.githubusercontent.com/46373586/145783469-2d8d4388-6050-409e-9cf8-3c1d0ecb2ab3.png)

here is my yml code for this [project](https://github.com/imShakil/BloodBank)

```
trigger:
- master

pool:
  vmImage: ubuntu-latest // or macos-latest

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'test'
```
