### ISSUE TITLE
R package rgeos cannot be built on macos-latest

### ISSUE THREAD

**Issue by jamiemkass** [actions/virtual-environments#4748]
### Description

My Github Actions workflow for macos-latest fails because it cannot build the R package rgeos, although from what I understand there is no problem with the package (I can download it on my machine just fine). The exact error is: "Failed to build source package 'rgeos'". My workflow completes with other OS (windows, ubuntu, etc.).

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Virtual Environment
  Environment: macos-11
  Version: 20211207.1
  Included Software: https://github.com/actions/virtual-environments/blob/macOS-11/20211207.1/images/macos/macos-11-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-11%2F20211207.1

Download action repository 'actions/checkout@v2' (SHA:ec3a7ce113134d7a93b817d10a8272cb61118579)
Download action repository 'r-lib/actions@v1' (SHA:6df8d6458e01e38b8afba7c1f53a68165285079f)
Download action repository 'actions/upload-artifact@main' (SHA:82c141cc518b40d92cc801eee768e7aafc9c2fa2)
Getting action download info
Download action repository 'actions/cache@v2' (SHA:937d24475381cd9c75ae6db12cb4e79714b926ed)

### Expected behavior

The workflow completes, like it does on other OS (windows, ubuntu, etc.).

### Repro steps

1. Run Github Actions workflow with macos-latest on an R package that includes rgeos somewhere in its dependency chain.

**Comment by nikolai-frolov** [comment]
Hello @jamiemkass. Thanks for reporting, we'll take care about the issue investigation. I'm not sure but this one issue can be related: https://github.com/actions/virtual-environments/issues/4747

**Comment by al-cheb** [comment]
Hey, @jamiemkass 

With v2:
```
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-pandoc@v2
    - uses: r-lib/actions/setup-r@v2
      with:
          r-version: 'release'
          use-public-rspm: true
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
          extra-packages: rcmdcheck
```
![image](https://user-images.githubusercontent.com/47745270/146413021-341f5d69-250b-4135-8306-c40511350718.png)
