### ISSUE TITLE
Add cosign

### ISSUE THREAD

**Issue by JamieMagee** [actions/virtual-environments#4813]
### Tool name

cosign

### Tool license

Apache License 2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

1.4.1

### Approximate size

80MB

### Brief description of tool

Container Signing, Verification and Storage in an OCI registry.

It is promoted in a GitHub blog post[^1] and in starter workflows[^2]

[^1]: https://github.blog/2021-12-06-safeguard-container-signing-capability-actions/
[^2]: https://github.com/actions/starter-workflows/blob/5104ac42744c84c675b2f9e1168e89f1dd60c059/ci/docker-publish.yml#L40-L46

### URL for tool's homepage

https://github.com/sigstore/cosign

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
See https://github.com/sigstore/cosign-installer
```

### Tool installation time in runtime

a couple of seconds

### Are you willing to submit a PR?

yes

**Comment by miketimofeev** [comment]
Hi @JamieMagee!
The started workflow example executes install action and this is a recommended way to use consign as you can set up any version you like or stay on the latest. The installation takes not more than 2-3 seconds:
```yml
jobs:
  build:
    runs-on: ubuntu-latest

    name: Install Cosign and test presence in path
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.4.1'
      - name: Check install!
        run: cosign version
```
However, the action doesn't support other OSs at the moment and we recommend creating an issue in the https://github.com/sigstore/cosign-installer repository to add the support.
Until that you can use the following snippets to install consign in runtime, it won't take more than 5 seconds for macOS and 20 for windows:

**macOS**
```bash
csDownloadUrl=$(curl -s https://api.github.com/repos/sigstore/cosign/releases/latest | jq -r '.assets[].browser_download_url | select(contains("darwin-amd64"))' | head -n 1)
curl -L -o /tmp/cosign "$csDownloadUrl"
sudo xattr -rd com.apple.quarantine /tmp/cosign
mv /tmp/cosign /usr/local/bin/cosign
sudo chmod +x /usr/local/bin/cosign
cosign version
```
**windows**
```pwsh
$csBinary = Get-GitHubPackageDownloadUrl -RepoOwner "sigstore" -RepoName "cosign" -BinaryName "cosign-windows-amd64.exe" -Version "latest" -UrlFilter "*{Version}/{BinaryName}"
Start-DownloadWithRetry -Url $csBinary -DownloadPath "." -Name "cosign.exe"
./cosign.exe version
```

Considering fast installation time in runtime and maintenance concerns we would not like to add the tool to the image. Please use the action\snippets provided.
I'm going to close the issue, feel free to contact us if you have any concerns.
Thank you!
