### ISSUE TITLE
io_uring syscalls are not permitted

### ISSUE THREAD

**Issue by rojkov** [actions/virtual-environments#4819]
### Description

io_uring system calls fail in Azure Pipelines when agents from the ubuntu-18.04 and ubuntu-20.04 pools are used. Particularly the functions `io_uring_queue_init()` and `io_uring_queue_init_params()` from liburing return `EPERM` when called:
```
==================== Test output for //test/extensions/io_socket/io_uring:socket_interface_integration_test:
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from IpVersions/SocketInterfaceIntegrationTest
[ RUN      ] IpVersions/SocketInterfaceIntegrationTest.Basic/IPv4
[2021-12-29 12:18:01.195][29][critical][assert] [source/common/io/io_uring_impl.cc:34] assert failure: ret == 0. Details: unable to initialize io_uring: Operation not permitted
```

These functions succeed if the "arm-large" pool is used for CI jobs though.

The kernels used in ubuntu-18.04 and ubuntu-20.04 are v5.4 and v5.10 respectively and they have support for io_uring. Could it be too restrictive seccomp settings?

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

The logs can be found here https://dev.azure.com/cncf/envoy/_build/results?buildId=97556&view=logs&j=8c169225-0ae8-53bd-947f-07cb81846cb5&t=6b0ace90-28b2-51d9-2951-b1fd35e67dec&l=19000

```
Environment: ubuntu-20.04
Version: 20211219.1
Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20211219.1/images/linux/Ubuntu2004-README.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20211219.1
```

Example pull requests: https://github.com/envoyproxy/envoy/pull/19339 and https://github.com/envoyproxy/envoy/pull/19082

### Repro steps

Trigger a CI job in Azure Pipelines which initializes io_uring in ubuntu-18.04 and ubuntu-20.04 x86 VMs.

**Comment by dibir-magomedsaygitov** [comment]
Hello @rojkov. Thank you for your report. We will take a look.

**Comment by al-cheb** [comment]
@rojkov , Could you try to run a container with `--privileged` flag?

**Comment by rojkov** [comment]
@al-cheb adding `--privileged` didn't help (https://github.com/envoyproxy/envoy/pull/19082/files/63d0b78dc5a1c6ff29acf4013976204108d794c9..15b2730fbd97185365aeac5fde78a470498b4e2e). It still throws "Operation not permitted".

On my workstation the same test passes inside a non-privileged container.

**Comment by al-cheb** [comment]
@rojkov, Could you please share a small repo? 

I tested a simple app in the `envoyproxy/envoy-build-ubuntu` container and it works -  https://pastebin.com/raw/NZPH3RS
```
    runs-on: ubuntu-latest
    container: envoyproxy/envoy-build-ubuntu:81a93046060dbe5620d5b3aa92632090a9ee4da6
    steps:
    - run: |
        apt-get update
        apt-get install -y curl git build-essential
    - run: |
        curl -s https://pastebin.com/raw/NZPH3RS3 > hello.c
        git clone https://github.com/axboe/liburing.git
        make -C ./liburing
    - run: |
        gcc hello.c -o ./hello -I./liburing/src/include/ -L./liburing/src/ -Wall -O2 -D_GNU_SOURCE -luring
        ./hello
```
![image](https://user-images.githubusercontent.com/47745270/147729268-deff8100-391a-4be8-8473-f492771f53a9.png)

**Comment by rojkov** [comment]
Ok, I've just tried to run my failing test in Github Actions and it works too - https://github.com/rojkov/meta-helloworld/runs/4665477784?check_suite_focus=true
```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: envoyproxy/envoy-build-ubuntu:81a93046060dbe5620d5b3aa92632090a9ee4da6

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Run the test
        run: |
          NORUNFILES=yes ./io_uring_impl_test
```

The culprit seems to be somewhere in Azure Pipelines.
