### ISSUE TITLE
Add WKHTMLTOPDF

### ISSUE THREAD

**Issue by jethro-riosa** [actions/virtual-environments#482]
**Tool information**
- Tool name: wkhtmltopdf
- Add or update? add
- Desired version: latest version
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
wkhtmltopdf and wkhtmltoimage are open source (LGPLv3) command line tools to render HTML into PDF and various image formats using the Qt WebKit rendering engine. These run entirely "headless" and do not require a display or display service.
  - URL for tool's homepage: https://wkhtmltopdf.org/

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Are you willing to submit a PR?**

**Comment by maxim-lobanov** [comment]
Tool can be installed in runtime using the following script:
```
# Ubuntu
sudo apt-get install xvfb libfontconfig wkhtmltopdf
# macOS
brew cask install wkhtmltopdf
```
Installation takes about 25 seconds

**Comment by thejoebourneidentity** [comment]
Thanks for your suggestion @jethro-riosa . Considering how easy it is to install during your run, this is not something we will add to the image at this time.

**Comment by alexgordo** [comment]
To get this package running in my CI workflow I have the following as part of my config script:
```yml
- name: Install wkthtmltopdf
  run: |
    sudo apt-get install -y xfonts-base xfonts-75dpi
    wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
    sudo dpkg -i wkhtmltox_0.12.6-1.bionic_amd64.deb
```
I am using the `ubuntu-18.04` image for github actions

This installs the binary to `/usr/local/bin/wkthmltopdf`

The link may be go out of date, but you can see the latest on their [website](https://wkhtmltopdf.org/downloads.html)

**Comment by thibauds** [comment]
> Tool can be installed in runtime using the following script:
> 
> ```
> # Ubuntu
> sudo apt-get install xvfb libfontconfig wkhtmltopdf
> # macOS
> brew cask install wkhtmltopdf
> ```
> 
> Installation takes about 25 seconds

@maxim-lobanov @alexgordo 
Did you find a way to cache `wkhtmltopdf` in order to save these 25 seconds? I'm struggling with permission errors.

**Comment by alexgordo** [comment]
@thibauds Yes I cached the loading in the end by manually downloading the debs. The cache retrieves in 1s and the install takes 6s (on average).

To download & cache:
```yml
  - name: Cache wkthtmltopdf
    uses: actions/cache@v2
    id: cache-wkhtmltopdf
    with:
      path: "~/wkhtmltox/"
      key: ${{ runner.os }}-wkhtmltopdf-${{ hashFiles('**/*.deb') }}

  - name: Download wkthtmltopdf & dependencies
    if: steps.cache-wkhtmltopdf.outputs.cache-hit != 'true'
    run: |
      mkdir ~/wkhtmltox
      wget -O ~/wkhtmltox/wkhtmltox.deb https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
      wget -O ~/wkhtmltox/xfonts-encodings.deb http://archive.ubuntu.com/ubuntu/pool/main/x/xfonts-encodings/xfonts-encodings_1.0.4-2_all.deb
      wget -O ~/wkhtmltox/xfonts-utils.deb http://archive.ubuntu.com/ubuntu/pool/main/x/xfonts-utils/xfonts-utils_7.7+6_amd64.deb
      wget -O ~/wkhtmltox/xfonts-75dpi.deb http://archive.ubuntu.com/ubuntu/pool/universe/x/xfonts-75dpi/xfonts-75dpi_1.0.4+nmu1_all.deb
      wget -O ~/wkhtmltox/xfonts-base.deb http://archive.ubuntu.com/ubuntu/pool/main/x/xfonts-base/xfonts-base_1.0.4+nmu1_all.deb
```
Then to install:
```yml
  - name: Install wkhtmltopdf
    run: |
      sudo dpkg -i ~/wkhtmltox/xfonts-encodings.deb
      sudo dpkg -i ~/wkhtmltox/xfonts-utils.deb
      sudo dpkg -i ~/wkhtmltox/xfonts-75dpi.deb
      sudo dpkg -i ~/wkhtmltox/xfonts-base.deb
      sudo dpkg -i ~/wkhtmltox/wkhtmltox.deb
```
