### ISSUE TITLE
Windows long paths support

### ISSUE THREAD

**Issue by JamieMagee** [actions/virtual-environments#4913]
### Description

When attempting to checkout https://github.com/Azure/azure-sdk-for-net into a subdirectory on a Windows 2019 based runner I receive many error messages like the following:

```
error: unable to create file sdk/cognitiveservices/Microsoft.Azure.Management.CognitiveServices/tests/SessionRecords/CognitiveServices.Tests.CognitiveServicesAccountTests/CognitiveServicesAccountCreateAllApisTest.json: Filename too long
```

Please enable long paths support when building Windows images

```
New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Environment: windows-2019
Version: 20220116.1
```

https://github.com/microsoft/component-detection/runs/4874590492?check_suite_focus=true

### Is it regression?

No

### Repro steps

1. Try and check out a repository to a path with more than 260 characters [^1]

[^1]: https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation

**Comment by al-cheb** [comment]
Hey, @JamieMagee 
`LongPathsEnabled` is enabled - https://github.com/actions/virtual-environments/blob/a64db791f32ffe355d7397c1ac896d42686e9dfa/images/win/scripts/Installers/Initialize-VM.ps1#L70

**Comment by JamieMagee** [comment]
Interesting! After some more searching, it might be a configuration issue with git[^1]. Is it possible to set a git config default for the image?

```
git config --system core.longpaths true
```

[^1]: https://stackoverflow.com/a/22575737

**Comment by al-cheb** [comment]
> Interesting! After some more searching, it might be a configuration issue with git[1](#user-content-fn-1-b507e5cfdcfaa78f589133b5ab77bd53). Is it possible to set a git config default for the image?
> 
> ```
> git config --system core.longpaths true
> ```
> 
> ## Footnotes
> 1. https://stackoverflow.com/a/22575737 [↩](#user-content-fnref-1-b507e5cfdcfaa78f589133b5ab77bd53)

I will take a look at it. 

As a workaround set this flag in runtime: 
```
 - name: Set git core.longpaths flag
        run: |
            git config --system core.longpaths true
      - name: Clone verification repo (nuget/azure-sdk-for-net)
        uses: actions/checkout@v2.3.2
        with:
          repository: Azure/azure-sdk-for-net
          path: verification/projects/nuget
          ref: 1bf85a0ae26d1453e190dd2323fed43f560e9837
```
![image](https://user-images.githubusercontent.com/47745270/150284742-f0d9678c-558f-42fd-a907-82ac481f993b.png)
