### ISSUE TITLE
macos-11 is missing Tcl/Tk 8.6 shared libraries required by python >= 3.10.1

### ISSUE THREAD

**Issue by rokm** [actions/virtual-environments#4931]
### Description

`macos-11` environment is missing Tcl/Tk 8.6 shared libraries (`/usr/local/lib/libtcl8.6.dylib` and `/usr/local/lib/libtk8.6.dylib`) that are required by `tkinter` module in python >= 3.10.1 builds from `actions/python-versions`. 

Consequently, `tkinter` cannot be used with python >= 3.10.1 on `macos-11`, e.g., running `python3 -c 'import tkinter'`  results in 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/runner/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: dlopen(/Users/runner/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/lib-dynload/_tkinter.cpython-310-darwin.so, 2): Library not loaded: /usr/local/lib/libtk8.6.dylib
  Referenced from: /Users/runner/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/lib-dynload/_tkinter.cpython-310-darwin.so
  Reason: image not found
```

The earlier python builds (python <= 3.10.0) were built against (outdated) system Tcl/Tk 8.5 frameworks, but starting with 3.10.1, the `_tkinter` module is linked against Tcl/Tk 8.6 shared libraries that are supposed to be located in `/usr/local/lib`. These shared libraries are present on `macos-10.15`, but are missing from `macos-11`.

The same issue was reported here: https://github.com/actions/setup-python/issues/314. There, there is some confusion over inconsistent behavior, i.e., `tkinter` working in some repositories and not in some, which stems from `macos-latest` sometimes still translating to `macos-10.15` (where the issue is not present).

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20220118.8

Example of failed job(s): https://github.com/pyinstaller/pyinstaller/runs/4898415211?check_suite_focus=true

The above example shows that:
- Tcl/Tk 8.6 shared libraries are present in `macos-10.15` image, but missing from `macos-11`
- `tkinter` fails to import under python 3.10.1 and 3.10.2 on `macos-11` due to missing Tcl/Tk 8.6 shared libraries
- `tkinter` is successfully imported under python 3.10.0 on `macos-11`, because this build is still using old system-provided Tcl/Tk 8.5
- `tkinter` is successfuly imported under all three python 3.10 releases on `macos-10.15`

### Expected behavior

Tcl/Tk 8.6 shared libraries (`/usr/local/lib/libtcl8.6.dylib` and `/usr/local/lib/libtk8.6.dylib`) being present in the virtual image, and working `tkinter` in python >= 3.10.1.

### Actual behavior

Tcl/Tk 8.6 shared libraries (`/usr/local/lib/libtcl8.6.dylib` and `/usr/local/lib/libtk8.6.dylib`) are missing from the virtual environment, resulting in defunct `tkinter` with python >= 3.10.1.

### Repro steps

Basic job to reproduce the problem:
https://github.com/pyinstaller/pyinstaller/runs/4898415211?check_suite_focus=true

```
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.10.0', '3.10.1', '3.10.2']
        os: ['macos-10.15', 'macos-11']
      fail-fast: false
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check for presence of Tcl/Tk 8.6 libraries
        run: |
          ls -l /usr/local/lib/libtcl* || echo "Tcl/Tk 8.6 not found!"

      - name: Try importing tkinter
        run: python3 -c 'import tkinter'
```
