### ISSUE TITLE
Using `read -r -d` will cause an unexpected exit

### ISSUE THREAD

**Issue by SunsetYe66** [actions/virtual-environments#4932]
### Description

Using `read -r -d` will cause an unexpected exit only on Github Action Runners, which works fine on local bash. Haven't checked on self-host runners.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20220111.1

### Is it regression?

Have no idea

### Expected behavior

![image](https://user-images.githubusercontent.com/53211446/150577016-16be9c64-a4a5-455a-9b9a-9d83b3312928.png)
These `read -r -d` commands will correctly read multiple-line strings and will not throw an exception. The test passed on my own computer (macOS 12.1) and docker image `ubuntu-latest`

### Actual behavior

When it runs to Github Actions, the program will exit with code 1 and without any message.
![image](https://user-images.githubusercontent.com/53211446/150577401-8b8ed4ca-5384-4d72-ba19-70371bd8b564.png)

### Repro steps

write these code to `.github/workflows/debug.yml`:

```yaml
name: debug

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Debug
        continue-on-error: true
        run: |
          read -r -d '' detail2 << EOM
          test
          test
          EOM

          echo $detail2
```
