### ISSUE TITLE
Poetry dependency resolution suddenly fails with Python 3.6

### ISSUE THREAD

**Issue by connerxyz** [actions/virtual-environments#4954]
## Overview

- I have a Python package that is tested across Python versions 3.6, 3.7, 3.8 using a GitHub Action.
- The Action installs `poetry` and `tox` – `tox` calls `poetry install` and `poetry run pytest`
- This Action has worked for >6 months without issue, yet, now fails with Python ^3.6: `poetry` throws a `SolverProblemError` saying it can't solve versions for transitive dependencies (see output below).
- There have been no changes to dependencies (or any other significant changes to the package) that should result in this regression.
- I can run these same tests via `tox` with Python 3.6  on macOS 10.15 without any problem...
- I also checked out the last commit that ran via Actions successfully 2 months ago to find that the tests failed in the same way.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20220119.1 -> fails

I don't have a public example since this is happening within my employer's GitHub org.

### Is it regression?

Yes. Version: 20211129.1 -> works

### Expected behavior

The tests to pass (like they used to with Version: 20211129.1).

### Actual behavior

Below is an excerpt from the failed GitHub Action output. You'll see that inside the Python 3.6 environment, the transitive dependency `pillow` version appears to be solved for Python 3.7, which creates a `SolverProblemError`. 

I considered whether this was a problem with `poetry` and not GitHub Actions... but I am able to run all this just fine locally. I also added the Python version markers to my `pyproject.toml` file (e.g., pillow = {version = "8.4", python = "<3.7"}`), which fixed _this_ particular transitive dependency, but failed with for the same reason with the _next_ transitive dependency...

```
Writing lock file

  SolverProblemError

  The current project's Python requirement (3.6.15) is not compatible with some of the required packages Python requirement:
    - pillow requires Python >=3.7, so it will not be satisfied for Python 3.6.15
  
  Because no versions of genbadge match >=1.0.4,<1.0.6 || >1.0.6,<2.0.0
   and genbadge (1.0.6) depends on pillow (*), genbadge (>=1.0.4,<2.0.0) requires pillow (*).
  Because pillow (9.0.0) requires Python >=3.7
   and no versions of pillow match !=9.0.0, pillow is forbidden.
  Thus, genbadge is forbidden.
  So, because code-base-name depends on genbadge (^1.0.4), version solving failed.

  at /opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    For pillow, a possible solution would be to set the `python` property to "<empty>"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```

### Repro steps

Setup a GitHub Action that installs `poetry` and `tox` and runs across Python 3.6, 3.7, 3.8. Then run `pytest` via `tox`.

```
# GitHub Action
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - 'master'
    - 'main'
    - 'develop'
    - 'development'

  pull_request:
    branches:
    - 'master'
    - 'main'
    - 'develop'
    - 'development'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        env:
          # Excluding vars we use to configure pip and poetry with our GitHub org secrets
        run: |
          python -m pip install --upgrade pip
          pip install poetry tox
          # Excluding commands to configure pip and poetry with our GitHub org secrets
local/simple" >> .pip/pip.conf
      - name: Test with tox automation
        run: |
          tox
```

```
# tox.ini
[tox]
envlist = basepython
isolated_build = true
skipsdist = true

[testenv]
deps = poetry
setenv = PIP_CONFIG_FILE=.pip/pip.conf
commands =
    poetry install
    poetry run poe pytest
```
