### ISSUE TITLE
[macOS] Bundled miniconda is unusable, insufficient permissions

### ISSUE THREAD

**Issue by seemethere** [actions/virtual-environments#4955]
### Description

Currently the bundled miniconda is unusable by users attempting to install conda packages or create conda environments on macOS due to insufficient permissions on `/usr/local/miniconda/`.

Errors look like:
```
Collecting package metadata (current_repodata.json): ...working... failed
NotWritableError: The current user does not have write permissions to a required path.
  path: /usr/local/miniconda/pkgs/cache/53d7ef51.json
  uid: 501
  gid: 20

If you feel that permissions on this path are set incorrectly, you can manually
change them by executing

  $ sudo chown 501:20 /usr/local/miniconda/pkgs/cache/53d7ef51.json

In general, it's not advisable to use 'sudo conda'.


Error: Process completed with exit code 1.
```

Sample workflow run: https://github.com/seemethere/test-repo/actions/runs/1752322839

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
  Environment: macos-10.15
  Version: 20220124.1
  Included Software: actions/virtual-environments@macOS-10.15/20220124.1/images/macos/macos-10.15-Readme.md
  Image Release: actions/virtual-environments@macOS-10.15%2F20220124.1 (release)
```

### Expected behavior

Users should be able to use the bundled miniconda

### Actual behavior

```
Collecting package metadata (current_repodata.json): ...working... failed
NotWritableError: The current user does not have write permissions to a required path.
  path: /usr/local/miniconda/pkgs/cache/53d7ef51.json
  uid: 501
  gid: 20

If you feel that permissions on this path are set incorrectly, you can manually
change them by executing

  $ sudo chown 501:20 /usr/local/miniconda/pkgs/cache/53d7ef51.json

In general, it's not advisable to use 'sudo conda'.


Error: Process completed with exit code 1.
```

### Repro steps

```yaml
name: Testing macOS miniconda

on:
  pull_request:

jobs:
  test:
    runs-on: macos-10.15
    steps:
      - name: Attempt to create a conda environment
        run: |
          conda create -y -p ${RUNNER_TEMP}/build python=3.9
```
