### ISSUE TITLE
Databricks plugin failing to install on Windows agent in YAML pipeline

### ISSUE THREAD

**Issue by cjwrk** [actions/virtual-environments#5021]
### Description

The [DevOps for Azure Databricks plugin](https://marketplace.visualstudio.com/items?itemName=riserrad.azdo-databricks) appears to have stopped working when running on an agent with the image version:
20220131.1

The task works when running on an agent with the image version:
20220123.1

This is an extract from the pipeline logs on a failed run:
C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\pip.exe install databricks-cli
Error while installing databricks-cli: 
##[debug]check path : D:\a\_tasks\configuredatabricks_3830aa71-0bfb-45bd-ae00-6e82c877deae\0.5.2\task.json
##[debug]adding resource file: D:\a\_tasks\configuredatabricks_3830aa71-0bfb-45bd-ae00-6e82c877deae\0.5.2\task.json
##[debug]system.culture=en-US
Writing databricks-cli configuration to file: C:\Users\VssAdministrator\.databrickscfg

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20220131.1

### Is it regression?

20220123.1

### Expected behavior

The Databricks task should install and run successfully.

### Actual behavior

The databricks-cli package is failing to be installed on the agent via pip.

### Repro steps

Using a yaml pipeline use the following tasks to connect to Databricks and deploy some notebooks:

```
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x' 

          - task: riserrad.azdo-databricks.azdo-databricks-configuredatabricks.configuredatabricks@0
            displayName: 'Configure Databricks CLI'
            inputs:
              url: ${{ parameters.url }}
              token: $(token)

          - task: riserrad.azdo-databricks.azdo-databricks-deploynotebooks.deploynotebooks@0
            displayName: 'Deploy Notebooks to Workspace'
            inputs:
              notebooksFolderPath: '$(Agent.BuildDirectory)\DatabricksNotebooks'
              workspaceFolder: '${{ parameters.workspaceFolder }}'
```

The databricks-cli fails to install in the second task

**Comment by miketimofeev** [comment]
Hi @cjwrk!
Did you try other OS versions? The plugin seems very outdated and the documentation says it only supports Ubuntu16 (which is retired) and Windows-2016.

**Comment by cjwrk** [comment]
Hi,

I have tried with windows-2022 and it gives me the same error. When I try to use windows-2016 I get the error:
##[warning]An image label with the label windows-2016 does not exist.
,##[error]The remote provider was unable to process the request.

**Comment by miketimofeev** [comment]
@cjwrk the label is different, it's `vs2017-win2016`

**Comment by cjwrk** [comment]
Ok when using the correct label for the Windows 2016 agents it failed in the same way as the other OS versions. This was working yesterday on the old image but now the new image has been released it is breaking. Are there any changes to the image which could prevent pip from installing the databricks-cli?

This has broken our production release pipelines so could do with a fix/workaround urgently if you have one.

**Comment by miketimofeev** [comment]
@cjwrk I'm afraid we can't help here as we are not responsible for this custom task from the marketplace.
Installing `databricks-cli` directly works just fine.
```
steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.7'
  inputs:
    versionSpec: 3.7

- script: 'pip install databricks-cli'
  displayName: 'Command Line Script'

```
