### ISSUE TITLE
python-versions 3.10.2 release is missing windows files

### ISSUE THREAD

**Issue by Athanasius** [actions/virtual-environments#5023]
### Description

Whilst https://github.com/actions/python-versions/releases/tag/3.10.2-121429 added Python 3.10.2, it only has the darwin and linux files, nothing for win32.  As a consequence https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json does not, of course, have win32 entries.

Thus no GitHub workflows for Python on Windows can use 3.10.2.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/EDCD/EDMarketConnector/actions/runs/1796797978

### Expected behavior

That something like the following work in a GitHub Workflow:

```yml
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-python@v2.3.2
        with:
          python-version: "3.10.2"
          architecture: "x86"
```

### Actual behavior

```
Run actions/setup-python@v2.3.1
Version 3.10.2 was not found in the local cache
Error: Version 3.10.2 with arch x86 not found
The list of all available versions can be found here: [actions/python-versions@main/versions-manifest.json (raw)](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json)
```

### Repro steps

1.Set up a GitHub workflow including the example in 'Expected behaviour'.
2. Run it.
3. See it fail.
