### ISSUE TITLE
Different behaviors for cosmos db linux emulator on unbuntu 18 vs 20 image

### ISSUE THREAD

**Issue by DOMZE** [actions/virtual-environments#5036]
### Description

Copied from https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3010

**Describe the bug**
Using Azure DevOps and a ubuntu-latest hosted agent, when starting the container, the container returns right away the following:
```
This is an evaluation version.  There are [165] days left in the evaluation period.
Shutting Down
Shut Down
```

**Additional context**
Can't use older images ([tags](https://mcr.microsoft.com/v2/cosmosdb/linux/azure-cosmos-emulator/tags/list)) to see if the code has changes since, as it fails the evaluation time check
Is there something I can add as environment variable to get more logs out to diagnose the problem?

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Agent name: 'Hosted Agent'
Agent machine name: 'fv-az31-196'
Current agent version: '2.198.2'
Operating System
Virtual Environment
Virtual Environment Provisioner
Current image version: '20220131.1'
Agent running as: 'vsts'

### Expected behavior

The container should create the partitions and return "Started" at some point

### Actual behavior

The container exits and the logs shows
```
This is an evaluation version.  There are [165] days left in the evaluation period.
Shutting Down
Shut Down
```

### Repro steps

Create an Azure DevOps pipeline with the following:
```yaml
pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'
jobs:
- job: TestJob
  displayName: 'My Job'
  steps:
  - task: PowerShell@2
    name: showNetAdapters
    displayName: 'Show NetAdapters'
    inputs:
      pwsh: true
      targetType: inline
      script: |
        ifconfig
        $ipAddress = (hostname -I | awk '{print $1}')
        Write-Output "IpAddress = $ipAddress"
  - task: PowerShell@2
    name: startCosmosDb
    displayName: 'Start Azure Cosmos DB emulator'
    inputs:
      pwsh: true
      targetType: inline
      script: |
        $ipAddress = (hostname -I | awk '{print $1}')
        $containerId = (docker create -p 8081:8081 -p 10251:10251 -p 10252:10252 -p 10253:10253 -p 10254:10254 -m 3g --cpus=2.0 -e AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10 -e AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=false -e AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=$ipAddress mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator)
        Write-Host "##vso[task.setvariable variable=cosmosDbContainerId]$containerId"
        docker start $containerId
        Start-Sleep -Seconds 5
        $isStarted = $false
        while ($isStarted -eq $false) {
            $logs = (docker logs $containerId)
            if ($logs.Contains('Started')) {
                Write-Output "Container $containerId started."
                $isStarted = $true
                break;
            }
            Write-Output "Waiting for container $containerId to start"
            Write-Output ($logs | Out-String)
            Start-Sleep -Seconds 5
        }
  - script: |
      echo 'ContainerId = $(cosmosDbContainerId)'
      docker logs $(cosmosDbContainerId)
    displayName: Diagnostics
  - script: |
      ipAddress=$(hostname -I | awk '{print $1}')
      curl -k https://$ipAddress:8081/_explorer/emulator.pem > $(Agent.TempDirectory)/emulatorcert.crt
      sudo cp $(Agent.TempDirectory)/emulatorcert.crt /usr/local/share/ca-certificates/
      sudo update-ca-certificates
      echo "##vso[task.setvariable variable=cosmosDbEndpoint]https://$ipAddress:8081"
    displayName: 'Prepare emulator'
  - script: |
      if [ ! -z "$(cosmosDbContainerId)" ];
      then
        docker rm -f $(cosmosDbContainerId)
        sudo rm -f /usr/local/share/ca-certificates/emulatorcert.crt
      fi
    displayName: 'Clean Azure Cosmos DB emulator'
    condition: always()
```

**Comment by shilovmaksim** [comment]
Hi @DOMZE .
Thanks you for tour report. We will take a look at this.

**Comment by nikolai-frolov** [comment]
Hello @DOMZE your repro yml fails on [all environments](https://github.com/nikolai-frolov/image-testing/runs/5109295748?check_suite_focus=true) (not only on Ubuntu 20) since it incorrectly creates docker container for CosmosDB. Please use [this one guideline](https://docs.microsoft.com/en-us/azure/cosmos-db/linux-emulator?tabs=ssl-netstd21#run-on-linux) to correctly create container. These steps [work for me](https://github.com/nikolai-frolov/image-testing/runs/5111070936?check_suite_focus=true).
I'm going to close this issue since it's not related to image generation.

**Comment by DOMZE** [comment]
How does it incorrectly creates the docker container?

docker create and docker start is just docker run split in 2 commands (docker run = docker create + docker start)...
also on the official docs, they run the container in interactive mode (using `-it`), which clearly can't be done in an automated environment.
It also says after the running the container in interactive mode: After the emulator is running, _using a different terminal_, different terminal because the original terminal is blocked by TTY...

So to go back to my last point on Azure Devops (not github actions...), doing the command as you showed (docker run, results in the following error from docker):
the input device is not a TTY

which makes sense considering there's no TTY...

So just want to know, how can one work (in my azure devops agent using ubuntu 18 and not in ubuntu 20)? the SAME exact pipeline YAML?

**Comment by soenneker** [comment]
@nikolai-frolov 
The script below works (and is using the DevOps recommended Docker approach) yet if you specify `ubuntu-latest` as the image, it doesn't. You'll see that by the 'Stopping container' messages in the powershell task.

```yaml

trigger: none

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-18.04'

resources:
  containers:
  - container: azure-cosmosdb-emulator
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    ports:
    - "8081:8081"
    - "10251:10251"
    - "10252:10252"
    - "10253:10253"
    - "10254:10254"
    options: --name azure-cosmosdb-emulator -m 3g --cpus=2.0 -e AZURE_COSMOS_EMULATOR_PARTITION_COUNT=20 -e AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=false -e AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1

jobs:
- job: Job
  displayName: 'Job'

  services:
    azure-cosmosdb-emulator: azure-cosmosdb-emulator

  steps:

  - task: PowerShell@2
    name: startCosmosDb
    displayName: 'Wait for Cosmos'
    inputs:
      pwsh: true
      targetType: inline
      script: |
        $isStarted = $false
        while ($isStarted -eq $false) {
            $logs = (docker logs azure-cosmosdb-emulator)
            if ($logs.Contains('Started')) {
                Write-Output "Container $containerId started."
                $isStarted = $true
                break;
            }
            Write-Output "Waiting for container azure-cosmosdb-emulator to start"
            Write-Output ($logs | Out-String)
            Start-Sleep -Seconds 5
        }

```

**Comment by nikolai-frolov** [comment]
At the first of all, they use `-d` flag which allow to run container in background. Also [it works fine](https://github.com/nikolai-frolov/image-testing/runs/5121430059?check_suite_focus=true) without `-it` flags as well. 
```
- name: Check execution
        shell: pwsh
        run: |
          $ipaddr = ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}' | head -n 1
          docker pull mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
          docker run -d -p 8081:8081 -p 10251:10251 -p 10252:10252 -p 10253:10253 -p 10254:10254  -m 3g --cpus=2.0 --name=test-linux-emulator -e AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10 -e AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true -e AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=$ipaddr mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
          docker ps --all
```
Please double check parameters which are passed during container creation and provide the build link if it still doesn't work for you.

**Comment by soenneker** [comment]
Hi @nikolai-frolov could you give the yaml code I posted a try? It's pretty clear from there that the container is stopping immediately (and the pipeline won't complete)

**Comment by nikolai-frolov** [comment]
@soenneker it works fine on 20.04 ADO after adding of endpoint to your infinite cycle:
![image](https://user-images.githubusercontent.com/90333448/153470115-6298f454-b28a-4c00-a3d5-5fb7d4ade30b.png)
![image](https://user-images.githubusercontent.com/90333448/153470215-df5f09e4-9c5b-4945-82a1-62c8063af9ba.png)

```

trigger: none

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-20.04'

resources:
  containers:
  - container: azure-cosmosdb-emulator
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    ports:
    - "8081:8081"
    - "10251:10251"
    - "10252:10252"
    - "10253:10253"
    - "10254:10254"
    options: --name azure-cosmosdb-emulator -m 3g --cpus=2.0 -e AZURE_COSMOS_EMULATOR_PARTITION_COUNT=20 -e AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=false -e AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1

jobs:
- job: Job
  displayName: 'Job'

  services:
    azure-cosmosdb-emulator: azure-cosmosdb-emulator

  steps:

  - task: PowerShell@2
    name: startCosmosDb
    displayName: 'Wait for Cosmos'
    inputs:
      pwsh: true
      targetType: inline
      script: |
        $isStarted = $false
        $retriesCount = 10
        while ($isStarted -eq $false -or $retriesCount -ne 0) {
            $logs = (docker logs azure-cosmosdb-emulator)
            if ($logs.Contains('Started')) {
                Write-Output "Container $containerId started."
                $isStarted = $true
                break;
            }
            Write-Output "Waiting for container azure-cosmosdb-emulator to start"
            Write-Output ($logs | Out-String)
            Start-Sleep -Seconds 5
            $retriesCount--
        }
        docker ps --all
```

**Comment by nikolai-frolov** [comment]
Well, seems issue is reproducible not at all 100% cases. I will investigate this deeply.

**Comment by nikolai-frolov** [comment]
@milismsft does mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator image create logs somewhere? I can't find a reason why this container stops just after the start on ubuntu 20.04 (docker client is identical with 18.04 and it seems like compatibility issue for now)...
![image](https://user-images.githubusercontent.com/90333448/153484181-f1cb7f2c-3c67-4d77-ab4c-6bd7f2d35183.png)

**Comment by milismsft** [comment]
@nikolai-frolov did you try to execute that workload locally on a Ubuntu 20.04 Linux VM or local machine? The only issue that I'm aware of is when using the Azure DevOps pipeline configured with Ubuntu 20.04 (seems that 18.04 works just fine), and will recommend opening a support ticket with the respective Azure team.

There are no extra logs that can be retrieved at this time. The error seems to be coming from the initial setup which initializes the Windows sandbox we run the emulator under. There must be some policies or similar that are in the way of it, unfortunately without a local repro it will be a very hard thing to investigate.

**Comment by milismsft** [comment]
One more thing, the script above that checks for the emulator if it's started, that is incorrect actually. Just because the container is started/running, it does not translate into the emulator being ready to service requests. Please see our public documentation of how to verify that emulator is truly ready (i.e. check through the emulator's "explorer" link if the PEM public certificate key is available).

**Comment by nikolai-frolov** [comment]
I tried to reproduce the issue locally on VM with ubuntu-20.04 image, but without luck: every time it successfully starts a container. I used the following: 
```
$containerId = (docker create -p 8081:8081 -p 10251:10251 -p 10252:10252 -p 10253:10253 -p 10254:10254 -m 3g --cpus=2.0 -e AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10 -e AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=false -e AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1 mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator)
docker start $containerId
docker ps --all
```
When I tried to execute the same in the ADO pipeline it also passes (at least 5 pipelines pass in a row):
```
trigger: none

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-20.04'

jobs:
- job: Job
  displayName: 'Job'
  steps:
  - task: PowerShell@2
    name: startCosmosDb
    displayName: 'Wait for Cosmos'
    inputs:
      pwsh: true
      targetType: inline
      script: |
        $containerId = (docker create -p 8081:8081 -p 10251:10251 -p 10252:10252 -p 10253:10253 -p 10254:10254 -m 3g --cpus=2.0 -e AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10 -e AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=false -e AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1 mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator)
        docker start $containerId
        docker logs --timestamps --details $containerId
        docker ps --all
```
![image](https://user-images.githubusercontent.com/90333448/153573351-3280ede0-6806-4295-bce8-79f7cea3bba9.png)

On the other hand, issue still occurs during using an azure container:
```
trigger: none

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-20.04'

resources:
  containers:
  - container: azure-cosmosdb-emulator
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    ports:
    - "8081:8081"
    - "10251:10251"
    - "10252:10252"
    - "10253:10253"
    - "10254:10254"
    options: --name azure-cosmosdb-emulator -m 3g --cpus=2.0 -e AZURE_COSMOS_EMULATOR_PARTITION_COUNT=20 -e AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=false -e AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1

jobs:
- job: Job
  displayName: 'Job'

  services:
    azure-cosmosdb-emulator: azure-cosmosdb-emulator

  steps:

  - task: PowerShell@2
    name: startCosmosDb
    displayName: 'Wait for Cosmos'
    inputs:
      pwsh: true
      targetType: inline
      script: |
        $isStarted = $false
        $retriesCount = 10
        while ($isStarted -eq $false -and $retriesCount -ne 0) {
            $logs = (docker logs azure-cosmosdb-emulator)
            if ($logs.Contains('Started')) {
                Write-Output "Container $containerId started."
                $isStarted = $true
                break;
            }
            Write-Output "Waiting for container azure-cosmosdb-emulator to start"
            Write-Output ($logs | Out-String)
            Start-Sleep -Seconds 5
            $retriesCount--
        }
        docker ps --all
``` 
![image](https://user-images.githubusercontent.com/90333448/153573468-b68ede11-e55d-4997-821b-cad873090460.png)

Probably it should be investigated by owning team. I'm going to update https://github.com/microsoft/azure-pipelines-tasks/issues/15865 with my findings.
