### ISSUE TITLE
"DevToolsActivePort file doesn't exist" error when running Capybara tests using headless Chrome

### ISSUE THREAD

**Issue by stevehobbsdev** [actions/virtual-environments#506]
**Describe the bug**

I have a Rails app that uses Capybara to run some integration tests using Selenium and headless Chrome, but I get this error when the tests execute.

```
Chrome failed to start: exited abnormally.
        (unknown error: DevToolsActivePort file doesn't exist)
        (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) (Selenium::WebDriver::Error::UnknownError)
```

This is my job file (uses `ubuntu-latest`):

```yml
name: Application Build & Test
on: [push]

jobs:
  build:
    name: Build & run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.4"
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - uses: actions/cache@v1
        env:
          cache-name: gem-cache
        with:
          path: ./vendor/bundle
          key: build-${{ env.cache-name }}-${{ hashFiles('**/Gemfile.lock') }}

      - name: Build
        env:
          RAILS_ENV: test
        run: |
          sudo apt-get update && sudo apt-get -yqq install libpq-dev libsqlite3-dev
          gem install bundler:1.16.2
          bundle config set path 'vendor/bundle'
          bundle install --jobs 4 --retry 3
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Unit tests
        env:
          RAILS_ENV: test
          MAILER_TO: ${{ secrets.MAILER_TO }}
        run: |
          mkdir -p /tmp/test-results

          bundle exec rspec --format progress \
            --format RspecJunitFormatter \
            --out /tmp/test-results/rspec.xml \
            --format progress

      - name: Integration tests
        env:
          RAILS_ENV: test
          MAILER_TO: ${{ secrets.MAILER_TO }}
        run: |
          bundle exec cucumber --format junit --out /tmp/test-results/cucumber
```

This is how headless Chrome is initialized:

```ruby
Capybara.register_driver :headless_chrome do |app|
  capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(
    chromeOptions: { args: %w[headless disable-gpu no-sandbox disable-dev-shm-usage] }
  )

  Capybara::Selenium::Driver.new app,
                                 browser: :chrome,
                                 desired_capabilities: capabilities
end
```

I understand from [recent issues](https://github.com/actions/virtual-environments/issues/9) that Chromedriver is now supported by default on all images. Am I using it correctly?

**Area for Triage**: 

Ruby

**Question, Bug, or Feature?**: 
Question/bug

**Virtual environments affected**
- [ ] macOS 10.15
- [X] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Chromedriver to be available and working during my integration tests

**Actual behavior**

The error described above is received when trying to run integration tests using Selenium and headless Chrome.

The repository that I'm having trouble with is private but I am willing to add someone as a contributor to help diagnose the problem.
