### ISSUE TITLE
MinGW is no longer installed?

### ISSUE THREAD

**Issue by nagisa** [actions/virtual-environments#5065]
### Description

In the past `mingw` toolchain would be installed on `windows-latest` runners by default and was accessible like so:

```yaml
      - name: Add MSYS2 to the PATH
        run: echo "c:/msys64/bin" | Out-File -FilePath $env:GITHUB_PATH -Append
      - name: Add 32-bit mingw-w64 to the PATH
        run: echo "c:/msys64/mingw32/bin" | Out-File -FilePath $env:GITHUB_PATH -Append
        if: startsWith(matrix.target, 'i686')
      - name: Add 64-bit mingw-w64 to the PATH
        run: echo "c:/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Append
        if: startsWith(matrix.target, 'x86_64')
```

Today I found out that this is no longer the case. Listing out the files with `tree /F c:/msys64` reveals that the mingw directories are now empty:

```
2022-02-11T18:45:08.0264931Z +---mingw32
2022-02-11T18:45:08.0265381Z �   +---bin
2022-02-11T18:45:08.0265841Z �   +---etc
2022-02-11T18:45:08.0266234Z �   +---include
2022-02-11T18:45:08.0266702Z �   +---lib
2022-02-11T18:45:08.0267131Z �   +---share
2022-02-11T18:45:08.0267586Z +---mingw64
2022-02-11T18:45:08.0268068Z �   +---bin
2022-02-11T18:45:08.0268467Z �   +---etc
2022-02-11T18:45:08.0268903Z �   +---include
2022-02-11T18:45:08.0269304Z �   +---lib
2022-02-11T18:45:08.0269861Z �   +---share
```

Was this an intentional change? I believe this has started sometime between 24 days ago and today.

runner: windows-latest, not sure whichever one it is.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/rust-lang/stacker/actions/runs/1830970110

### Is it regression?

Yes, https://github.com/rust-lang/stacker/actions/runs/1173987344

### Expected behavior

MinGW should work for both i686 and x86_64.

### Actual behavior

x86_64-w64-mingw32-gcc seems to be provided by chocolatey…?

### Repro steps

List `c:/msys64/mingw{32,64}/bin`
