### ISSUE TITLE
Reproducing the Windows 2019 image

### ISSUE THREAD

**Issue by MarcDenman** [actions/virtual-environments#507]
**Describe the bug**
For various reasons we are generating our own copy of the `Windows Server 2019` image. We have found the process to be very flaky and our build of the image often fails at seemingly random points (20 minutes, 50 minutes, several hours in). A rerun of the build will go past the point of the previous failure with no changes needed.

Are you experiencing this behaviour as well or does it run well for you with no random failures? Our current best approach is running several isolated packer builds simultaneously and hoping one finishes with no errors! 

**Area for Triage**: 
Deployment/Release

**Question, Bug, or Feature?**: 
Question

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
Windows 2019 packer build runs correctly on a repeatable basis

**Actual behavior**
Random failures whilst building the Windows 2019 image.

**Comment by alepauly** [comment]
Hi @MarcDenman, thanks for reaching out! What's the rate of flakiness that you are seeing and is there any specific type of error you are seeing? We do see occasional (~1/6th of builds) failures mostly due to network issues or third-party package sources not responding. Also, are you running the builds off a cloud VM, a local box, a server? What type of network connection does it have?

**Comment by jmos5156** [comment]
In short yes. I've experienced the same and more. There are several issues already discussed in this repo from WinRM timeout, download failures, validation checks not working, to installs not completing. I'd say it's around 1/4 of all builds I do.

There are a couple of suggestions of issues with Azure but even so, this repo offers you the full bells and whistles Windows 2019 agent build which just seems to flaky to run for several hours, at cost, for it to fail. That's too much investment IMHO.

I've run this in most European Azure locations with varying levels of success.
Firstly I have trimmed down the vast numbers of installs to only what I need. I don't need several python versions, for example. I carefully review the validation steps as it annoys me that the process can fail simply because of an error in the validation process. I don't like this as it has branched me away from this repo and would prefer to remain closer to the changes seen here.

Also, watch out for dependencies between packages. This has caught me out several times.
I have resorted to running several builds each tackling a single install just to test the code. If these work individually, I will attempt a full build, but there's no guarantee it will work.

**Comment by alepauly** [comment]
> I carefully review the validation steps as it annoys me that the process can fail simply because of an error in the validation process.

@jmos5156 - Agreed! These are frustrating to say the least. To help reduce these type of failures we (finally) were able to put in place a sort of "CI" to verify all PRs prior to merging into master. 

One option to increase the likelihood of the build succeeding is to build off the latest release branch. Release branches indicate that the scripts built in production, however, since there are dependencies in packages that might have moved since then, this path is not full proof.

If it helps at all, we've had most luck building in CUS region of Azure.

**Comment by MarcDenman** [comment]
@alepauly Thanks for quick response. That is very useful to know. We are currently around a 35% failure rate. We are currently running it on both an Azure VM in UK South plus a server in our data centre while we workout where is most reliable.

We are also orchestrating via Azure Pipelines (private agents) but that doesn't seem to be causing a problem(apart from timeouts but we have fixed that!).

It is very useful to know about CUS, will try that tomorrow and see if that helps. Is there anything we can do to help make it more reliable?

I have added some errors below, a lot of the errors we have had are network related though we have had a few builds fail the same step (installing powershell core).

<details><summary>Errors</summary>

```
    vhd: The install of mingw was NOT successful.
    vhd: Error while running 'C:\ProgramData\chocolatey\lib\mingw\tools\chocolateyinstall.ps1'.
    vhd:  See log for details.
    vhd:
    vhd: Chocolatey installed 0/1 packages. 1 packages failed.
    vhd:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    vhd:
    vhd: Failures
    vhd:  - mingw (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\mingw\tools\chocolateyinstall.ps1'
```

```
    vhd: Downloading azure-cli
    vhd:   from 'https://azurecliprod.blob.core.windows.net/msi/azure-cli-2.1.0.msi'
    vhd: Progress: 93% - Saving 46.69 MB of 50.02 MBChocolatey timed out waiting for the command to finish. The timeout
    vhd:  specified (or the default value) was '2700' seconds. Perhaps try a
    vhd:  higher `--execution-timeout`? See `choco -h` for details.
    vhd: The install of azure-cli was NOT successful.
    vhd: Error while running 'C:\ProgramData\chocolatey\lib\azure-cli\tools\chocolateyInstall.ps1'.
    vhd:  See log for details.
    vhd:
    vhd: Chocolatey installed 0/1 packages. 1 packages failed.
    vhd:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    vhd:
    vhd: Failures
    vhd:  - azure-cli (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\azure-cli\tools\chocolateyInstall.ps1'.
```
```
==> vhd: Provisioning with Powershell...
==> vhd: Provisioning with powershell script: ********\virtual-environments\images\win/scripts/Installers/Install-PowershellCore.ps1
    vhd: VERBOSE: About to download package from
    vhd: 'https://github.com/PowerShell/PowerShell/releases/download/v7.0.0/PowerShell-7.0.0-win-x64.msi'
==> vhd: Quiet install failed, please rerun install without -Quiet switch or ensure you have administrator rights
==> vhd: At line:393 char:21
==> vhd: + ...             throw "Quiet install failed, please rerun install without ...
```
</details>

@jmos5156 Good to know it isn't just us, thank you. We have started trimming out the parts we don't want as well but similarly, we don't want to fork too far away from this repo. The dependencies between packages is a very good point. I would have completely missed that.

**Comment by alepauly** [comment]
@MarcDenman @jmos5156 definitely not just you two (and us). I've heard from others with similar problems. I'm hoping we can soon spend some time figuring out ways to improve on the problems we are running into while generating the image. We have ideas, it's just a matter of finding time ⌛️

**Comment by elduddz** [comment]
I don't suppose it would be possible to get a share of the image created on a SIG or even the vhd?

**Comment by jmos5156** [comment]
I know this chat has now been closed but @alepauly if there is anything that I can help with, in any small part shout out.
FYI, I ran two builds overnight. Both failed. One on a chocolately download for Azure CLI, the second on waiting for WinRM. Both in West Europe. This is frustrating to watch. On the WinRM side, I actually wait for the Packer output where is says waiting for WinRM. If I see it not continuing on for say 5-7 mins (usually it happens within a minute or two), I run these commands via the Run Command option in VM settings in the portal...

```
$Cert = New-SelfSignedCertificate -CertstoreLocation Cert:\LocalMachine\My -DnsName "$env:COMPUTERNAME"
Remove-Item -Path WSMan:\Localhost\listener\listener* -Recurse
New-Item -Path WSMan:\LocalHost\Listener -Transport HTTPS -Address * -CertificateThumbPrint $Cert.Thumbprint -Force
Stop-Service winrm
Start-Service winrm
```

FYI, we are a heavy user of Desired State Configuration (DSC). We use it for pretty much everything, from installing and configure AD, SQL, webservers, we install 3rd party products etc... and this is vastly more reliable. If it wasn't for the fact that packer wraps up the deployment, image creation and clean up all in one, I'd invest my time in refactoring this in DSC. That would obviously break me away from the community effort which I'd rather not, but assure me of a completed build at the end.

**Comment by alepauly** [comment]
@jmos5156 I'll reopen so we can continue to document the issues affecting reliably reproducing the Win2019 image and help each other find ways to improve it.

For your WinRM problem, we never see that now. We used to a while back but stopped seeing it when we changed our network configuration. For context, the machines we use to run the builds are Azure VM themselves and we found that a combination of network reliability issues and policies would often get in the way of WinRM establishing connection.

To solve this we changed the configuration so that Packer would no longer attempt to create its own vnet and instead use the vnet that we supply. That vnet is configured as a peer of the vnet where the machine running the build is, so they effectively live in the same network and there is no need to open ports to the public internet or register a public IP. For this you'll want to include the following two params in your packer call:
```
                -var "private_virtual_network_with_public_ip=false"
                -var "virtual_network_name=<your vnet name>" 
```

Note that we had to peer the vnets because of internal configs but in your case you might be able to get away with simply using the same vnet for both. Hope this helps!

**Comment by jmos5156** [comment]
So if I understand correctly you are using self-hosted agents to run the packer image building from twp peered vnets where packer is creating the image in the other. This means WinRM is working 'internally' and therefore more reliable.
If correct - I see.
Unfortunately, I don't have this setup and use Azure-hosted agents to do the heavy lifting.

**Comment by elduddz** [comment]
We attempted this build on the Azure Pipelines pool one time, but didnt know that after 6 hours the build gets cancelled 🤣 

I have had 2 parallel builds running on tin we own in the same building as us. from there I was able to run 2 builds, one to UKSouth and the other using Central US and see which wins. The UK south crashed out after getting the toolcache. the Central US one completed.

I was wondering if the validation could call back to the installer on error to have another go.

my UKS falls over on the powershell-core get which uses an aka link. I converted this to a chocolatey install and added a bit more defence around it (see below).

The problem with packer is that after the build fails you get nothing useful, the image might be corrupted, and in the case of a managed disk, I am not sure you get anything useable.

```powershell
function Install-Choco {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$install,
        [int]$retries = 5
    )

    begin { }
    process {
        $condition = $false
        $count = 0
        do {
            Write-Output "running: powershell choco install $install -y"
            powershell choco install $install -y

            $installed = powershell choco list -lo $install --all
            $match = (($installed -match "^$install.*").Length -ne 0)
            if ($match) {
                Write-Output "package installed: $install"
                $condition = $true
            }
            else {
                $count++
                if ($count -eq $retries) {
                    Write-Error "Could not install $install after $count attempts"
                    exit 1
                }
            }
        } while ($condition -eq $false)
    }
    end { }
}
```

this doesnt handle the more complete choco's yet, and if you install a package with this name as a part of it, it would give a false positive, but deals with the basic install -y setup ok.

doing this and using choco for powershell core actually helped that element successfully install.

**Comment by elduddz** [comment]
Both cus and suk failed after hitting Wix install. Not had this before.

```
azure-arm: Chocolatey v0.10.15
    azure-arm: Installing the following packages:
    azure-arm: wixtoolset
    azure-arm: By installing you accept licenses for the packages.
    azure-arm: wixtoolset not installed. An error occurred during installation:
    azure-arm:  The operation has timed out
    azure-arm: wixtoolset package files install completed. Performing other installation steps.
    azure-arm: The install of wixtoolset was NOT successful.
    azure-arm: wixtoolset not installed. An error occurred during installation:
    azure-arm:  The operation has timed out
    azure-arm:
    azure-arm: Chocolatey installed 0/1 packages. 1 packages failed.
    azure-arm:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    azure-arm:
    azure-arm: Failures
    azure-arm:  - wixtoolset (exited 1) - wixtoolset not installed. An error occurred during installation:
    azure-arm:  The operation has timed out
```

Adding script mentioned above and trying again.

**Comment by elduddz** [comment]
just reiteration of the intermittent nature of the internet, this was a new extension added for the 20200308.0 release

```
_work\45\s\virtual-environments\images\win/scripts/Installers/Windows2019/Install-AnalysisExtenstion.ps1
    azure-arm: Downloading Microsoft.DataTools.AnalysisServices.vsix extension
==> azure-arm: Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (429)."
==> azure-arm: At C:\Windows\Temp\script-5e6732ed-391b-0775-6ef9-1c4750aefbc9.ps1:10 char:1
    azure-arm: Installing Microsoft.DataTools.AnalysisServices.vsix extension
==> azure-arm: + (New-Object System.Net.WebClient).DownloadFile($extensionUrl, $extens ...
==> azure-arm: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
==> azure-arm:     + FullyQualifiedErrorId : WebException
==> azure-arm:
    azure-arm: Unsuccessful exit code returned by the installation process: 2001.
==> azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...
==> azure-arm: 
==> azure-arm: Cleanup requested, deleting resource group ...
==> azure-arm: Resource group has been deleted.
Build 'azure-arm' errored: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]
```

**Comment by elduddz** [comment]
Another
```
_work\47\s\virtual-environments\images\win/scripts/Installers/Install-AzureCli.ps1
    azure-arm: Chocolatey v0.10.15
    azure-arm: Installing the following packages:
    azure-arm: azure-cli
    azure-arm: By installing you accept licenses for the packages.
    azure-arm: Progress: Downloading azure-cli 2.2.0... 100%
    azure-arm:
    azure-arm: azure-cli v2.2.0 [Approved]
    azure-arm: azure-cli package files install completed. Performing other installation steps.
    azure-arm: Downloading azure-cli
    azure-arm:   from 'https://azurecliprod.blob.core.windows.net/msi/azure-cli-2.2.0.msi'
    azure-arm: Progress: 84% - Saving 42.63 MB of 50.25 MBChocolatey timed out waiting for the command to finish. The timeout
    azure-arm:  specified (or the default value) was '2700' seconds. Perhaps try a
    azure-arm:  higher `--execution-timeout`? See `choco -h` for details.
    azure-arm: The install of azure-cli was NOT successful.
```
