### ISSUE TITLE
Unmet dependencies when installing wine32 on ubuntu-latest (ubuntu-20.04)

### ISSUE THREAD

**Issue by FreeSlave** [actions/virtual-environments#5077]
### Description

When trying to install wine32 on ubuntu-latest (ubuntu-20.04) I get the following error from `apt`:
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 wine32:i386 : Depends: libwine:i386 (= 5.0-3ubuntu1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Shell command that I tried to install wine32:
```
sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt install wine32
```

I've just tried the same in docker image of ubuntu-20.04 and had no errors. So it's probably some problem with repos or apt configuration in the image that github uses.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Environment: ubuntu-20.04
Version: 20220207.1

[Link to the example of broken build](https://github.com/FreeSlave/github-workflow-test/runs/5199440932?check_suite_focus=true)

### Repro steps

Start a workflow on ubuntu-latest that installs wine32 on some step. Example:
```
name: build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Install wine32
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt install wine32 --fix-broken --install-recommends --install-suggests
```
