### ISSUE TITLE
Visual studio build is stuck

### ISSUE THREAD

**Issue by jyeros** [actions/virtual-environments#5178]
### Description

I am trying to build an .msi file using VisualStudio. The build looks like is finishing (because the logs), but the command is stuck. I tested the same script inside the run with with the same version of the VisualStudio `17.1.32210.238` and the powershell `7.1.2` and it worked fine. 

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Version: 20220227.1
BuildLink: https://github.com/jyeros/VSTestInstaller/runs/5419050077

### Repro steps

The steps to reproduce the issue are in this [workflow file](https://github.com/jyeros/VSTestInstaller/blob/4047a31adf0d667cb6dbf96c6d013f2d276fed99/.github/workflows/win-release.yaml).

Create a step with two lines:
1. Env assignment
2. Build sln with VisualStudio.

If the env assignment is removed, then it works. See [build](https://github.com/jyeros/VSTestInstaller/runs/5419113819) based on https://github.com/jyeros/VSTestInstaller/commit/354033d201de08122ac934718b7ec4466acc3996

**Comment by nikolai-frolov** [comment]
Hello @jyeros, this is a known issue with devenv tool on Visual Studio 2022 (https://developercommunity.visualstudio.com/t/Visual-Studio-2022-devenvcom-task-goes/1644249), so unfortunately we can't assist here since it's external for us. As a workaround we can suggest you to use msbuild instead: it allows restore packages and build project much faster and it's already available in Windows images. Example:
```
steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: msbuild restore
      shell: cmd
      run: |
        msbuild /t:restore "%SLN_PATH%"
    - name: compile debug
      shell: cmd
      run: |
        msbuild "%SLN_PATH%" /p:Configuration=Debug
    - name: compile release
      shell: cmd
      run: |
        msbuild "%SLN_PATH%" /p:Configuration=Release
```
