### ISSUE TITLE
Azure Pipelines NuGet task not using stated versions of NuGet on either windows-2019 or -2022 images

### ISSUE THREAD

**Issue by AtOMiCNebula** [actions/virtual-environments#5220]
### Description

The image readmes list much newer versions of NuGet than are actually used by the Azure Pipelines NuGet tasks.  This caused a pipeline break when we recently tried to move a pipeline from windows-2019 to windows-2022, though when we looked closer, both images have issues.

NuGet versions:
* Windows Server 2019 (Version 20220306.1)
  * script task: 6.1.0.106 (same as [readme](https://github.com/actions/virtual-environments/blob/win22/20220306.1/images/win/Windows2019-Readme.md#package-management))
  * NuGet@2(.198.0) task: 5.8.0
* Windows Server 2022 (Version 20220306.1)
  * script task: 6.1.0.106 (same as [readme](https://github.com/actions/virtual-environments/blob/win22/20220306.1/images/win/Windows2022-Readme.md#package-management))
  * NuGet@2(.198.0) task: 4.1.0

It's not clear to me whether this is an issue with the agent image or the task; either the agent scripts aren't installing NuGet where the NuGet task expects to find it, or the task is finding an older version than what is placed in the system.  Starting with agent image folks to start.

This appears to be related to #4754, which was closed too quickly. ☹️ 

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20220306.1

### Is it regression?

No

### Expected behavior

Agent image and NuGet task both agree on a (modern) version of NuGet to use

### Actual behavior

Agent image and NuGet tasks do not agree, and windows-2022 image ends up using an older version of NuGet than the windows-2019 image, which can cause functional regressions when pipelines upgrade to new images.

### Repro steps

Azure Pipelines YAML (also repros from Designer pipelines):
```yaml
pool:
  vmImage: windows-2022 # or windows-2019
steps:
- task: NuGetCommand@2
  displayName: 'NuGet@2: custom-help'
  inputs:
    command: custom
    arguments: help

- script: 'nuget help'
  displayName: 'script: nuget help'
```

Observe that versions displayed by each task do not match.
