### ISSUE TITLE
[Ubuntu 20.04] Apt update, focal InRelease' changed its 'Origin' value

### ISSUE THREAD

**Issue by mimartin12** [actions/virtual-environments#5237]
### Description

Ubuntu runners across projects are experiencing issues when running `apt update`. 
Currently it's throwing this error.

```
W: Conflicting distribution: [packages.microsoft.com/ubuntu/20.04/prod](https://packages.microsoft.com/ubuntu/20.04/prod) focal InRelease (expected focal but got testing)
E: Repository '[packages.microsoft.com/ubuntu/20.04/prod](https://packages.microsoft.com/ubuntu/20.04/prod) focal InRelease' changed its 'Origin' value from 'microsoft-ubuntu-focal-prod focal' to 'microsoft-ubuntu-focal-prod testing'
E: Repository '[packages.microsoft.com/ubuntu/20.04/prod](https://packages.microsoft.com/ubuntu/20.04/prod) focal InRelease' changed its 'Label' value from 'microsoft-ubuntu-focal-prod focal' to 'microsoft-ubuntu-focal-prod testing'
E: Repository '[packages.microsoft.com/ubuntu/20.04/prod](https://packages.microsoft.com/ubuntu/20.04/prod) focal InRelease' changed its 'Codename' value from 'focal' to 'testing'
Error: Process completed with exit code 100.
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20220227.1
Build Link: https://github.com/bitwarden/browser/runs/5559962459?check_suite_focus=true#step:3:42

### Is it regression?

No

### Expected behavior

Jobs should complete as they have been.
https://github.com/bitwarden/browser/runs/5559561569?check_suite_focus=true#step:3:1

### Actual behavior

Jobs fail during `apt update` tasks.

### Repro steps

Run a workflow with this job
```yaml
jobs:
  cloc:
    name: CLOC
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Set up cloc
        run: |
          sudo apt update
          sudo apt -y install cloc
      - name: Print lines of code
        run: cloc --include-lang TypeScript,JavaScript,HTML,Sass,CSS --vcs git
```
