### ISSUE TITLE
/bin/sh: jq: command not found

### ISSUE THREAD

**Issue by kceb** [actions/virtual-environments#526]
**Describe the bug**

Some of my macOS builds just recently started failing because I am reliant on `jq` for some of my steps. It seems like it should still be included: https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md

Did it not get added to PATH? Did jq get removed?

**Area for Triage**: Apple

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
`jq` commands should work out of the box

**Actual behavior**

I get `/bin/sh: jq: command not found` error when using `jq` on macOS. Same command works as expected on ubuntu.

**Comment by miketimofeev** [comment]
Hi @kceb! I can't repro it, this works just fine for me. 
```
name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Check jq
      run: |
        jq --version
      shell: bash

```
Could you provide some more details about how your run looks like?
