### ISSUE TITLE
Failed test in GitHub Actions when local test run on my Mac works well

### ISSUE THREAD

**Issue by bigMOTOR** [actions/virtual-environments#531]
**Describe the bug**
I have failed test in GitHub Actions and have no idea where to dig because the local test runs on my Mac well with success result. I use Combine on lates MacOS, maybe this is the reason.
But I consider it as a bug because I believe local and CI’s MacOS behavior should be the same.
```
Error:2020-03-06 08:59:53.328 xcodebuild[1366:11971] [MT] IDEResultKit: Warning: While writing a result bundle to /Users/runner/Library/Developer/Xcode/DerivedData/AirConnect-aokmlrgaakifmbgovglpmzlxlfhq/Logs/Test/Run-AirConnect-2020.03.06_08-59-13-+0000.xcresult, not all contents have been imported, as the Staging directory still contains the following files/directories: ["2_Test"]630Testing failed:631632Test session results, code coverage, and logs:633/Users/runner/Library/Developer/Xcode/DerivedData/AirConnect-aokmlrgaakifmbgovglpmzlxlfhq/Logs/Test/Run-AirConnect-2020.03.06_08-59-13-+0000.xcresult634635AirConnectTests:636AirConnect.app (1668) encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted. (Underlying error: Crash: AirConnect (1668): Namespace SIGNAL, Code 0x4))637638** TEST FAILED **639640Testing started on 'My Mac'641##[error]Process completed with exit code 65.
```

**Area for Triage**: 

contains: 'Apple'
addLabels: ['Area: Apple']
assign: ['sergey-akhalkov']

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [+] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by al-cheb** [comment]
Hello, @bigMOTOR 
Could you please provide steps to reproduce the issue?

**Comment by bigMOTOR** [comment]
Hi @al-cheb,
It's quite difficult to provide STR because they are just "run the action on this particular repo", but this repo is private. I tried to copy some pieces of this code, but the issue didn't reproduce there.
So I suggest that the simplest solution will be - just invite a person who will be assigned for this task into my repo. Does it work for you?

**Comment by bigMOTOR** [comment]
@al-cheb btw
Is it correct a workflow to run the tests under MacOS on GitHub env:
```
name: Swift MacOS - Build and Run tests

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: |
          xcodebuild clean test -project AirConnect.xcodeproj -scheme AirConnect -destination 'platform=OS X,arch=x86_64' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        
```

**Comment by al-cheb** [comment]
@bigMOTOR 
Could you please provide logs with --verbose parameter?

**Comment by bigMOTOR** [comment]
@al-cheb please take a look: [AirConnect Actions Log](https://gist.github.com/bigMOTOR/51e03ebee420c5d8aacc4977ae79393e)

**Comment by al-cheb** [comment]
@bigMOTOR 
Try to add env variable at a buildind step:
```
 env:
       FASTLANE_EXPLICIT_OPEN_SIMULATOR : "2"
```

**Comment by bigMOTOR** [comment]
@al-cheb Thanks for your help!
I tried. Unfortunately it doesn't help.
```
name: Swift MacOS - Build and Run tests

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        env: 
          FASTLANE_EXPLICIT_OPEN_SIMULATOR: "2"
        run: |
          xcodebuild clean test -project AirConnect.xcodeproj -scheme AirConnect -destination 'platform=OS X,arch=x86_64' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -verbose
```
