### ISSUE TITLE
Runner Version Update for Ubuntu causes conda stalling

### ISSUE THREAD

**Issue by mrmundt** [actions/virtual-environments#5363]
### Description

The default runner version updated from 2.289.1 -> 2.289.2 sometime in the last few days. After the update, any of our actions which utilize conda/miniconda + ubuntu are stalling. These jobs had no issue before, but something about the new environment causes conda to stall forever (with no useful errors), eventually failing due to job timeout limits.

Previously passing action: https://github.com/Pyomo/pyomo/runs/5859040336?check_suite_focus=true
Now failing action: https://github.com/Pyomo/pyomo/runs/5859238370?check_suite_focus=true

I have also reported this issue to conda ([Issue 11401](https://github.com/conda/conda/issues/11401))

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Current runner version: '2.289.2'
Operating System
  Ubuntu
  20.04.4
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20220330.0
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20220330.0/images/linux/Ubuntu2004-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220330.0
Virtual Environment Provisioner
  1.0.0.0-main-20220325-1
```

### Is it regression?

2.289.1 (Link provided in description)

### Expected behavior

Conda installations should still work - or at least error more helpfully (though that is likely a request for the conda side).

### Actual behavior

Conda installations do not work and seemingly stall/get stuck forever.

### Repro steps

Set up a job using either `ubuntu-latest` or `ubuntu-18.04` and utilize the following options:
```
os: ubuntu-18.04
python: 3.9
PYENV: conda
```
Then set up conda:
```
    - name: Set up Miniconda Python ${{ matrix.python }}
      if: matrix.PYENV == 'conda'
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python }}
```
Then try to install anything using conda:
```
$ conda install -q -y -c conda-forge wheel mpi4py openmpi  ply coverage pytest pytest-parallel parameterized pybind11 Sphinx>2 sphinx-copybutton sphinx_rtd_theme>0.5 sphinxcontrib-jsmath sphinxcontrib-napoleon numpy dill ipython matplotlib networkx numpy openpyxl pint python-louvain pyyaml sympy xlrd casadi numdifftools pandas scipy seaborn 

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
```

**Comment by mrmundt** [comment]
Just an additional note, @al-cheb - I tried to install a much smaller list of packages (`wheel` by itself, for example - an extremely common package) and still ran into the issue. So no need for a complex or long list of packages.

**Comment by al-cheb** [comment]
@mrmundt,

I created a simple workflow:

```
    runs-on: ubuntu-latest
    steps:
      - name: Set up Miniconda Python 3.9
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9
      - run: |
          conda install -q -y -c conda-forge wheel
```

![image](https://user-images.githubusercontent.com/47745270/162394559-47f281cb-7d2b-4045-89b0-ff15b1d26532.png)
