### ISSUE TITLE
Build with DotNetCoreCLI@2 stopped working on win2022, works on 2019

### ISSUE THREAD

**Issue by abatishchev** [actions/virtual-environments#5372]
### Description

More details at https://github.com/microsoft/azure-pipelines-tasks/issues/16099.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

```
Agent name: 'Hosted Agent'
Agent machine name: 'WIN-PN73OOGFNP6'
Current agent version: '2.202.0'
Operating System
Virtual Environment
Virtual Environment Provisioner
Current image version: '20220330.1'
```

Failed build: https://dev.azure.com/abatishchev/OpenSource/_build/results?buildId=984&view=results
Succeeded build after rolling back to win2019: https://dev.azure.com/abatishchev/OpenSource/_build/results?buildId=986&view=results

### Is it regression?

Yes

### Expected behavior

Build succeeds.

### Actual behavior

Build fails with error:

> CSC : error CS0006: Metadata file 'D:\mscorlib.dll' could not be found [D:\a\1\s\src\JWT\JWT.csproj]

### Repro steps

```yml
pool:
  vmImage: windows-latest

steps:
- task: UseDotNet@2
  displayName: 'Install .NET 6.0.x'
  inputs:
    packageType: sdk
    version: '6.0.x'
    installationPath: '$(Agent.ToolsDirectory)/dotnet'

- task: NuGetCommand@2
  displayName: 'Restore NuGet packages for .NET Framework'
  inputs:
    command: 'restore'
    restoreSolution: $(solution)

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '-c $(buildConfiguration) --no-restore'

```
