### ISSUE TITLE
Strawberry perl openssl broken on Windows

### ISSUE THREAD

**Issue by hbuckle** [actions/virtual-environments#547]
**Describe the bug**
Since making strawberry perl the default openssl no longer works

```yaml
jobs:
  - job: job1
    pool:
      vmImage: windows-latest
    steps:
      - pwsh: |
          $ErrorView = "NormalView"
          Get-Command openssl
          & openssl req -x509 -nodes -days 100000 -newkey "rsa:2048" -keyout key.pem -out key.public -subj "/CN=test"
```

```
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     openssl.exe                                        1.1.1.3    C:\Strawberry\c\bin\openssl.exe
Can't open C:/Strawberry/c/ssl/openssl.cnf for reading, No such file or directory
5320:error:02001003:system library:fopen:No such process:crypto/bio/bss_file.c:72:fopen('C:/Strawberry/c/ssl/openssl.cnf','r')
5320:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:79:
Generating a RSA private key
..........+++++
.............+++++
writing new private key to 'key.pem'
-----
unable to find 'distinguished_name' in config
problems making Certificate Request
5320:error:0E06D06A:configuration file routines:NCONF_get_string:no conf or environment variable:crypto/conf/conf_lib.c:270:
```

**Virtual environments affected**
- [x] Windows Server 2019

**Expected behavior**
The strawberry perl openssl should not be on the path, the path should contain C:\Program Files\OpenSSL\bin\openssl.exe
