### ISSUE TITLE
macOS cant run most of Apple Scripts because of UI block

### ISSUE THREAD

**Issue by Shchvova** [actions/virtual-environments#553]
**Describe the bug**

I'm trying to build a DMG using GitHub actions, but it involves popular tool [create_dmg](https://github.com/andreyvit/create-dmg) which utilizes Apple Script.
Problem is, it shows up a request for permissions, which one doesn't even have to be admin to accept. But since 

<img width="532" alt="image" src="https://user-images.githubusercontent.com/130387/76631402-9e099680-657c-11ea-9610-0cc140a6f02b.png">

```sh
# this resets granted permissions, if you want to test it locally. No sudo required.
# tccutil reset AppleEvents
# simple script to close all finder windows. In GitHub action this will timeout
osascript -e 'tell application "Finder" to close windows'
```

**Area for Triage**: 
Scripting and command line
Apple

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
OSAScripts to execute instantly.
One doesn't have to be an admin to allow this, just regular user. Also, once allowed, it will keep the behaviour. May be include this permissions in base image?

**Actual behavior**
It fails because of timeout, waiting for the GUI. No one there to click the button. This just sad.
[Here](https://github.com/Shchvova/plugin-sample/actions/runs/55096684) is example of failing action
```yml
name: OSA Script Failure
on: push
jobs:
  fail:
    runs-on: macos-latest
    steps:
      - run: osascript -e 'tell application "Finder" to close windows'
```
It  may seem like this is related to the #113, but Full Disk Access is much more dramatic permission to ask, and with full disk access, indeed, one can change contents of the TCC.db, which is sqlite3 database containing permissions, with lots of hacks. But this is rather sub-case, requiring way less intrusion into the OS.

**Comment by Shchvova** [comment]
For my specific case I solved the issue with using another tool, https://github.com/sindresorhus/create-dmg

**Comment by maxim-lobanov** [comment]
@Shchvova , thank you for your report and fix.
Unfortunately, we didn't have a chance to provide quick workaround for this issue because of the enabled SIP on Hosted macOS images. It prevents modifying system files and this issue can't be resolved in runtime.

We are looking at the ways to solve this problem globally but not solution and ETA for now.

**Comment by Shchvova** [comment]
That’s alright. To be honest, ability to build open source macOS Apps for free in such a comfortable way is amazing by itself.

**Comment by paulz** [comment]
We are experiencing the same issue. Please allow running osascript for Mac actions.

Currently the image starts with open Finder windows and some of them are blocking our UI tests.
When we try to close Finder windows we get this error.

```
Run osascript -e 'tell application "Finder" to close every window'
29:47: execution error: Finder got an error: AppleEvent timed out. (-1712)
##[error]Process completed with exit code 1.
```

**Comment by miketimofeev** [comment]
@Shchvova @paulz we've added support for running Apple Scripts on the system. The changes will be deployed next week.
Thank you!

**Comment by paulz** [comment]
Thank you, so much @miketimofeev! We temporarily went to hosted action and looking forward to return back to GitHub virtual environments. Apple Scripts are huge help for us in macOS test automation.

**Comment by miketimofeev** [comment]
Unfortunately, we have found another issue with Apple Script on macOS 10.15 so the fix won't be included in the next week's VM image.

**Comment by paulz** [comment]
Thank you, we have a workaround for now to close Finder without Apple Script:
```
# Close Finder
launchctl unload /System/Library/LaunchAgents/com.apple.Finder.plist
# Close Notification window
killall UserNotificationCenter || true
```
as suggested here: https://github.com/actions/virtual-environments/issues/977#issuecomment-639087879

But we need Apple Script for other tasks in the UI Tests, especially to ability to control other applications. It would be great if osascript would be in the whitelist for Privacy in particular for Screen Recording and Accessibility. Or if we can control Security & Privacy settings or have SIP disabled image.

**Comment by miketimofeev** [comment]
@Shchvova @paulz the image with Apple Script support has been successfully deployed. This works fine now:
```
  set -e
  echo "tell application \"System Events\"
  click at {123,456}
  end tell
  " > b.scpt
  osascript b.scpt
  shell: /bin/bash -e {0}
group 1 of scroll area 1 of application process Finder
```
I'm going to close the issue, but feel free to contact us if you have any concerns.
Thank you!

**Comment by paulz** [comment]
Trying to run the Apple Script even with sudo
```
  sudo osascript -e 'tell application "Finder" to close windows' || true
```

I am getting timeout error:
> execution error: Finder got an error: AppleEvent timed out. (-1712)

https://github.com/sparta-science/MacSwitchActivation/runs/792253844?check_suite_focus=true#step:3:4

@miketimofeev do you have a link to successful run of an apple script?

**Comment by miketimofeev** [comment]
@paulz here it is
https://github.com/miketimofeev/actionstest/runs/792596066?check_suite_focus=true
But I've tried `sudo osascript -e 'tell application "Finder" to close windows'` and it didn't work because of another permission request
![image](https://user-images.githubusercontent.com/48208649/85225732-c99de780-b3db-11ea-9c4f-a42767b0d17b.png)

**Comment by miketimofeev** [comment]
@paulz I've succeeded in finding the necessary permissions, a new VM image will be deployed next week. The following workaround can be used until then
```
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: test osa
        shell: bash
        run: |
          sqlite3 "/Users/runner/Library/Application Support/com.apple.TCC/TCC.db" "insert into access (service, client, client_type, allowed, prompt_count, indirect_object_identifier_type, indirect_object_identifier) values ('kTCCServiceAppleEvents', '/bin/bash', 1, 1, 1, 0, 'com.apple.finder')"
          osascript -e 'tell application "Finder" to close windows'
```

**Comment by paulz** [comment]
it worked! 
https://github.com/sparta-science/connect/runs/802016625?check_suite_focus=true#step:3:3
Thank you, @miketimofeev!

How would can we check if new image has been deployed?

Would we see a new version in the setup job step?
What we have there now is:
```
  Environment: macos-10.15
  Version: 20200610.3
```

**Comment by miketimofeev** [comment]
@paulz we're currently deploying this vm image, which doesn't include related changes:
https://github.com/actions/virtual-environments/releases/tag/macos-10.15%2F20200618.1
I'll notify you when the fixed VM image is deployed.

**Comment by miketimofeev** [comment]
@paulz @Shchvova The 10.15 image with the fix has been deployed, however, AzDO 10.14 macOS image will be fixed in next week's deployment so I'm going to leave this issue open for one more week.

**Comment by paulz** [comment]
Thank you, 🙏, confirming it works for me now:

on the new version of the Virtual Environment:

> Virtual Environment
>   Environment: macos-10.15
>   Version: 20200625.2


 **Version: 20200625.2**
https://github.com/sparta-science/MacSwitchActivation/runs/835626937?check_suite_focus=true#step:3:2
run successfully executing this apple script:

> sudo osascript -e 'tell application "Finder" to close windows'

 **Version: 20200610.3**
was failing with timeout error:
https://github.com/sparta-science/MacSwitchActivation/runs/835612190?check_suite_focus=true#step:3:4
> 29:42: execution error: Finder got an error: AppleEvent timed out. (-1712)

Hard to notice, but when we rerun previous failure it's still runs on the old image. 
https://github.com/sparta-science/MacSwitchActivation/runs/835626937?check_suite_focus=true#step:1:8
and reports it did run days ago. Is it how it supposed to look? Or is there another view of all runs of a particular commit?

**Comment by miketimofeev** [comment]
@Shchvova @paulz apple script works on both GitHub actions and AzDO. I'm going to close the issue, but feel free to contact us if you have any concerns.
Thank you!

**Comment by mitm001** [comment]
I am hitting same issue running java jpackage from an AdoptOpenJDK install with the github runner.

```
 Current runner version: '2.273.0'
Operating System
  Mac OS X
  10.15.6
  19G2021
Virtual Environment
  Environment: macos-10.15
  Version: 20200829.1
  Included Software: https://github.com/actions/virtual-environments/blob/macos-10.15/20200829.1/images/macos/macos-10.15-Readme.md
```
```
2020-09-03 00:48:36.975 diskimages-helper[1172:8455] _postflightMountPointsAfterDAMount: disk2 aborting because no mount point found.
/dev/disk2          	GUID_partition_scheme          	
/dev/disk2s1        	Apple_HFS                      	/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/jdk.incubator.jpackage6368649391411397710/images/packit
Running [/usr/bin/SetFile, -c, icnC, /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/jdk.incubator.jpackage6368649391411397710/images/packit/.VolumeIcon.icns]
Running [/usr/bin/SetFile, -a, C, /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/jdk.incubator.jpackage6368649391411397710/images/packit]
Running [osascript, /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/jdk.incubator.jpackage6368649391411397710/config/packit-dmg-setup.scpt]
/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/jdk.incubator.jpackage6368649391411397710/config/packit-dmg-setup.scpt:60:109: execution error: Finder got an error: AppleEvent timed out. (-1712)
java.io.IOException: Command [osascript, /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/jdk.incubator.jpackage6368649391411397710/config/packit-dmg-setup.scpt] exited with 1 code
	at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.Executor.executeExpectSuccess(Executor.java:73)
	at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.IOUtils.exec(IOUtils.java:179)
	at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.IOUtils.exec(IOUtils.java:150)
	at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.MacDmgBundler.buildDMG(MacDmgBundler.java:348)
	at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.MacDmgBundler.bundle(MacDmgBundler.java:75)
	at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.MacDmgBundler.execute(MacDmgBundler.java:451)
	at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.Arguments.generateBundle(Arguments.java:641)
	at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.Arguments.processArguments(Arguments.java:514)
	at jdk.incubator.jpackage/jdk.incubator.jpackage.main.Main.execute(Main.java:97)
	at jdk.incubator.jpackage/jdk.incubator.jpackage.main.Main.main(Main.java:51)
```

**Comment by hendriks73** [comment]
Hi,

I'm using

```
sqlite3 "/Users/runner/Library/Application Support/com.apple.TCC/TCC.db" "insert into access (service, client, client_type, allowed, prompt_count, indirect_object_identifier_type, indirect_object_identifier) values ('kTCCServiceAppleEvents', '/bin/bash', 1, 1, 1, 0, 'com.apple.Photos')"
```

before running AppleScripts against the Photos.app, but pretty much regardless what I run, I always get a timeout (on `macos-latest`).

```
NSAppleScriptErrorAppName = Photos;
NSAppleScriptErrorBriefMessage = "AppleEvent timed out.";
NSAppleScriptErrorMessage = "Photos got an error: AppleEvent timed out.";
NSAppleScriptErrorNumber = "-1712";
NSAppleScriptErrorRange = "NSRange: {34, 6}";
```

Is it possible that the Photos.app is caught in some sort of "run for the first time" modal dialog and therefore does not react to AppleScripts?

Thanks.

**Comment by miketimofeev** [comment]
Hi @hendriks73!
Yes, it's possible. If you are able to provide the AppleScript failing on the execution then we can try it on the VM and see what the exact pop-up it is.

**Comment by hendriks73** [comment]
Cool. Please see https://github.com/hendriks73/applescriptphotosworkflow Thank you!

**Comment by hendriks73** [comment]
This is just for demo purposes:

```
jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Attempt to call stuff on Photos via AppleScript
        shell: bash
        # Manipulate TCC, see https://github.com/actions/virtual-environments/issues/553#issuecomment-648109166
        # in order to allow AppleScript automation of Photos.app
        run: |
          sqlite3 "/Users/runner/Library/Application Support/com.apple.TCC/TCC.db" "insert into access (service, client, client_type, allowed, prompt_count, indirect_object_identifier_type, indirect_object_identifier) values ('kTCCServiceAppleEvents', '/bin/bash', 1, 1, 1, 0, 'com.apple.Photos')"
          osascript -e "tell application \"Photos\" to return albums"
```
