### ISSUE TITLE
MySQL service unavailable on ubuntu-18.04

### ISSUE THREAD

**Issue by milanaleksic** [actions/virtual-environments#576]
**Describe the bug**
We were using for some weeks already MySQL server on `ubuntu-18.04` without any issues. It seems that since recently MySQL does not work correctly or that something has changed slightly, enough to cause issues

**Area for Triage**: 

```
jobs:
  backend-tests:
    name: Run backend tests
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Setup MySQL
        run: mysql -u root -proot < .github/mysql-init/0_init.sql
```

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**

Runner version: '2.165.2'

```
Run mysql -u root -proot < .github/mysql-init/0_init.sql
  mysql -u root -proot < .github/mysql-init/0_init.sql
  shell: /bin/bash -e {0}
  env:
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.242/x64
    JAVA_HOME_8.0.242_x64: /opt/hostedtoolcache/jdk/8.0.242/x64
mysql: [Warning] Using a password on the command line interface can be insecure.
```

**Actual behavior**

Runner version: '2.165.2'

```
Run mysql -u root -proot < .github/mysql-init/0_init.sql
  mysql -u root -proot < .github/mysql-init/0_init.sql
  shell: /bin/bash -e {0}
  env:
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.242/x64
    JAVA_HOME_8.0.242_x64: /opt/hostedtoolcache/jdk/8.0.242/x64
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
##[error]Process completed with exit code 1.
```

1. Why did all of a sudden mysqld.sock became unavailable 13th and 16th March 2020?
