### ISSUE TITLE
Suddenly half supported WSL 2 breaks workflows

### ISSUE THREAD

**Issue by Vampire** [actions/virtual-environments#5760]
### Description

I have a daily running CI for all sorts of combinations for my https://github.com/Vampire/setup-wsl action. These tests started to fail today after you deployed the latest windows-2022 image yesterday and today my users started to complain too.

While the documentation of the `windows-2022` build states that still just WSL 1 is supported, it seems suddenly this changed to having halfway WSL 2 support, but without the necessary kernel installed.

This breaks workflows out there as the Linux distributions fail to install now.

Was this an intended, just not documented change and I need to compensate in my action?
Was this an unintended change you are going to revert / fix?
Was this a half-way change and you improve on it for example by installing the missing kernel by default?
...?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image version: 20220614.0
Build: https://github.com/Vampire/setup-wsl/actions/runs/2505987309

### Is it regression?

yes, latest working version: 20220607.3, latest working build: https://github.com/Vampire/setup-wsl/actions/runs/2499049305

### Expected behavior

Does not suddenly break

### Actual behavior

Suddenly breaks

### Repro steps

```yaml
    runs-on: windows-2022
    ...
    steps  
      - name: Setup WSL for tarantool
        uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu-20.04
```
