### ISSUE TITLE
Regression in handling of matrix variables on MacOS

### ISSUE THREAD

**Issue by solodon4** [actions/virtual-environments#584]
**Describe the bug**
A matrix job that was explicitly excluded is still being ran (starting March 17, 2020) and fails unable to resolve one of the variables in the matrix (see detailed description below).

**Area for Triage**: Apple

**Bug**

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
An expected behavior would be what was happening before March 17: macos-latest job shouldn't have been ran or listed at all since it was explicitly excluded from the run.

**Actual behavior**
I have a very simple [CI matrix](https://github.com/solodon4/Boost-for-Android/blob/master/.github/workflows/ci.yml#L8-L19) that I have embedded into one of my open source forks to demonstrate this bug. The matrix has 2 regular dimensions *os* and *flavor*:
```
        os: [ubuntu-latest,macos-latest]
        flavor: [Debug]
```
and then one dependent variable *variation* embedded via include directive:
```
        include:
          # includes a new variable of 'variation' for each host os
          - os: ubuntu-latest
            variation: linux
          - os: macos-latest
            variation: mac
```
We then exclude macos-latest via exclude directive:
```
        exclude: # Disable combinations to save minutes
          - os: macos-latest
          #- os: ubuntu-latest
```
just to not waste expensive MacOS minutes when we don't have to. 

Up until March 16, 2020 everything was working fine, however, on March 17, 2020 some regression was made to GitHub Actions, which now forces macos-latest configuration still to be included even though it was explicitly excluded. 

**Please note:** the above repro is not the one on which this regression was found, so don't expect to see the change from March 16th to 17th on this repo. I discovered it on a private repo, I have just recreated the matrix on this open-source repo to demonstrate the bug as it manifests today.

If you look at the [jobs that were ran](https://github.com/solodon4/Boost-for-Android/actions/runs/59144999), you will notice that the job that wasn't supposed to be ran or listed at all is named as [build (macos-latest, mac)](https://github.com/solodon4/Boost-for-Android/runs/520101756?check_suite_focus=true), which is a combination of *os* and *variation*. However, the job that was supposed to be ran and did indeed ran is listed as [build (ubuntu-latest, Debug)](https://github.com/solodon4/Boost-for-Android/runs/520101750?check_suite_focus=true), which is a combination of *os* and *flavor*.

Judging from runs before March 17, the synthetic variable is never mentioned in the name of the build, so the mac job that wasn't even supposed to be ran was supposed to be called `build (macos-latest, Debug)` instead of `build (macos-latest, mac)`. If you expand that job, you will see in the expansion of step 3 (Setup Environment Variables) that variable ${{ matrix.flavor }} was expanded to empty string, which is why the job failed, however that job wasn't even supposed to be ran!

Let me know if anything is not clear. I'd also appreciate a workaround before a fix is made. Thank you!

**Comment by maxim-lobanov** [comment]
Hello @solodon4 , thank you for the detailed report.
This repository manages only content of Hosted images for GA and AzDO, not the build running process. For me, it looks like the issue with [actions/runner](https://github.com/actions/runner).

@TingluoHuang , @ericsciple , Hello! Does it make sense to move this issue to your repository for further investigation?

**Comment by solodon4** [comment]
Thanks @maxim-lobanov! So shall I resubmit this bug in actions/runner or will this bug get moved there somehow? Btw, is it even possible to move issues between repositories on github?

**Comment by maxim-lobanov** [comment]
@solodon4 , let's wait for their answer (to be sure that it is correct direction).
May be @alepauly also can confirm?

**Comment by ericsciple** [comment]
@solodon4 sorry for the disruption.

We overloaded `include` to allow explicit matrix combinations.

Now, instead of:

```yaml
 os: [ubuntu-latest,macos-latest]
  flavor: [Debug]
include:
  - os: ubuntu-latest
    variation: linux
  - os: macos-latest
    variation: mac
```

You can now author as:

```yaml
include:
  - os: ubuntu-latest
    variation: linux
    flavor: Debug
  - os: macos-latest
    variation: mac
    flavor: Debug
```

If you find that easier. Excludes are processed first, then includes.

**Comment by solodon4** [comment]
OK, this regression is not just on MacOS, it also happens on Ubuntu latest, which I just validated.

Thanks for reply @ericsciple! Are you saying the new behavior is by design? It doesn't seem to be logical if so.

Having *flavor* in includes just makes it harder to maintain CI workflow because now I have to change that value in multiple places. Besides, the actual project on which I discovered this regression has yet another variable *target*, which can be desktop or mobile, so the number of places to update will double again.

**Comment by ericsciple** [comment]
> now I have to change that value in multiple places

Ah I see. Yea that's not ideal.

For a small set of combinations, may be easier to maintain explicit list?

```yaml
        include:
          - os: macos-latest
            variation: mac
            flavor: Debug
          - os: ubuntu-latest
            variation: linux
            flavor: Debug
```

Trade off either way whether `include` is processed before/after `exclude`. After enables knockout large section of the cross product and add back subset.
