### ISSUE TITLE
libsystemd-dev : Depends: libsystemd0 (= 249.11-0ubuntu3) but 249.11-0ubuntu3.1 is to be installed

### ISSUE THREAD

**Issue by to-s** [actions/virtual-environments#5872]
### Description

We had the same issue around two weeks ago, than it was gone and now it's there again.

The Github Support asked us to open an issue here.

https://support.github.com/ticket/personal/0/1680493

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/to-s/libsystemd0-fail/runs/7229572792?check_suite_focus=true

```
Virtual Environment
  Environment: ubuntu-22.04
  Version: 20220626.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu22/20220626.1/images/linux/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu22%2F20220626.1
```

### Is it regression?

yes

### Expected behavior

No fail.

### Actual behavior

```
Run sudo apt install libsystemd-dev -y
  sudo apt install libsystemd-dev -y
  shell: /usr/bin/bash -e {0}
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 libsystemd-dev : Depends: libsystemd0 (= [2](https://github.com/to-s/libsystemd0-fail/runs/7229572792?check_suite_focus=true#step:4:2)49.11-0ubuntu[3](https://github.com/to-s/libsystemd0-fail/runs/7229572792?check_suite_focus=true#step:4:3)) but 2[4](https://github.com/to-s/libsystemd0-fail/runs/7229572792?check_suite_focus=true#step:4:5)[9](https://github.com/to-s/libsystemd0-fail/runs/7229572792?check_suite_focus=true#step:4:10).11-0ubuntu3.1 is to be installed
E: Unable to correct problems, you have held broken packages.
Error: Process completed with exit code [10](https://github.com/to-s/libsystemd0-fail/runs/7229572792?check_suite_focus=true#step:4:11)0.
```

### Repro steps

Setup a any repo with the following workflow file:

```
name: libsystemd0 fail

on: 
  workflow_dispatch:

jobs:
  libsystemd-dev-install:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: apt update
        run: sudo apt update
      - name: apt upgrade
        run: sudo apt upgrade
      - name: install libsystemd-dev
        run: sudo apt install libsystemd-dev -y
```
