### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by psandhu79** [actions/virtual-environments#5925]
### Tool name

gke-gcloud-auth-plugin

### Tool license

Apache License v. 2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Same version as the Google SDK 

### Brief description of tool

Kubectl will soon be removing the auth code to connect to GKE clusters 

https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke

Would like this to be added to the Google SDK install on the agents

In this file 
https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/google-cloud-sdk.sh

After line
apt-get install -y google-cloud-sdk=369.0.0-0

add this line
apt-get install google-cloud-sdk-gke-gcloud-auth-plugin

### URL for tool's homepage

https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke

### Provide a basic test case to validate the tool's functionality.

```bash
Connect to GKE cluster

Run kubectl get pods
```

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments where you need the tool

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
    sudo apt update
    sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin
    echo "##vso[task.setvariable variable=USE_GKE_GCLOUD_AUTH_PLUGIN]True"
```

### Tool installation time in runtime

15 seconds

### Are you willing to submit a PR?

Yes

**Comment by mikhailkoliada** [comment]
@psandhu79 Hi!

Thanks, we will decide on the tool addition and get back to you.

**Comment by mikhailkoliada** [comment]
@psandhu79 could you please also change the title of the ticket to reflect the wanted package?

**Comment by eric41** [comment]
It's unclear to me whether this'll be included in the image or that I should install it at runtime every build. Could someone enlighten me? Thanks!

**Comment by ddobranic** [comment]
hi @eric41 , it can be installed in runtime and it doesn't take much time, so we decided not to include it in the image.

**Comment by consideRatio** [comment]
## For reference, a journey of handling this

To do `gcloud components install gke-gcloud-auth-plugin` doesn't work.

```shell
# using this to add it doesn't work
gcloud components install gke-gcloud-auth-plugin

# it errors like
ERROR: (gcloud.components.install) 
You cannot perform this action because the Google Cloud CLI component manager 
is disabled for this installation. You can run the following command 
to achieve the same result for this installation: 

sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin
```

To do `sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin` doesn't work directly either.

```shell
# using this to add it doesn't work either, as the apt repository
# used to install gcloud-sdk was removed
sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin

# it errors like
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package google-cloud-sdk-gke-gcloud-auth-plugin
```

Since this repo is removing the apt-get repository following installing the gcloud-sdk apt package, we have to add it back as well to install the plugin.

https://github.com/actions/runner-images/blob/9753e7301e19e29b89b0622b811bbb9b3891d02e/images/linux/scripts/installers/google-cloud-sdk.sh#L7-L17

This is what ended up working for me.

```yaml
      # Install pre-requisite for "gcloud container clusters get-credentials"
      # command with a modern k8s client.
      #
      # Snippet based on
      # https://github.com/actions/runner-images/blob/9753e7301e19e29b89b0622b811bbb9b3891d02e/images/linux/scripts/installers/google-cloud-sdk.sh#L9-L13.
      #
      - name: Install gke-gcloud-auth-plugin
        run: |
          REPO_URL="https://packages.cloud.google.com/apt"
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] $REPO_URL cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list >/dev/null
          sudo wget -q https://packages.cloud.google.com/apt/doc/apt-key.gpg -O /usr/share/keyrings/cloud.google.gpg

          sudo apt-get update -y
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
```

![image](https://user-images.githubusercontent.com/3837114/209685880-03738804-cf44-4fa1-b706-09408c905600.png)
