### ISSUE TITLE
fatal error - cygheap base mismatch detected

### ISSUE THREAD

**Issue by evandrocoan** [actions/virtual-environments#594]
**Describe the bug**
I am trying to install `msys2` with `choco install msys2`, but it is not working because in the middle of the installation I have these: https://github.com/evandroforks/anki/runs/522578741#step:6:224 (the installation is not failing because of this, but it is breaking the installation on future use)
```
      0 [main] bash (968) D:\a\anki\anki\msys64\usr\bin\bash.exe: *** fatal error - cygheap base mismatch detected - 0x180330408/0x180317408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
```

Someone somewhere is already putting a `cygwin1.dll` file on the system path or loading some process which uses it. After searching, I could find that git for windows has its own mingw installation and that mingw is installed by chocolatey: https://github.com/actions/virtual-environments/blob/master/images/win/scripts/Installers/Install-MinGW.ps1

**Question, Bug, or Feature?**: 
Choose "Bug"

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
It would be very appreciated if no one else started putting/loading cygwin process/dlls on the virtual environment.

I am installing `msys2` because either `mingw` from `chocolatey` or `git for windows` have a package manager, so I cannot install my packages in them. That is whay I am installing `msys2`. Because it has a package manager and I can install new packages as `gettext`, `rsync`, `wget`, etc.

**Actual behavior**
Create a workflow:
```yml
name: Windows Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure environment variables
        run: |
          $new_path=("$env:GITHUB_WORKSPACE\msys64\usr\bin;$env:PATH")
          echo "::set-env name=PATH::$new_path;"
          echo "::set-env name=ChocolateyToolsLocation::$env:GITHUB_WORKSPACE"
      - name: Set up ripgrep, pyaudio, msys2
        shell: cmd
        run: |
          choco install --no-progress --yes ripgrep msys2
          pacman -S --noconfirm gettext rsync wget
```

The installation will not fail, but you will get several errors in the middle of it:
```
     0 [main] bash (968) D:\a\anki\anki\msys64\usr\bin\bash.exe: *** fatal error - cygheap base mismatch detected - 0x180330408/0x180317408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
...
```

Later the processes are not working to work correctly. 

I am well aware of https://github.com/numworks/setup-msys2 the problem is that they work with a completely isolated installation of `msys2`  which had to be used with `msys2do <command>` instead of just `command`. Making the project harder to run on both linux and windows. The point is not the alternative tools I could use, but GitHub Actions environment being shipped by default with something which breaks new tools installations.

This problem is quite hard to figure out why it is happening and from where is this coming from. It could be due `choco install mingw` or `git for windows` or `openssl` installation, etc, or all of them together.
