### ISSUE TITLE
Video screencapture fails on Macos-latest

### ISSUE THREAD

**Issue by lemnis** [actions/virtual-environments#5960]
### Description

I was trying to capture the desktop of macOS, but the outputted file is a pixel mess. Screencapture does work on macOS 10 & 12

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Environment: macos-11
  Version: 20220719.1

### Is it regression?

No

### Expected behavior

Getting a 10 seconds of the desktop

### Actual behavior

See below, the pixels in the video are misaligned.

Uploading foo-2.mov…

### Repro steps

Run below workflow and download the artifacts:
```
name: Screencapture

on:
  push:
    branches: [ "master" ]

jobs:
  latest:
    runs-on: macos-latest

    steps:
    - run: screencapture -T0 -V 10 foo.mov
    - uses: actions/upload-artifact@v3
      with:
        name: latest
        path: foo.mov
  


```
