### ISSUE TITLE
VSTest has a -preview indication

### ISSUE THREAD

**Issue by MichelZ** [actions/virtual-environments#5971]
### Description

When running tests on Azure Devops, Windows Server 2022 today (2022-07-26), it looks like a preview version of Visual Studio's vstest is used:

```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe "@D:\a\_temp\syvwbhqrxhn.tmp"
Microsoft (R) Test Execution Command Line Tool Version 17.2.0-preview-20220401-07 (x64)
```

Instead of the preview version, it should use the release version?

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

```
Starting: Initialize job
Agent name: 'Hosted Agent'
Agent machine name: 'fv-az290-973'
Current agent version: '2.206.1'
Operating System
Virtual Environment
Environment: windows-2022
Version: 20220710.1
Included Software: https://github.com/actions/virtual-environments/blob/win22/20220710.1/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/win22%2F20220710.1
Virtual Environment Provisioner
1.0.0.0-main-20220701-2
Current image version: '20220710.1'
Agent running as: 'VssAdministrator'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: UseDotNet (2.206.0)
Downloading task: DownloadPipelineArtifact (2.198.0)
Downloading task: CopyFiles (2.200.0)
Downloading task: VSTest (2.205.0)
Checking job knob settings.
   Knob: AgentToolsDirectory = C:\hostedtoolcache\windows Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: AgentPerflog = c:\vsts\perflog Source: ${VSTS_AGENT_PERFLOG} 
Finished checking job knob settings.
Start tracking orphan processes.
Finishing: Initialize job
```

### Is it regression?

No

### Expected behavior

Uses a release build of vstest

### Actual behavior

Uses a preview version of vstest

### Repro steps

Execute a vstest task

```
- task: VSTest@2
  displayName: 'Run integration tests (.NET FX)'
  condition: and(succeeded(), eq(variables['RunTests'], 'true'))
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '**\Microsoft.Identity.Test.Integration.netfx\bin\**\net4*\Microsoft.Identity.Test.Integration.NetFx.dll'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    rerunFailedTests: true
    rerunMaxAttempts: '3'
    runInParallel: false
    codeCoverageEnabled: true
```
