### ISSUE TITLE
Pre-install Android NDK versions on Actions images

### ISSUE THREAD

**Issue by samtstern** [actions/virtual-environments#643]
**Tool information**
- Tool name: Android NDK
- Add or update? Update
- Desired version: 20
- Approximate size: Unknown
- If this is an add request: N/A

**Area for Triage**:
Android

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, it takes about 1.5 minutes

**Are you willing to submit a PR?**
Yes!

**Comment by samtstern** [comment]
Submitted at the recommendation of @maxim-lobanov in this comment:
https://github.com/actions/virtual-environments/issues/578#issuecomment-605886387

Installing a few common versions of the Android NDK would make builds faster, reduce network traffic, and reduce build complexity.

My Android build used to be super simple:
```yaml
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew clean ktlint build
```

Then an Android update forced me to add this:
```yaml
  build:
    runs-on: ubuntu-latest
    steps:
    # ...
    - name: Install NDK
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}
```

That took my build from 9m40s to 11m20s so now I am considering adding NDK caching but that's even more complexity to my very simple workflow.
