### ISSUE TITLE
Announce/Feedback: Removing Windows Server 2016 virtual environment

### ISSUE THREAD

**Issue by kaylangan** [actions/virtual-environments#68]
The Windows Server 2016 virtual environment will be removed in January 2020. You will need to update your workflow files to run on `windows-latest` which will run on the Windows Server 2019 environment instead.

Update 12/10: We have moved the deprecation date to January 2020.

**Comment by wipe2238** [comment]
Does that mean Visual Studio 2017 will be added to `windows-latest`?

**Comment by NickCraver** [comment]
The post and tweet mention Windows 2016 **R2** ([post link](https://github.blog/changelog/2019-10-31-github-actions-windows-server-2016-r2-virtual-environment-will-be-removed-on-november-7/), [tweet link](https://twitter.com/GHchangelog/status/1189977225308909568)).

Can we please remove the R2 there to fix the notes? Or I'm very confused...there wasn't a Windows 2016 R2 ever released to the public AFAIK.

**Comment by kaylangan** [comment]
> Does that mean Visual Studio 2017 will be added to `windows-latest`?

That is the plan. We don't yet have a firm ETA, but ideally by end of the year.

> The post and tweet mention Windows 2016 R2

This is how it's been referred to in our documentation: https://help.github.com/en/github/automating-your-workflow-with-github-actions/software-in-virtual-environments-for-github-actions

**Comment by NickCraver** [comment]
@kaylangan I'm not sure what the best way to say this is, but: that OS doesn't exist. It was a bug in the original documentation too then :)

**Comment by kaylangan** [comment]
@NickCraver Fixed now. Thanks! 🙂

**Comment by hugovk** [comment]
📍 Maybe pin this issue for extra visibility?

**Comment by tvatter** [comment]
... wouldn't it make more sense to wait until Visual Studio 2017 is added to `windows-latest` ? Without it (i.e., on the current `windows-latest`), although `"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" my_platform` executes without problem, I still get the dreaded `error: Microsoft Visual C++ 14.0 is required` when trying to install a package.

**Comment by alepauly** [comment]
@tvatter @hugovk We're working on adding the ```Microsoft.VisualStudio.Component.VC.140``` [component](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2019) to the VS2019 install. It should show up in the environment in the next few weeks.

**Comment by Skycoder42** [comment]
@alepauly Is there an issue for VC.140 (msvc2015) **and** VC.141 (msvc2017) to track when they have been added?

**Comment by LorenzE** [comment]
Are there any news on adding msvc2017 support to windows-latest (windows server 2019)? I am asking because my builds on windows are dependent on pre-built Qt binaries, which ship for <= msvc2017 only. Thx :)

**Comment by alepauly** [comment]
@LorenzE @Skycoder42 - sorry for the silence here so far but we did make some changes to the windows 2019 runner to include msvc140 (vs2015) and a missing component for msvc141 (vs2017). The latest built rolling out right now has those changes but it won't reach your repos probably until Friday this week or Monday. I'll do my best to keep this issue up to date but please don't hesitate to ping me if you have any questions. Thanks!

**Comment by LorenzE** [comment]
@alepauly Thanks for keeping us in the loop!

**Comment by rvanmil** [comment]
We also need Visual Studio 2017 to keep our cordova-windows builds going. For a while it was possible to run vs2017 on the 2019 environment by installing it through the chocolatey `visualstudio2017buildtools` package, but this has stopped working somewhere around december 12th (the installer fails silently).

**Comment by kaylangan** [comment]
@rvanmil can you point me to a build?

**Comment by rvanmil** [comment]
> @rvanmil can you point me to a build?

Over here, but this is a private repo: https://github.com/oliverit/infrax-cordova-app-wfm/commit/8057bd462c963b3e30b1a209327f1f811a9ac177/checks?check_suite_id=372173496

This is the workflow script I'm using:

```
name: Build for Windows

on:
  push:
    tags:
    - 'v*'

jobs:
  build:

    runs-on: windows-2016

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Node.js 8
      uses: actions/setup-node@master
      with:
        node-version: '8.x'
        registry-url: 'https://npm.pkg.github.com'

    - name: Import code signing certificate
      shell: powershell
      run: ./build/certificate.ps1

    - name: Add Yarn global bin to path
      shell: bash
      run: echo "::add-path::$(yarn global bin)"

    - name: Install Cordova
      shell: bash
      run: yarn global add cordova@9

    - name: Install dependencies
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
      run: yarn install

    - name: Build - TST - Webpack
      shell: bash
      run: yarn build-tst

    - name: Build - TST - Cordova
      shell: bash
      env:
        MSBUILDDIR: '/C/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin'
        NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
      run: >
        export FILENAME_X64=CordovaApp.Windows10_$(node -p "require('./package.json').version").0_x64 &&
        export FILENAME_X86=CordovaApp.Windows10_$(node -p "require('./package.json').version").0_x86 &&
        cordova prepare windows &&
        cordova build windows --release --archs="x86 x64" --bundle --win --buildConfig=build/build-tst.json &&
        mv ./platforms/windows/build/windows/release/x64/win10/Upload/$FILENAME_X64/$FILENAME_X64.appx ./App-x64-TST.appx &&
        mv ./platforms/windows/build/windows/release/x86/win10/Upload/$FILENAME_X86/$FILENAME_X86.appx ./App-x86-TST.appx

    - name: Build - PRD - Webpack
      shell: bash
      run: yarn build-prd

    - name: Build - PRD - Cordova
      shell: bash
      env:
        MSBUILDDIR: '/C/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin'
        NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
      run: >
        export FILENAME_X64=CordovaApp.Windows10_$(node -p "require('./package.json').version").0_x64 &&
        export FILENAME_X86=CordovaApp.Windows10_$(node -p "require('./package.json').version").0_x86 &&
        cordova prepare windows &&
        cordova build windows --release --archs="x86 x64" --bundle --win --buildConfig=build/build-prd.json &&
        mv ./platforms/windows/build/windows/release/x64/win10/Upload/$FILENAME_X64/$FILENAME_X64.appx ./App-x64-PRD.appx &&
        mv ./platforms/windows/build/windows/release/x86/win10/Upload/$FILENAME_X86/$FILENAME_X86.appx ./App-x86-PRD.appx

    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          App-x64-TST.appx
          App-x86-TST.appx
          App-x64-PRD.appx
          App-x86-PRD.appx
```
