### ISSUE TITLE
Update/Add Chrome and web drivers on macOS

### ISSUE THREAD

**Issue by DanTup** [actions/virtual-environments#7]
Chrome is available on Linux and Windows, for absent from macOS. It'd be nice if it was available on all.

It's not complicated to add ourselves, but it adds more noise to the workflow file (I have a growing list of things like this that just set up one tool on one OS).

```yaml
      - name: Setup Chrome
        if: matrix.os == 'macOS-latest'
        run: brew cask install google-chrome
```
