### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by vivekkr12** [actions/virtual-environments#70]
**Describe the bug**
During build of a vue app using vue cli, nodejs 10x, build fails with the following error:
`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

**Virtual environments affected**
- [ ] macOS 10.14
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Build should run successfully.

**Actual behavior**
Build fails with the error mentioned above. Error logs
https://github.com/OutdoorRD/trails-viz/commit/b88b74b170ba77c4c0f4cbc817022f69e4b73e4c/checks?check_suite_id=290912535

**Comment by maxim-lobanov** [comment]
Hi!
Is this issue still actual?

**Comment by vivekkr12** [comment]
Can be avoided by setting max heap size.
`export NODE_OPTIONS="--max_old_space_size=4096"`

**Comment by KumarAbhirup** [comment]
I see the issue even after doing `export NODE_OPTIONS="--max_old_space_size=4096"`...

Please reopen...

**Comment by maxim-lobanov** [comment]
@KumarAbhirup , Initial issue was related to Node.js configuration rather image itself. If you think that your issue comes from something broken on image, feel free to create the new issue and provide minimal repro steps for the issue.

**Comment by sidverma32** [comment]
check this answe: https://stackoverflow.com/questions/38558989/node-js-heap-out-of-memory/66914674#66914674

**Comment by helloint** [comment]
considering the Node.js [document](https://nodejs.org/api/cli.html#--max-old-space-sizesize-in-megabytes), should be --**max-old-space-size**=SIZE, but tested both `max_old_space_size` and `max-old-space-size` works.

**Comment by AbeerAhmad** [comment]
> Can be avoided by setting max heap size. `export NODE_OPTIONS="--max_old_space_size=4096"`
Where to put it in github actions?

**Comment by fisprak** [comment]
@AbeerAhmad In `run` or `env` blocks.

`run`

```yaml
jobs:
  make-love:
    steps:
      - name: "Just do it"
        run: |
        export NODE_OPTIONS="--max_old_space_size=4096"
        npm start
```

`env`

```yaml
jobs:
  make-love:
    steps:
      - name: "Nothing is impossible"
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: npm start
```
