### ISSUE TITLE
Ubuntu PyPy3 version 7.3.0 'import lzma' error

### ISSUE THREAD

**Issue by miketimofeev** [actions/virtual-environments#730]
**Describe the bug**
PyPy3 on both Ubuntu 16&18 failed when trying to import lzma module with the following error:
`ImportError: /opt/hostedtoolcache/PyPy/3.6.9/x64/lib_pypy/_lzma_cffi.pypy36-pp73-x86_64-linux-gnu.so: undefined symbol: lzma_index_stream_padding`

**Area for Triage**: 
Python

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
The code works:
```
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "pypy3"
      - name: Import lzma
        run: python -c "import lzma"
```

**Actual behavior**
`run: python -c "import lzma"` fails when using PyPy3
