### ISSUE TITLE
Set Locale

### ISSUE THREAD

**Issue by BrightRan** [actions/virtual-environments#762]
In [this ticket](https://github.community/t5/GitHub-Actions/Set-Locale/td-p/54314), the user wants to change the runner machine's locale language to PT-BR, he uses the below step to do set the locale:
```yaml
      - name: SetLocale
        run: |
          sudo apt-get update && sudo apt-get install tzdata locales -y && sudo locale-gen pt_BR.UTF-8
          sudo localectl set-locale LANG="pt_BR.UTF-8"
          export LANG="pt_BR.UTF-8"
          sudo update-locale
          echo "Testing language settings"
          echo "All languages..."
          locale -a
          echo "Actual locale"
          locale
          echo "Actual numeric settings"
          locale -c -k LC_NUMERIC
          echo "LANG Variable"
          echo "$LANG"
          echo "LocaleCtl"
          localectl status
          echo "Printing decimal"
          printf "%'.3f\n" 123123,123
```
The locale language seems changed successfully, but when he tries to check the number formats and date formats, they are shown inconsistent with the locale language.

**Comment by dsame** [comment]
printf is built in command of bash and a bash process does not catch up the locale settings changed with the same process.

The following code in the above workflow [works as expected](https://github.com/dsame/actions-demo/runs/611352187?check_suite_focus=true)
```
          echo "Printing decimal in child shell"
          /bin/bash -c "printf \"%'.3f\n\" 123123,123"
```

**Comment by hugoj-goncalves** [comment]
@dsame 
I can't really say that I understand but it's cool that it works that way. I'm no linux expert at all.
Why is it different from running these commands locally/in a docker?
As I'm using without a problem in those two situations.
Would it work if I create a shell script with everything inside, or would I still need to call _/bin/bash -c_ for everything I need localized?

**Comment by maxim-lobanov** [comment]
@hugoj-goncalves , I believe it will also work if we use different steps for setting locale and testing it because the second step will be new shell session:
```
- name: SetLocale
  run: |
          sudo apt-get update && sudo apt-get install tzdata locales -y && sudo locale-gen pt_BR.UTF-8
          sudo localectl set-locale LANG="pt_BR.UTF-8"
          export LANG="pt_BR.UTF-8"
          sudo update-locale
          locale -a
          locale
          locale -c -k LC_NUMERIC
          localectl status
- name: Test
  run: |
          echo "Printing decimal"
          printf "%'.3f\n" 123123,123
```

**Comment by hugoj-goncalves** [comment]
@maxim-lobanov That definitely is not the case as my first test was like that :disappointed: 
I had a SetLocale step and a SetTime step which I just used _date_ command to check if timezone was okay.
![image](https://user-images.githubusercontent.com/10927715/80103793-dae98580-854b-11ea-90b4-6b21741208a3.png)
As you can see it didn't print _date_ respecting the locale change.

**Comment by al-cheb** [comment]
@hugoj-goncalves 
```
env:
  LANG: "pt_BR.UTF-8"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: pt_BR.UTF-8
      run: |
          sudo locale-gen pt_BR.UTF-8
          sudo update-locale LANG=pt_BR.UTF-8
    - name: date
      run: |
          date
```

![time - Copy](https://user-images.githubusercontent.com/47745270/80125445-54a86000-859a-11ea-9dae-051bccc681e9.JPG)

**Comment by hugoj-goncalves** [comment]
@al-cheb oh wow...
would've never guessed it tough
everything worked just fine that way (just the _printf_ thing that needs the _bash -c_ to work)

![image](https://user-images.githubusercontent.com/10927715/80129829-05e4d100-856e-11ea-9846-9697808274b6.png)

It's still a little confusing for me but I guess this issue is solved. Sorry about the trouble.

**Comment by galaxy4public** [comment]
Just in case somebody stumbles on this thread, the following command in the above comments does not seem right:
```
sudo locale-gen pt_BR.UTF-8

**Comment by al-cheb** [comment]
@galaxy4public, Just for example:
```
$ locale-gen NOTFOUNDLOCALE
Error: 'NOTFOUNDLOCALE' is not a supported language or locale
```
Find a parameter $1:
```
$ cat /usr/sbin/locale-gen | grep 'is not a supported'
        echo "Error: '$1' is not a supported language or locale" >&2
```

As you can see $1 is the first argument

**Comment by galaxy4public** [comment]
Well, I trust that on your system it works like you showcased, however [Ubuntu's man page](http://manpages.ubuntu.com/manpages/focal/man8/locale-gen.8.html) does not mention such a behaviour and other distros do not follow it too (e.g. on Archlinux the script is pretty simple and does not respect any arguments to `locale-gen`)

**Comment by AlenaSviridenko** [comment]
Hi! I am closing this issue since the original question was solved. 
Please, feel free to file a new ticket if you have any other issues with locale.
Thank you!

**Comment by robinmatz** [comment]
Hey,

I am experiencing some issues related to the locale settings inside a GitHub Actions pipeline. I am trying to run test cases with x3270 using Robotframework. This is the [link to my fork](https://github.com/robinmatz/Robot-Framework-Mainframe-3270-Library/tree/ci-test).

This is what the [.yml](https://github.com/robinmatz/Robot-Framework-Mainframe-3270-Library/blob/ci-test/.github/workflows/run-tests.yml) looks like:
```
# This workflow runs the test suites with different versions of python
name: tests

on: [push, pull_request]

env:
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US:en"
  LC_ALL: "en_US.UTF-8"

jobs:
  tests:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        sudo apt-get install -y xvfb x3270 locales
        python -m pip install -r robotframework_mainframe3270.egg-info/requires.txt
        
    - name: Run tests
      run: |
        sudo locale-gen ${{ env.LANG }}
        sudo update-locale LANG=${{ env.LANG }}
        xvfb-run robot --exclude No-CI --loglevel DEBUG tests
    
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Tests results python${{ matrix.python-version }}
        path: |
          log.html
          report.html
          output.xml
```

This is the [error](https://github.com/robinmatz/Robot-Framework-Mainframe-3270-Library/runs/4524027696?check_suite_focus=true#step:5:23) I am getting:

![image](https://user-images.githubusercontent.com/76647407/146163611-fbce9b48-64eb-4dd3-9811-e7bea88fce90.png)


I am struggling to understand why the encoding is not set correctly. Any help would be very much appreciated!
