### ISSUE TITLE
Mono version 6.8.0.123 does not use Xamarin.iOS 13.16.0.13

### ISSUE THREAD

**Issue by jmichas** [actions/virtual-environments#821]
**Describe the bug**
Selecting the latest mono version using 6_8_0 yields version 6.8.0.123 as expected, but the accompanying Xamarin iOS version is still 13.4. It should be 13.16.0.13 which by everything I can find is on the macOS-latest image, but there is no way to select it.

This is immensely important as we are past the Apple deadline (4/30/20) for removing UIWebView references. The mtouch arguments to support removing the references with the linker are only supported in versions > 13.4 so, no builds can be submitted. This included testflight beta builds that have already been approved by Apple.

**Area for Triage**: Xamarin

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [X] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Selecting the latest mono version should give you the latest xamarin.ios version.

**Actual behavior**
Mono 6.8.0.123 => Xamarin.iOS 13.14.1.39

1. Step 1
2. Step 2

**Comment by maxim-lobanov** [comment]
Hello @jmichas !
Could you please try symlink `6_8_1`?

`6_8_0` - Mono 6.8, Xamarin.iOS 13.14, Xamarin.Mac 6.14, Xamarin.Android 10.2
`6_8_1` - Mono 6.8, Xamarin.iOS 13.16, Xamarin.Mac 6.16, Xamarin.Android 10.2

Btw, configuration `Mono 6.8, Xamarin.iOS 13.16, Xamarin.Mac 6.16, Xamarin.Android 10.2` is default on the image if you don't override anything.

If you use GitHub Actions, you can use action [setup-xamarin](https://github.com/marketplace/actions/setup-xamarin) to switch Xamarin bundles. In this case, you don't need worry about symlinks.

**Comment by jmichas** [comment]
@maxim-lobanov Thanks. Thats seems to be working. But it is extremely confusing. I never found anywhere in the documentation that shows some sort of mapping between the 6_8_0 notation and the actual version numbers. Even more confusing is selecting 6_8_0 and 6_8_1 both yield mono 6.8.0.123 but _0 is xamarin 13.14 and _1 is 13.16.

Regarding using the defaults, which I also didn't see anywhere in the docs, I am using this in my yaml:
```
# To manually select a Xamarin SDK version on the Microsoft-hosted macOS agent,
# configure this task with the *Mono* version that is associated with the
# Xamarin SDK version that you need, and set the "enabled" property to true.
# See https://go.microsoft.com/fwlink/?linkid=871629
- script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh $(mono_version)
  displayName: 'Select the Xamarin SDK version'
  enabled: true

- task: Bash@3
  displayName: "Set Mono Version $(mono_version)"
  inputs:
    targetType: 'inline'
    script: |
      SYMLINK=$(mono_version)
      MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
      echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
      echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
      echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
      mono --version

- script: /bin/bash -c "echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'$(xcode);sudo xcode-select --switch $(xcode)/Contents/Developer"
  displayName: 'Select XCode Version'
  enabled: true
```
Are you saying that I can remove these an I should get the latest versions of mono, xam ios and xcode?
Do I need to have Xamarin.iOS in demands?

Thanks again, I have a build going right now.
