### ISSUE TITLE
BOOST_ROOT directory is missing

### ISSUE THREAD

**Issue by rkennedy** [actions/virtual-environments#83]
[Documentation says](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners) `BOOST_ROOT` refers to the directory where the Boost library is installed. Although the environment variable is set to a plausible value, I find the directory doesn't exist.

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
I expected to see a list of hundreds of .hpp files.

**Actual behavior**
I used the following workflow:

```yaml
name: Build
on:
- push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        ls -lR ${BOOST_ROOT}
```

This is the output I see:

```
ls: cannot access '/usr/local/share/boost/1.69.0': No such file or directory
```

Have I misunderstood how to use Boost in this environment?
