### ISSUE TITLE
Cached node on ubuntu not set up correctly

### ISSUE THREAD

**Issue by damccorm** [actions/virtual-environments#870]
**Describe the bug**
I think [this commit](https://github.com/actions/virtual-environments/commit/9b1143ddddc87e3924cc36a7cefc3d14c4bf10cb) introduced a bug and isn't setting up node modules correctly.

**Area for Triage**: JavaScript and Node.js

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
We should be able to install a different version of npm after installing node.

**Actual behavior**
Trying to do this results in an error: `Error: Cannot find module 'semver'`

You can see this behaving correctly on a downloaded version of node and incorrectly on the cached version. In this example, I use Node 8.16.2 since that's the highest version that isn't the cached version (8.17.0) - https://dev.azure.com/vstscix/damccormTest/_build/results?buildId=115122&view=logs&j=4021d9ab-6287-5638-9fd6-4c6c049820ed&t=b5b3e3e4-1b78-582b-1ea4-c44df544cec9. Uses the following yaml:

```
trigger:
- master

jobs:
- job: cachedNode
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  # Use node 8, npm 5
  - task: NodeTool@0
    displayName: Use node 8
    inputs:
      versionSpec: "8.x"

  - script: npm i -g npm@6.9.0 --force
    displayName: Use npm version 6.9.0

- job: downloadedNode
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - task: NodeTool@0
    displayName: Use node 8
    inputs:
      versionSpec: "8.16.2"

  - script: npm i -g npm@6.9.0 --force
    displayName: Use npm version 6.9.0
```

cc the following people who created or reviewed the pr: @dmitry-shibanov @sergey-akhalkov @AlenaSviridenko @maxim-lobanov
