### ISSUE TITLE
SonarQubeAnalyze issue on macos images version 3.230.0

### ISSUE THREAD

**Issue by themaroqa** [actions/virtual-environments#8873]
### Description

I am not sure if this is actually the root cause or just a random coincidence. 
What I see is that if the job takes the new macos11 and macos12 version (3.230.0) the SonarQubeAnalyze fails with the following error:
```
SonarScanner for MSBuild 5.14
Using the .NET Core version of the Scanner for MSBuild
Post-processing started.
##[error]15:01:06.688  The SonarScanner for MSBuild integration failed: SonarQube was unable to collect the required information about your projects.
Possible causes:
  1. The project has not been built - the project must be built in between the begin and end steps
  2. An unsupported version of MSBuild has been used to build the project. Currently MSBuild 14.0.25420.1 and higher are supported.
  3. The begin, build and end steps have not all been launched from the same folder
  4. None of the analyzed projects have a valid ProjectGuid and you have not used a solution (.sln)
15:01:06.688  The SonarScanner for MSBuild integration failed: SonarQube was unable to collect the required information about your projects.
Possible causes:
  1. The project has not been built - the project must be built in between the begin and end steps
  2. An unsupported version of MSBuild has been used to build the project. Currently MSBuild 14.0.25420.1 and higher are supported.
  3. The begin, build and end steps have not all been launched from the same folder
  4. None of the analyzed projects have a valid ProjectGuid and you have not used a solution (.sln)
15:01:06.688  Generation of the sonar-properties file failed. Unable to complete the analysis.
##[error]15:01:06.695  Post-processing failed. Exit code: 1
15:01:06.695  Post-processing failed. Exit code: 1
##[error]The process '/usr/local/bin/dotnet' failed with exit code 1
```

As soon as my buid pipeline can use version 3.227.1 of the agent the task complete succesfully without any other intervention.

I am happy to provide further details if requested. 

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Agent machine name: 'Mac-1700664192648'
Current agent version: '3.230.0'
Runner Image
Image: macos-11
Version: 20231117.2
Included Software: https://github.com/actions/runner-images/blob/macOS-11/20231117.2/images/macos/macos-11-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macOS-11%2F20231117.2

Agent machine name: 'Mac-1700647624311'
Current agent version: '3.230.0'
Runner Image
Image: macos-12
Version: 20231115.2
Included Software: https://github.com/actions/runner-images/blob/macOS-12/20231115.2/images/macos/macos-12-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20231115.2

### Is it regression?

yes

### Expected behavior

Task complete succesfully

### Actual behavior

Task fail

### Repro steps

Run the SonarQubeAnalyze task on a dotnet project

**Comment by mikhailkoliada** [comment]
Hey, as per logs you are using unsupported msbuild version and it does not seem we can help here, what's your pipeline?

**Comment by ilia-shipitsin** [comment]
@themaroqa , do you have some publicly available project to have a look ? or some repro steps maybe

**Comment by themaroqa** [comment]
Hi @ilia-shipitsin, I don't have a public repo to share with you. I can try to provide you with a mock of our build steps. Hopefully this will help you on understanding the issue; please note that the following snippet is part of a template we use:

```
  - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'sonarqube-production-$(System.TeamProject)'
        scannerMode: 'MSBuild'
        projectKey: '$(System.TeamProject)$(Build.Repository.Name)xandroidm'
        projectName: '$(Build.Repository.Name)-xamarin-android-mobile'
        projectVersion: '$(Build.SourceBranchName)'
        extraProperties: |
          sonar.exclusions=${{ parameters.sonarQubeExclude }}
          sonar.qualitygate.wait=${{ parameters.sonarQubeGate }}

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        if (Test-Path -Path "$(Build.Repository.LocalPath)/$(Build.Repository.Name)") {
          Write-Host "##vso[task.setvariable variable=solutionDir;]$(Build.Repository.LocalPath)/$(Build.Repository.Name)/"
        }
        else {
          Write-Host "##vso[task.setvariable variable=solutionDir;]$(Build.Repository.LocalPath)/"
        }

  - task: MSBuild@1
    inputs:
      solution: '${{ parameters.solutionPath }}'
      msbuildArguments: '/t:restore /p:Configuration=${{ parameters.buildConfiguration }}'

  - task: MSBuild@1
    inputs:
      solution: '${{ parameters.solutionPath }}'
      msbuildArguments: '/t:build /p:Configuration=${{ parameters.buildConfiguration }} /p:AndroidBuildApplicationPackage=True /p:AndroidPackageFormat=${{ parameters.packageFormat }} /p:AndroidKeyStore=True /p:AndroidSigningKeyStore=$(mySecureFile.secureFilePath) /p:AndroidSigningStorePass=${{ parameters.keystorePassword }} /p:AndroidSigningKeyAlias=${{ parameters.keystoreAlias }} /p:AndroidSigningKeyPass=${{ parameters.keyPassword }} /p:SolutionDir=$(solutionDir)'


  - task: SonarQubeAnalyze@5
```

The powershell script in the middle is meant for managing some repos where we checkout multiple repositories. It shouldn't be the root cause of the problem but I wanted to include it in the snippet.
Another sidenote is that the solutionPath parameter it can be both a sln path or a csprj path depending on the projects.

I just want to remark that the above works perfectly when running on a previous image of macos-12 and macos-11

**Comment by ilia-shipitsin** [comment]
well, it looks like something in `SonarQubePrepare@5` task.
I asked in community forum https://community.sonarsource.com/t/where-can-i-get-support-for-sonarqubeprepare-5-task/105186

**Comment by themaroqa** [comment]
for anyone hitting the same issue: for me the root cause was the dotnet version. Using dotnet 8 the task fails. As a workaround (while waiting for sonarsource or microsoft to fix the problem) you can add the following in the yaml:
```
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '7.0.x'
```

Adding that snippet resolved my issue.
