### ISSUE TITLE
Old cargo cache left over from the build in Windows and Linux

### ISSUE THREAD

**Issue by mzabaluev** [actions/virtual-environments#895]
**Describe the bug**
Parts of the `~/.cargo` file tree baked into the virtual environments `windows-latest` and `ubuntu-latest` contain cached crate registry data left over from the build.

**Area for Triage**: 
Rust

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
The only contents of the `~/.cargo` directory that should be present in the pristine virtual environment are the Rust toolchain binaries in `bin/` and the `env` script, and possibly some configuration dotfiles. The subdirectories `registry` and `git` cache dependencies for package builds and should either be left empty or not be present.

**Actual behavior**
A description with steps to reproduce the issue.

1. Run this GitHub workflow:

```yaml
name: Test cargo behavior

on: push

jobs:
  generate-lockfile:
    strategy:
      matrix:
        expunge-index: [true, false]
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - if: ${{ matrix.expunge-index }}
        name: Clear cargo registry index
        run: |
          rm -r -fo ~\.cargo\registry\index

      - run: cargo generate-lockfile -vv
```

2. Check the time it takes to run `cargo generate-lockfile` in each of the two jobs.

Cargo attempts to check out the head of the [crates.io registry index repository](https://github.com/rust-lang/crates.io-index) into a predictably named directory under `~/.cargo/registry/index`.
Apparently, if the working copy directory is already present, but its local head commit is way back in the current history of the frequently updated index, the git backend ends up doing something that works way slower on Windows than a clean clone. This should probably be fixed in cargo, but it will take more effort than doing a bit more post-build cleanup here.

There are also crate sources left in `~/.cargo/registry/cache` and `~/.cargo/registry/src`; the whole thing looks like a leftover from a `cargo install` performed during the build of the virtual environment. These files need to be removed, as they only bloat the images.
