### ISSUE TITLE
broken apt-get packages on ubuntu

### ISSUE THREAD

**Issue by klei1984** [actions/virtual-environments#904]
**Describe the bug**
Since an hour ubuntu-latest as well as ubuntu-18.04 fails to execute the following command:

```sudo apt-get install -y -qq build-essential gcc-multilib libsdl2-dev:i386 libsdl2-mixer-dev:i386```

Relevant script down to failing step:
```
name: Build Workflow
on:
  push:
    branches:
    - master
    paths-ignore:
    - '**.md'
    - '**.yml'
    - '**/doc'

  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    paths-ignore:
    - '**.md'
    - '**.yml'
    - '**/doc'

jobs:
  Linux-i386:
    runs-on: ubuntu-18.04

    env:
      BUILD_DIR: build
      BUILD_TYPE: Debug

    steps:
    - name: Setup Dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update -y -qq
        sudo apt-get install -y -qq build-essential gcc-multilib libsdl2-dev:i386 libsdl2-mixer-dev:i386 
```

Error log:
```
 Setup Dependencies
    BUILD_TYPE: Debug
Run sudo dpkg --add-architecture i386
  sudo dpkg --add-architecture i386
  sudo apt-get update -y -qq
  sudo apt-get install -y -qq build-essential gcc-multilib libsdl2-dev:i386 libsdl2-mixer-dev:i386
  shell: /bin/bash -e {0}
  env:
    BUILD_DIR: build
    BUILD_TYPE: Debug
E: Unable to correct problems, you have held broken packages.
##[error]Process completed with exit code 100.
```

**Area for Triage**: 

Maybe Packages area?

**Question, Bug, or Feature?**: 

Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
The command worked for many months and started failing just an hour ago.
[Working build](https://github.com/klei1984/max/runs/682312656?check_suite_focus=true).
[Failing build](https://github.com/klei1984/max/runs/690555212?check_suite_focus=true)

**Actual behavior**
The issue occurs when additional packages are tried to be installed onto clean ubuntu VM. Just use the provided action script from the report. It should be possible to reproduce the issue with it.
