### ISSUE TITLE
macos-14 breaks setup-ruby action

### ISSUE THREAD

**Issue by ghost** [actions/virtual-environments#9257]
### Description

Post announcement of macos-14 runners being available, I updated my action to use runs-on: `macos-14`. The `setup-ruby` is now broken.

```
Run ruby/setup-ruby@v1
Using 3.2.2 as input from file .ruby-version
Error: The current runner (macos-14-arm64) was detected as self-hosted because the platform does not match a GitHub-hosted runner image (or that image is deprecated and no longer supported).
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
  Image: macos-14-arm64
  Version: 20240116.1
  Included Software: https://github.com/actions/runner-images/blob/macOS-14/20240116.1/images/macos/macos-14-arm64-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-14%2F20240116.1
```

### Is it regression?

No

### Expected behavior

`setup-ruby` action proceeds normally

### Actual behavior

`setup-ruby` action fails

### Repro steps

```
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup ruby & gems
        uses: ruby/setup-ruby@v1
        with:
          #ruby-version: '3.2' # Not needed with a .ruby-version file
          bundler-cache: true
```
