### ISSUE TITLE
Tar cannot overwrite read-only files on Windows

### ISSUE THREAD

**Issue by mzabaluev** [actions/virtual-environments#936]
**Describe the bug**
`C:\Windows\System32\tar.exe` fails to remove existing files that need to be overwritten by an archive extraction, but have the read-only attribute.

**Area for Triage**: 
Scripting and command line

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
This workflow should succeed despite read-only object files present in the `.git` directory.

```yaml
jobs:
  test:
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v2

      - name: List read-only files
        run: Get-ChildItem .git -Recurse -Attributes ReadOnly

      - name: Pack and unpack
        run: |
          C:\windows\System32\tar.exe -cz -f ${{ runner.temp }}\repo.tgz .
          C:\windows\System32\tar.exe -xzv -f ${{ runner.temp }}\repo.tgz
```

The [cache action](https://github.com/actions/cache) uses this tar executable in this way. `tar` works with these options on the Unix OSes where git also makes its object/pack files read-only, and I haven't found any tar options that could be used to force removal of read-only files specifically on Windows.

**Actual behavior**
[Failure][run] with "Can't unlink already-existing object" errors referring to the read-only files.

[run]: https://github.com/mzabaluev/github-actions-playground/runs/707224514?check_suite_focus=true
